/** Agent actions for tracking, keying, and roto workflows. */
import type { MotionAction } from "./catalog.js";

export const MEDIA_EFFECT_ACTIONS: MotionAction[] = [
  {
    id: "motion.analysis.tracking.request",
    aliases: ["track this video", "run point tracking", "run planar tracking", "analyze camera motion", "track footage for stabilization", "create tracking analysis"],
    permission: "write_local",
    mutates: true,
    calls: ["motion.analysis.tracking.request", "motion.analysis.tracking.inspect", "motion.receipts.read"],
    verify: [
      "Tracking request persists a source-hashed lifecycle with confidence, residual, lost/recovered, solver, containment, and receipt evidence.",
      "Inspect confirms the package-local video bytes still match the persisted source identity.",
    ],
    surfaces: ["tracking", "prompt", "preview", "receipts"],
  },
  {
    id: "motion.analysis.tracking.inspect",
    aliases: ["inspect tracking analysis", "show tracking confidence", "show lost tracking spans", "check tracking source", "tracking status"],
    permission: "read_motion",
    mutates: false,
    calls: ["motion.analysis.tracking.inspect"],
    verify: ["Tracking inspection returns lifecycle attempts, last-good analysis, confidence spans, and current/stale source identity without mutation."],
    surfaces: ["tracking", "prompt", "preview", "receipts"],
  },
  {
    id: "motion.analysis.tracking.apply",
    aliases: ["apply tracking stabilization", "stabilize this footage", "attach track to layer", "use planar track for stabilization", "apply tracked camera correction"],
    permission: "edit_motion",
    mutates: true,
    calls: ["motion.analysis.tracking.inspect", "motion.analysis.tracking.apply", "motion.analysis.tracking.verify", "motion.preview.frame", "motion.receipts.read"],
    verify: [
      "Apply compiles a current last-good track into ordinary transform keyframes, retains explicit confidence gaps, and stores an exact reversible attachment.",
      "Verify confirms analysis id, source hash, and generated keyframes before preview or Cut handoff.",
    ],
    surfaces: ["tracking", "timeline", "prompt", "preview", "receipts"],
  },
  {
    id: "motion.analysis.tracking.detach",
    aliases: ["detach tracking stabilization", "remove stabilization", "restore transform before tracking", "unlink tracked motion", "undo attached track"],
    permission: "edit_motion",
    mutates: true,
    calls: ["motion.analysis.tracking.verify", "motion.analysis.tracking.detach", "motion.preview.frame", "motion.receipts.read"],
    verify: ["Detach restores the exact prior x, y, scale, and rotation keyframes and removes only the tracking attachment."],
    surfaces: ["tracking", "timeline", "prompt", "preview", "receipts"],
  },
  {
    id: "motion.analysis.tracking.verify",
    aliases: ["verify tracking stabilization", "check tracking attachment", "check stabilized keyframes", "verify track before cut handoff", "is tracking current"],
    permission: "read_motion",
    mutates: false,
    calls: ["motion.analysis.tracking.verify"],
    verify: ["Tracking verification reports missing or drifted attachments, analysis ids, source bytes, and generated keyframes without mutation."],
    surfaces: ["tracking", "timeline", "prompt", "preview", "receipts"],
  },
  {
    id: "motion.keying.inspect",
    aliases: ["inspect chroma key", "show green screen controls", "inspect layer keying", "check roto mask", "show key and roto state"],
    permission: "read_motion",
    mutates: false,
    calls: ["motion.keying.inspect"],
    verify: ["Inspection reports the bounded key controls, animated roto state, and tracking attachment without mutation."],
    surfaces: ["keying", "roto", "prompt", "preview"],
  },
  {
    id: "motion.keying.apply",
    aliases: ["key out green screen", "apply chroma key", "remove green background", "key this footage", "apply spill suppression", "clean green screen matte"],
    permission: "edit_motion",
    mutates: true,
    calls: ["motion.keying.inspect", "motion.keying.apply", "motion.preview.frame", "motion.receipts.read"],
    verify: ["Apply creates a copy-on-write package, validates bounded key and matte-cleanup controls, previews the keyed pixels, and emits a receipt."],
    surfaces: ["keying", "prompt", "preview", "receipts"],
  },
  {
    id: "motion.keying.remove",
    aliases: ["remove chroma key", "disable green screen key", "restore unkeyed footage", "clear layer keying"],
    permission: "edit_motion",
    mutates: true,
    calls: ["motion.keying.inspect", "motion.keying.remove", "motion.preview.frame", "motion.receipts.read"],
    verify: ["Remove deletes only the chroma-key contract in a copy-on-write package and preserves the source package and roto mask."],
    surfaces: ["keying", "prompt", "preview", "receipts"],
  },
  {
    id: "motion.roto.upsert",
    aliases: ["create roto mask", "animate roto mask", "update rotoscope path", "attach tracking to roto", "isolate subject with roto"],
    permission: "edit_motion",
    mutates: true,
    calls: ["motion.keying.inspect", "motion.roto.upsert", "motion.preview.frame", "motion.receipts.read"],
    verify: ["Upsert validates stable vertex identities, bounded frames and tangents, optional source-hashed tracking attachment, rendered mask evidence, and a mutation receipt."],
    surfaces: ["roto", "tracking", "timeline", "prompt", "preview", "receipts"],
  },
  {
    id: "motion.roto.tracking.detach",
    aliases: ["detach roto tracking", "unlink tracking from roto", "keep roto frames remove tracking", "remove tracked roto attachment"],
    permission: "edit_motion",
    mutates: true,
    calls: ["motion.keying.inspect", "motion.roto.tracking.detach", "motion.preview.frame", "motion.receipts.read"],
    verify: ["Detach removes only the roto tracking attachment while preserving the exact animated vertex frames."],
    surfaces: ["roto", "tracking", "timeline", "prompt", "preview", "receipts"],
  },
  {
    id: "motion.roto.remove",
    aliases: ["remove roto mask", "delete rotoscope mask", "clear subject mask", "restore unmasked footage"],
    permission: "edit_motion",
    mutates: true,
    calls: ["motion.keying.inspect", "motion.roto.remove", "motion.preview.frame", "motion.receipts.read"],
    verify: ["Remove deletes only the roto mask in a copy-on-write package and preserves chroma-key controls."],
    surfaces: ["roto", "prompt", "preview", "receipts"],
  },
];
