/**
 * Surface -> command-id catalog for ShellX Motion action coverage.
 *
 * Role: the static `SURFACE_COMMANDS` table mapping each host UI surface (packages, timeline, template
 * inspector, ...) to the debug/command ids reachable from it. Extracted verbatim from `catalog.ts` so the
 * action catalog file stays under the module-size gate. Data only; the coverage logic is unchanged.
 *
 * Dependencies: none (a plain Record<string, string[]> of literals).
 *
 * Primary callers: `packages/actions/src/catalog.ts` (actionCoverage).
 */
export const SURFACE_COMMANDS: Record<string, string[]> = {
  packages: ["motion.packages.browse"],
  timeline: ["motion.state", "motion.open", "motion.timeline.panel", "motion.timeline.keyframes.panel", "motion.timeline.transitions.panel", "motion.timeline.easing.panel", "motion.media.panel", "motion.audio.panel", "motion.analysis.tracking.apply", "motion.analysis.tracking.detach", "motion.analysis.tracking.verify", "motion.timeline.inspect", "motion.timeline.playhead.set", "motion.timeline.range.select", "motion.timeline.viewport.set", "motion.timeline.duration.policy", "motion.timeline.duration.policy.set", "motion.timeline.marker.upsert", "motion.timeline.marker.delete", "motion.timeline.scene.create", "motion.timeline.scene.delete", "motion.timeline.scene.reorder", "motion.timeline.scene.resize", "motion.timeline.scene.name.set", "motion.timeline.easing.presets", "motion.timeline.animation.presets", "motion.timeline.animation.preset.apply", "motion.timeline.keyframe.upsert", "motion.timeline.keyframe.delete", "motion.timeline.keyframe.move", "motion.timeline.keyframe.easing.apply", "motion.timeline.keyframe.shift", "motion.timeline.keyframe.scale", "motion.timeline.keyframe.duplicate", "motion.timeline.keyframe.distribute", "motion.timeline.keyframe.range.delete", "motion.timeline.keyframe.reverse", "motion.timeline.keyframe.snap", "motion.timeline.layer.create", "motion.timeline.layer.trim", "motion.timeline.layer.split", "motion.timeline.layer.text.set", "motion.timeline.layer.style.set", "motion.timeline.layer.transform.set", "motion.timeline.layer.effect.set", "motion.timeline.layer.rich.set", "motion.timeline.layer.blend.set", "motion.timeline.layer.crop.set", "motion.timeline.layer.mask.set", "motion.timeline.layer.fit.set", "motion.timeline.layer.media.set", "motion.timeline.layer.name.set", "motion.timeline.layer.visibility.set", "motion.timeline.layer.lock", "motion.timeline.layer.delete", "motion.timeline.layer.duplicate", "motion.timeline.layer.reorder", "motion.timeline.cleanup", "motion.timeline.track.create", "motion.timeline.track.reorder", "motion.timeline.track.delete", "motion.timeline.track.rename", "motion.timeline.track.lock", "motion.timeline.track.mute", "motion.timeline.track.solo", "motion.timeline.track.volume", "motion.timeline.track.fade", "motion.timeline.track.pan", "motion.timeline.layer.ducking.set", "motion.timeline.layer.track.assign", "motion.timeline.caption.import", "motion.timeline.caption.upsert", "motion.timeline.transition.upsert", "motion.timeline.transition.delete", "motion.select", "motion.highlight"],
  templateInspector: ["motion.state", "motion.open", "motion.package.patch", "motion.template.catalog", "motion.template.plan", "motion.template.panel", "motion.template.controls", "motion.template.apply", "motion.template.media.replace"],
  preview: ["motion.preview.panel", "motion.preview.frame", "motion.preview.playhead", "motion.preview.strip", "motion.media.panel", "motion.analysis.tracking.inspect", "motion.analysis.tracking.verify", "motion.connector.panel", "motion.capabilities.match", "motion.capabilities.panel", "motion.render.cancel", "motion.render.retry", "motion.render.status", "motion.render.queue", "motion.export.panel", "motion.export.plan", "motion.quality.panel", "motion.html.snippet.export", "motion.html.snippet.import", "motion.otio.export", "motion.otio.import"],
  receipts: ["motion.receipts.list", "motion.receipts.read", "motion.receipts.panel", "motion.analysis.tracking.request", "motion.analysis.tracking.inspect", "motion.analysis.tracking.apply", "motion.analysis.tracking.detach", "motion.analysis.tracking.verify", "motion.platform.verification.panel", "motion.quality.panel", "motion.connector.panel", "motion.agent.transcript", "motion.prompt.queue", "motion.prompt.cancel", "motion.prompt.retry", "motion.render.queue", "motion.export.plan", "motion.review.html.bundle", "motion.source.import", "motion.source.to_scripted_video", "motion.storyboard.panel", "motion.storyboard.graph", "motion.html.snippet.export", "motion.html.snippet.import", "motion.otio.export", "motion.otio.import", "motion.package.archive", "motion.package.extract", "motion.support.bundle"],
  tracking: ["motion.analysis.tracking.request", "motion.analysis.tracking.inspect", "motion.analysis.tracking.apply", "motion.analysis.tracking.detach", "motion.analysis.tracking.verify"],
  assets: ["motion.assets.panel", "motion.media.panel"],
  brand: ["motion.brand.panel"],
  prompt: [
    "motion.actions.find",
    "motion.actions.guide",
    "motion.actions.plan",
    "motion.actions.panel",
    "motion.capabilities.match",
    "motion.capabilities.panel",
    "motion.prompt.run",
    "motion.prompt.queue",
    "motion.prompt.cancel",
    "motion.prompt.retry",
    "motion.agent.panel",
    "motion.agent.health",
    "motion.agent.transcript",
    "motion.packages.browse",
    "motion.timeline.panel",
    "motion.timeline.keyframes.panel",
    "motion.timeline.transitions.panel",
    "motion.timeline.easing.panel",
    "motion.receipts.panel",
    "motion.platform.verification.panel",
    "motion.assets.panel",
    "motion.brand.panel",
    "motion.audio.panel",
    "motion.media.panel",
    "motion.script.compile",
    "motion.analysis.tracking.request",
    "motion.analysis.tracking.inspect",
    "motion.analysis.tracking.apply",
    "motion.analysis.tracking.detach",
    "motion.analysis.tracking.verify",
    "motion.preview.panel",
    "motion.preview.playhead",
    "motion.preview.strip",
    "motion.render.cancel",
    "motion.render.retry",
    "motion.render.queue",
    "motion.render.final",
    "motion.render.batch",
    "motion.connector.panel",
    "motion.export.presets",
    "motion.export.panel",
    "motion.export.plan",
    "motion.quality.panel",
    "motion.package.archive",
    "motion.package.extract",
    "motion.source.import",
    "motion.source.to_scripted_video",
    "motion.storyboard.panel",
    "motion.storyboard.graph",
    "motion.html.snippet.export",
    "motion.html.snippet.import",
    "motion.otio.export",
    "motion.otio.import",
    "motion.review.html.bundle",
    "motion.timeline.playhead.set",
    "motion.timeline.range.select",
    "motion.timeline.viewport.set",
    "motion.timeline.duration.policy",
    "motion.timeline.duration.policy.set",
    "motion.timeline.marker.upsert",
    "motion.timeline.marker.delete",
    "motion.timeline.scene.create",
    "motion.timeline.scene.delete",
    "motion.timeline.scene.reorder",
    "motion.timeline.scene.resize",
    "motion.timeline.scene.name.set",
    "motion.timeline.easing.panel",
    "motion.timeline.easing.presets",
    "motion.timeline.animation.presets",
    "motion.timeline.animation.preset.apply",
    "motion.timeline.keyframe.upsert",
    "motion.timeline.keyframe.delete",
    "motion.timeline.keyframe.move",
    "motion.timeline.keyframe.easing.apply",
    "motion.timeline.keyframe.shift",
    "motion.timeline.keyframe.scale",
    "motion.timeline.keyframe.duplicate",
    "motion.timeline.keyframe.distribute",
    "motion.timeline.keyframe.range.delete",
    "motion.timeline.keyframe.reverse",
    "motion.timeline.keyframe.snap",
    "motion.timeline.layer.create",
    "motion.timeline.layer.trim",
    "motion.timeline.layer.split",
    "motion.timeline.layer.text.set",
    "motion.timeline.layer.style.set",
    "motion.timeline.layer.transform.set",
    "motion.timeline.layer.effect.set",
    "motion.timeline.layer.blend.set",
    "motion.timeline.layer.crop.set",
    "motion.timeline.layer.mask.set",
    "motion.timeline.layer.fit.set",
    "motion.timeline.layer.media.set",
    "motion.timeline.layer.name.set",
    "motion.timeline.layer.visibility.set",
    "motion.timeline.layer.lock",
    "motion.timeline.layer.delete",
    "motion.timeline.layer.duplicate",
    "motion.timeline.layer.reorder",
    "motion.timeline.cleanup",
    "motion.timeline.track.create",
    "motion.timeline.track.reorder",
    "motion.timeline.track.delete",
    "motion.timeline.track.rename",
    "motion.timeline.track.lock",
    "motion.timeline.track.mute",
    "motion.timeline.track.solo",
    "motion.timeline.track.volume",
    "motion.timeline.track.fade",
    "motion.timeline.track.pan",
    "motion.timeline.layer.ducking.set",
    "motion.timeline.layer.track.assign",
    "motion.timeline.caption.import",
    "motion.timeline.caption.upsert",
    "motion.timeline.transition.upsert",
    "motion.timeline.transition.delete",
    "motion.canvas.package",
    "motion.canvas.bridge_export",
    "motion.browser.workflow.capture",
    "motion.connector.canvas_to_mp4",
    "motion.connector.canvas_to_cut",
    "motion.connector.script_to_cut",
    "motion.connector.source_to_cut",
    "motion.connector.cut_generate_to_cut",
    "motion.connector.template_to_cut",
    "motion.template.catalog",
    "motion.template.plan",
    "motion.template.panel",
    "motion.template.controls",
    "motion.template.apply",
    "motion.template.media.replace",
    "motion.quality.panel",
    "motion.quality.check"
  ]
};
