import { AGENT_SURFACE_PURPOSES } from "./catalog-agent-surface-purposes.js";
import { AUTHORING_INTEGRATION_PURPOSES } from "./catalog-authoring-integration-purposes.js";
import { CHECKPOINT_STORYBOARD_PURPOSES } from "./catalog-checkpoint-storyboard-purposes.js";
import { PARTICLE_STRUCTURAL_PURPOSES } from "./catalog-particle-structural-purposes.js";
import { SHAPE_GEOMETRY_PURPOSES } from "./catalog-shape-geometry-purposes.js";
import { TIMELINE_REMAINING_PURPOSES } from "./catalog-timeline-remaining-purposes.js";

/**
 * One line saying what a command is FOR.
 *
 * Exported because the MCP tool listing needs it: a tool described only as
 * "debug command motion.render.final. permission=render_motion. mutates=true." tells an agent
 * nothing about when to reach for it. An independent agent tester called the bare listings
 * "near-useless" and had to fall back on actions.guide for every decision.
 */
export function purposeForCall(call: string): string {
  const purposes: Record<string, string> = {
    "motion.state": "Read current package and UI state before mutation; retained host-receipt summaries currently require the Linux stable receipt reader.",
    "motion.package.patch": "Apply a validated copy-on-write Motion package patch; the source package remains unchanged.",
    "motion.package.asset.import": "Copy one host-approved external file into an existing package revision under assets/ without a template-specific binding.",
    "motion.lottie.import": "Create a Motion package from a host-approved Lottie JSON source inside host-configured input and output roots.",
    "motion.dotlottie.import": "Create a Motion package from a host-approved dotLottie container inside host-configured input and output roots, optionally selecting its declared animation and theme.",
    "motion.revision.transaction.plan": "Preview a bounded list of typed timeline edits without writing a package or receipt.",
    "motion.revision.transaction": "Apply a bounded list of typed timeline edits atomically as one copy-on-write package revision.",
    "motion.preview.frame": "Render one deterministic PNG preview with a receipt; the strict no-fallback GPU lane is visual-only and proves neither audio nor final media.",
    "motion.preview.panel": "Show a read-only preview player with playhead state, active timeline refs, preview modes, and render follow-ups.",
    "motion.preview.playhead": "Render the current timeline playhead as a deterministic preview frame.",
    "motion.preview.strip": "Render a deterministic timeline preview strip with per-frame evidence.",
    "motion.render.status": "On Linux, read historical render status from stable host receipt files, which only describe work that has finished writing evidence and never observe a live worker.",
    "motion.package.create": "Create a new, valid, renderable Motion package from nothing. The first step when building something original rather than importing it.",
    "motion.package.validate": "Check a package is structurally valid without rendering it — identity, layers, dimensions, hosts and lanes.",
    "motion.platform.requirements": "Report per-operation readiness: satisfied for this invocation versus possible by any route, with FFmpeg, FFprobe, and browser status plus installOptions; it only reports source-only GPU policy and never proves GPU.",
    "motion.job.get": "Ask what one job is doing right now: pending, running, or ended with an outcome. Answers live work the receipt views cannot see.",
    "motion.job.list": "List this caller's jobs, live work first and finished work newest first.",
    "motion.job.submit": "Submit a coordinator-cancellable ordinary streamed or closed segmented final-video render and receive its durable job id before expensive work starts.",
    "motion.job.cancel": "Request cancellation from the coordinator that owns the live worker; wait for its terminal state before claiming it stopped.",
    "motion.job.retry": "Create a new coordinator job linked to a retryable failed source job.",
    "motion.job.events": "Read the durable ordered event stream for one visible coordinator job.",
    "motion.render.cancel": "On Linux, write a historical render-cancellation annotation through the stable receipt store. It never signals a running worker.",
    "motion.render.retry": "On Linux, write a historical render-retry annotation through the stable receipt store. It does not create a new render.",
    "motion.render.queue": "On Linux, read stable historical render receipt rows and their annotations; it never observes or queues a live worker.",
    "motion.prompt.queue": "On Linux, read stable receipt-derived prompt annotations and follow-ups; it never observes a live provider.",
    "motion.prompt.cancel": "On Linux, write a stable receipt-derived prompt-cancellation annotation; it never stops a live provider.",
    "motion.prompt.retry": "On Linux, write a stable receipt-derived prompt-retry annotation; it never starts a live provider.",
    "motion.actions.panel": "Show grouped actions, permission tiers, prompt commands, and suggested prompt-run follow-ups.",
    "motion.agent.panel": "Show local CLI agent selection policy, adapter command shapes, safety guarantees, and prompt follow-ups.",
    "motion.agent.health": "Probe local CLI subscription agent readiness without mutating packages.",
    "motion.agent.snapshot": "Read a compact path-free snapshot from host-approved package and receipt roots, with only the authenticated caller's jobs.",
    "motion.packages.browse": "Browse local Motion packages with package metadata, template availability, asset counts, and suggested follow-up actions.",
    "motion.media.panel": "Show media layer source readiness, trim/loop/playback controls, and export-preset compatibility warnings.",
    "motion.audio.panel": "Show resolved audio mix inputs, automation, track controls, document-master declaration, ducking, and export-preset compatibility warnings.",
    "motion.audio.master.set": "Set or clear bounded document-level final-program audio controls; a declared loudness target is realized post-mix and proved only by a delivered-file receipt.",
    "motion.audio.crossfade.set": "Apply a matched linear or equal-power crossfade to two already-exactly-overlapping audio sources without moving their timing.",
    "motion.procedural.audio-envelope.produce": "Decode one approved local source layer into bounded data-only RMS samples for procedural audio-envelope nodes.",
    "motion.analysis.tracking.request": "Run contained point or planar analysis for a manifest-declared package video, then persist its retryable lifecycle in a copied package through separate host-approved input and empty output roots.",
    "motion.analysis.tracking.inspect": "Inspect tracking confidence, lifecycle attempts, last-good data, and current source identity without mutation.",
    "motion.analysis.tracking.apply": "Compile a current tracking result into reversible ordinary transform keyframes in a copied package.",
    "motion.analysis.tracking.detach": "Restore the exact transform keyframes that existed before tracking stabilization was attached.",
    "motion.analysis.tracking.verify": "Verify attachment identity, source bytes, and generated stabilization keyframes without mutation.",
    "motion.render.final": "Render final media through the selected renderer lane, opt into closed durable segments, or reuse an exact v2 attested artifact at the same output path.",
    "motion.render.cache.plan": "Observe whether an exact v2 attested render entry is currently verified, without creating files or authorizing a later render.",
    "motion.render.batch": "Render data rows into per-row media outputs with the selected export preset.",
    "motion.export.presets": "List supported export presets with codecs, extensions, MIME types, and audio/alpha support.",
    "motion.export.panel": "Show export presets as grouped UI cards with recommended choices and render arguments; optional retained platform-receipt coverage currently requires Linux.",
    "motion.export.plan": "Plan the export preset, feature impact, deterministic capture preflight, quality gates, and render follow-up arguments.",
    "motion.timeline.panel": "Show the timeline as panel-ready playhead controls, layer rows, scenes, tracks, markers, and suggested actions.",
    "motion.timeline.keyframes.panel": "Show animated layers, keyframe target ranges, easing usage, preset counts, and suggested keyframe actions.",
    "motion.timeline.transitions.panel": "Show enter and exit transitions with timing windows, easing usage, type counts, and suggested transition actions.",
    "motion.timeline.inspect": "Inspect timeline scenes, tracks, markers, and layer track refs.",
    "motion.timeline.playhead.set": "On Linux, move the timeline playhead as durable editor state without mutating MotionIR; unsupported hosts refuse before creating state.",
    "motion.timeline.range.select": "On Linux, select an in/out timeline range as durable editor state without mutating MotionIR; unsupported hosts refuse before creating state.",
    "motion.timeline.viewport.set": "On Linux, set timeline viewport range, zoom, and pixels-per-second as durable editor state; unsupported hosts refuse before creating state.",
    "motion.timeline.duration.policy": "Read package duration policy and protected intro/outro regions.",
    "motion.timeline.duration.policy.set": "Set package duration policy metadata for protected regions, min/max duration, and resize behavior.",
    "motion.timeline.marker.upsert": "Insert or replace a timeline marker and optionally attach it to a scene.",
    "motion.timeline.marker.delete": "Remove a timeline marker and prune stale scene marker refs.",
    "motion.timeline.scene.create": "Create a storyboard scene with timing, optional display name, and optional track or marker refs.",
    "motion.timeline.scene.delete": "Remove a storyboard scene while preserving referenced timeline content and package duration.",
    "motion.timeline.scene.reorder": "Reorder storyboard scene rows while preserving timing, refs, and package duration.",
    "motion.timeline.scene.resize": "Resize a scene duration and optionally ripple later scenes, layers, and markers.",
    "motion.timeline.scene.name.set": "Set a timeline scene display name without renaming stable scene ids or hand-authoring JSON pointer patches.",
    "motion.timeline.easing.panel": "Inspect sampled easing curves and package usage across keyframes and transitions.",
    "motion.timeline.easing.presets": "List named and cubic-bezier easing presets available for keyframes and transitions.",
    "motion.timeline.animation.presets": "List reusable entrance and exit animation presets available for layer keyframes.",
    "motion.timeline.animation.preset.apply": "Apply a reusable animation preset to one or more layers as deterministic keyframes with receipt evidence.",
    "motion.timeline.transition.presets": "List reusable named transition presets with lane and use-case guidance.",
    "motion.timeline.transition.preset.apply": "Apply one named transition preset to a layer as validated transitions, keyframes, and effects.",
    "motion.timeline.keyframe.upsert": "Insert or replace a typed timeline keyframe without hand-authoring JSON pointer patches.",
    "motion.timeline.keyframe.delete": "Remove a typed timeline keyframe without hand-authoring JSON pointer patches.",
    "motion.timeline.keyframe.move": "Move an existing typed timeline keyframe to a new timestamp while preserving its value and easing.",
    "motion.timeline.keyframe.easing.apply": "Apply an easing preset to one keyframe or a selected keyframe time range.",
    "motion.timeline.keyframe.shift": "Shift a selected typed keyframe range by a positive or negative delta while preserving values and easing.",
    "motion.timeline.keyframe.scale": "Stretch or compress a selected typed keyframe range around an origin while preserving values and easing.",
    "motion.timeline.keyframe.duplicate": "Copy a selected typed keyframe range by a positive or negative offset while preserving original keyframes, values, and easing.",
    "motion.timeline.keyframe.distribute": "Space three or more typed keyframes evenly between the first and last selected timestamps while preserving values and easing.",
    "motion.timeline.keyframe.range.delete": "Remove a selected typed keyframe range while preserving other targets and pruning empty keyframe containers.",
    "motion.timeline.keyframe.reverse": "Reverse a selected typed keyframe range in time while preserving values and easing.",
    "motion.timeline.keyframe.snap": "Snap a selected typed keyframe range to the package frame grid while preserving values and easing.",
    "motion.timeline.layer.create": "Create a typed text, shape, media, environment, points, or other bounded data-only layer with stack and optional track placement evidence.",
    "motion.timeline.layer.trim": "Update layer start, duration, and optional media source trim fields without hand-authoring JSON pointer patches.",
    "motion.timeline.layer.split": "Split a layer at an absolute timeline timestamp while preserving segment timing, media trim, keyframes, transitions, and track order.",
    "motion.timeline.layer.text.set": "Set text on an existing text or caption layer without hand-authoring JSON pointer patches.",
    "motion.timeline.layer.style.set": "Set a supported top-level layer style property without hand-authoring JSON pointer patches.",
    "motion.timeline.layer.transform.set": "Set a supported static layer transform or opacity value without hand-authoring JSON pointer patches.",
    "motion.timeline.layer.effect.set": "Set a supported static layer visual effect value without hand-authoring JSON pointer patches.",
    "motion.timeline.layer.rich.set": "Set one inspector-exposed, allow-listed path reveal, environment, shader, particle, 3D, camera/depth, motion-blur, or film control.",
    ...PARTICLE_STRUCTURAL_PURPOSES,
    ...SHAPE_GEOMETRY_PURPOSES,
    "motion.timeline.layer.blend.set": "Set a supported static layer blend mode without hand-authoring JSON pointer patches.",
    "motion.timeline.layer.crop.set": "Set a static image or video source crop rectangle without hand-authoring JSON pointer patches.",
    "motion.timeline.layer.mask.set": "Set a static visual-layer rectangular or rounded mask without hand-authoring JSON pointer patches.",
    "motion.timeline.layer.fit.set": "Set a static image or video media fit mode without hand-authoring JSON pointer patches.",
    "motion.timeline.layer.media.set": "Set a media layer source and canonicalize stale direct source aliases without hand-authoring JSON pointer patches.",
    "motion.timeline.layer.name.set": "Set a timeline layer display name without renaming stable layer ids or hand-authoring JSON pointer patches.",
    "motion.timeline.layer.visibility.set": "Hide or show a timeline layer without deleting it or hand-authoring JSON pointer patches.",
    "motion.timeline.layer.lock": "Lock or unlock a timeline layer with receipt evidence so later edit commands can honor layer protection.",
    "motion.timeline.layer.delete": "Delete a layer while removing stale track refs and preserving receipt evidence.",
    "motion.timeline.layer.duplicate": "Duplicate a layer while preserving animation, transitions, timing, and track order evidence.",
    "motion.timeline.layer.reorder": "Reorder a layer in the global timeline stack while syncing track layer order evidence.",
    "motion.timeline.cleanup": "Remove stale or duplicate track, scene, and marker refs while normalizing package duration with receipt evidence.",
    "motion.timeline.track.create": "Create a timeline track and optionally attach existing untracked layers with receipt evidence.",
    "motion.timeline.track.reorder": "Reorder timeline tracks with old/new stack index and track-order receipt evidence.",
    "motion.timeline.track.delete": "Delete a timeline track while preserving layers, optionally detaching layer refs, and pruning scene refs.",
    "motion.timeline.track.rename": "Rename a timeline track with old/new name and changed-path receipt evidence.",
    "motion.timeline.track.lock": "Lock or unlock a timeline track with receipt evidence so later edit commands can honor track protection.",
    "motion.timeline.track.mute": "Mute or unmute a timeline track with receipt evidence so final renders can honor track audio state.",
    "motion.timeline.track.solo": "Solo or unsolo a timeline track with receipt evidence so final renders can isolate track audio state.",
    "motion.timeline.track.volume": "Set timeline track gain with receipt evidence so final renders can honor track audio level.",
    "motion.timeline.track.fade": "Set timeline track fade-in and fade-out defaults with receipt evidence so final renders can honor track audio fades.",
    "motion.timeline.track.pan": "Set timeline track stereo balance with receipt evidence so final renders can honor track audio pan.",
    "motion.timeline.layer.ducking.set": "Set ducking on an audio layer so final renders lower it under trigger layers. Default mode 'timed' lowers the layer across each trigger's time window (level-independent); mode 'sidechain' uses true level-dependent FFmpeg sidechaincompress (threshold/ratio/attack/release) so it only ducks while the trigger audio is actually loud.",
    "motion.timeline.layer.track.assign": "Assign or reorder a layer on a timeline track while keeping layer track refs and track layer order consistent.",
    "motion.timeline.caption.import": "Parse SRT, VTT, or plain captions into typed caption layers on a timeline caption track.",
    "motion.timeline.caption.upsert": "Insert or replace one caption layer with text, timing, style, and caption track evidence.",
    "motion.timeline.transition.upsert": "Insert or replace a layer enter or exit transition without hand-authoring JSON pointer patches.",
    "motion.timeline.transition.delete": "Remove a layer enter or exit transition without hand-authoring JSON pointer patches.",
    ...CHECKPOINT_STORYBOARD_PURPOSES,
    "motion.script.compile": "Compile structured scripted-video input from a host-approved root or inline into an empty host-approved Motion package output, committing the receipt after the complete package.",
    "motion.package.script.author": "Author one host-approved local inline web/html/canvas entry from a data-only source package into a separate empty copy-on-write output; the source remains unchanged.",
    "motion.capabilities.match": "Match the package and requested output against renderer lane capability cards before rendering.",
    "motion.capabilities.panel": "Show grouped renderer lane cards with support badges, package fit, recommended lane, and follow-up match or export-plan actions.",
    "motion.template.catalog": "List available Motion templates from explicit package roots.",
    "motion.template.panel": "Show grouped TemplateIR controls with current bound Motion values and follow-up actions.",
    "motion.template.controls": "List host-editable template controls for the current package.",
    "motion.template.apply": "Apply host-editable template values through declared bindings.",
    "motion.template.media.replace": "Replace a TemplateIR media slot with a copied package-local asset and bound MotionIR refs.",
    "motion.canvas.package": "Convert a Canvas frame selection into a Motion package and resource catalog under host-approved roots, requiring an empty output and a host-approved sourceRoot for inline assets.",
    "motion.canvas.bridge_export": "Export a trusted Canvas frame selection and bridge receipt to a no-clobber destination.",
    "motion.quality.panel": "Show quality-manifest samples, baselines, regions, audio policy, and suggested quality follow-up commands.",
    "motion.quality.check": "Check rendered-media dimensions, audio, and sampled-frame quality against optional baseline thresholds with a receipt; it does not accept delivery or release.",
    "motion.connector.panel": "Show the current P2A Template-to-Cut and P2B Canvas/Script/Source-to-Cut connector lifecycle; legacy named routes are compatibility-only.",
    "motion.connector.canvas_to_cut": "On Linux, turn host-approved Canvas selection input evidence into one no-clobber P2B delivery in an absent or empty output: Browser preview and Browser-to-FFmpeg H.264 rendered_media with artifact handle, receipts, and Cut plan; never mutate Cut.",
    "motion.connector.canvas_to_mp4": "On Linux, run the Canvas-to-MP4 compatibility harness, writing Motion package and resource evidence to a trusted no-clobber output and either dry-running or rendering the selected preset, with no Cut plan or Cut mutation; macOS and Windows refuse before creating connector output state.",
    "motion.connector.script_to_cut": "On Linux, turn scripted-video input evidence into one no-clobber P2B delivery in an absent or empty output: Browser preview and Browser-to-FFmpeg H.264 rendered_media with artifact handle, receipts, and Cut plan; never mutate Cut.",
    "motion.connector.source_to_cut": "On Linux, turn host-approved imported Markdown input evidence into one no-clobber P2B delivery in an absent or empty output: Browser preview and Browser-to-FFmpeg H.264 rendered_media with artifact handle, receipts, and Cut plan; never mutate Cut.",
    "motion.connector.cut_generate_to_cut": "On Linux, run the legacy Cut Generate compatibility flow from one script to package, Browser preview, Browser-to-FFmpeg H.264 rendered_media, and Cut plan; macOS and Windows refuse before creating output state, and it never inserts anything directly into Cut.",
    "motion.connector.template_to_cut": "On Linux, apply values to immutable admitted template input evidence and publish one no-clobber P2A Browser-to-FFmpeg H.264 rendered_media delivery with browser preview, artifact handle, receipts, and Cut plan; it allows no dry run and never mutates Cut.",
    "motion.review.html.bundle": "Collect render, preview, quality, and receipt evidence into a portable HTML review bundle only in trusted absent-or-empty scratch, from host receipt roots.",
    "motion.source.import": "Import a public source or supplied Markdown into a host-approved empty output, preserving source identity and receipt evidence.",
    "motion.source.to_scripted_video": "Lower imported Markdown from a host-approved input root into deterministic scripted-video JSON and receipt evidence in a host-approved empty output.",
    "motion.storyboard.panel": "Review scripted-video storyboard metadata, readiness diagnostics, source refs, frame timings, and follow-up compile or Cut handoff actions.",
    "motion.storyboard.graph": "Review scripted-video source, asset, template, engine, review, sequence graph facts, and readiness diagnostics before compile or Cut handoff.",
    "motion.html.snippet.export": "Export a Motion package from host-approved roots as standalone HTML/CSS to a trusted empty output, with timing metadata and adapter lossiness diagnostics.",
    "motion.html.snippet.import": "Import a bounded inert ShellX/HyperFrames-style HTML composition from a host-approved path into a trusted empty package output, staging verified local media and a receipt.",
    "motion.otio.export": "Export a Motion package from host-approved roots to a trusted OpenTimelineIO output path with a receipt.",
    "motion.otio.import": "Import an OpenTimelineIO timeline from a host-approved path into a trusted Motion package output with a receipt.",
    "motion.package.archive": "Export the current Motion package as a deterministic portable .shellxmotion archive with receipt evidence.",
    "motion.package.extract": "Extract a portable .shellxmotion archive into a local Motion package with receipt evidence.",
    "motion.support.bundle": "Collect redacted local diagnostics for support handoff only in trusted absent scratch, summarizing optional host receipt-root evidence.",
    "motion.platform.verification.panel": "On Linux, summarize stable Linux, Windows, macOS, and aggregate platform verification receipts.",
    "motion.agent.transcript": "On Linux, read stable prompt and agent receipt transcripts as panel-ready redacted evidence.",
    "motion.receipts.panel": "On Linux, summarize stable host-owned receipts for a panel with recent activity, warnings, failures, and artifacts.",
    "motion.assets.panel": "Summarize package assets, MotionIR asset refs, layer usage, hashes, and missing local files.",
    "motion.brand.panel": "Summarize design-token groups and brand provenance for package handoff.",
    "motion.receipts.read": "On Linux, read identity-stable host-owned evidence for the operation.",
    ...AGENT_SURFACE_PURPOSES,
    ...AUTHORING_INTEGRATION_PURPOSES,
    ...TIMELINE_REMAINING_PURPOSES,
  };
  return purposes[call] ?? `Run ${call}.`;
}
