import type { MotionSdkOperation } from "./types.js";

export const REQUIRED_OPERATION_FIELDS: Record<MotionSdkOperation, string[]> = {
  validate: ["packageRoot"],
  compile: ["outDir"],
  preview: ["packageRoot", "outDir"],
  render: ["packageRoot", "outputPath", "preset"],
  renderCachePlan: ["packageRoot", "outputPath", "preset"],
  status: ["receiptsRoot"],
  cancel: ["receiptsRoot", "jobId"],
  timelineEdit: ["packageRoot", "outDir"],
  revisionTransactionPlan: ["packageRoot", "base", "steps"],
  revisionTransaction: ["packageRoot", "outDir", "base", "steps"],
  trackingRequest: ["packageRoot", "outDir", "analysisId", "assetId", "mode", "model"],
  trackingInspect: ["packageRoot", "analysisId"],
  trackingApply: ["packageRoot", "outDir", "analysisId", "layerId"],
  trackingDetach: ["packageRoot", "outDir", "layerId"],
  trackingVerify: ["packageRoot", "layerId"],
  keyingInspect: ["packageRoot", "layerId"],
  keyingApply: ["packageRoot", "outDir", "layerId"],
  keyingRemove: ["packageRoot", "outDir", "layerId"],
  rotoUpsert: ["packageRoot", "outDir", "layerId"],
  rotoTrackingDetach: ["packageRoot", "outDir", "layerId"],
  rotoRemove: ["packageRoot", "outDir", "layerId"],
  compositingInspect: ["packageRoot"],
  compositingSet: ["packageRoot", "outDir"],
  compositingRemove: ["packageRoot", "outDir"],
  gltfImport: ["sourcePath", "outDir"],
  proceduralInspect: ["packageRoot"],
  proceduralSet: ["packageRoot", "outDir"],
  proceduralSetEnabled: ["packageRoot", "outDir", "relationshipId"],
  proceduralBake: ["packageRoot", "outDir"],
  proceduralDetach: ["packageRoot", "outDir", "relationshipId"],
  proceduralAudioEnvelopeProduce: ["packageRoot", "outDir", "sourceLayerId", "envelopeId"],
  cutoutRigBake: ["packageRoot", "outDir", "sourceLayerId"],
  audioMasterSet: ["packageRoot", "outDir", "master"],
  audioCrossfadeSet: ["packageRoot", "outDir", "fromLayerId", "toLayerId", "durationMs"],
};

export const ALLOWED_OPERATION_FIELDS: Record<MotionSdkOperation, string[]> = {
  validate: ["packageRoot", "receiptsRoot"],
  compile: ["script", "outDir", "createdAt"],
  preview: ["packageRoot", "outDir", "lane", "atMs", "workflowPath"],
  render: [
    "packageRoot", "outputPath", "preset", "artifactRoot", "receiptsRoot",
    "frameLane", "workflowPath", "qualityManifestPath", "keepFrames", "segmented", "reuseAttested", "idempotencyKey", "cutHandoff",
  ],
  renderCachePlan: [
    "packageRoot", "outputPath", "preset", "frameLane", "atMs", "minUniqueFrameHashes", "workflowPath", "qualityManifestPath",
  ],
  status: ["receiptsRoot", "jobId"],
  cancel: ["receiptsRoot", "jobId", "reason"],
  timelineEdit: ["packageRoot", "outDir", "receiptsRoot", "createdBy", "edit"],
  revisionTransactionPlan: ["packageRoot", "base", "steps"],
  revisionTransaction: ["packageRoot", "outDir", "base", "steps", "createdBy"],
  trackingRequest: [
    "packageRoot", "outDir", "analysisId", "assetId", "mode", "model",
    "reference", "settings", "receiptsRoot", "createdAt",
  ],
  trackingInspect: ["packageRoot", "analysisId"],
  trackingApply: [
    "packageRoot", "outDir", "analysisId", "layerId", "segmentIndex",
    "includeLowConfidence", "receiptsRoot",
  ],
  trackingDetach: ["packageRoot", "outDir", "layerId", "receiptsRoot"],
  trackingVerify: ["packageRoot", "layerId", "analysisId"],
  keyingInspect: ["packageRoot", "layerId"],
  keyingApply: ["packageRoot", "outDir", "layerId", "keying", "receiptsRoot"],
  keyingRemove: ["packageRoot", "outDir", "layerId", "receiptsRoot"],
  rotoUpsert: ["packageRoot", "outDir", "layerId", "mask", "receiptsRoot"],
  rotoTrackingDetach: ["packageRoot", "outDir", "layerId", "receiptsRoot"],
  rotoRemove: ["packageRoot", "outDir", "layerId", "receiptsRoot"],
  compositingInspect: ["packageRoot"],
  compositingSet: ["packageRoot", "outDir", "graph", "receiptsRoot", "createdBy"],
  compositingRemove: ["packageRoot", "outDir", "receiptsRoot", "createdBy"],
  gltfImport: ["sourcePath", "outDir", "createdBy", "createdAt"],
  proceduralInspect: ["packageRoot", "atMs"],
  proceduralSet: ["packageRoot", "outDir", "relationship", "receiptsRoot", "createdBy"],
  proceduralSetEnabled: ["packageRoot", "outDir", "relationshipId", "enabled", "receiptsRoot", "createdBy"],
  proceduralBake: ["packageRoot", "outDir", "relationshipIds", "startMs", "endMs", "sampleEveryFrames", "receiptsRoot", "createdBy"],
  proceduralDetach: ["packageRoot", "outDir", "relationshipId", "receiptsRoot", "createdBy"],
  proceduralAudioEnvelopeProduce: ["packageRoot", "outDir", "sourceLayerId", "envelopeId", "sampleEveryMs", "channel", "receiptsRoot", "createdBy"],
  cutoutRigBake: ["packageRoot", "outDir", "sourceLayerId", "rig", "receiptsRoot", "createdBy"],
  audioMasterSet: ["packageRoot", "outDir", "master", "receiptsRoot", "createdBy"],
  audioCrossfadeSet: ["packageRoot", "outDir", "fromLayerId", "toLayerId", "durationMs", "curve", "receiptsRoot", "createdBy"],
};
