/** Fixed shipping-private receipt for C6B5b lifecycle COW installation; no Debug route imports it. */
import { canonicalJson, canonicalJsonSha256, compareCodeUnits, readBoundedStableFile, writeVerifiedBoundedFile } from "@shellx-motion/core";
import { join } from "node:path";
import { PackageEditTransactionError } from "../package-edit-transaction.js";

export const C6B5B_RECEIPT_PATH = "receipts/checkpoint-storyboard-lifecycle-materialization.v1.json";
const HASH = /^[a-f0-9]{64}$/u, MAX_RECEIPT_BYTES = 1024 * 1024;
export interface C6B5bInventory { readonly sha256: string; readonly entryCount: number; readonly leafCount: number; }
export interface C6B5bExactBase {
  readonly packageId: string; readonly manifestRawSha256: string; readonly motionRawSha256: string; readonly manifestCanonicalSha256: string; readonly motionCanonicalSha256: string; readonly inventory: C6B5bInventory;
  readonly planFingerprint: string; readonly profileFingerprint: string; readonly storyboardId: string; readonly storyboardSha256: string; readonly storyboardRevision: number;
  readonly sourceLayerPrefixCount: number; readonly sourceLayerPrefixSha256: string; readonly generatedLayerIds: readonly string[]; readonly generatedLayerIdsSha256: string; readonly generatedLayersSha256: string; readonly timingSha256: string; readonly outputCanonicalMotionSha256: string;
}
export interface C6B5bPlanEvidence {
  readonly schema: "shellx-motion/private-checkpoint-storyboard-lifecycle-profile-plan@1";
  readonly fingerprint: string;
  readonly storyboard: { readonly id: string; readonly sha256: string; readonly revision: number; readonly fingerprint: string };
  readonly base: { readonly package: { readonly id: string; readonly motionPath: string }; readonly manifest: { readonly id: string; readonly sha256: string }; readonly canonicalMotion: { readonly id: string; readonly sha256: string }; readonly persistedMotion: { readonly id: string; readonly sha256: string } };
  readonly lowererProfile: { readonly fingerprint: string; readonly schema: "shellx-motion/private-checkpoint-storyboard-lifecycle-profile@1"; readonly supportedCapabilities: readonly unknown[]; readonly rootShapeKinds: readonly unknown[]; readonly propertyMask: readonly unknown[]; readonly lifecycle: "absent-create-present-optional-remove" };
  readonly operations: readonly unknown[]; readonly layers: readonly unknown[];
  readonly intendedChanges: { readonly paths: readonly string[]; readonly layers: { readonly operation: string; readonly sourceLayerCount: number; readonly appendLayerIds: readonly string[] } };
}
export interface CheckpointStoryboardLifecycleMaterializationReceipt {
  readonly schema: "shellx-motion/private-checkpoint-storyboard-lifecycle-materialization-receipt@1"; readonly operation: "checkpoint-storyboard.lifecycle.materialize"; readonly status: "passed";
  readonly approval: { readonly storyboard: { readonly id: string; readonly sha256: string; readonly revision: number; readonly record: unknown }; readonly plan: C6B5bPlanEvidence; readonly projection: { readonly sourceLayerPrefixCount: number; readonly sourceLayerPrefixSha256: string; readonly generatedLayerIds: readonly string[]; readonly generatedLayerIdsSha256: string; readonly generatedLayersSha256: string; readonly timingSha256: string; readonly outputCanonicalMotionSha256: string } };
  readonly base: { readonly expected: C6B5bExactBase; readonly reopened: C6B5bExactBase };
  readonly output: { readonly packageId: string; readonly manifestRawSha256: string; readonly motionRawSha256: string; readonly canonicalMotionSha256: string; readonly nonReceiptInventory: C6B5bInventory; readonly preservedLeaves: { readonly sha256: string; readonly count: number }; readonly changed: { readonly paths: readonly string[]; readonly count: 2; readonly motionPropertyPaths: readonly ["layers"]; readonly motionPropertyPathCount: 1 } };
  readonly transaction: { readonly cow: "closed-inventory-finalize-after-edit"; readonly installed: true; readonly exclusiveReceipt: true; readonly workspaceCleanup: "not-attested" }; readonly renderer: { readonly invoked: false; readonly pixels: false }; readonly fingerprint: string;
}

export function bindC6B5bExactBase(base: Omit<C6B5bExactBase, "planFingerprint" | "profileFingerprint" | "storyboardId" | "storyboardSha256" | "storyboardRevision" | "sourceLayerPrefixCount" | "sourceLayerPrefixSha256" | "generatedLayerIds" | "generatedLayerIdsSha256" | "generatedLayersSha256" | "timingSha256" | "outputCanonicalMotionSha256">, plan: C6B5bPlanEvidence, prefix: { readonly count: number; readonly sha256: string }, outputCanonicalMotionSha256: string): C6B5bExactBase {
  assertPlanEvidence(plan);
  const ids = Object.freeze([...plan.intendedChanges.layers.appendLayerIds]);
  return Object.freeze({ ...base, planFingerprint: plan.fingerprint, profileFingerprint: plan.lowererProfile.fingerprint, storyboardId: plan.storyboard.id, storyboardSha256: plan.storyboard.sha256, storyboardRevision: plan.storyboard.revision, sourceLayerPrefixCount: prefix.count, sourceLayerPrefixSha256: prefix.sha256, generatedLayerIds: ids, generatedLayerIdsSha256: canonicalJsonSha256(ids), generatedLayersSha256: canonicalJsonSha256(plan.layers), timingSha256: canonicalJsonSha256(plan.layers.map((layer: any) => ({ id: layer.id, startMs: layer.startMs, durationMs: layer.durationMs }))), outputCanonicalMotionSha256 });
}

export function createC6B5bReceipt(plan: C6B5bPlanEvidence, storyboard: unknown, source: C6B5bExactBase, output: C6B5bExactBase, motionPath: string, nonReceiptInventory: C6B5bInventory, preservedLeaves: { sha256: string; count: number }): CheckpointStoryboardLifecycleMaterializationReceipt {
  assertPlanEvidence(plan); assertPlanBaseEvidence(plan, source); assertExactBaseEvidence(source); assertExactBaseEvidence(output);
  if (source.packageId !== output.packageId || source.manifestRawSha256 !== output.manifestRawSha256 || source.manifestCanonicalSha256 !== output.manifestCanonicalSha256 || !same(projection(source), projection(output))) throw new PackageEditTransactionError("copy_mismatch", "C6B5b output projection or unchanged manifest bytes are not bound to its exact source facts.");
  const payload: Omit<CheckpointStoryboardLifecycleMaterializationReceipt, "fingerprint"> = {
    schema: "shellx-motion/private-checkpoint-storyboard-lifecycle-materialization-receipt@1", operation: "checkpoint-storyboard.lifecycle.materialize", status: "passed",
    approval: { storyboard: { id: plan.storyboard.id, sha256: plan.storyboard.sha256, revision: plan.storyboard.revision, record: structuredClone(storyboard) }, plan: structuredClone(plan), projection: projection(source) },
    base: { expected: source, reopened: source },
    output: { packageId: output.packageId, manifestRawSha256: output.manifestRawSha256, motionRawSha256: output.motionRawSha256, canonicalMotionSha256: output.motionCanonicalSha256, nonReceiptInventory, preservedLeaves, changed: { paths: Object.freeze([motionPath, C6B5B_RECEIPT_PATH].sort(compareCodeUnits)), count: 2, motionPropertyPaths: ["layers"], motionPropertyPathCount: 1 } },
    transaction: { cow: "closed-inventory-finalize-after-edit", installed: true, exclusiveReceipt: true, workspaceCleanup: "not-attested" }, renderer: { invoked: false, pixels: false },
  };
  return frozen({ ...payload, fingerprint: canonicalJsonSha256(payload) });
}

export async function writeC6B5bReceipt(root: string, receipt: CheckpointStoryboardLifecycleMaterializationReceipt): Promise<void> {
  const bytes = Buffer.from(`${canonicalJson(receipt)}\n`, "utf8"); if (bytes.byteLength > MAX_RECEIPT_BYTES) throw new PackageEditTransactionError("package_limit_exceeded", "C6B5b receipt exceeds 1 MiB.");
  try { await writeVerifiedBoundedFile(join(root, C6B5B_RECEIPT_PATH), bytes, { label: "C6B5b lifecycle materialization receipt", maxBytes: MAX_RECEIPT_BYTES, withinRoot: root }); }
  catch { throw new PackageEditTransactionError("copy_mismatch", "C6B5b receipt could not be exclusively published."); }
  if (!same(await readC6B5bReceipt(root), receipt)) throw new PackageEditTransactionError("copy_mismatch", "C6B5b receipt differs after staged publication.");
}

export async function readC6B5bReceipt(root: string): Promise<CheckpointStoryboardLifecycleMaterializationReceipt> {
  const file = await readBoundedStableFile(join(root, C6B5B_RECEIPT_PATH), { label: "C6B5b lifecycle materialization receipt", maxBytes: MAX_RECEIPT_BYTES, withinRoot: root, requireSingleLink: true });
  let value: unknown; try { value = JSON.parse(file.bytes.toString("utf8")); } catch { throw new PackageEditTransactionError("copy_mismatch", "C6B5b receipt is not JSON."); }
  const receipt = record(value, ["schema", "operation", "status", "approval", "base", "output", "transaction", "renderer", "fingerprint"], "C6B5b receipt");
  if (receipt.schema !== "shellx-motion/private-checkpoint-storyboard-lifecycle-materialization-receipt@1" || receipt.operation !== "checkpoint-storyboard.lifecycle.materialize" || receipt.status !== "passed") throw new PackageEditTransactionError("copy_mismatch", "C6B5b receipt identity is invalid.");
  const { fingerprint, ...payload } = receipt; if (typeof fingerprint !== "string" || !HASH.test(fingerprint) || canonicalJsonSha256(payload) !== fingerprint || file.bytes.toString("utf8") !== `${canonicalJson(receipt)}\n`) throw new PackageEditTransactionError("copy_mismatch", "C6B5b receipt integrity is invalid.");
  const approval = record(receipt.approval, ["storyboard", "plan", "projection"], "C6B5b receipt approval"), storyboard = record(approval.storyboard, ["id", "sha256", "revision", "record"], "C6B5b receipt storyboard"), plan = approval.plan as C6B5bPlanEvidence;
  assertPlanEvidence(plan); id(storyboard.id, "C6B5b receipt storyboard.id"); hash(storyboard.sha256, "C6B5b receipt storyboard.sha256"); integer(storyboard.revision, "C6B5b receipt storyboard.revision", 1, 1_000_000);
  const expected = readC6B5bExactBase(record(receipt.base, ["expected", "reopened"], "C6B5b receipt base").expected), reopened = readC6B5bExactBase((receipt.base as Record<string, unknown>).reopened);
  assertExactBaseEvidence(expected); assertExactBaseEvidence(reopened); assertPlanBaseEvidence(plan, expected);
  if (!same(expected, reopened) || expected.planFingerprint !== plan.fingerprint || expected.storyboardId !== storyboard.id || expected.storyboardSha256 !== storyboard.sha256 || expected.storyboardRevision !== storyboard.revision || plan.storyboard.id !== storyboard.id || plan.storyboard.sha256 !== storyboard.sha256 || plan.storyboard.revision !== storyboard.revision) throw new PackageEditTransactionError("copy_mismatch", "C6B5b receipt base or approval storyboard binding is inconsistent.");
  const projectionValue = record(approval.projection, ["sourceLayerPrefixCount", "sourceLayerPrefixSha256", "generatedLayerIds", "generatedLayerIdsSha256", "generatedLayersSha256", "timingSha256", "outputCanonicalMotionSha256"], "C6B5b receipt projection");
  if (!same(projectionValue, projection(expected))) throw new PackageEditTransactionError("copy_mismatch", "C6B5b receipt lifecycle projection is inconsistent.");
  const output = record(receipt.output, ["packageId", "manifestRawSha256", "motionRawSha256", "canonicalMotionSha256", "nonReceiptInventory", "preservedLeaves", "changed"], "C6B5b receipt output"); id(output.packageId, "C6B5b receipt output.packageId"); [output.manifestRawSha256, output.motionRawSha256, output.canonicalMotionSha256].forEach((value) => hash(value, "C6B5b receipt output hash")); if (output.packageId !== expected.packageId || output.manifestRawSha256 !== expected.manifestRawSha256 || output.canonicalMotionSha256 !== expected.outputCanonicalMotionSha256) throw new PackageEditTransactionError("copy_mismatch", "C6B5b receipt output does not retain unchanged manifest or Motion facts."); inventory(output.nonReceiptInventory); const preserved = record(output.preservedLeaves, ["sha256", "count"], "C6B5b receipt preserved leaves"); hash(preserved.sha256, "C6B5b receipt preserved leaves.sha256"); integer(preserved.count, "C6B5b receipt preserved leaves.count", 0, 100_000);
  const changed = record(output.changed, ["paths", "count", "motionPropertyPaths", "motionPropertyPathCount"], "C6B5b receipt changed"); if (!Array.isArray(changed.paths) || !same(changed.paths, [...changed.paths].sort(compareCodeUnits)) || changed.count !== 2 || !same(changed.motionPropertyPaths, ["layers"]) || changed.motionPropertyPathCount !== 1) throw new PackageEditTransactionError("copy_mismatch", "C6B5b receipt changed-leaf evidence is invalid.");
  const transaction = record(receipt.transaction, ["cow", "installed", "exclusiveReceipt", "workspaceCleanup"], "C6B5b receipt transaction"); if (transaction.cow !== "closed-inventory-finalize-after-edit" || transaction.installed !== true || transaction.exclusiveReceipt !== true || transaction.workspaceCleanup !== "not-attested") throw new PackageEditTransactionError("copy_mismatch", "C6B5b receipt transaction is invalid.");
  const renderer = record(receipt.renderer, ["invoked", "pixels"], "C6B5b receipt renderer"); if (renderer.invoked !== false || renderer.pixels !== false) throw new PackageEditTransactionError("copy_mismatch", "C6B5b receipt renderer evidence is invalid.");
  return frozen({ ...receipt, approval: { storyboard, plan, projection: projectionValue }, base: { expected, reopened }, output }) as unknown as CheckpointStoryboardLifecycleMaterializationReceipt;
}

export function readC6B5bExactBase(value: unknown): C6B5bExactBase {
  const base = record(value, ["packageId", "manifestRawSha256", "motionRawSha256", "manifestCanonicalSha256", "motionCanonicalSha256", "inventory", "planFingerprint", "profileFingerprint", "storyboardId", "storyboardSha256", "storyboardRevision", "sourceLayerPrefixCount", "sourceLayerPrefixSha256", "generatedLayerIds", "generatedLayerIdsSha256", "generatedLayersSha256", "timingSha256", "outputCanonicalMotionSha256"], "C6B5b exact base");
  id(base.packageId, "C6B5b exact base.packageId"); [base.manifestRawSha256, base.motionRawSha256, base.manifestCanonicalSha256, base.motionCanonicalSha256, base.planFingerprint, base.profileFingerprint, base.storyboardSha256, base.sourceLayerPrefixSha256, base.generatedLayerIdsSha256, base.generatedLayersSha256, base.timingSha256, base.outputCanonicalMotionSha256].forEach((value) => hash(value, "C6B5b exact base hash")); id(base.storyboardId, "C6B5b exact base.storyboardId"); integer(base.storyboardRevision, "C6B5b exact base.storyboardRevision", 1, 1_000_000); integer(base.sourceLayerPrefixCount, "C6B5b exact base.sourceLayerPrefixCount", 0, 10_000); const sourceInventory = readInventory(base.inventory), generatedLayerIds = dataStringArray(base.generatedLayerIds, "C6B5b exact base generated layer ids");
  const exact = frozen({ packageId: base.packageId, manifestRawSha256: base.manifestRawSha256, motionRawSha256: base.motionRawSha256, manifestCanonicalSha256: base.manifestCanonicalSha256, motionCanonicalSha256: base.motionCanonicalSha256, inventory: sourceInventory, planFingerprint: base.planFingerprint, profileFingerprint: base.profileFingerprint, storyboardId: base.storyboardId, storyboardSha256: base.storyboardSha256, storyboardRevision: base.storyboardRevision, sourceLayerPrefixCount: base.sourceLayerPrefixCount, sourceLayerPrefixSha256: base.sourceLayerPrefixSha256, generatedLayerIds, generatedLayerIdsSha256: base.generatedLayerIdsSha256, generatedLayersSha256: base.generatedLayersSha256, timingSha256: base.timingSha256, outputCanonicalMotionSha256: base.outputCanonicalMotionSha256 });
  assertExactBaseEvidence(exact); return exact;
}

function assertPlanEvidence(plan: C6B5bPlanEvidence): void {
  const data = record(plan, ["schema", "storyboard", "base", "lowererProfile", "operations", "layers", "intendedChanges", "evidence", "fingerprint"], "C6B5b lifecycle plan"), { fingerprint, ...payload } = data;
  const storyboard = record(data.storyboard, ["id", "sha256", "revision", "fingerprint"], "C6B5b lifecycle plan storyboard"), base = record(data.base, ["package", "manifest", "canonicalMotion", "persistedMotion"], "C6B5b lifecycle plan base"), packageFact = record(base.package, ["id", "motionPath"], "C6B5b lifecycle plan package"), manifest = record(base.manifest, ["id", "sha256"], "C6B5b lifecycle plan manifest"), canonicalMotion = record(base.canonicalMotion, ["id", "sha256"], "C6B5b lifecycle plan canonical Motion"), persistedMotion = record(base.persistedMotion, ["id", "sha256"], "C6B5b lifecycle plan persisted Motion"), profile = record(data.lowererProfile, ["schema", "supportedCapabilities", "rootShapeKinds", "propertyMask", "lifecycle", "fingerprint"], "C6B5b lifecycle plan profile"), { fingerprint: profileFingerprint, ...profilePayload } = profile;
  if (data.schema !== "shellx-motion/private-checkpoint-storyboard-lifecycle-profile-plan@1" || typeof fingerprint !== "string" || !HASH.test(fingerprint) || canonicalJsonSha256(payload) !== fingerprint || !idOk(storyboard.id) || !HASH.test(storyboard.sha256) || !HASH.test(storyboard.fingerprint) || !Number.isSafeInteger(storyboard.revision) || storyboard.revision < 1 || !idOk(packageFact.id) || typeof packageFact.motionPath !== "string" || !idOk(manifest.id) || !HASH.test(manifest.sha256) || !idOk(canonicalMotion.id) || !HASH.test(canonicalMotion.sha256) || !idOk(persistedMotion.id) || !HASH.test(persistedMotion.sha256) || profile.schema !== "shellx-motion/private-checkpoint-storyboard-lifecycle-profile@1" || typeof profileFingerprint !== "string" || !HASH.test(profileFingerprint) || canonicalJsonSha256(profilePayload) !== profileFingerprint || !Array.isArray(profile.supportedCapabilities) || !Array.isArray(profile.rootShapeKinds) || !Array.isArray(profile.propertyMask) || profile.lifecycle !== "absent-create-present-optional-remove" || !Array.isArray(data.operations) || !Array.isArray(data.layers) || !same(data.intendedChanges && record(data.intendedChanges, ["paths", "layers"], "C6B5b lifecycle intended changes").paths, ["/layers"])) throw new PackageEditTransactionError("source_changed", "C6B5b received incomplete or self-inconsistent C6B5a lifecycle plan evidence.");
  const layers = record(record(data.intendedChanges, ["paths", "layers"], "C6B5b lifecycle intended changes").layers, ["operation", "sourceLayerCount", "appendLayerIds"], "C6B5b lifecycle intended layer changes"), ids = dataStringArray(layers.appendLayerIds, "C6B5b lifecycle append layer ids");
  if (layers.operation !== "append" || !Number.isSafeInteger(layers.sourceLayerCount) || layers.sourceLayerCount < 0 || data.layers.length !== ids.length || data.layers.some((layer, index) => !layer || typeof layer !== "object" || (layer as { id?: unknown }).id !== ids[index])) throw new PackageEditTransactionError("source_changed", "C6B5b lifecycle plan layers do not match its sealed append projection.");
}
function assertPlanBaseEvidence(plan: C6B5bPlanEvidence, base: C6B5bExactBase): void {
  if (plan.base.package.id !== base.packageId || plan.base.manifest.sha256 !== base.manifestCanonicalSha256 || plan.base.canonicalMotion.sha256 !== base.motionCanonicalSha256 || plan.base.persistedMotion.sha256 !== base.motionRawSha256 || plan.fingerprint !== base.planFingerprint || plan.lowererProfile.fingerprint !== base.profileFingerprint || plan.storyboard.id !== base.storyboardId || plan.storyboard.sha256 !== base.storyboardSha256 || plan.storyboard.revision !== base.storyboardRevision || plan.intendedChanges.layers.sourceLayerCount !== base.sourceLayerPrefixCount || !same(plan.intendedChanges.layers.appendLayerIds, base.generatedLayerIds) || canonicalJsonSha256(plan.layers) !== base.generatedLayersSha256 || canonicalJsonSha256(plan.layers.map((layer: any) => ({ id: layer.id, startMs: layer.startMs, durationMs: layer.durationMs }))) !== base.timingSha256 || canonicalJsonSha256(base.generatedLayerIds) !== base.generatedLayerIdsSha256) throw new PackageEditTransactionError("copy_mismatch", "C6B5b lifecycle plan, projection, or exact base is inconsistent.");
}
function assertExactBaseEvidence(base: C6B5bExactBase): void { if (canonicalJsonSha256(base.generatedLayerIds) !== base.generatedLayerIdsSha256) throw new PackageEditTransactionError("copy_mismatch", "C6B5b exact base generated-layer identity hash is inconsistent."); }
function projection(base: C6B5bExactBase) { return { sourceLayerPrefixCount: base.sourceLayerPrefixCount, sourceLayerPrefixSha256: base.sourceLayerPrefixSha256, generatedLayerIds: base.generatedLayerIds, generatedLayerIdsSha256: base.generatedLayerIdsSha256, generatedLayersSha256: base.generatedLayersSha256, timingSha256: base.timingSha256, outputCanonicalMotionSha256: base.outputCanonicalMotionSha256 }; }
function record(value: unknown, keys: readonly string[], label: string): Record<string, any> {
  try {
    if (!value || typeof value !== "object" || Array.isArray(value) || Object.getPrototypeOf(value) !== Object.prototype) throw new Error("not a plain object");
    const descriptors = Object.getOwnPropertyDescriptors(value), actual = Reflect.ownKeys(value);
    if (actual.length !== keys.length || actual.some((key) => typeof key !== "string" || !keys.includes(key)) || keys.some((key) => !Object.hasOwn(descriptors, key) || !descriptors[key]!.enumerable || !("value" in descriptors[key]!))) throw new Error("unsupported fields");
    return Object.fromEntries(keys.map((key) => [key, (descriptors[key] as PropertyDescriptor & { value: unknown }).value]));
  } catch { throw new PackageEditTransactionError("copy_mismatch", `${label} has unsupported fields.`); }
}
function hash(value: unknown, label: string): void { if (typeof value !== "string" || !HASH.test(value)) throw new PackageEditTransactionError("copy_mismatch", `${label} is invalid.`); }
function id(value: unknown, label: string): void { if (!idOk(value)) throw new PackageEditTransactionError("copy_mismatch", `${label} is invalid.`); }
function idOk(value: unknown): value is string { return typeof value === "string" && /^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$/u.test(value); }
function integer(value: unknown, label: string, minimum: number, maximum: number): void { if (typeof value !== "number" || !Number.isSafeInteger(value) || value < minimum || value > maximum) throw new PackageEditTransactionError("copy_mismatch", `${label} is invalid.`); }
function inventory(value: unknown): void { readInventory(value); }
function readInventory(value: unknown): C6B5bInventory { const data = record(value, ["sha256", "entryCount", "leafCount"], "C6B5b inventory"); hash(data.sha256, "C6B5b inventory.sha256"); integer(data.entryCount, "C6B5b inventory.entryCount", 1, 100_000); integer(data.leafCount, "C6B5b inventory.leafCount", 1, 100_000); return Object.freeze({ sha256: data.sha256, entryCount: data.entryCount, leafCount: data.leafCount }); }
function dataStringArray(value: unknown, label: string): readonly string[] {
  try {
    if (!Array.isArray(value) || Object.getPrototypeOf(value) !== Array.prototype) throw new Error("not an array");
    const descriptors = Object.getOwnPropertyDescriptors(value) as Record<string, PropertyDescriptor>, keys = Reflect.ownKeys(value), lengthDescriptor = descriptors["length"], length = lengthDescriptor && "value" in lengthDescriptor ? lengthDescriptor.value : undefined;
    if (!Number.isSafeInteger(length) || length < 0 || length > 10_000 || keys.length !== length + 1 || Object.getOwnPropertySymbols(value).length !== 0 || !Object.hasOwn(descriptors, "length") || !lengthDescriptor || lengthDescriptor.enumerable || !("value" in lengthDescriptor)) throw new Error("array shape");
    const values: string[] = [];
    for (let index = 0; index < length; index += 1) { const descriptor = descriptors[String(index)]; if (!descriptor || !descriptor.enumerable || !("value" in descriptor) || !idOk(descriptor.value)) throw new Error("array value"); values.push(descriptor.value); }
    return Object.freeze(values);
  } catch { throw new PackageEditTransactionError("copy_mismatch", `${label} are invalid.`); }
}
function same(left: unknown, right: unknown): boolean { return canonicalJsonSha256(left) === canonicalJsonSha256(right); }
function frozen<T>(value: T): T { if (value && typeof value === "object" && !Object.isFrozen(value)) { for (const child of Object.values(value as object)) frozen(child); Object.freeze(value); } return value; }
