/** Shipping-private output-only C6B5b diagnostic reopen. It accepts no source, approval, plan, or writer authority. */
import { lstat, realpath } from "node:fs/promises";
import { isAbsolute, relative, resolve, sep } from "node:path";
import { canonicalJsonSha256, compileMotionDocumentCompositing, loadSchema, validateDocument, validateMotionProceduralGraph, validateMotionRelationActions, validateMotionRelations, type MotionDocument } from "@shellx-motion/core";
import { compileCheckpointStoryboardLifecycleProfilePlan } from "@shellx-motion/core/internal/checkpoint-storyboard-lifecycle-profile";
import { validateMotionBehaviors } from "@shellx-motion/core/internal/motion-behavior-validation";
import { assertTrustedWorkspaceAnchorPath, withTrustedWorkspaceAnchor } from "@shellx-motion/core/internal/trusted-host-workspace";
import { PackageEditTransactionError } from "../package-edit-transaction.js";
import { snapshotPackageEditTree } from "../package-edit-tree-snapshot.js";
import { c6B5bCurrentInventory, c6B5bNonReceiptInventory, c6B5bPrefixFacts, c6B5bPreservedLeaves, c6B5bSame, closedC6B5bInventory, observeC6B5bPackage, type CheckpointStoryboardLifecycleMaterializationOutputHost } from "./checkpoint-storyboard-lifecycle-materialize-facts-private.js";
import { C6B5B_RECEIPT_PATH, readC6B5bReceipt, type C6B5bPlanEvidence, type CheckpointStoryboardLifecycleMaterializationReceipt } from "./checkpoint-storyboard-lifecycle-materialize-receipt-private.js";

export type { CheckpointStoryboardLifecycleMaterializationOutputHost } from "./checkpoint-storyboard-lifecycle-materialize-facts-private.js";
export interface CheckpointStoryboardLifecycleMaterializationInstalledOutput {
  readonly schema: "shellx-motion/private-checkpoint-storyboard-lifecycle-materialization-installed-output@1";
  readonly receipt: { readonly schema: "shellx-motion/private-checkpoint-storyboard-lifecycle-materialization-receipt@1"; readonly fingerprint: string };
  readonly package: { readonly id: string; readonly manifest: { readonly rawSha256: string; readonly canonicalSha256: string }; readonly motion: { readonly rawSha256: string; readonly canonicalSha256: string }; readonly currentInventory: { readonly sha256: string; readonly entryCount: number; readonly leafCount: number }; readonly nonReceiptInventory: { readonly sha256: string; readonly entryCount: number; readonly leafCount: number }; readonly preservedLeaves: { readonly sha256: string; readonly count: number } };
  readonly storyboard: { readonly id: string; readonly sha256: string; readonly revision: number };
  readonly plan: { readonly fingerprint: string }; readonly profile: { readonly fingerprint: string };
  readonly layers: { readonly sourcePrefix: { readonly count: number; readonly sha256: string }; readonly ids: readonly string[]; readonly idsSha256: string; readonly generatedSha256: string; readonly timingSha256: string };
  readonly materialization: { readonly changedMotionRoot: "layers"; readonly changedLeafCount: 2; readonly renderer: { readonly invoked: false; readonly pixels: false } };
}

/** Reopens solely through output/workspace authority. A receipt is an integrity witness, never durable account provenance. */
export async function reopenCheckpointStoryboardLifecycleMaterializationOutput(host: CheckpointStoryboardLifecycleMaterializationOutputHost): Promise<CheckpointStoryboardLifecycleMaterializationInstalledOutput> {
  return await withOutputWorkspaceAuthority(host, async (outputRoot, canonicalHost) => {
    const before = await readC6B5bReceipt(outputRoot), output = await observeC6B5bPackage(outputRoot, canonicalHost); assertReceiptBinding(before, output); await assertCompleteMotion(output.pkg.motion);
    if (canonicalJsonSha256(compileMotionDocumentCompositing(output.pkg.motion)) !== canonicalJsonSha256(output.pkg.motion)) throw new PackageEditTransactionError("copy_mismatch", "C6B5b reopened output compositing compilation is not idempotent.");
    const source = reconstructSource(output.pkg.motion, before), plan = await recompile(before, output.pkg.manifest, source);
    if (!c6B5bSame(plan, before.approval.plan)) throw new PackageEditTransactionError("copy_mismatch", "C6B5b receipt-retained storyboard no longer recompiles its sealed lifecycle plan.");
    const suffix = output.pkg.motion.layers.slice(before.base.expected.sourceLayerPrefixCount);
    if (!c6B5bSame(suffix, plan.layers) || !c6B5bSame(suffix.map((layer) => layer.id), before.base.expected.generatedLayerIds) || canonicalJsonSha256(suffix) !== before.base.expected.generatedLayersSha256 || canonicalJsonSha256(suffix.map((layer) => ({ id: layer.id, startMs: layer.startMs, durationMs: layer.durationMs }))) !== before.base.expected.timingSha256 || canonicalJsonSha256(output.pkg.motion) !== before.base.expected.outputCanonicalMotionSha256) throw new PackageEditTransactionError("copy_mismatch", "C6B5b output layer prefix, suffix, timing, or whole Motion identity differs from the receipt.");
    const snapshot = await snapshotPackageEditTree(outputRoot), nonReceiptInventory = c6B5bNonReceiptInventory(snapshot), currentInventory = await closedC6B5bInventory(outputRoot, canonicalHost), preservedLeaves = c6B5bPreservedLeaves(snapshot, output.pkg.manifest.motion);
    const expectedPaths = [output.pkg.manifest.motion, C6B5B_RECEIPT_PATH].sort();
    const receiptEntryDelta = currentInventory.entryCount - nonReceiptInventory.entryCount;
    // Adding the receipt either adds one file row, or replaces the previously admitted empty
    // `receipts/` directory marker.  The exact hashes above still bind both full inventories.
    if (!c6B5bSame(nonReceiptInventory, before.output.nonReceiptInventory) || !c6B5bSame(currentInventory, c6B5bCurrentInventory(snapshot)) || (receiptEntryDelta !== 0 && receiptEntryDelta !== 1) || currentInventory.leafCount !== nonReceiptInventory.leafCount + 1 || !c6B5bSame(preservedLeaves, before.output.preservedLeaves) || !c6B5bSame(before.output.changed.paths, expectedPaths) || before.output.changed.count !== 2 || before.output.changed.motionPropertyPaths[0] !== "layers" || before.output.changed.motionPropertyPathCount !== 1) throw new PackageEditTransactionError("copy_mismatch", "C6B5b output inventory or preserved leaves differ from the fixed receipt.");
    const afterOutput = await observeC6B5bPackage(outputRoot, canonicalHost), afterSnapshot = await snapshotPackageEditTree(outputRoot), afterInventory = await closedC6B5bInventory(outputRoot, canonicalHost), after = await readC6B5bReceipt(outputRoot);
    if (afterOutput.base.packageId !== output.base.packageId || afterOutput.base.manifestRawSha256 !== output.base.manifestRawSha256 || afterOutput.base.motionRawSha256 !== output.base.motionRawSha256 || afterOutput.base.motionCanonicalSha256 !== output.base.motionCanonicalSha256 || !c6B5bSame(c6B5bCurrentInventory(afterSnapshot), currentInventory) || !c6B5bSame(afterInventory, currentInventory) || !c6B5bSame(after, before)) throw new PackageEditTransactionError("copy_mismatch", "C6B5b receipt, inventory, or package changed during installed-output reopen.");
    return Object.freeze({ schema: "shellx-motion/private-checkpoint-storyboard-lifecycle-materialization-installed-output@1", receipt: Object.freeze({ schema: before.schema, fingerprint: before.fingerprint }), package: Object.freeze({ id: output.base.packageId, manifest: Object.freeze({ rawSha256: output.base.manifestRawSha256, canonicalSha256: output.base.manifestCanonicalSha256 }), motion: Object.freeze({ rawSha256: output.base.motionRawSha256, canonicalSha256: output.base.motionCanonicalSha256 }), currentInventory, nonReceiptInventory, preservedLeaves }), storyboard: Object.freeze({ id: before.approval.storyboard.id, sha256: before.approval.storyboard.sha256, revision: before.approval.storyboard.revision }), plan: Object.freeze({ fingerprint: plan.fingerprint }), profile: Object.freeze({ fingerprint: plan.lowererProfile.fingerprint }), layers: Object.freeze({ sourcePrefix: c6B5bPrefixFacts(source.layers), ids: Object.freeze([...before.base.expected.generatedLayerIds]), idsSha256: before.base.expected.generatedLayerIdsSha256, generatedSha256: before.base.expected.generatedLayersSha256, timingSha256: before.base.expected.timingSha256 }), materialization: Object.freeze({ changedMotionRoot: "layers" as const, changedLeafCount: 2 as const, renderer: Object.freeze({ invoked: false as const, pixels: false as const }) }) });
  });
}

function assertReceiptBinding(receipt: CheckpointStoryboardLifecycleMaterializationReceipt, output: Awaited<ReturnType<typeof observeC6B5bPackage>>): void {
  const source = receipt.base.expected;
  if (!c6B5bSame(source, receipt.base.reopened) || output.base.packageId !== receipt.output.packageId || output.base.packageId !== source.packageId || output.base.manifestRawSha256 !== receipt.output.manifestRawSha256 || receipt.output.manifestRawSha256 !== source.manifestRawSha256 || output.base.manifestCanonicalSha256 !== source.manifestCanonicalSha256 || output.base.motionRawSha256 !== receipt.output.motionRawSha256 || output.base.motionCanonicalSha256 !== receipt.output.canonicalMotionSha256 || output.base.motionCanonicalSha256 !== source.outputCanonicalMotionSha256 || receipt.approval.plan.fingerprint !== source.planFingerprint || receipt.approval.plan.lowererProfile.fingerprint !== source.profileFingerprint || receipt.approval.storyboard.id !== source.storyboardId || receipt.approval.storyboard.sha256 !== source.storyboardSha256 || receipt.approval.storyboard.revision !== source.storyboardRevision || receipt.renderer.invoked !== false || receipt.renderer.pixels !== false) throw new PackageEditTransactionError("copy_mismatch", "C6B5b reopened package identity differs from its fixed receipt.");
}
function reconstructSource(output: MotionDocument, receipt: CheckpointStoryboardLifecycleMaterializationReceipt): MotionDocument {
  const count = receipt.base.expected.sourceLayerPrefixCount, suffix = output.layers.slice(count); if (count < 0 || output.layers.length !== count + receipt.base.expected.generatedLayerIds.length || c6B5bPrefixFacts(output.layers.slice(0, count)).sha256 !== receipt.base.expected.sourceLayerPrefixSha256 || suffix.some((layer, index) => layer.id !== receipt.base.expected.generatedLayerIds[index])) throw new PackageEditTransactionError("copy_mismatch", "C6B5b output cannot reconstruct its sealed source layer prefix.");
  const source = structuredClone(output) as MotionDocument; source.layers = output.layers.slice(0, count); if (canonicalJsonSha256(source) !== receipt.base.expected.motionCanonicalSha256) throw new PackageEditTransactionError("copy_mismatch", "C6B5b reconstructed source Motion identity differs from its receipt."); return source;
}
async function assertCompleteMotion(motion: MotionDocument): Promise<void> { const validation = await validateDocument(await loadSchema("motion"), motion), procedural = motion.relationships ? validateMotionProceduralGraph(motion.relationships, motion) : { ok: true }, behaviors = validateMotionBehaviors(motion.behaviors, motion), relations = validateMotionRelations(motion.relations, motion), actions = Object.hasOwn(motion, "relationActions") ? validateMotionRelationActions(motion.relationActions) : { ok: true }; if (!validation.ok || !procedural.ok || !behaviors.ok || !relations.ok || !actions.ok) throw new PackageEditTransactionError("copy_mismatch", "C6B5b reopened output has an invalid Motion authority graph."); }
async function recompile(receipt: CheckpointStoryboardLifecycleMaterializationReceipt, manifest: unknown, motion: MotionDocument): Promise<C6B5bPlanEvidence> {
  try { return compileCheckpointStoryboardLifecycleProfilePlan({ schema: "shellx-motion/private-checkpoint-storyboard-lifecycle-profile-request@1", storyboard: receipt.approval.storyboard.record, base: { packageId: receipt.base.expected.packageId, manifest, motion, persistedMotionSha256: receipt.base.expected.motionRawSha256 } }); }
  catch (error) { throw new PackageEditTransactionError("copy_mismatch", `C6B5b output cannot recompile its sealed lifecycle plan: ${message(error)}`); }
}
async function withOutputWorkspaceAuthority<T>(host: CheckpointStoryboardLifecycleMaterializationOutputHost, operation: (outputRoot: string, canonicalHost: CheckpointStoryboardLifecycleMaterializationOutputHost) => Promise<T>): Promise<T> {
  const workspaceRoot = resolve(host.packageWorkspaceRoot), outputSpelling = resolve(host.outputPackageRoot); if (!strictDescendant(workspaceRoot, outputSpelling)) throw new PackageEditTransactionError("unsafe_output", "C6B5b output must be a strict descendant of the host workspace.");
  try { await assertTrustedWorkspaceAnchorPath(host.packageWorkspaceAuthority, workspaceRoot); } catch (error) { throw new PackageEditTransactionError("unsafe_output", `C6B5b output workspace authority is invalid: ${message(error)}`); }
  return await withTrustedWorkspaceAnchor(host.packageWorkspaceAuthority, async () => { const before = await lstat(outputSpelling); if (!before.isDirectory() || before.isSymbolicLink()) throw new PackageEditTransactionError("unsafe_output", "C6B5b output package root is not a trusted directory."); const outputRoot = await realpath(outputSpelling).catch((error) => { throw new PackageEditTransactionError("unsafe_output", `C6B5b output package root cannot be canonicalized: ${message(error)}`); }); if (outputRoot !== outputSpelling || !strictDescendant(workspaceRoot, outputRoot)) throw new PackageEditTransactionError("unsafe_output", "C6B5b output package root must be a canonical strict workspace descendant without intermediate symlinks."); const after = await lstat(outputRoot); if (!after.isDirectory() || after.isSymbolicLink() || after.dev !== before.dev || after.ino !== before.ino) throw new PackageEditTransactionError("unsafe_output", "C6B5b output package root changed while canonicalizing."); return await operation(outputRoot, Object.freeze({ outputPackageRoot: outputRoot, packageWorkspaceRoot: workspaceRoot, packageWorkspaceAuthority: host.packageWorkspaceAuthority })); });
}
function strictDescendant(root: string, path: string): boolean { const suffix = relative(root, path); return suffix !== "" && suffix !== ".." && !suffix.startsWith(`..${sep}`) && !isAbsolute(suffix); }
function message(error: unknown): string { return error instanceof Error ? error.message : String(error); }
