/**
 * The keyframe-target vocabulary: which targets exist, and which value family each one belongs to.
 *
 * Lifted out of `timeline.ts` unchanged. It is 150 lines of pure data with no behaviour, and its
 * presence there was the largest single block standing between that file and its size budget; the
 * evaluator reads these sets, it does not define them.
 *
 * KNOWN SECOND COPY — `validate.ts` declares its own `SUPPORTED_KEYFRAME_TARGETS`,
 * `NON_NEGATIVE_KEYFRAME_TARGETS`, `PAN_KEYFRAME_TARGETS`, `BLEND_MODE_KEYFRAME_TARGETS`,
 * `POSITIVE_KEYFRAME_TARGETS`, `COLOR_KEYFRAME_TARGETS` and the two alignment value tuples, and they
 * are byte-identical to the ones here today (checked when this module was created). That duplication
 * predates this module and converting the validator to read from here is a separate change with its
 * own regression surface, so it is named here rather than silently half-done: there were two copies
 * before, there are two copies now, and this is the one the evaluator uses.
 *
 * Dependencies: `./types` only (type-level). Primary callers: `./timeline`.
 */
import type { MotionKeyframeTarget } from "./types";

/** Canonical accepted-keyframe-target list; exported so published contracts advertise it without a drifting copy. */
export const SUPPORTED_KEYFRAME_TARGET_LIST: MotionKeyframeTarget[] = [
  "transform.x",
  "transform.y",
  "transform.width",
  "transform.height",
  "transform.originX",
  "transform.originY",
  "transform.scale",
  "transform.rotation",
  "opacity",
  "volume",
  "pan",
  "blendMode",
  "playbackRate",
  "fill",
  "style.fill",
  "style.color",
  "style.stroke",
  "style.borderColor",
  "style.backgroundColor",
  "style.background",
  "style.strokeWidth",
  "style.borderWidth",
  "style.fontSize",
  "style.fontWeight",
  "style.letterSpacing",
  "style.textAlign",
  "style.verticalAlign",
  "style.alignY",
  "style.lineHeight",
  "style.width",
  "style.height",
  "style.radius",
  "style.borderRadius",
  "style.padding",
  "style.paddingX",
  "style.paddingY",
  "style.paddingTop",
  "style.paddingRight",
  "style.paddingBottom",
  "style.paddingLeft",
  "mask.inset.top",
  "mask.inset.right",
  "mask.inset.bottom",
  "mask.inset.left",
  "crop.x",
  "crop.y",
  "crop.width",
  "crop.height",
  "style.shadow.x",
  "style.shadow.y",
  "style.shadow.offsetX",
  "style.shadow.offsetY",
  "style.shadow.blur",
  "style.shadow.spread",
  "style.shadow.blurRadius",
  "style.shadow.spreadRadius",
  "style.shadow.color",
  "style.textShadow.x",
  "style.textShadow.y",
  "style.textShadow.offsetX",
  "style.textShadow.offsetY",
  "style.textShadow.blur",
  "style.textShadow.blurRadius",
  "style.textShadow.color",
  "effects.blur",
  "effects.brightness",
  "effects.contrast",
  "effects.saturate",
  "effects.grayscale",
  "effects.glow.radius",
  "effects.glow.color",
  "gradient.angle",
  "environment.intensity",
  "environment.wind",
  "environment.dropSpeed",
  "environment.dropLength",
  "environment.ground.horizon",
  "environment.ground.wetness",
  "environment.ground.roughness",
  "environment.ground.rippleAmount",
  "environment.ground.splashAmount",
  "environment.ground.reflectionStrength",
  "environment.atmosphere.mist",
  "environment.atmosphere.lensDroplets",
  "environment.surface.horizon",
  "environment.surface.waveScale",
  "environment.surface.waveHeight",
  "environment.surface.waveSpeed",
  "environment.surface.direction",
  "environment.surface.choppiness",
  "environment.optics.reflectionStrength",
  "environment.optics.refractionStrength",
  "environment.optics.fresnel",
  "environment.optics.caustics",
  "environment.optics.clarity",
  "environment.optics.foam",
  "environment.fall.intensity",
  "environment.fall.speed",
  "environment.fall.wind",
  "environment.fall.turbulence",
  "environment.fall.flakeSize",
  "environment.fall.focusFalloff",
  "environment.ground.accumulation",
  "environment.ground.drift",
  "environment.ground.contactAmount",
  "environment.atmosphere.haze",
  "environment.atmosphere.depthFade",
  "environment.fog.density",
  "environment.fog.speed",
  "environment.fog.scale",
  "environment.fog.turbulence",
  "environment.fog.height",
  "environment.fog.lightStrength"
];
export const SUPPORTED_KEYFRAME_TARGETS: ReadonlySet<string> = new Set(SUPPORTED_KEYFRAME_TARGET_LIST);
export const NON_NEGATIVE_KEYFRAME_TARGETS = new Set<MotionKeyframeTarget>([
  "volume",
  "style.width",
  "style.height",
  "style.radius",
  "style.borderRadius",
  "style.padding",
  "style.paddingX",
  "style.paddingY",
  "style.paddingTop",
  "style.paddingRight",
  "style.paddingBottom",
  "style.paddingLeft",
  "mask.inset.top",
  "mask.inset.right",
  "mask.inset.bottom",
  "mask.inset.left",
  "crop.x",
  "crop.y",
  "style.strokeWidth",
  "style.borderWidth",
  "style.shadow.blur",
  "style.shadow.spread",
  "style.shadow.blurRadius",
  "style.shadow.spreadRadius",
  "style.textShadow.blur",
  "style.textShadow.blurRadius",
  "effects.blur",
  "effects.brightness",
  "effects.contrast",
  "effects.saturate",
  "effects.grayscale",
  "effects.glow.radius"
]);
export const PAN_KEYFRAME_TARGETS = new Set<MotionKeyframeTarget>(["pan"]);
export const BLEND_MODE_KEYFRAME_TARGETS = new Set<MotionKeyframeTarget>(["blendMode"]);
export const POSITIVE_KEYFRAME_TARGETS = new Set<MotionKeyframeTarget>(["playbackRate", "style.fontSize", "style.fontWeight", "style.lineHeight", "crop.width", "crop.height"]);
export const COLOR_KEYFRAME_TARGETS = new Set<MotionKeyframeTarget>(["fill", "style.fill", "style.color", "style.stroke", "style.borderColor", "style.backgroundColor", "style.background", "style.shadow.color", "style.textShadow.color", "effects.glow.color"]);
export const TEXT_ALIGN_KEYFRAME_VALUES = ["left", "center", "right"] as const;
export const VERTICAL_ALIGN_KEYFRAME_VALUES = ["top", "middle", "center", "bottom"] as const;
export const DISCRETE_STRING_KEYFRAME_TARGETS = new Set<MotionKeyframeTarget>(["blendMode", "style.textAlign", "style.verticalAlign", "style.alignY"]);
