/**
 * The public two-stage contract for `shellx-motion/motion@1` validation.
 *
 * JSON Schema can describe a portable document's local shape. It cannot prove
 * document-wide properties such as cross references, graph validity, shared
 * execution budgets, or whether a renderer can produce an artifact. Keep
 * those distinct questions named and ordered here rather than letting each
 * product surface imply a different guarantee.
 */
export const MOTION_VALIDATION_CONTRACT = "shellx-motion/motion-validation@1" as const;

export const MOTION_VALIDATION_STAGE_ORDER = ["structural", "semantic"] as const;
export type MotionValidationStage = (typeof MOTION_VALIDATION_STAGE_ORDER)[number];
export type MotionValidationStageStatus = "passed" | "failed" | "not_run";

/** Stable response vocabulary shared by the CLI, Debug API/MCP, and local SDK. */
export type MotionValidationReport = {
  contract: typeof MOTION_VALIDATION_CONTRACT;
  /** Validation never proves a rendered artifact; inspect a render receipt for that evidence. */
  renderability: "not_proven";
} & (
  | { structural: "failed"; semantic: "not_run" }
  | { structural: "passed"; semantic: "failed" | "passed" }
);

export interface MotionValidationStageDefinition {
  id: MotionValidationStage;
  authority: string;
  scope: string;
}

/**
 * Code-owned public wording. Both the generated JSON Schema and generated
 * validation guide consume these definitions, so their scope cannot drift.
 */
export const MOTION_VALIDATION_STAGES: readonly MotionValidationStageDefinition[] = [
  {
    id: "structural",
    authority: "schemas/motion.schema.json",
    scope: "Portable JSON shape, required fields, primitive bounds, and declared built-in payload forms."
  },
  {
    id: "semantic",
    authority: "packages/core/src/validate.ts",
    scope: "Document-wide graph integrity, cross references, ordering, renderer constraints, and execution budgets."
  }
] as const;

/** Generated-schema comment, intentionally derived from the stable contract above. */
export function motionValidationSchemaComment(): string {
  return `${MOTION_VALIDATION_CONTRACT}: structural JSON Schema is stage 1 only; stage 2 runtime semantic validation is authoritative for document-wide graph, cross-reference, ordering, renderer, and execution-budget invariants. A structural pass does not prove renderability or a rendered artifact.`;
}

/** Make a response report without inventing a renderability success claim. */
export function motionValidationReport(failedStage?: MotionValidationStage): MotionValidationReport {
  if (failedStage === "structural") {
    return {
      contract: MOTION_VALIDATION_CONTRACT,
      structural: "failed",
      semantic: "not_run",
      renderability: "not_proven"
    };
  }
  if (failedStage === "semantic") {
    return {
      contract: MOTION_VALIDATION_CONTRACT,
      structural: "passed",
      semantic: "failed",
      renderability: "not_proven"
    };
  }
  return {
    contract: MOTION_VALIDATION_CONTRACT,
    structural: "passed",
    semantic: "passed",
    renderability: "not_proven"
  };
}

/** Generated public guide from the same authority as the schema comment. */
export function renderMotionValidationGuide(): string {
  const [structural, semantic] = MOTION_VALIDATION_STAGES;
  return `# Motion document validation\n\n` +
    `> Generated from \`packages/core/src/motion-validation-contract.ts\`. Do not edit this file directly.\n\n` +
    `Motion document validation follows [\`${MOTION_VALIDATION_CONTRACT}\`](../../schemas/motion.schema.json). Its stages always run in this order:\n\n` +
    `1. **${structural.id}** — ${structural.scope} Authority: \`${structural.authority}\`.\n` +
    `2. **${semantic.id}** — ${semantic.scope} Authority: \`${semantic.authority}\`.\n\n` +
    `A passing JSON Schema check is **not** proof that a package is renderable. A passing two-stage validation is also **not** proof of a rendered artifact; run preview or render and inspect its receipt for renderer/output evidence.\n\n` +
    `The CLI, Debug API/MCP, and local SDK expose the same completed validation report vocabulary: \`failed/not_run\` for structural failure, \`passed/failed\` for semantic failure, or \`passed/passed\` for a two-stage pass; \`renderability\` remains \`not_proven\` until a render receipt is inspected.\n\n` +
    `Regenerate: \`pnpm docs:validation\` · Verify: \`pnpm docs:check\`\n`;
}
