import { PUBLIC_SCHEMA_EXTENSION_COMMENT as EXTENSION_COMMENT } from "./motion-public-schema-environments";
import { buildLayerDefinitions } from "./motion-public-schema-layers";
import { buildLayoutApplicationDefinitions } from "./motion-public-schema-layout-applications";
import { buildMotionLayoutGapAnimationDefinitions } from "./motion-layout-gap-animation-public-schema";
import { buildMotionBehaviorDefinitions } from "./motion-public-schema-behaviors";
import { buildMotionRelationDefinitions } from "./motion-public-schema-relations";
import { buildMotionRelationActionDefinitions } from "./motion-relation-actions-public-schema";
import { buildMotionScene3DAnimationDefinitions } from "./motion-scene3d-animation-public-schema";
import { motionValidationSchemaComment } from "./motion-validation-contract";

/**
 * The public identity and root required fields for a Motion document.
 *
 * `validate-schemas.ts` consumes these values too, so the hand-written runtime
 * validator and the generated public contract cannot drift on document identity
 * or root structure. Detailed runtime validation remains in `validate.ts`: it
 * preserves the existing path-specific errors and is deliberately not invoked by
 * this generation-only module.
 */
export const MOTION_DOCUMENT_SCHEMA = "shellx-motion/motion@1" as const;
export const MOTION_DOCUMENT_REQUIRED = [
  "schema",
  "id",
  "name",
  "durationMs",
  "fps",
  "width",
  "height",
  "layers",
  "assets",
  "provenance"
] as const;

const COLOR = { type: "string", minLength: 1 };

/**
 * Builds the canonical published JSON Schema for `shellx-motion/motion@1`.
 *
 * Keep this module data-only. It is imported by `contracts:generate` and by the
 * runtime schema registry, but never by the render hot path. The generated file
 * is `schemas/motion.schema.json`; `contracts:check` compares its exact bytes to
 * this result so hand-editing the published contract cannot silently drift.
 */
export function buildMotionPublicSchema(): Record<string, unknown> {
  return {
    $schema: "https://json-schema.org/draft/2020-12/schema",
    $id: MOTION_DOCUMENT_SCHEMA,
    $comment: `Generated by packages/core/src/motion-public-schema.ts. ${motionValidationSchemaComment()} Objects deliberately remain open to x-* extension namespaces; the schema narrows portable fields that are safe to validate without document-wide reference or budget analysis.`,
    type: "object",
    required: [...MOTION_DOCUMENT_REQUIRED],
    properties: {
      schema: { const: MOTION_DOCUMENT_SCHEMA },
      id: { type: "string", minLength: 1 },
      name: { type: "string", minLength: 1 },
      durationMs: { type: "number", exclusiveMinimum: 0 },
      fps: { type: "number", exclusiveMinimum: 0 },
      width: { type: "integer", exclusiveMinimum: 0 },
      height: { type: "integer", exclusiveMinimum: 0 },
      background: COLOR,
      audio: { $ref: "#/$defs/audioDocument" },
      provenance: {
        type: "object",
        properties: {
          sourceApp: { type: "string", minLength: 1 },
          createdBy: { type: "string", minLength: 1 },
          workflow: { type: "string", minLength: 1 },
          sourceSchema: { type: "string", minLength: 1 },
          projectId: { type: "string", minLength: 1 },
          selectedFrameId: { type: "string", minLength: 1 },
          integrationProtocol: { type: "integer", minimum: 0 },
          compatibilityAdapter: { type: "string", minLength: 1 },
          dataRowId: { type: "string", minLength: 1 },
          dataRowKey: { type: "string", minLength: 1 },
          dataRowHash: { type: "string", minLength: 1 }
        },
        $comment: EXTENSION_COMMENT
      },
      safeAreas: {
        type: "object",
        additionalProperties: { $ref: "#/$defs/safeArea" },
        $comment: "Safe-area identifiers are document-defined; each value may carry x-* extensions."
      },
      tracks: { type: "array", items: { $ref: "#/$defs/track" } },
      scenes: { type: "array", items: { $ref: "#/$defs/scene" } },
      markers: { type: "array", items: { $ref: "#/$defs/marker" } },
      layoutApplications: { type: "array", maxItems: 16, items: { $ref: "#/$defs/layoutApplication" } },
      layoutGapAnimation: { $ref: "#/$defs/motionLayoutGapAnimation" },
      behaviors: { $ref: "#/$defs/motionBehaviors" },
      relations: { $ref: "#/$defs/motionRelations" },
      scene3dAnimation: { $ref: "#/$defs/motionScene3dAnimation" },
      relationActions: { $ref: "#/$defs/motionRelationActions" },
      layers: { type: "array", items: { $ref: "#/$defs/layer" } },
      assets: { type: "array", items: { $ref: "#/$defs/asset" } }
    },
    $defs: {
      safeArea: {
        type: "object",
        properties: {
          top: { type: "number", minimum: 0 },
          right: { type: "number", minimum: 0 },
          bottom: { type: "number", minimum: 0 },
          left: { type: "number", minimum: 0 }
        },
        $comment: EXTENSION_COMMENT
      },
      track: {
        type: "object",
        required: ["id", "type"],
        properties: {
          id: { type: "string", minLength: 1 },
          type: { type: "string", minLength: 1 },
          name: { type: "string" },
          order: { type: "number" },
          layerIds: { type: "array", items: { type: "string", minLength: 1 } },
          locked: { type: "boolean" },
          muted: { type: "boolean" },
          solo: { type: "boolean" },
          volume: { type: "number", minimum: 0 },
          pan: { type: "number", minimum: -1, maximum: 1 },
          fadeInMs: { type: "number", minimum: 0 },
          fadeOutMs: { type: "number", minimum: 0 }
        },
        $comment: EXTENSION_COMMENT
      },
      audioDocument: {
        type: "object",
        properties: { master: { $ref: "#/$defs/audioMaster" } },
        additionalProperties: false
      },
      audioMaster: {
        type: "object",
        properties: {
          volume: { type: "number", minimum: 0, maximum: 4 },
          fadeInMs: { type: "number", minimum: 0 },
          fadeOutMs: { type: "number", minimum: 0 },
          fadeCurve: { enum: ["linear", "equal-power"] },
          loudness: { $ref: "#/$defs/audioLoudnessTarget" }
        },
        minProperties: 1,
        additionalProperties: false,
        $comment: "A document-level final-program control. A declared loudness target is realized by fixed single-pass loudnorm and independently verified by delivered-media readback."
      },
      audioLoudnessTarget: {
        type: "object",
        required: ["integratedLufs", "toleranceLufs", "maxTruePeakDbtp"],
        properties: {
          integratedLufs: { type: "number", minimum: -70, maximum: -5 },
          toleranceLufs: { type: "number", minimum: 0, maximum: 24 },
          maxTruePeakDbtp: { type: "number", minimum: -9, maximum: 0 },
          maxLoudnessRangeLu: { type: "number", minimum: 1, maximum: 50 }
        },
        additionalProperties: false
      },
      scene: {
        type: "object",
        required: ["id", "startMs", "durationMs"],
        properties: {
          id: { type: "string", minLength: 1 },
          name: { type: "string" },
          startMs: { type: "number", minimum: 0 },
          durationMs: { type: "number", exclusiveMinimum: 0 },
          layerIds: { type: "array", items: { type: "string", minLength: 1 } },
          trackIds: { type: "array", items: { type: "string", minLength: 1 } },
          markerIds: { type: "array", items: { type: "string", minLength: 1 } }
        },
        $comment: EXTENSION_COMMENT
      },
      marker: {
        type: "object",
        required: ["id", "atMs"],
        properties: {
          id: { type: "string", minLength: 1 },
          atMs: { type: "number", minimum: 0 },
          label: { type: "string" },
          type: { type: "string" },
          durationMs: { type: "number", minimum: 0 },
          color: COLOR
        },
        $comment: EXTENSION_COMMENT
      },
      asset: {
        $comment: "Most asset families are host-defined. Font and restricted shader assets have validator-owned portable structure and are narrowed here; other asset records remain open.",
        allOf: [
          { $ref: "#/$defs/fontAsset" },
          { $ref: "#/$defs/shaderAsset" }
        ]
      },
      fontAsset: {
        if: {
          type: "object",
          required: ["type"],
          properties: { type: { const: "font" } }
        },
        then: {
          type: "object",
          required: ["id", "type", "family", "source"],
          properties: {
            id: { type: "string", pattern: "^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$" },
            type: { const: "font" },
            family: { type: "string", pattern: "^[A-Za-z0-9][A-Za-z0-9 ._-]{0,127}$" },
            source: {
              type: "object",
              required: ["path", "mimeType"],
              properties: {
                path: { type: "string", minLength: 1 },
                mimeType: { enum: ["font/woff2", "font/woff", "font/ttf", "font/otf"] }
              },
              $comment: EXTENSION_COMMENT
            },
            weight: { type: "integer", minimum: 1, maximum: 1000 },
            style: { enum: ["normal", "italic", "oblique"] }
          },
          $comment: EXTENSION_COMMENT
        }
      },
      shaderAsset: {
        if: {
          type: "object",
          required: ["type"],
          properties: { type: { const: "shader" } }
        },
        then: {
          type: "object",
          required: ["id", "type", "source"],
          properties: {
            id: { type: "string", pattern: "^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$" },
            type: { const: "shader" },
            source: {
              type: "object",
              required: ["path", "mimeType"],
              properties: {
                path: { type: "string", minLength: 1 },
                mimeType: { const: "text/x-shellx-motion-glsl" }
              },
              $comment: EXTENSION_COMMENT
            }
          },
          $comment: EXTENSION_COMMENT
        }
      },
      ...buildLayerDefinitions(),
      ...buildLayoutApplicationDefinitions(),
      ...buildMotionLayoutGapAnimationDefinitions(),
      ...buildMotionBehaviorDefinitions(),
      ...buildMotionRelationDefinitions(),
      ...buildMotionScene3DAnimationDefinitions(),
      ...buildMotionRelationActionDefinitions()
    }
  };
}
