import type { GpuRuntimeFailure } from "./gpu-runtime-types";
import type { GpuPageScene3dGltfPbrPipelineIdentity } from "./gpu-page-scene3d-gltf-pbr-pipeline";

export const GPU_PAGE_SCENE3D_GLTF_PBR_RESOURCE_SCHEMA = "shellx-motion/gpu-page-scene3d-gltf-pbr-resources@1" as const;

export interface GpuPageScene3dGltfPbrTextureInput {
  readonly resourceId: string; readonly assetRef: string; readonly encodedSha256: string; readonly decodedRgbaSha256: string;
  readonly width: number; readonly height: number; readonly decodedRgbaByteLength: number; readonly mipLevelCount: number; readonly mipmappedRgbaByteLength: number; readonly rgbaBase64: string;
}
export interface GpuPageScene3dGltfPbrPrimitiveInput {
  readonly id: string; readonly sourceSha256: string; readonly textureResourceId: string; readonly vertexCount: number; readonly indexCount: number;
  readonly vertexBufferSha256: string; readonly vertexBufferByteLength: number; readonly indexBufferSha256: string; readonly indexBufferByteLength: number; readonly verticesBase64: string; readonly indicesBase64: string;
  readonly modelMatrix: readonly number[]; readonly material: { readonly baseColorFactor: readonly [number, number, number, number]; readonly metallicFactor: number; readonly roughnessFactor: number; readonly emissiveFactor: readonly [number, number, number] };
}
export interface GpuPageScene3dGltfPbrResourceInput {
  readonly schema: typeof GPU_PAGE_SCENE3D_GLTF_PBR_RESOURCE_SCHEMA; readonly staticFingerprint: string; readonly frameFingerprint: string; readonly sourceSha256: string;
  readonly pbr: { readonly abi: "shellx-motion/browser-scene3d-gltf-pbr-sdr@1"; readonly baseColorTextureFormat: "rgba8unorm-srgb"; readonly baseColorTextureTransfer: "srgb-to-linear-hardware"; readonly factorSpace: "linear-gltf"; readonly brdf: "ggx-smith-schlick-directional@1"; readonly ambient: "bounded-diffuse@1"; readonly directionalLight: { readonly direction: readonly [-0.4, -0.8, -0.4]; readonly color: readonly [1, 1, 1]; readonly intensity: 1; readonly ambientDiffuse: 0.15 }; readonly outputTransfer: "linear-to-srgb-explicit" };
  readonly pipeline: GpuPageScene3dGltfPbrPipelineIdentity; readonly textures: readonly GpuPageScene3dGltfPbrTextureInput[]; readonly primitives: readonly GpuPageScene3dGltfPbrPrimitiveInput[];
  readonly camera: { readonly viewport: { readonly width: 1280; readonly height: 720 }; readonly projection: "perspective@1"; readonly fovDeg: 42; readonly near: number; readonly far: number; readonly position: readonly [number, number, number]; readonly target: readonly [number, number, number]; readonly viewProjection: readonly number[] };
  readonly budget: { readonly vertexBufferBytes: number; readonly indexBufferBytes: number; readonly uniformBufferBytes: number; readonly decodedTextureBytes: number; readonly mipmappedTextureBytes: number; readonly gpuResourceBytes: number; readonly renderTargetBytes: number; readonly depthTargetBytes: number; readonly readbackBufferBytes: number; readonly frameGpuResourceBytes: number; readonly peakGpuResourceBytes: number };
}
export interface GpuPageScene3dGltfPbrResourceMetrics {
  readonly schema: "shellx-motion/gpu-page-scene3d-gltf-pbr-resource-metrics@1"; readonly staticFingerprint: string; readonly textureSlots: number; readonly textureBytes: number; readonly vertexBufferSlots: number; readonly vertexBufferBytes: number; readonly indexBufferSlots: number; readonly indexBufferBytes: number; readonly uniformBufferSlots: number; readonly uniformBufferBytes: number; readonly bindGroupSlots: number; readonly renderTargetSlots: 1; readonly renderTargetBytes: number; readonly depthTargetSlots: 1; readonly depthTargetBytes: number; readonly readbackBufferBytes: number; readonly peakGpuResourceBytes: number; readonly mipGenerationPasses: number; readonly preparationOperations: 1; readonly renderedFrames: number; readonly lateAllocationRefusals: number; readonly retainedFrameAllocations: 0; readonly gpuResourceBytes: number;
}
export type GpuPageScene3dGltfPbrResourceOutput = { readonly ok: true; readonly metrics: GpuPageScene3dGltfPbrResourceMetrics } | { readonly ok: false; readonly failure: GpuRuntimeFailure };
export interface GpuPageScene3dGltfPbrReleaseEvidence { readonly schema: "shellx-motion/gpu-page-scene3d-gltf-pbr-release@1"; readonly reason: "terminal" | "cancelled"; readonly hadResources: boolean; readonly destroyedTextures: number; readonly destroyedVertexBuffers: number; readonly destroyedIndexBuffers: number; readonly destroyedUniformBuffers: number; readonly destroyedRenderTargets: 0 | 2; readonly releasedGpuResourceBytes: number; readonly remainingGpuResourceBytes: 0; }

/** Creates bounded immutable PBR resources and all mip levels once; no frame call can grow them. */
export async function prepareWebGpuPageSessionScene3dGltfPbrResources(input: GpuPageScene3dGltfPbrResourceInput): Promise<GpuPageScene3dGltfPbrResourceOutput> {
  type BufferFacade = { destroy?(): void };
  type TextureFacade = { createView(value?: unknown): unknown; destroy?(): void };
  type Pipeline = { getBindGroupLayout(index: number): unknown };
  type Device = { createTexture(value: unknown): TextureFacade; createBuffer(value: unknown): BufferFacade; createSampler(value: unknown): unknown; createBindGroup(value: unknown): unknown; createCommandEncoder(): { beginRenderPass(value: unknown): { setPipeline(value: unknown): void; setBindGroup(index: number, value: unknown): void; draw(count: number): void; end(): void }; finish(): unknown }; queue: { writeTexture(target: unknown, data: Uint8Array, layout: unknown, size: unknown): void; writeBuffer(buffer: unknown, offset: number, data: ArrayBufferLike): void; submit(commands: readonly unknown[]): void; onSubmittedWorkDone?(): Promise<void> } };
  type Stored = { texture: TextureFacade; vertex: BufferFacade; index: BufferFacade; uniform: BufferFacade; bindGroup: unknown; indexCount: number };
  type Resources = { staticFingerprint: string; frameFingerprint: string; metrics: GpuPageScene3dGltfPbrResourceMetrics; renderedFrames: number; textures: TextureFacade[]; primitives: Stored[]; target: TextureFacade; depth: TextureFacade };
  type State = { device: Device; limits: { maxTextureDimension2D: number; maxBufferSize: number }; gltfPbrPipeline?: Pipeline; gltfPbrMipPipeline?: Pipeline; gltfPbrPipelineIdentity?: GpuPageScene3dGltfPbrPipelineIdentity; gltfPbrResources?: Resources };
  const browserGlobal = globalThis as unknown as { GPUBufferUsage?: Record<string, number>; GPUTextureUsage?: Record<string, number>; __shellxMotionGpuSessionV1?: State };
  // This function is serialized into Playwright's page, so its ceilings stay self-contained.
  const MAX_TEXTURES = 16, MAX_PRIMITIVES = 16, MAX_TEXTURE_BYTES = 16 * 1024 * 1024, MAX_RESOURCE_BYTES = 48 * 1024 * 1024;
  const state = browserGlobal.__shellxMotionGpuSessionV1, bufferUsage = browserGlobal.GPUBufferUsage, textureUsage = browserGlobal.GPUTextureUsage;
  if (!state?.device || !state.gltfPbrPipeline || !state.gltfPbrMipPipeline || !bufferUsage || !textureUsage) return fail("gpu_device_unavailable", "The fixed glTF PBR pipeline must be installed before its resources.");
  if (![bufferUsage.COPY_DST, bufferUsage.VERTEX, bufferUsage.INDEX, bufferUsage.UNIFORM, textureUsage.COPY_DST, textureUsage.COPY_SRC, textureUsage.TEXTURE_BINDING, textureUsage.RENDER_ATTACHMENT].every((value) => typeof value === "number")) return fail("gpu_render_failed", "The WebGPU device lacks the fixed glTF PBR resource usage flags.");
  const admitted = await admit(input, state.gltfPbrPipelineIdentity, state.limits);
  if (!admitted) return fail("gpu_limits_exceeded", "The fixed glTF PBR resource input is malformed, unverified, or over its resource ceiling.");
  if (state.gltfPbrResources) return state.gltfPbrResources.staticFingerprint === input.staticFingerprint && state.gltfPbrResources.frameFingerprint === input.frameFingerprint ? { ok: true, metrics: state.gltfPbrResources.metrics } : fail("gpu_resource_refused", "The fixed glTF PBR page session permits one static resource identity.");
  const textures: TextureFacade[] = [], primitives: Stored[] = []; let target: TextureFacade | undefined, depth: TextureFacade | undefined;
  try {
    const sampler = state.device.createSampler({ addressModeU: "repeat", addressModeV: "repeat", magFilter: "linear", minFilter: "linear", mipmapFilter: "linear" });
    const texturesById = new Map<string, TextureFacade>(); let mipGenerationPasses = 0;
    for (const texture of input.textures) {
      const rgba = decodeBase64(texture.rgbaBase64, texture.decodedRgbaByteLength);
      const resource = state.device.createTexture({ size: { width: texture.width, height: texture.height, depthOrArrayLayers: 1 }, format: "rgba8unorm-srgb", mipLevelCount: texture.mipLevelCount, usage: textureUsage.COPY_DST | textureUsage.TEXTURE_BINDING | textureUsage.RENDER_ATTACHMENT });
      textures.push(resource); state.device.queue.writeTexture({ texture: resource, mipLevel: 0 }, rgba, { bytesPerRow: texture.width * 4, rowsPerImage: texture.height }, { width: texture.width, height: texture.height, depthOrArrayLayers: 1 });
      for (let level = 1; level < texture.mipLevelCount; level += 1) {
        const bindGroup = state.device.createBindGroup({ layout: state.gltfPbrMipPipeline.getBindGroupLayout(0), entries: [{ binding: 0, resource: resource.createView({ baseMipLevel: level - 1, mipLevelCount: 1 }) }, { binding: 1, resource: sampler }] });
        const encoder = state.device.createCommandEncoder(), pass = encoder.beginRenderPass({ colorAttachments: [{ view: resource.createView({ baseMipLevel: level, mipLevelCount: 1 }), loadOp: "clear", storeOp: "store" }] });
        pass.setPipeline(state.gltfPbrMipPipeline); pass.setBindGroup(0, bindGroup); pass.draw(3); pass.end(); state.device.queue.submit([encoder.finish()]); mipGenerationPasses += 1;
      }
      texturesById.set(texture.resourceId, resource);
    }
    if (state.device.queue.onSubmittedWorkDone) await state.device.queue.onSubmittedWorkDone();
    for (const primitive of input.primitives) {
      const texture = texturesById.get(primitive.textureResourceId); if (!texture) throw new Error("missing admitted texture");
      const vertex = state.device.createBuffer({ size: primitive.vertexBufferByteLength, usage: bufferUsage.COPY_DST | bufferUsage.VERTEX });
      const index = state.device.createBuffer({ size: primitive.indexBufferByteLength, usage: bufferUsage.COPY_DST | bufferUsage.INDEX });
      const uniform = state.device.createBuffer({ size: 256, usage: bufferUsage.COPY_DST | bufferUsage.UNIFORM });
      const vertexBytes = decodeBase64(primitive.verticesBase64, primitive.vertexBufferByteLength), indexBytes = decodeBase64(primitive.indicesBase64, primitive.indexBufferByteLength);
      state.device.queue.writeBuffer(vertex, 0, vertexBytes.buffer); state.device.queue.writeBuffer(index, 0, indexBytes.buffer); state.device.queue.writeBuffer(uniform, 0, uniformData(primitive, input).buffer);
      const bindGroup = state.device.createBindGroup({ layout: state.gltfPbrPipeline.getBindGroupLayout(0), entries: [{ binding: 0, resource: { buffer: uniform } }, { binding: 1, resource: texture.createView() }, { binding: 2, resource: sampler }] });
      primitives.push({ texture, vertex, index, uniform, bindGroup, indexCount: primitive.indexCount });
    }
    target = state.device.createTexture({ size: { width: 1280, height: 720, depthOrArrayLayers: 1 }, format: "rgba8unorm", usage: textureUsage.RENDER_ATTACHMENT | textureUsage.COPY_SRC });
    depth = state.device.createTexture({ size: { width: 1280, height: 720, depthOrArrayLayers: 1 }, format: "depth24plus", usage: textureUsage.RENDER_ATTACHMENT });
    const metrics: GpuPageScene3dGltfPbrResourceMetrics = Object.freeze({ schema: "shellx-motion/gpu-page-scene3d-gltf-pbr-resource-metrics@1", staticFingerprint: input.staticFingerprint, textureSlots: textures.length, textureBytes: input.budget.mipmappedTextureBytes, vertexBufferSlots: primitives.length, vertexBufferBytes: input.budget.vertexBufferBytes, indexBufferSlots: primitives.length, indexBufferBytes: input.budget.indexBufferBytes, uniformBufferSlots: primitives.length, uniformBufferBytes: input.budget.uniformBufferBytes, bindGroupSlots: primitives.length, renderTargetSlots: 1, renderTargetBytes: input.budget.renderTargetBytes, depthTargetSlots: 1, depthTargetBytes: input.budget.depthTargetBytes, readbackBufferBytes: input.budget.readbackBufferBytes, peakGpuResourceBytes: input.budget.peakGpuResourceBytes, mipGenerationPasses, preparationOperations: 1, renderedFrames: 0, lateAllocationRefusals: 0, retainedFrameAllocations: 0, gpuResourceBytes: input.budget.frameGpuResourceBytes });
    state.gltfPbrResources = { staticFingerprint: input.staticFingerprint, frameFingerprint: input.frameFingerprint, metrics, renderedFrames: 0, textures, primitives, target, depth }; return { ok: true, metrics };
  } catch {
    for (const primitive of primitives) { primitive.vertex.destroy?.(); primitive.index.destroy?.(); primitive.uniform.destroy?.(); }
    for (const texture of textures) texture.destroy?.(); target?.destroy?.(); depth?.destroy?.(); return fail("gpu_render_failed", "The fixed glTF PBR page resource preparation failed closed.");
  }

  function fail(code: GpuRuntimeFailure["code"], message: string): GpuPageScene3dGltfPbrResourceOutput { return { ok: false, failure: { code, message } }; }
  function decodeBase64(value: string, expectedBytes: number): Uint8Array { if (typeof value !== "string" || !/^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$/.test(value) || value.length !== Math.ceil(expectedBytes / 3) * 4) throw new Error("base64"); const binary = atob(value), bytes = new Uint8Array(binary.length); if (bytes.byteLength !== expectedBytes) throw new Error("base64 length"); for (let index = 0; index < binary.length; index += 1) bytes[index] = binary.charCodeAt(index); return bytes; }
  function uniformData(primitive: GpuPageScene3dGltfPbrPrimitiveInput, plan: GpuPageScene3dGltfPbrResourceInput): Float32Array { const values = new Float32Array(64); values.set(primitive.modelMatrix, 0); values.set(plan.camera.viewProjection, 16); values.set(primitive.material.baseColorFactor, 32); values.set([...primitive.material.emissiveFactor, primitive.material.metallicFactor], 36); values.set([primitive.material.roughnessFactor, plan.pbr.directionalLight.ambientDiffuse, 0, 0], 40); values.set([...plan.pbr.directionalLight.direction, plan.pbr.directionalLight.intensity], 44); values.set([...plan.pbr.directionalLight.color, 0], 48); values.set([...plan.camera.position, 0], 52); return values; }
  async function byteIdentities(plan: GpuPageScene3dGltfPbrResourceInput): Promise<boolean> {
    try {
      for (const texture of plan.textures) { const rgba = decodeBase64(texture.rgbaBase64, texture.decodedRgbaByteLength); if (await sha256(rgba) !== texture.decodedRgbaSha256) return false; }
      for (const primitive of plan.primitives) {
        const vertices = decodeBase64(primitive.verticesBase64, primitive.vertexBufferByteLength), indices = decodeBase64(primitive.indicesBase64, primitive.indexBufferByteLength);
        if (await sha256(vertices) !== primitive.vertexBufferSha256 || await sha256(indices) !== primitive.indexBufferSha256) return false;
        if (!Array.from(new Float32Array(vertices.buffer)).every(Number.isFinite)) return false;
        const parsedIndices = new Uint32Array(indices.buffer); if (parsedIndices.length !== primitive.indexCount || !Array.from(parsedIndices).every((index) => index < primitive.vertexCount)) return false;
      }
      return true;
    } catch { return false; }
  }
  async function sha256(bytes: Uint8Array): Promise<string> { const cryptoApi = globalThis.crypto; if (!cryptoApi?.subtle) throw new Error("Web Crypto unavailable"); const digest = new Uint8Array(await cryptoApi.subtle.digest("SHA-256", bytes as unknown as BufferSource)); let value = ""; for (const byte of digest) value += byte.toString(16).padStart(2, "0"); return value; }
  async function admit(value: unknown, identity: GpuPageScene3dGltfPbrPipelineIdentity | undefined, limits: State["limits"]): Promise<boolean> {
    if (!value || typeof value !== "object" || !identity) return false; const plan = value as GpuPageScene3dGltfPbrResourceInput;
    if (!exactKeys(plan, ["schema", "staticFingerprint", "frameFingerprint", "sourceSha256", "pbr", "pipeline", "textures", "primitives", "camera", "budget"]) || plan.schema !== "shellx-motion/gpu-page-scene3d-gltf-pbr-resources@1" || !hash(plan.staticFingerprint) || !hash(plan.frameFingerprint) || !hash(plan.sourceSha256) || !pipeline(plan.pipeline, identity) || !pbr(plan.pbr) || !camera(plan.camera) || !Array.isArray(plan.textures) || !Array.isArray(plan.primitives) || plan.textures.length < 1 || plan.textures.length > MAX_TEXTURES || plan.primitives.length < 1 || plan.primitives.length > MAX_PRIMITIVES || !budget(plan.budget)) return false;
    const textureIds = new Set<string>(), primitiveIds = new Set<string>(); let decoded = 0, mipmapped = 0, vertices = 0, indices = 0;
    for (const texture of plan.textures) { if (!textureShape(texture, limits) || textureIds.has(texture.resourceId)) return false; textureIds.add(texture.resourceId); decoded += texture.decodedRgbaByteLength; mipmapped += texture.mipmappedRgbaByteLength; }
    for (const primitive of plan.primitives) { if (!primitiveShape(primitive, limits, textureIds) || primitiveIds.has(primitive.id) || primitive.sourceSha256 !== plan.sourceSha256) return false; primitiveIds.add(primitive.id); vertices += primitive.vertexBufferByteLength; indices += primitive.indexBufferByteLength; }
    return decoded === plan.budget.decodedTextureBytes && mipmapped === plan.budget.mipmappedTextureBytes && vertices === plan.budget.vertexBufferBytes && indices === plan.budget.indexBufferBytes && plan.budget.uniformBufferBytes === plan.primitives.length * 256 && plan.budget.gpuResourceBytes === vertices + indices + plan.budget.uniformBufferBytes + mipmapped && plan.budget.gpuResourceBytes <= MAX_RESOURCE_BYTES && plan.budget.renderTargetBytes === 1280 * 720 * 4 && plan.budget.depthTargetBytes === 1280 * 720 * 4 && plan.budget.readbackBufferBytes === 1280 * 720 * 4 && plan.budget.readbackBufferBytes <= limits.maxBufferSize && plan.budget.frameGpuResourceBytes === plan.budget.gpuResourceBytes + plan.budget.renderTargetBytes + plan.budget.depthTargetBytes && plan.budget.peakGpuResourceBytes === plan.budget.frameGpuResourceBytes + plan.budget.readbackBufferBytes && plan.budget.peakGpuResourceBytes <= 64 * 1024 * 1024 && await byteIdentities(plan);
  }
  function textureShape(value: unknown, limits: State["limits"]): value is GpuPageScene3dGltfPbrTextureInput { if (!value || typeof value !== "object") return false; const texture = value as GpuPageScene3dGltfPbrTextureInput; const decoded = texture.width * texture.height * 4; return exactKeys(texture, ["resourceId", "assetRef", "encodedSha256", "decodedRgbaSha256", "width", "height", "decodedRgbaByteLength", "mipLevelCount", "mipmappedRgbaByteLength", "rgbaBase64"]) && identifier(texture.resourceId) && localRef(texture.assetRef) && hash(texture.encodedSha256) && hash(texture.decodedRgbaSha256) && integer(texture.width, 1, limits.maxTextureDimension2D) && integer(texture.height, 1, limits.maxTextureDimension2D) && Number.isSafeInteger(decoded) && decoded === texture.decodedRgbaByteLength && decoded <= MAX_TEXTURE_BYTES && texture.mipLevelCount === mipLevels(texture.width, texture.height).levels && texture.mipmappedRgbaByteLength === mipLevels(texture.width, texture.height).bytes && typeof texture.rgbaBase64 === "string" && texture.rgbaBase64.length === Math.ceil(decoded / 3) * 4; }
  function primitiveShape(value: unknown, limits: State["limits"], textureIds: ReadonlySet<string>): value is GpuPageScene3dGltfPbrPrimitiveInput { if (!value || typeof value !== "object") return false; const primitive = value as GpuPageScene3dGltfPbrPrimitiveInput; return exactKeys(primitive, ["id", "sourceSha256", "textureResourceId", "vertexCount", "indexCount", "vertexBufferSha256", "vertexBufferByteLength", "indexBufferSha256", "indexBufferByteLength", "verticesBase64", "indicesBase64", "modelMatrix", "material"]) && identifier(primitive.id) && hash(primitive.sourceSha256) && textureIds.has(primitive.textureResourceId) && integer(primitive.vertexCount, 3, 1_048_576) && integer(primitive.indexCount, 3, 3_145_728) && primitive.indexCount % 3 === 0 && primitive.vertexBufferByteLength === primitive.vertexCount * 32 && primitive.indexBufferByteLength === primitive.indexCount * 4 && primitive.vertexBufferByteLength <= limits.maxBufferSize && primitive.indexBufferByteLength <= limits.maxBufferSize && hash(primitive.vertexBufferSha256) && hash(primitive.indexBufferSha256) && typeof primitive.verticesBase64 === "string" && primitive.verticesBase64.length === Math.ceil(primitive.vertexBufferByteLength / 3) * 4 && typeof primitive.indicesBase64 === "string" && primitive.indicesBase64.length === Math.ceil(primitive.indexBufferByteLength / 3) * 4 && arrays(primitive.modelMatrix, 16, -10_000, 10_000) && material(primitive.material); }
  function pbr(value: GpuPageScene3dGltfPbrResourceInput["pbr"]): boolean { return !!value && exactKeys(value, ["abi", "baseColorTextureFormat", "baseColorTextureTransfer", "factorSpace", "brdf", "ambient", "directionalLight", "outputTransfer"]) && value.abi === "shellx-motion/browser-scene3d-gltf-pbr-sdr@1" && value.baseColorTextureFormat === "rgba8unorm-srgb" && value.baseColorTextureTransfer === "srgb-to-linear-hardware" && value.factorSpace === "linear-gltf" && value.brdf === "ggx-smith-schlick-directional@1" && value.ambient === "bounded-diffuse@1" && value.outputTransfer === "linear-to-srgb-explicit" && exactKeys(value.directionalLight, ["direction", "color", "intensity", "ambientDiffuse"]) && JSON.stringify(value.directionalLight) === JSON.stringify({ direction: [-0.4, -0.8, -0.4], color: [1, 1, 1], intensity: 1, ambientDiffuse: 0.15 }); }
  function pipeline(value: unknown, identity: GpuPageScene3dGltfPbrPipelineIdentity): boolean { return !!value && typeof value === "object" && exactKeys(value as Record<string, unknown>, ["abi", "pipelineImplementationSha256", "resourceCeilingSha256"]) && sameIdentity(value as GpuPageScene3dGltfPbrPipelineIdentity, identity); }
  function camera(value: unknown): value is GpuPageScene3dGltfPbrResourceInput["camera"] { if (!value || typeof value !== "object") return false; const camera = value as GpuPageScene3dGltfPbrResourceInput["camera"]; return exactKeys(camera, ["viewport", "projection", "fovDeg", "near", "far", "position", "target", "viewProjection"]) && exactKeys(camera.viewport, ["width", "height"]) && camera.viewport.width === 1280 && camera.viewport.height === 720 && camera.projection === "perspective@1" && camera.fovDeg === 42 && finite(camera.near, 0.01, 100) && finite(camera.far, camera.near + 0.001, 10_000) && arrays(camera.position, 3, -10_000, 10_000) && arrays(camera.target, 3, -10_000, 10_000) && arrays(camera.viewProjection, 16, -1_000_000, 1_000_000); }
  function material(value: GpuPageScene3dGltfPbrPrimitiveInput["material"]): boolean { return !!value && exactKeys(value, ["baseColorFactor", "metallicFactor", "roughnessFactor", "emissiveFactor"]) && arrays(value.baseColorFactor, 4, 0, 1) && value.baseColorFactor[3] === 1 && arrays(value.emissiveFactor, 3, 0, 64) && finite(value.metallicFactor, 0, 1) && finite(value.roughnessFactor, 0, 1); }
  function budget(value: unknown): value is GpuPageScene3dGltfPbrResourceInput["budget"] { return !!value && typeof value === "object" && exactKeys(value as Record<string, unknown>, ["vertexBufferBytes", "indexBufferBytes", "uniformBufferBytes", "decodedTextureBytes", "mipmappedTextureBytes", "gpuResourceBytes", "renderTargetBytes", "depthTargetBytes", "readbackBufferBytes", "frameGpuResourceBytes", "peakGpuResourceBytes"]) && Object.values(value as Record<string, unknown>).every((entry) => integer(entry, 0, 64 * 1024 * 1024)); }
  function mipLevels(width: number, height: number): { levels: number; bytes: number } { let levels = 0, bytes = 0, w = width, h = height; while (true) { levels += 1; bytes += w * h * 4; if (w === 1 && h === 1) return { levels, bytes }; w = Math.max(1, Math.floor(w / 2)); h = Math.max(1, Math.floor(h / 2)); } }
  function sameIdentity(left: GpuPageScene3dGltfPbrPipelineIdentity, right: GpuPageScene3dGltfPbrPipelineIdentity): boolean { return !!left && left.abi === right.abi && left.pipelineImplementationSha256 === right.pipelineImplementationSha256 && left.resourceCeilingSha256 === right.resourceCeilingSha256; }
  function arrays(value: unknown, length: number, minimum: number, maximum: number): boolean { return Array.isArray(value) && value.length === length && value.every((entry) => finite(entry, minimum, maximum)); }
  function finite(value: unknown, minimum: number, maximum: number): value is number { return typeof value === "number" && Number.isFinite(value) && value >= minimum && value <= maximum; }
  function integer(value: unknown, minimum: number, maximum: number): value is number { return typeof value === "number" && Number.isSafeInteger(value) && value >= minimum && value <= maximum; }
  function exactKeys(value: object, expected: readonly string[]): boolean { const actual = Object.keys(value).sort(), wanted = [...expected].sort(); return actual.length === wanted.length && actual.every((key, index) => key === wanted[index]); }
  function hash(value: unknown): value is string { return typeof value === "string" && /^[a-f0-9]{64}$/.test(value); }
  function identifier(value: unknown): value is string { return typeof value === "string" && /^[a-z][a-z0-9-]{0,127}$/.test(value); }
  function localRef(value: unknown): value is string { return typeof value === "string" && /^(?:[a-z0-9][a-z0-9._-]{0,127}\/){0,7}[a-z0-9][a-z0-9._-]{0,127}$/.test(value); }
}

/** Read only metrics from one immutable material preparation; no legacy session metric is widened. */
export function readWebGpuPageSessionScene3dGltfPbrResourceMetrics(): GpuPageScene3dGltfPbrResourceMetrics | null {
  const state = (globalThis as unknown as { __shellxMotionGpuSessionV1?: { gltfPbrResources?: { metrics: GpuPageScene3dGltfPbrResourceMetrics; renderedFrames: number } } }).__shellxMotionGpuSessionV1;
  const resources = state?.gltfPbrResources; return resources ? Object.freeze({ ...resources.metrics, renderedFrames: resources.renderedFrames }) : null;
}

/** Actual terminal/cancellation destruction evidence for the material-only resource owner. */
export function releaseWebGpuPageSessionScene3dGltfPbrResources(reason: "terminal" | "cancelled" = "terminal"): GpuPageScene3dGltfPbrReleaseEvidence {
  type ResourceState = { metrics: GpuPageScene3dGltfPbrResourceMetrics; textures: Array<{ destroy?(): void }>; primitives: Array<{ vertex: { destroy?(): void }; index: { destroy?(): void }; uniform: { destroy?(): void } }>; target: { destroy?(): void }; depth: { destroy?(): void } };
  const state = (globalThis as unknown as { __shellxMotionGpuSessionV1?: { gltfPbrResources?: ResourceState } }).__shellxMotionGpuSessionV1;
  const resources = state?.gltfPbrResources;
  if (!resources) return { schema: "shellx-motion/gpu-page-scene3d-gltf-pbr-release@1", reason, hadResources: false, destroyedTextures: 0, destroyedVertexBuffers: 0, destroyedIndexBuffers: 0, destroyedUniformBuffers: 0, destroyedRenderTargets: 0, releasedGpuResourceBytes: 0, remainingGpuResourceBytes: 0 };
  for (const texture of resources.textures) texture.destroy?.();
  for (const primitive of resources.primitives) { primitive.vertex.destroy?.(); primitive.index.destroy?.(); primitive.uniform.destroy?.(); }
  resources.target.destroy?.(); resources.depth.destroy?.();
  delete state!.gltfPbrResources;
  return { schema: "shellx-motion/gpu-page-scene3d-gltf-pbr-release@1", reason, hadResources: true, destroyedTextures: resources.textures.length, destroyedVertexBuffers: resources.primitives.length, destroyedIndexBuffers: resources.primitives.length, destroyedUniformBuffers: resources.primitives.length, destroyedRenderTargets: 2, releasedGpuResourceBytes: resources.metrics.gpuResourceBytes, remainingGpuResourceBytes: 0 };
}
