import type { InternalGpuFramePlan } from "./gpu-runtime-types";

const MAX_DRAW_BATCHES=2_048,MAX_POINTS=65_536,MAX_COMPUTE_PARTICLE_FIELDS=1,MAX_COMPUTE_PARTICLES=131_072,MAX_TRIANGLE_VERTICES=65_535,MAX_IMAGES=256,MAX_TEXT_DRAWS=128,MAX_TEXT_UTF8_BYTES=64*1024,MAX_TEXT_SURFACE_PIXELS=32*1024*1024,MAX_GRADIENT_STOPS=4_096,MAX_PIXELS=16_777_216,MAX_PLAN_BYTES=4*1024*1024;
const POINT_BYTES=32,TRIANGLE_VERTEX_BYTES=24,IMAGE_VERTEX_BYTES=120,CHROMA_KEY_UNIFORM_BYTES=48,CHROMA_MATTE_CLEANUP_UNIFORM_BYTES=32,TEXT_VERTEX_BYTES=160,GRADIENT_UNIFORM_BYTES=336,STYLED_RECTANGLE_UNIFORM_BYTES=80,COMPOSITE_UNIFORM_BYTES=64,BLUR_UNIFORM_BYTES=16,GLOW_UNIFORM_BYTES=32,MASK_UNIFORM_BYTES=48,ADJUSTMENT_UNIFORM_BYTES=48,EFFECT_MODULE_UNIFORM_BYTES=160,SCENE_3D_VERTEX_BYTES=24,SCENE_3D_INDEX_BYTES=4,SCENE_3D_OBJECT_UNIFORM_BYTES=192,ENVIRONMENT_UNIFORM_BYTES=208,MATERIAL_UNIFORM_BYTES=144;

/** Re-admits the exact finite Core budget record before renderer resources open. */
export function admitGpuFrameBudget(value: unknown): InternalGpuFramePlan["budget"] | null {
  if (!isRecord(value)) return null;
  const rectangleCount = integer(value.rectangleCount, 0, MAX_DRAW_BATCHES), pointCount = integer(value.pointCount, 0, MAX_POINTS), computeParticleFieldCount=integer(value.computeParticleFieldCount,0,MAX_COMPUTE_PARTICLE_FIELDS),computeParticleCount=integer(value.computeParticleCount,0,MAX_COMPUTE_PARTICLES), triangleVertexCount = integer(value.triangleVertexCount, 0, MAX_TRIANGLE_VERTICES), imageCount = integer(value.imageCount, 0, MAX_IMAGES), chromaKeyCount = integer(value.chromaKeyCount, 0, MAX_IMAGES), chromaMatteCleanupCount = integer(value.chromaMatteCleanupCount, 0, 64), chromaMatteCleanupPassCount = integer(value.chromaMatteCleanupPassCount, 0, 64 * 9), textCount = integer(value.textCount, 0, MAX_TEXT_DRAWS), textUtf8Bytes = integer(value.textUtf8Bytes, 0, MAX_TEXT_UTF8_BYTES), textSurfacePixels = integer(value.textSurfacePixels, 0, MAX_TEXT_SURFACE_PIXELS);
  const scene3dCount=integer(value.scene3dCount,0,4),scene3dObjectCount=integer(value.scene3dObjectCount,0,32),scene3dVertexCount=integer(value.scene3dVertexCount,0,8_192),scene3dIndexCount=integer(value.scene3dIndexCount,0,49_152),environmentCount=integer(value.environmentCount,0,32),materialCount=integer(value.materialCount,0,8),gradientStopCount=integer(value.gradientStopCount,0,MAX_GRADIENT_STOPS),pointBufferBytes=integer(value.pointBufferBytes,0,MAX_POINTS*POINT_BYTES),computeParticleBufferBytes=integer(value.computeParticleBufferBytes,0,16*1024*1024),computeParticleComputeDispatchCount=integer(value.computeParticleComputeDispatchCount,0,1),computeParticleRasterPassCount=integer(value.computeParticleRasterPassCount,0,2),triangleBufferBytes=integer(value.triangleBufferBytes,0,MAX_TRIANGLE_VERTICES*TRIANGLE_VERTEX_BYTES),imageVertexBufferBytes=integer(value.imageVertexBufferBytes,0,MAX_IMAGES*IMAGE_VERTEX_BYTES),chromaKeyUniformBytes=integer(value.chromaKeyUniformBytes,0,MAX_IMAGES*CHROMA_KEY_UNIFORM_BYTES),chromaMatteCleanupUniformBytes=integer(value.chromaMatteCleanupUniformBytes,0,64*9*CHROMA_MATTE_CLEANUP_UNIFORM_BYTES),textVertexBufferBytes=integer(value.textVertexBufferBytes,0,MAX_TEXT_DRAWS*IMAGE_VERTEX_BYTES);
  const scene3dVertexBufferBytes=integer(value.scene3dVertexBufferBytes,0,8_192*SCENE_3D_VERTEX_BYTES),scene3dIndexBufferBytes=integer(value.scene3dIndexBufferBytes,0,49_152*SCENE_3D_INDEX_BYTES),scene3dUniformBytes=integer(value.scene3dUniformBytes,0,32*SCENE_3D_OBJECT_UNIFORM_BYTES),environmentUniformBytes=integer(value.environmentUniformBytes,0,32*ENVIRONMENT_UNIFORM_BYTES),materialUniformBytes=integer(value.materialUniformBytes,0,8*MATERIAL_UNIFORM_BYTES),gradientUniformBytes=integer(value.gradientUniformBytes,0,MAX_DRAW_BATCHES*GRADIENT_UNIFORM_BYTES),styledRectangleUniformBytes=integer(value.styledRectangleUniformBytes,0,MAX_DRAW_BATCHES*STYLED_RECTANGLE_UNIFORM_BYTES);
  const blendModeCount=integer(value.blendModeCount,0,MAX_DRAW_BATCHES),colorEffectCount=integer(value.colorEffectCount,0,MAX_DRAW_BATCHES),blurEffectCount=integer(value.blurEffectCount,0,MAX_DRAW_BATCHES),glowEffectCount=integer(value.glowEffectCount,0,MAX_DRAW_BATCHES),maskCount=integer(value.maskCount,0,MAX_DRAW_BATCHES),blurPassCount=integer(value.blurPassCount,0,MAX_DRAW_BATCHES*4),adjustmentCount=integer(value.adjustmentCount,0,MAX_DRAW_BATCHES),motionBlurGroupCount=integer(value.motionBlurGroupCount,0,MAX_DRAW_BATCHES),motionBlurSampleCount=integer(value.motionBlurSampleCount,0,MAX_DRAW_BATCHES*8),groupCount=integer(value.groupCount,0,64),groupMaxDepth=integer(value.groupMaxDepth,0,5),compositeCount=integer(value.compositeCount,0,MAX_DRAW_BATCHES),compositeUniformBytes=integer(value.compositeUniformBytes,0,MAX_DRAW_BATCHES*COMPOSITE_UNIFORM_BYTES),blurUniformBytes=integer(value.blurUniformBytes,0,MAX_DRAW_BATCHES*4*BLUR_UNIFORM_BYTES),glowUniformBytes=integer(value.glowUniformBytes,0,MAX_DRAW_BATCHES*GLOW_UNIFORM_BYTES),maskUniformBytes=integer(value.maskUniformBytes,0,MAX_DRAW_BATCHES*MASK_UNIFORM_BYTES),adjustmentUniformBytes=integer(value.adjustmentUniformBytes,0,MAX_DRAW_BATCHES*ADJUSTMENT_UNIFORM_BYTES),chromaMatteCleanupIntermediateTextureBytes=integer(value.chromaMatteCleanupIntermediateTextureBytes,0,MAX_PIXELS*4*3),compositeIntermediateTextureBytes=integer(value.compositeIntermediateTextureBytes,0,MAX_PIXELS*4*24),estimatedPlanBytes=integer(value.estimatedPlanBytes,0,MAX_PLAN_BYTES);
  const values=[rectangleCount,pointCount,computeParticleFieldCount,computeParticleCount,triangleVertexCount,imageCount,chromaKeyCount,chromaMatteCleanupCount,chromaMatteCleanupPassCount,textCount,textUtf8Bytes,textSurfacePixels,scene3dCount,scene3dObjectCount,scene3dVertexCount,scene3dIndexCount,environmentCount,materialCount,gradientStopCount,pointBufferBytes,computeParticleBufferBytes,computeParticleComputeDispatchCount,computeParticleRasterPassCount,triangleBufferBytes,imageVertexBufferBytes,chromaKeyUniformBytes,chromaMatteCleanupUniformBytes,textVertexBufferBytes,scene3dVertexBufferBytes,scene3dIndexBufferBytes,scene3dUniformBytes,environmentUniformBytes,materialUniformBytes,gradientUniformBytes,styledRectangleUniformBytes,blendModeCount,colorEffectCount,blurEffectCount,glowEffectCount,maskCount,blurPassCount,adjustmentCount,motionBlurGroupCount,motionBlurSampleCount,groupCount,groupMaxDepth,compositeCount,compositeUniformBytes,blurUniformBytes,glowUniformBytes,maskUniformBytes,adjustmentUniformBytes,chromaMatteCleanupIntermediateTextureBytes,compositeIntermediateTextureBytes,estimatedPlanBytes];
  if (values.some((entry) => entry === null)) return null;
  if (computeParticleFieldCount === null || computeParticleCount === null || computeParticleBufferBytes === null) return null;
  if (computeParticleFieldCount === 0 ? computeParticleCount !== 0 || computeParticleBufferBytes !== 0 || computeParticleComputeDispatchCount !== 0 || computeParticleRasterPassCount !== 0 : computeParticleFieldCount !== 1 || computeParticleCount < 100_000 || computeParticleComputeDispatchCount !== 1 || (computeParticleRasterPassCount !== 1 && computeParticleRasterPassCount !== 2)) return null;
  const moduleFieldsPresent = value.effectModuleCount !== undefined || value.effectModuleUniformBytes !== undefined || value.effectModuleTextureLoadCount !== undefined || value.effectModulePassCount !== undefined;
  const effectModuleCount = integer(value.effectModuleCount, 1, 1), effectModuleUniformBytes = integer(value.effectModuleUniformBytes, EFFECT_MODULE_UNIFORM_BYTES, EFFECT_MODULE_UNIFORM_BYTES), effectModuleTextureLoadCount = integer(value.effectModuleTextureLoadCount, 2, 5), effectModulePassCount = integer(value.effectModulePassCount, 1, 1);
  if (moduleFieldsPresent && (effectModuleCount === null || effectModuleUniformBytes === null || effectModuleTextureLoadCount === null || effectModulePassCount === null)) return null;
  return { rectangleCount, pointCount, computeParticleFieldCount, computeParticleCount, triangleVertexCount, imageCount, chromaKeyCount, chromaMatteCleanupCount, chromaMatteCleanupPassCount, textCount, textUtf8Bytes, textSurfacePixels, scene3dCount, scene3dObjectCount, scene3dVertexCount, scene3dIndexCount, environmentCount, materialCount, gradientStopCount, pointBufferBytes, computeParticleBufferBytes, computeParticleComputeDispatchCount, computeParticleRasterPassCount, triangleBufferBytes, imageVertexBufferBytes, chromaKeyUniformBytes, chromaMatteCleanupUniformBytes, textVertexBufferBytes, scene3dVertexBufferBytes, scene3dIndexBufferBytes, scene3dUniformBytes, environmentUniformBytes, materialUniformBytes, gradientUniformBytes, styledRectangleUniformBytes, blendModeCount, colorEffectCount, blurEffectCount, glowEffectCount, maskCount, blurPassCount, adjustmentCount, ...(moduleFieldsPresent ? { effectModuleCount: effectModuleCount!, effectModuleUniformBytes: effectModuleUniformBytes!, effectModuleTextureLoadCount: effectModuleTextureLoadCount!, effectModulePassCount: effectModulePassCount! } : {}), motionBlurGroupCount, motionBlurSampleCount, groupCount, groupMaxDepth, compositeCount, compositeUniformBytes, blurUniformBytes, glowUniformBytes, maskUniformBytes, adjustmentUniformBytes, chromaMatteCleanupIntermediateTextureBytes, compositeIntermediateTextureBytes, estimatedPlanBytes } as InternalGpuFramePlan["budget"];
}

function integer(value: unknown, minimum: number, maximum: number): number | null { return typeof value === "number" && Number.isInteger(value) && value >= minimum && value <= maximum ? value : null; }
function isRecord(value: unknown): value is Record<string, unknown> { return Boolean(value) && typeof value === "object" && !Array.isArray(value); }
