import type {
  GpuScene2dVideoResource,
  GpuVideoFrameRequest,
  GpuVideoSourceSnapshot,
  MotionPackage
} from "@shellx-motion/core";
import type { GpuSessionRgbaImageResource } from "./gpu-runtime-types";

/** A stable page texture slot tied to one Core-owned immutable video source. */
export interface GpuPreviewVideoTextureSlot {
  layerId: string;
  assetRef: string;
  resourceId: string;
  width: number;
  height: number;
  sourceSnapshotSha256: string;
  decodeContractSha256: string;
}

/** Probe facts are scalar evidence only; no media path or decoder crosses into Chromium. */
export interface GpuPreviewVideoProviderProbe {
  snapshots: ReadonlyMap<string, GpuVideoSourceSnapshot>;
  slots: readonly GpuPreviewVideoTextureSlot[];
}

/** One immutable exact-time RGBA result for a request generated by Core. */
export interface GpuPreviewDecodedVideoFrame {
  request: GpuVideoFrameRequest;
  resource: GpuScene2dVideoResource;
  /**
   * Bounded proof of the provider's selected constant-frame-rate decode point.
   * This is preview observation only; it is deliberately separate from Core's
   * requested source time and from any final-render decode contract.
   */
  selection: GpuPreviewCfrFrameSelection;
  /** Exact RGBA bytes that replace the previously reserved page-owned texture in place. */
  upload: GpuSessionRgbaImageResource;
}

export interface GpuPreviewCfrFrameSelection {
  policy: "cfr-floor-request-sourceAtUs-to-stream-pts";
  decodedPts: string;
  timeBase: string;
  frameDurationPts: string;
  decodedPtsUs: string;
}

export interface GpuPreviewDecodedVideoFrameBatch {
  atUs: number;
  frames: readonly GpuPreviewDecodedVideoFrame[];
}

/** Preview-only observation; it cannot attest final staging, encoding, muxing, or audio. */
export interface GpuPreviewVideoFrameProviderEvidence {
  schema: "shellx-motion/gpu-preview-video-frame-provider@1";
  surface: "preview-visual-only";
  sourceCount: number;
  decodedFrameCount: number;
  cache: {
    hits: number;
    misses: number;
    evictions: number;
    deduplicated: number;
    entries: number;
    bytes: number;
    highWaterEntries: number;
    highWaterBytes: number;
    capacityEntries: number;
    capacityBytes: number;
    inFlightBytes: number;
    inFlightHighWaterBytes: number;
  };
}

export interface GpuPreviewVideoProviderCleanupEvidence {
  closed: true;
  releasedFrames: number;
  releasedSources: number;
  privateScratchReleased: true;
}

/**
 * Host-injected exact-time preview seam. It receives Core requests rather than
 * recomputing trim, loops, group-local time, or playback rate in the browser.
 */
export interface GpuPreviewVideoFrameProvider {
  readonly inputHashes: Readonly<Record<string, string>>;
  readonly evidence: Readonly<GpuPreviewVideoFrameProviderEvidence>;
  probe(signal: AbortSignal): Promise<GpuPreviewVideoProviderProbe>;
  framesFor(requests: readonly GpuVideoFrameRequest[], signal: AbortSignal): Promise<GpuPreviewDecodedVideoFrameBatch>;
  close(): Promise<GpuPreviewVideoProviderCleanupEvidence>;
}

export interface GpuPreviewVideoProviderOpenContext {
  pkg: MotionPackage;
  signal: AbortSignal;
}

export type OpenGpuPreviewVideoFrameProvider = (context: GpuPreviewVideoProviderOpenContext) => Promise<GpuPreviewVideoFrameProvider>;
