import { createHash } from "node:crypto";
import { canonicalJsonSha256, type MotionPackage } from "@shellx-motion/core";
import {
  HDR10_DEPTH_BYTES,
  HDR10_MAX_PEAK_GPU_BYTES,
  HDR10_RGBA16FLOAT_BYTES,
  SCENE3D_GLTF_PBR_HDR10_ADMISSION_FINGERPRINT,
  resolveScene3dGltfPbrHdr10FinalRoute,
  type Scene3dGltfPbrHdr10FinalRoute,
} from "@shellx-motion/core/internal/scene3d-gltf-pbr-hdr10-final";
import { resolveScene3dGltfPbrFinalRoute, type Scene3dGltfPbrFinalRoute } from "@shellx-motion/core/internal/scene3d-gltf-pbr-final";
import { GPU_PAGE_SCENE3D_GLTF_PBR_CATALOG } from "./gpu-page-scene3d-gltf-pbr-contract";
import { GPU_PAGE_SCENE3D_GLTF_PBR_HDR10_CATALOG, GPU_PAGE_SCENE3D_GLTF_PBR_HDR10_PIPELINE_IDENTITY } from "./gpu-page-scene3d-gltf-pbr-hdr10-contract";
import { renderWebGpuPageSessionScene3dGltfPbrHdr10Frame } from "./gpu-page-scene3d-gltf-pbr-hdr10-frame";
import { installWebGpuPageSessionScene3dGltfPbrHdr10Pipeline } from "./gpu-page-scene3d-gltf-pbr-hdr10-pipeline";
import { GPU_PAGE_SCENE3D_GLTF_PBR_HDR10_READBACK_SCHEMA, readWebGpuPageSessionScene3dGltfPbrHdr10Frame, type GpuPageScene3dGltfPbrHdr10ReadbackEvidence } from "./gpu-page-scene3d-gltf-pbr-hdr10-readback";
import { prepareWebGpuPageSessionScene3dGltfPbrHdr10Resources, releaseWebGpuPageSessionScene3dGltfPbrHdr10Resources, type GpuPageScene3dGltfPbrHdr10ReleaseEvidence, type GpuPageScene3dGltfPbrHdr10ResourceInput, type GpuPageScene3dGltfPbrHdr10ResourceMetrics } from "./gpu-page-scene3d-gltf-pbr-hdr10-resources";
import { closeWebGpuPageSessionScene3dGltfPbrHdr10, openWebGpuPageSessionScene3dGltfPbrHdr10 } from "./gpu-page-scene3d-gltf-pbr-hdr10-session-page";
import { createGpuScene3dGltfPbrResourceInput, type GpuScene3dGltfPbrPage } from "./gpu-scene3d-gltf-pbr-material-route";
import type { GpuRuntimeFailure } from "./gpu-runtime-types";

export type GpuScene3dGltfPbrHdr10RouteResolution = Readonly<{ readonly kind: "absent" }> | Readonly<{ readonly kind: "present"; readonly hdrRoute: Scene3dGltfPbrHdr10FinalRoute; readonly sdrRoute: Scene3dGltfPbrFinalRoute }>;
export interface GpuScene3dGltfPbrHdr10Page extends GpuScene3dGltfPbrPage {}

/** Reopens both Core routes and cross-binds their catalog/static/frame/source identities before any page call. */
export async function resolveGpuScene3dGltfPbrHdr10Route(pkg: MotionPackage): Promise<GpuScene3dGltfPbrHdr10RouteResolution> {
  const hdr = await resolveScene3dGltfPbrHdr10FinalRoute(pkg, { sdrRendererCatalogSha256: GPU_PAGE_SCENE3D_GLTF_PBR_CATALOG.sha256, hdr10RendererCatalogSha256: GPU_PAGE_SCENE3D_GLTF_PBR_HDR10_CATALOG.sha256 });
  if (hdr.kind === "absent") return Object.freeze({ kind: "absent" });
  const sdr = await resolveScene3dGltfPbrFinalRoute(pkg, GPU_PAGE_SCENE3D_GLTF_PBR_CATALOG.sha256);
  if (sdr.kind !== "present" || !sameRoute(hdr.route, sdr.route)) throw new Error("HDR10 PBR Browser route did not reproduce the authenticated SDR route.");
  return Object.freeze({ kind: "present", hdrRoute: hdr.route, sdrRoute: sdr.route });
}

/** Crosses the authenticated Core snapshots into a page-safe immutable resource message. */
export function createGpuScene3dGltfPbrHdr10ResourceInput(value: unknown): GpuPageScene3dGltfPbrHdr10ResourceInput {
  const route = value as { hdrRoute: Scene3dGltfPbrHdr10FinalRoute; sdrRoute: Scene3dGltfPbrFinalRoute };
  if (!route?.hdrRoute || !route.sdrRoute || !sameRoute(route.hdrRoute, route.sdrRoute)) throw new Error("HDR10 PBR Browser route requires exact authenticated Core route snapshots.");
  const base = createGpuScene3dGltfPbrResourceInput(route.sdrRoute.renderPlan), hdr = route.hdrRoute.staticPlan, staticGpuBytes = base.budget.gpuResourceBytes;
  if (hdr.admissionFingerprint !== SCENE3D_GLTF_PBR_HDR10_ADMISSION_FINGERPRINT || hdr.source.sha256 !== base.sourceSha256 || hdr.inheritedSdr.staticPlanFingerprint !== base.staticFingerprint || hdr.inheritedSdr.framePlanFingerprint !== base.frameFingerprint || hdr.inheritedSdr.routeFingerprint !== route.sdrRoute.fingerprint || hdr.inheritedSdr.rendererCatalogSha256 !== GPU_PAGE_SCENE3D_GLTF_PBR_CATALOG.sha256 || hdr.resourceFacts.staticGpuBytes !== staticGpuBytes || hdr.resourceFacts.rgba16floatTargetBytes !== HDR10_RGBA16FLOAT_BYTES || hdr.resourceFacts.depthTargetBytes !== HDR10_DEPTH_BYTES || hdr.resourceFacts.rgba16floatReadbackBytes !== HDR10_RGBA16FLOAT_BYTES || hdr.resourceFacts.frameGpuBytes !== staticGpuBytes + HDR10_RGBA16FLOAT_BYTES + HDR10_DEPTH_BYTES || hdr.resourceFacts.peakGpuBytes !== hdr.resourceFacts.frameGpuBytes + HDR10_RGBA16FLOAT_BYTES || hdr.resourceFacts.peakGpuBytes > HDR10_MAX_PEAK_GPU_BYTES) throw new Error("HDR10 PBR Browser route Core static facts are invalid.");
  const input = { schema: "shellx-motion/gpu-page-scene3d-gltf-pbr-hdr10-resources@1" as const, staticFingerprint: hdr.fingerprint, sdrStaticFingerprint: base.staticFingerprint, frameFingerprint: base.frameFingerprint, sourceSha256: base.sourceSha256, pbr: clone(base.pbr), pipeline: GPU_PAGE_SCENE3D_GLTF_PBR_HDR10_PIPELINE_IDENTITY, textures: clone(base.textures), primitives: clone(base.primitives), camera: clone(base.camera), budget: { staticGpuBytes, renderTargetBytes: HDR10_RGBA16FLOAT_BYTES as 7_372_800, depthTargetBytes: HDR10_DEPTH_BYTES as 3_686_400, readbackBytes: HDR10_RGBA16FLOAT_BYTES as 7_372_800, frameGpuBytes: hdr.resourceFacts.frameGpuBytes, peakGpuBytes: hdr.resourceFacts.peakGpuBytes } };
  return freeze(input) as GpuPageScene3dGltfPbrHdr10ResourceInput;
}

/** Opens, prepares, renders, reads, releases, and closes one HDR page session; it never calls FFmpeg. */
export async function renderGpuScene3dGltfPbrHdr10Page(page: GpuScene3dGltfPbrHdr10Page, route: unknown, signal?: AbortSignal): Promise<{ readonly ok: true; readonly readback: { readonly bytesPerRow: 10240; readonly paddedBase64: string; readonly evidence: GpuPageScene3dGltfPbrHdr10ReadbackEvidence }; readonly metrics: GpuPageScene3dGltfPbrHdr10ResourceMetrics; readonly release: GpuPageScene3dGltfPbrHdr10ReleaseEvidence; readonly close: { readonly deviceDestroyed: boolean; readonly forcedResourceRelease: boolean } } | { readonly ok: false; readonly failure: GpuRuntimeFailure; readonly release: GpuPageScene3dGltfPbrHdr10ReleaseEvidence | null; readonly close: { readonly deviceDestroyed: boolean; readonly forcedResourceRelease: boolean } | null }> {
  type Failure = { readonly ok: false; readonly failure: GpuRuntimeFailure; readonly release: GpuPageScene3dGltfPbrHdr10ReleaseEvidence | null };
  type Success = { readonly ok: true; readonly readback: { readonly bytesPerRow: 10240; readonly paddedBase64: string; readonly evidence: GpuPageScene3dGltfPbrHdr10ReadbackEvidence }; readonly metrics: GpuPageScene3dGltfPbrHdr10ResourceMetrics; readonly release: GpuPageScene3dGltfPbrHdr10ReleaseEvidence };
  const finish = async (outcome: Failure | Success) => { let close: { readonly deviceDestroyed: boolean; readonly forcedResourceRelease: boolean } | null = null; try { const candidate = await page.evaluate(closeWebGpuPageSessionScene3dGltfPbrHdr10); if (closeEvidence(candidate)) close = candidate; } catch { /* terminal page close is separately evidenced below */ } if (!outcome.ok || !close || !close.deviceDestroyed) return { ok: false as const, failure: outcome.ok ? failed("HDR10 PBR terminal page close did not destroy its device.") : outcome.failure, release: outcome.release, close }; return { ...outcome, close }; };
  let release: GpuPageScene3dGltfPbrHdr10ReleaseEvidence | null = null;
  try {
    if (signal?.aborted) return { ok: false, failure: cancelled(), release: null, close: null };
    let input: GpuPageScene3dGltfPbrHdr10ResourceInput; try { input = createGpuScene3dGltfPbrHdr10ResourceInput(route); } catch (error) { return { ok: false, failure: { code: "gpu_resource_refused", message: error instanceof Error ? error.message : "HDR10 PBR Core route was refused." }, release: null, close: null }; }
    const opened = await page.evaluate(openWebGpuPageSessionScene3dGltfPbrHdr10, { powerPreference: "high-performance" }) as { ok: boolean; failure?: GpuRuntimeFailure }; if (!opened.ok) return await finish({ ok: false, failure: opened.failure ?? failed("HDR10 PBR page session could not open."), release: null });
    const installed = await page.evaluate(installWebGpuPageSessionScene3dGltfPbrHdr10Pipeline, GPU_PAGE_SCENE3D_GLTF_PBR_HDR10_PIPELINE_IDENTITY) as { ok: boolean; failure?: GpuRuntimeFailure }; if (!installed.ok) return await finish({ ok: false, failure: installed.failure ?? failed("HDR10 PBR pipeline could not install."), release: null });
    if (signal?.aborted) { release = await releasePage(page, "cancelled"); return await finish({ ok: false, failure: cancelled(), release }); }
    const prepared = await page.evaluate(prepareWebGpuPageSessionScene3dGltfPbrHdr10Resources, input) as { ok: boolean; metrics?: GpuPageScene3dGltfPbrHdr10ResourceMetrics; failure?: GpuRuntimeFailure }; if (!prepared.ok || !validMetrics(prepared.metrics, input, 0)) { release = await releasePage(page, "terminal"); return await finish({ ok: false, failure: prepared.ok ? failed("HDR10 PBR preparation returned invalid resource facts.") : prepared.failure ?? failed("HDR10 PBR resource preparation failed."), release }); }
    if (signal?.aborted) { release = await releasePage(page, "cancelled"); return await finish({ ok: false, failure: cancelled(), release }); }
    const frame = await page.evaluate(renderWebGpuPageSessionScene3dGltfPbrHdr10Frame, { schema: "shellx-motion/gpu-page-scene3d-gltf-pbr-hdr10-frame@1", staticFingerprint: input.staticFingerprint, sdrStaticFingerprint: input.sdrStaticFingerprint, frameFingerprint: input.frameFingerprint }) as { ok: boolean; metrics?: GpuPageScene3dGltfPbrHdr10ResourceMetrics; failure?: GpuRuntimeFailure }; if (!frame.ok || !validMetrics(frame.metrics, input, 1)) { release = await releasePage(page, "terminal"); return await finish({ ok: false, failure: frame.ok ? failed("HDR10 PBR frame returned invalid resource facts.") : frame.failure ?? failed("HDR10 PBR frame failed."), release }); }
    const readback = await page.evaluate(readWebGpuPageSessionScene3dGltfPbrHdr10Frame, { schema: GPU_PAGE_SCENE3D_GLTF_PBR_HDR10_READBACK_SCHEMA, staticFingerprint: input.staticFingerprint, sdrStaticFingerprint: input.sdrStaticFingerprint, frameFingerprint: input.frameFingerprint }) as { ok: boolean; width?: number; height?: number; bytesPerRow?: number; paddedBase64?: string; evidence?: GpuPageScene3dGltfPbrHdr10ReadbackEvidence; failure?: GpuRuntimeFailure }; if (!readback.ok || !validReadback(readback, input, frame.metrics)) { release = await releasePage(page, "terminal"); return await finish({ ok: false, failure: readback.ok ? failed("HDR10 PBR readback did not match the authenticated page contract.") : readback.failure ?? failed("HDR10 PBR readback failed."), release }); }
    if (signal?.aborted) { release = await releasePage(page, "cancelled"); return await finish({ ok: false, failure: cancelled(), release }); }
    release = await releasePage(page, "terminal"); if (!validTerminalRelease(release, input)) return await finish({ ok: false, failure: failed("HDR10 PBR resources did not produce exact terminal cleanup evidence."), release });
    return await finish({ ok: true, readback: { bytesPerRow: readback.bytesPerRow, paddedBase64: readback.paddedBase64, evidence: readback.evidence }, metrics: frame.metrics!, release });
  } catch { if (!release) release = await releasePage(page, "terminal"); return await finish({ ok: false, failure: failed("HDR10 PBR page session failed before terminal completion."), release }); }
}

function sameRoute(hdr: Scene3dGltfPbrHdr10FinalRoute, sdr: Scene3dGltfPbrFinalRoute): boolean { return hdr.packageId === sdr.packageId && hdr.staticPlan.inheritedSdr.routeFingerprint === sdr.fingerprint && hdr.staticPlan.inheritedSdr.staticPlanFingerprint === sdr.renderPlan.staticPlan.fingerprint && hdr.staticPlan.inheritedSdr.framePlanFingerprint === sdr.renderPlan.framePlan.fingerprint && hdr.staticPlan.inheritedSdr.sceneStateSha256 === sdr.sceneStateSha256 && hdr.staticPlan.source.sha256 === sdr.renderPlan.staticPlan.source.sha256 && hdr.inputHashes["scene3d-gltf-pbr-hdr10-catalog"] === GPU_PAGE_SCENE3D_GLTF_PBR_HDR10_CATALOG.sha256 && hdr.inputHashes["scene3d-gltf-pbr-hdr10-sdr-catalog"] === GPU_PAGE_SCENE3D_GLTF_PBR_CATALOG.sha256; }
async function releasePage(page: GpuScene3dGltfPbrHdr10Page, reason: "terminal" | "cancelled"): Promise<GpuPageScene3dGltfPbrHdr10ReleaseEvidence | null> { try { return await page.evaluate(releaseWebGpuPageSessionScene3dGltfPbrHdr10Resources, reason) as GpuPageScene3dGltfPbrHdr10ReleaseEvidence; } catch { return null; } }
function validMetrics(value: unknown, input: GpuPageScene3dGltfPbrHdr10ResourceInput, renderedFrames: 0 | 1): value is GpuPageScene3dGltfPbrHdr10ResourceMetrics { if (!value || typeof value !== "object" || !exactKeys(value, ["schema", "staticFingerprint", "textureSlots", "primitiveSlots", "staticGpuBytes", "renderTargetBytes", "depthTargetBytes", "readbackBytes", "frameGpuBytes", "peakGpuBytes", "mipGenerationPasses", "preparationOperations", "renderedFrames", "retainedFrameAllocations"])) return false; const metrics = value as GpuPageScene3dGltfPbrHdr10ResourceMetrics; return metrics.schema === "shellx-motion/gpu-page-scene3d-gltf-pbr-hdr10-resource-metrics@1" && metrics.staticFingerprint === input.staticFingerprint && metrics.textureSlots === input.textures.length && metrics.primitiveSlots === input.primitives.length && metrics.staticGpuBytes === input.budget.staticGpuBytes && metrics.renderTargetBytes === input.budget.renderTargetBytes && metrics.depthTargetBytes === input.budget.depthTargetBytes && metrics.readbackBytes === input.budget.readbackBytes && metrics.frameGpuBytes === input.budget.frameGpuBytes && metrics.peakGpuBytes === input.budget.peakGpuBytes && metrics.mipGenerationPasses === input.textures.reduce((sum, texture) => sum + texture.mipLevelCount - 1, 0) && metrics.preparationOperations === 1 && metrics.renderedFrames === renderedFrames && metrics.retainedFrameAllocations === 0; }
function validReadback(value: unknown, input: GpuPageScene3dGltfPbrHdr10ResourceInput, metrics: GpuPageScene3dGltfPbrHdr10ResourceMetrics): value is { readonly ok: true; readonly width: 1280; readonly height: 720; readonly bytesPerRow: 10240; readonly paddedBase64: string; readonly evidence: GpuPageScene3dGltfPbrHdr10ReadbackEvidence } { if (!value || typeof value !== "object" || !exactKeys(value, ["ok", "width", "height", "bytesPerRow", "paddedBase64", "evidence"])) return false; const readback = value as { ok: unknown; width: unknown; height: unknown; bytesPerRow: unknown; paddedBase64: unknown; evidence: unknown }; if (readback.ok !== true || readback.width !== 1280 || readback.height !== 720 || readback.bytesPerRow !== 10_240 || typeof readback.paddedBase64 !== "string" || !canonicalBase64(readback.paddedBase64, 7_372_800)) return false; const evidence = readback.evidence as GpuPageScene3dGltfPbrHdr10ReadbackEvidence; return !!evidence && typeof evidence === "object" && exactKeys(evidence, ["schema", "staticFingerprint", "sdrStaticFingerprint", "frameFingerprint", "bytesPerRow", "mappedByteLength", "transientReadbackBufferBytes", "processingChunkBytes", "rawRgba16floatSha256", "frameGpuBytes", "peakGpuBytes", "mapOperations", "mappedBufferUnmapped", "mappedBufferDestroyed"]) && evidence.schema === "shellx-motion/gpu-page-scene3d-gltf-pbr-hdr10-readback-evidence@1" && evidence.staticFingerprint === input.staticFingerprint && evidence.sdrStaticFingerprint === input.sdrStaticFingerprint && evidence.frameFingerprint === input.frameFingerprint && evidence.bytesPerRow === 10_240 && evidence.mappedByteLength === 7_372_800 && evidence.transientReadbackBufferBytes === 7_372_800 && evidence.processingChunkBytes === 65_535 && /^[a-f0-9]{64}$/.test(evidence.rawRgba16floatSha256) && evidence.rawRgba16floatSha256 === createHash("sha256").update(Buffer.from(readback.paddedBase64, "base64")).digest("hex") && evidence.frameGpuBytes === metrics.frameGpuBytes && evidence.peakGpuBytes === metrics.peakGpuBytes && evidence.mapOperations === 1 && evidence.mappedBufferUnmapped === true && evidence.mappedBufferDestroyed === true; }
function validTerminalRelease(value: GpuPageScene3dGltfPbrHdr10ReleaseEvidence | null, input: GpuPageScene3dGltfPbrHdr10ResourceInput): value is GpuPageScene3dGltfPbrHdr10ReleaseEvidence { return !!value && exactKeys(value, ["schema", "reason", "hadResources", "destroyedTextures", "destroyedVertexBuffers", "destroyedIndexBuffers", "destroyedUniformBuffers", "destroyedRenderTargets", "releasedGpuBytes", "remainingGpuBytes"]) && value.schema === "shellx-motion/gpu-page-scene3d-gltf-pbr-hdr10-release@1" && value.reason === "terminal" && value.hadResources && value.destroyedTextures === input.textures.length && value.destroyedVertexBuffers === input.primitives.length && value.destroyedIndexBuffers === input.primitives.length && value.destroyedUniformBuffers === input.primitives.length && value.destroyedRenderTargets === 2 && value.remainingGpuBytes === 0 && value.releasedGpuBytes === input.budget.frameGpuBytes; }
function closeEvidence(value: unknown): value is { readonly deviceDestroyed: boolean; readonly forcedResourceRelease: boolean } { return !!value && typeof value === "object" && exactKeys(value, ["deviceDestroyed", "forcedResourceRelease"]) && typeof (value as { deviceDestroyed?: unknown }).deviceDestroyed === "boolean" && typeof (value as { forcedResourceRelease?: unknown }).forcedResourceRelease === "boolean"; }
function canonicalBase64(value: string, expectedBytes: number): boolean { if (value.length !== Math.ceil(expectedBytes / 3) * 4 || value.length % 4 !== 0) return false; let padding = 0; if (value.endsWith("=")) { padding = value.endsWith("==") ? 2 : 1; if (padding !== (3 - expectedBytes % 3) % 3) return false; } for (let index = 0; index < value.length - padding; index += 1) { const code = value.charCodeAt(index); if (!((code >= 65 && code <= 90) || (code >= 97 && code <= 122) || (code >= 48 && code <= 57) || code === 43 || code === 47)) return false; } const bytes = Buffer.from(value, "base64"); return bytes.byteLength === expectedBytes && bytes.toString("base64") === value; }
function exactKeys(value: object, expected: readonly string[]): boolean { const actual = Object.keys(value).sort(), wanted = [...expected].sort(); return actual.length === wanted.length && actual.every((key, index) => key === wanted[index]); }
function clone<T>(value: T): T { return structuredClone(value); }
function freeze<T>(value: T): T { if (value && typeof value === "object" && !Object.isFrozen(value)) { for (const child of Object.values(value as Record<string, unknown>)) freeze(child); Object.freeze(value); } return value; }
function failed(message: string): GpuRuntimeFailure { return { code: "gpu_render_failed", message }; }
function cancelled(): GpuRuntimeFailure { return { code: "gpu_cancelled", message: "HDR10 PBR page work was cancelled and terminal cleanup was requested." }; }
