import type { GpuRuntimeFailure } from "./gpu-runtime-types";

export const GPU_PAGE_SCENE3D_GLTF_PBR_HDR10_READBACK_SCHEMA = "shellx-motion/gpu-page-scene3d-gltf-pbr-hdr10-readback@1" as const;
export interface GpuPageScene3dGltfPbrHdr10ReadbackInput { readonly schema: typeof GPU_PAGE_SCENE3D_GLTF_PBR_HDR10_READBACK_SCHEMA; readonly staticFingerprint: string; readonly sdrStaticFingerprint: string; readonly frameFingerprint: string; }
export interface GpuPageScene3dGltfPbrHdr10ReadbackEvidence { readonly schema: "shellx-motion/gpu-page-scene3d-gltf-pbr-hdr10-readback-evidence@1"; readonly staticFingerprint: string; readonly sdrStaticFingerprint: string; readonly frameFingerprint: string; readonly bytesPerRow: 10240; readonly mappedByteLength: 7_372_800; readonly transientReadbackBufferBytes: 7_372_800; readonly processingChunkBytes: 65_535; readonly rawRgba16floatSha256: string; readonly frameGpuBytes: number; readonly peakGpuBytes: number; readonly mapOperations: 1; readonly mappedBufferUnmapped: true; readonly mappedBufferDestroyed: true; }
export type GpuPageScene3dGltfPbrHdr10ReadbackOutput = { readonly ok: true; readonly width: 1280; readonly height: 720; readonly bytesPerRow: 10240; readonly paddedBase64: string; readonly evidence: GpuPageScene3dGltfPbrHdr10ReadbackEvidence } | { readonly ok: false; readonly failure: GpuRuntimeFailure };

/** One aligned rgba16float map-read copy; raw bytes are chunk-processed and the mapped buffer is destroyed before return. */
export async function readWebGpuPageSessionScene3dGltfPbrHdr10Frame(input: GpuPageScene3dGltfPbrHdr10ReadbackInput): Promise<GpuPageScene3dGltfPbrHdr10ReadbackOutput> {
  const WIDTH = 1280, HEIGHT = 720, BYTES_PER_ROW = 10_240, BYTE_LENGTH = 7_372_800, CHUNK = 65_535, MAX_PEAK = 72 * 1024 * 1024;
  type Buffer = { mapAsync(mode: number): Promise<void>; getMappedRange(): ArrayBuffer; unmap(): void; destroy?(): void };
  type Resources = { staticFingerprint: string; sdrStaticFingerprint: string; frameFingerprint: string; target: unknown; metrics: { readbackBytes: number; frameGpuBytes: number; peakGpuBytes: number } };
  type Device = { createBuffer(value: unknown): Buffer; createCommandEncoder(): { copyTextureToBuffer(source: { texture: unknown }, destination: { buffer: Buffer; bytesPerRow: number; rowsPerImage: number }, size: { width: number; height: number; depthOrArrayLayers: number }): void; finish(): unknown }; queue: { submit(commands: readonly unknown[]): void; onSubmittedWorkDone?(): Promise<void> } };
  const global = globalThis as unknown as { GPUBufferUsage?: Record<string, number>; GPUMapMode?: Record<string, number>; btoa?(value: string): string; crypto?: { subtle?: { digest(algorithm: string, data: unknown): Promise<ArrayBuffer> } }; __shellxMotionGpuHdr10PbrSessionV1?: { device?: Device; limits?: { maxTextureDimension2D: number; maxBufferSize: number }; resources?: Resources; lost?: boolean } }, state = global.__shellxMotionGpuHdr10PbrSessionV1, resources = state?.resources, usage = global.GPUBufferUsage, mapMode = global.GPUMapMode;
  if (!state?.device || !resources || !usage || !mapMode || !global.crypto?.subtle) return fail("gpu_device_unavailable", "The HDR10 PBR readback has no prepared page resources.");
  if (!valid(input, resources)) return fail("gpu_resource_refused", "The HDR10 PBR readback identity does not match prepared resources.");
  if (state.lost) return fail("gpu_device_lost", "The HDR10 PBR device was lost before readback.");
  if (!state.limits || state.limits.maxTextureDimension2D < WIDTH || state.limits.maxBufferSize < BYTE_LENGTH || resources.metrics.readbackBytes !== BYTE_LENGTH || resources.metrics.peakGpuBytes !== resources.metrics.frameGpuBytes + BYTE_LENGTH || resources.metrics.peakGpuBytes > MAX_PEAK || typeof usage.COPY_DST !== "number" || typeof usage.MAP_READ !== "number" || typeof mapMode.READ !== "number") return fail("gpu_limits_exceeded", "The HDR10 PBR readback exceeds admitted device or resource limits.");
  let buffer: Buffer | undefined, mapped = false, cleanupError = false, result: GpuPageScene3dGltfPbrHdr10ReadbackOutput | undefined;
  try {
    buffer = state.device.createBuffer({ size: BYTE_LENGTH, usage: usage.COPY_DST | usage.MAP_READ }); const encoder = state.device.createCommandEncoder();
    encoder.copyTextureToBuffer({ texture: resources.target }, { buffer, bytesPerRow: BYTES_PER_ROW, rowsPerImage: HEIGHT }, { width: WIDTH, height: HEIGHT, depthOrArrayLayers: 1 }); state.device.queue.submit([encoder.finish()]); if (state.device.queue.onSubmittedWorkDone) await state.device.queue.onSubmittedWorkDone(); await buffer.mapAsync(mapMode.READ); mapped = true;
    const raw = new Uint8Array(buffer.getMappedRange()), paddedBase64 = base64(raw), rawRgba16floatSha256 = await sha(raw); result = { ok: true, width: WIDTH, height: HEIGHT, bytesPerRow: BYTES_PER_ROW, paddedBase64, evidence: { schema: "shellx-motion/gpu-page-scene3d-gltf-pbr-hdr10-readback-evidence@1", staticFingerprint: input.staticFingerprint, sdrStaticFingerprint: input.sdrStaticFingerprint, frameFingerprint: input.frameFingerprint, bytesPerRow: BYTES_PER_ROW, mappedByteLength: BYTE_LENGTH, transientReadbackBufferBytes: BYTE_LENGTH, processingChunkBytes: CHUNK, rawRgba16floatSha256, frameGpuBytes: resources.metrics.frameGpuBytes, peakGpuBytes: resources.metrics.peakGpuBytes, mapOperations: 1, mappedBufferUnmapped: true, mappedBufferDestroyed: true } };
  } catch { result = fail("gpu_render_failed", "The HDR10 PBR frame could not complete bounded readback."); }
  finally { try { if (mapped) buffer?.unmap(); } catch { cleanupError = true; } try { buffer?.destroy?.(); } catch { cleanupError = true; } }
  return cleanupError ? fail("gpu_render_failed", "The HDR10 PBR mapped readback buffer did not terminally release.") : result!;
  function fail(code: GpuRuntimeFailure["code"], message: string): GpuPageScene3dGltfPbrHdr10ReadbackOutput { return { ok: false, failure: { code, message } }; }
  function valid(value: unknown, current: Resources): value is GpuPageScene3dGltfPbrHdr10ReadbackInput { return !!value && typeof value === "object" && Object.keys(value).sort().join(",") === "frameFingerprint,schema,sdrStaticFingerprint,staticFingerprint" && (value as GpuPageScene3dGltfPbrHdr10ReadbackInput).schema === "shellx-motion/gpu-page-scene3d-gltf-pbr-hdr10-readback@1" && ["staticFingerprint", "sdrStaticFingerprint", "frameFingerprint"].every((key) => /^[a-f0-9]{64}$/.test((value as Record<string, string>)[key]!)) && (value as GpuPageScene3dGltfPbrHdr10ReadbackInput).staticFingerprint === current.staticFingerprint && (value as GpuPageScene3dGltfPbrHdr10ReadbackInput).sdrStaticFingerprint === current.sdrStaticFingerprint && (value as GpuPageScene3dGltfPbrHdr10ReadbackInput).frameFingerprint === current.frameFingerprint; }
  function base64(bytes: Uint8Array): string { if (bytes.byteLength !== BYTE_LENGTH || typeof global.btoa !== "function") throw new Error("readback base64"); let result = ""; for (let offset = 0; offset < bytes.length; offset += CHUNK) { const chunk = bytes.subarray(offset, Math.min(offset + CHUNK, bytes.length)); let binary = ""; for (let index = 0; index < chunk.length; index += 8_192) binary += String.fromCharCode(...chunk.subarray(index, Math.min(index + 8_192, chunk.length))); result += global.btoa(binary); } return result; }
  async function sha(bytes: Uint8Array): Promise<string> { const digest = new Uint8Array(await global.crypto!.subtle!.digest("SHA-256", bytes)); return Array.from(digest).map((byte) => byte.toString(16).padStart(2, "0")).join(""); }
}
