import { createHash } from "node:crypto";
import { canonicalJson, canonicalJsonSha256, streamingFrameTimestampMs } from "@shellx-motion/core";
import { GPU_ADAPTER_REQUEST_OPTIONS, openGpuRuntime, type GpuRuntimeSession } from "./gpu-browser-runtime";
import { GPU_PAGE_SCENE3D_GLTF_PBR_HDR10_CATALOG, GPU_PAGE_SCENE3D_GLTF_PBR_HDR10_PIPELINE_IDENTITY } from "./gpu-page-scene3d-gltf-pbr-hdr10-contract";
import { renderWebGpuPageSessionScene3dGltfPbrHdr10Frame } from "./gpu-page-scene3d-gltf-pbr-hdr10-frame";
import { installWebGpuPageSessionScene3dGltfPbrHdr10Pipeline } from "./gpu-page-scene3d-gltf-pbr-hdr10-pipeline";
import { readWebGpuPageSessionScene3dGltfPbrHdr10StreamingFrame, releaseWebGpuPageSessionScene3dGltfPbrHdr10StreamingReadback, reserveWebGpuPageSessionScene3dGltfPbrHdr10StreamingReadback } from "./gpu-page-scene3d-gltf-pbr-hdr10-streaming-readback";
import { prepareWebGpuPageSessionScene3dGltfPbrHdr10Resources, terminalReleaseWebGpuPageSessionScene3dGltfPbrHdr10Resources } from "./gpu-page-scene3d-gltf-pbr-hdr10-resources";
import { closeWebGpuPageSessionScene3dGltfPbrHdr10, openWebGpuPageSessionScene3dGltfPbrHdr10 } from "./gpu-page-scene3d-gltf-pbr-hdr10-session-page";
import { createGpuScene3dGltfPbrHdr10ResourceInput, type GpuScene3dGltfPbrHdr10RouteResolution } from "./gpu-scene3d-gltf-pbr-hdr10-session";
import { isGpuBrowserProcess, isGpuFinalLaunchContext, isPrecontainedGpuBrowser, type GpuStreamingJobContext } from "./gpu-process-containment";
import type { GpuRuntimeEvidence } from "./gpu-runtime-types";

export { resolveGpuScene3dGltfPbrHdr10Route } from "./gpu-scene3d-gltf-pbr-hdr10-session";
export type { GpuScene3dGltfPbrHdr10RouteResolution } from "./gpu-scene3d-gltf-pbr-hdr10-session";
export { GPU_PAGE_SCENE3D_GLTF_PBR_HDR10_CATALOG, GPU_PAGE_SCENE3D_GLTF_PBR_HDR10_PIPELINE_IDENTITY } from "./gpu-page-scene3d-gltf-pbr-hdr10-contract";

export const GPU_SCENE3D_GLTF_PBR_HDR10_STREAMING_PRODUCER_SCHEMA = "shellx-motion/gpu-scene3d-gltf-pbr-hdr10-streaming-producer@1" as const;
export interface GpuScene3dGltfPbrHdr10StreamingFrame { readonly index: number; readonly atMs: number; readonly schema: "shellx-motion/browser-scene3d-gltf-pbr-hdr10-readback@1"; readonly staticFingerprint: string; readonly sdrStaticFingerprint: string; readonly frameFingerprint: string; readonly rawRgba16floatSha256: string; readonly width: 1280; readonly height: 720; readonly bytesPerRow: 10240; readonly byteOrder: "ieee754-binary16-le"; readonly rgba16float: Buffer; }
export interface GpuScene3dGltfPbrHdr10StreamingSink { write(frame: GpuScene3dGltfPbrHdr10StreamingFrame): Promise<void>; }
export interface GpuScene3dGltfPbrHdr10StreamingProducerEvidence { readonly schema: typeof GPU_SCENE3D_GLTF_PBR_HDR10_STREAMING_PRODUCER_SCHEMA; readonly routeFingerprint: string; readonly packageId: string; readonly inputHashes: Readonly<Record<string, string>>; readonly catalogSha256: string; readonly pipelineSha256: string; readonly runtime: GpuRuntimeEvidence | null; readonly framesRendered: number; readonly rawFrameSequenceSha256: string | null; readonly retainedRawFrames: 0; readonly readback: { readonly reservedReadbackBufferBytes: 7_372_800; readonly readbackBufferAllocations: 0 | 1; readonly mapOperations: number; readonly released: boolean; }; readonly cleanup: { readonly state: "pending" | "complete" | "failed"; readonly resourcesReleased: boolean; readonly readbackReleased: boolean; readonly pageClosed: boolean; }; readonly fingerprint: string | null; }
export interface GpuScene3dGltfPbrHdr10StreamingProducer { readonly frameCount: 90; readonly width: 1280; readonly height: 720; readonly fps: 30; readonly durationMs: 3000; readonly evidence: GpuScene3dGltfPbrHdr10StreamingProducerEvidence; produce(sink: GpuScene3dGltfPbrHdr10StreamingSink, job: GpuStreamingJobContext): Promise<void>; }
type PresentRoute = Extract<GpuScene3dGltfPbrHdr10RouteResolution, { kind: "present" }>;

/** HDR-only persistent producer. It shares neither an SDR catalog nor a raw-frame cache. */
export function createGpuScene3dGltfPbrHdr10StreamingProducer(route: PresentRoute, timeline: { readonly width: number; readonly height: number; readonly fps: number; readonly durationMs: number }): GpuScene3dGltfPbrHdr10StreamingProducer {
  if (timeline.width !== 1280 || timeline.height !== 720 || timeline.fps !== 30 || timeline.durationMs !== 3000) throw new Error("HDR10 PBR direct final requires exactly 1280x720 at 30fps for 3000ms.");
  const resourceInput = createGpuScene3dGltfPbrHdr10ResourceInput(route); let active = false, evidence = initial(route);
  return { frameCount: 90, width: 1280, height: 720, fps: 30, durationMs: 3000, get evidence() { return evidence; }, async produce(sink, job) {
    if (active || !sink || typeof sink.write !== "function" || job.admission !== "pre-acquired" || typeof job.watchProcess !== "function" || !isGpuFinalLaunchContext(job)) throw new Error("HDR10 PBR streaming requires one pre-acquired contained Browser job and sink.");
    active = true; evidence = initial(route); let runtime: GpuRuntimeSession | undefined, prepared = false, reserved = false, closed = false, cleanupFailed = false; const sequence = createHash("sha256");
    try {
      throwIfAborted(job.signal); const opened = await openGpuRuntime({ finalBrowser: { scratchRoot: job.scratchRoot, maxProcessTreeRssBytes: job.maxProcessTreeRssBytes, signal: job.signal } }); if (!opened.ok) throw new Error(opened.failure.message); runtime = opened.session;
      const browser = runtime.browserProcess; if (!isGpuBrowserProcess(browser) || !isPrecontainedGpuBrowser(browser.containment, browser.pid, job.maxProcessTreeRssBytes)) throw new Error("HDR10 PBR streaming refused an uncontained Chromium process."); job.watchProcess(browser.pid);
      const initialized = await runtime.page.evaluate(openWebGpuPageSessionScene3dGltfPbrHdr10, GPU_ADAPTER_REQUEST_OPTIONS); if (!isOk(initialized)) throw new Error("HDR10 PBR page initialization was refused.");
      const assessed = await runtime.assessRender(initialized.runtime); if (!assessed.ok) throw new Error(assessed.failure.message); evidence = withRuntime(evidence, assessed.evidence);
      const installed = await runtime.page.evaluate(installWebGpuPageSessionScene3dGltfPbrHdr10Pipeline, GPU_PAGE_SCENE3D_GLTF_PBR_HDR10_PIPELINE_IDENTITY); if (!isOk(installed)) throw new Error("HDR10 PBR pipeline installation was refused.");
      const setup = await runtime.page.evaluate(prepareWebGpuPageSessionScene3dGltfPbrHdr10Resources, resourceInput); if (!isPrepared(setup, resourceInput)) throw new Error("HDR10 PBR resource preparation returned invalid facts."); prepared = true;
      const reservation = await runtime.page.evaluate(reserveWebGpuPageSessionScene3dGltfPbrHdr10StreamingReadback, readbackInput(resourceInput)); if (!isOk(reservation)) throw new Error("HDR10 PBR readback reservation was refused."); reserved = true;
      for (let index = 0; index < 90; index += 1) {
        throwIfAborted(job.signal); const rendered = await runtime.page.evaluate(renderWebGpuPageSessionScene3dGltfPbrHdr10Frame, frameInput(resourceInput)); if (!isRendered(rendered, resourceInput, index + 1)) throw new Error("HDR10 PBR frame render returned invalid facts.");
        const readback = await runtime.page.evaluate(readWebGpuPageSessionScene3dGltfPbrHdr10StreamingFrame, readbackInput(resourceInput)); const raw = parseReadback(readback, resourceInput, index);
        try { await sink.write(raw); } finally { raw.rgba16float.fill(0); }
        sequence.update(canonicalJson({ index, atMs: raw.atMs, sha256: raw.rawRgba16floatSha256 })); evidence = Object.freeze({ ...evidence, framesRendered: index + 1, readback: { ...evidence.readback, readbackBufferAllocations: 1 as const, mapOperations: index + 1 } });
      }
      evidence = Object.freeze({ ...evidence, rawFrameSequenceSha256: sequence.digest("hex") });
    } finally {
      if (runtime && reserved) { const released = await runtime.page.evaluate(releaseWebGpuPageSessionScene3dGltfPbrHdr10StreamingReadback).catch(() => null); if (!released?.hadReservedBuffer || !released.destroyedReservedBuffer || released.remainingReadbackBufferBytes !== 0 || released.mapOperations !== evidence.framesRendered) cleanupFailed = true; else evidence = Object.freeze({ ...evidence, readback: { ...evidence.readback, released: true } }); }
      if (runtime && prepared) { const released = await runtime.page.evaluate(terminalReleaseWebGpuPageSessionScene3dGltfPbrHdr10Resources).catch(() => null); if (!validRelease(released, resourceInput)) cleanupFailed = true; else evidence = Object.freeze({ ...evidence, cleanup: { ...evidence.cleanup, resourcesReleased: true } }); }
      if (runtime) { try { const result = await runtime.page.evaluate(closeWebGpuPageSessionScene3dGltfPbrHdr10); if (!result?.deviceDestroyed || result.forcedResourceRelease) cleanupFailed = true; await runtime.close(); closed = true; } catch { cleanupFailed = true; } }
      evidence = finish(evidence, closed, cleanupFailed); active = false; if (cleanupFailed) throw new Error("HDR10 PBR streaming terminal cleanup evidence was incomplete.");
    }
  } };
}

function initial(route: PresentRoute): GpuScene3dGltfPbrHdr10StreamingProducerEvidence { return Object.freeze({ schema: GPU_SCENE3D_GLTF_PBR_HDR10_STREAMING_PRODUCER_SCHEMA, routeFingerprint: route.hdrRoute.fingerprint, packageId: route.hdrRoute.packageId, inputHashes: Object.freeze({ ...route.hdrRoute.inputHashes }), catalogSha256: GPU_PAGE_SCENE3D_GLTF_PBR_HDR10_CATALOG.sha256, pipelineSha256: GPU_PAGE_SCENE3D_GLTF_PBR_HDR10_PIPELINE_IDENTITY.pipelineImplementationSha256, runtime: null, framesRendered: 0, rawFrameSequenceSha256: null, retainedRawFrames: 0, readback: { reservedReadbackBufferBytes: 7_372_800 as const, readbackBufferAllocations: 0 as const, mapOperations: 0, released: false }, cleanup: { state: "pending" as const, resourcesReleased: false, readbackReleased: false, pageClosed: false }, fingerprint: null }); }
function withRuntime(evidence: GpuScene3dGltfPbrHdr10StreamingProducerEvidence, runtime: GpuRuntimeEvidence): GpuScene3dGltfPbrHdr10StreamingProducerEvidence { return Object.freeze({ ...evidence, runtime }); }
function finish(evidence: GpuScene3dGltfPbrHdr10StreamingProducerEvidence, pageClosed: boolean, failed: boolean): GpuScene3dGltfPbrHdr10StreamingProducerEvidence { const cleanup = Object.freeze({ ...evidence.cleanup, state: failed ? "failed" as const : "complete" as const, readbackReleased: evidence.readback.released, pageClosed }); const base = { ...evidence, cleanup, fingerprint: undefined }; return Object.freeze({ ...base, fingerprint: canonicalJsonSha256(base) }); }
function readbackInput(input: { staticFingerprint: string; sdrStaticFingerprint: string; frameFingerprint: string }) { return { schema: "shellx-motion/gpu-page-scene3d-gltf-pbr-hdr10-streaming-readback@1" as const, staticFingerprint: input.staticFingerprint, sdrStaticFingerprint: input.sdrStaticFingerprint, frameFingerprint: input.frameFingerprint }; }
function frameInput(input: { staticFingerprint: string; sdrStaticFingerprint: string; frameFingerprint: string }) { return { schema: "shellx-motion/gpu-page-scene3d-gltf-pbr-hdr10-frame@1" as const, staticFingerprint: input.staticFingerprint, sdrStaticFingerprint: input.sdrStaticFingerprint, frameFingerprint: input.frameFingerprint }; }
function isOk(value: unknown): value is { ok: true; runtime?: unknown } { return !!value && typeof value === "object" && (value as { ok?: unknown }).ok === true; }
function isPrepared(value: unknown, input: { staticFingerprint: string; budget: { frameGpuBytes: number; peakGpuBytes: number } }): boolean { const metrics = (value as { metrics?: Record<string, unknown> })?.metrics; return isOk(value) && !!metrics && metrics.staticFingerprint === input.staticFingerprint && metrics.frameGpuBytes === input.budget.frameGpuBytes && metrics.peakGpuBytes === input.budget.peakGpuBytes && metrics.renderedFrames === 0 && metrics.retainedFrameAllocations === 0; }
function isRendered(value: unknown, input: { staticFingerprint: string; budget: { frameGpuBytes: number; peakGpuBytes: number } }, count: number): boolean { const metrics = (value as { metrics?: Record<string, unknown> })?.metrics; return isOk(value) && !!metrics && metrics.staticFingerprint === input.staticFingerprint && metrics.frameGpuBytes === input.budget.frameGpuBytes && metrics.peakGpuBytes === input.budget.peakGpuBytes && metrics.renderedFrames === count && metrics.retainedFrameAllocations === 0; }
function parseReadback(value: unknown, input: { staticFingerprint: string; sdrStaticFingerprint: string; frameFingerprint: string; budget: { frameGpuBytes: number; peakGpuBytes: number } }, index: number): GpuScene3dGltfPbrHdr10StreamingFrame { const readback = value as Record<string, unknown>, evidence = readback?.evidence as Record<string, unknown>; if (!isOk(value) || readback.width !== 1280 || readback.height !== 720 || readback.bytesPerRow !== 10_240 || typeof readback.paddedBase64 !== "string" || !evidence || evidence.staticFingerprint !== input.staticFingerprint || evidence.sdrStaticFingerprint !== input.sdrStaticFingerprint || evidence.frameFingerprint !== input.frameFingerprint || evidence.bytesPerRow !== 10_240 || evidence.mappedByteLength !== 7_372_800 || evidence.reservedReadbackBufferBytes !== 7_372_800 || evidence.readbackBufferAllocations !== 1 || evidence.mapOperations !== index + 1 || evidence.mappedBufferUnmapped !== true || evidence.retainedReadbackBuffer !== true || evidence.frameGpuBytes !== input.budget.frameGpuBytes || evidence.peakGpuBytes !== input.budget.peakGpuBytes || !hash(evidence.rawRgba16floatSha256)) throw new Error("HDR10 PBR page returned a forged readback envelope."); const rgba16float = canonicalBase64(readback.paddedBase64, 7_372_800); const sha256 = createHash("sha256").update(rgba16float).digest("hex"); if (sha256 !== evidence.rawRgba16floatSha256) throw new Error("HDR10 PBR page readback bytes do not match their evidence."); return Object.freeze({ index, atMs: streamingFrameTimestampMs(index, 30, 3000), schema: "shellx-motion/browser-scene3d-gltf-pbr-hdr10-readback@1", staticFingerprint: input.staticFingerprint, sdrStaticFingerprint: input.sdrStaticFingerprint, frameFingerprint: input.frameFingerprint, rawRgba16floatSha256: sha256, width: 1280, height: 720, bytesPerRow: 10_240, byteOrder: "ieee754-binary16-le", rgba16float }); }
function canonicalBase64(value: string, bytes: number): Buffer { if (value.length !== Math.ceil(bytes / 3) * 4 || !/^[A-Za-z0-9+/]*={0,2}$/.test(value)) throw new Error("HDR10 PBR readback base64 is invalid."); const decoded = Buffer.from(value, "base64"); if (decoded.byteLength !== bytes || decoded.toString("base64") !== value) throw new Error("HDR10 PBR readback base64 is non-canonical."); return decoded; }
function validRelease(value: unknown, input: { textures: readonly unknown[]; primitives: readonly unknown[]; budget: { frameGpuBytes: number } }): boolean { const release = value as Record<string, unknown>; return !!release && release.reason === "terminal" && release.hadResources === true && release.destroyedTextures === input.textures.length && release.destroyedVertexBuffers === input.primitives.length && release.destroyedIndexBuffers === input.primitives.length && release.destroyedUniformBuffers === input.primitives.length && release.destroyedRenderTargets === 2 && release.releasedGpuBytes === input.budget.frameGpuBytes && release.remainingGpuBytes === 0; }
function hash(value: unknown): value is string { return typeof value === "string" && /^[a-f0-9]{64}$/.test(value); }
function throwIfAborted(signal: AbortSignal): void { if (signal.aborted) throw signal.reason instanceof Error ? signal.reason : new Error("HDR10 PBR streaming was cancelled."); }
