import type { GpuRuntimeFailure } from "./gpu-runtime-types";

/** Fixed v2 field ABI: two 64-byte storage/vertex buffers, never particle history. */
export interface GpuPageComputeParticleV2Metrics {
  readonly schema: "shellx-motion/gpu-page-particle-compute-v2@1";
  readonly abi: "shellx-motion/gpu-compute-particle-field@2";
  readonly pointRaster: "gpu-native-instanced";
  readonly positionEvaluation: "core-cpu-exact-time" | "gpu-fixed-analytic-time" | "mixed-core-cpu-and-gpu-fixed-analytic-time";
  readonly computeField: "not-used" | "fixed-analytic-v2";
  readonly computeParticleBufferSlots: number;
  readonly computeParticleBufferBytes: number;
  readonly computeParticleBufferHighWaterSlots: number;
  readonly computeParticleBufferHighWaterBytes: number;
  readonly adapterComputeParticleInstanceLimit: number;
  readonly computeParticleDispatches: number;
  readonly instanceBytes: 64;
  readonly retainedBufferCount: 2;
  readonly uniformBytes: 432;
  readonly rasterCalls: number;
  readonly headRasterCalls: number;
  readonly trailRasterCalls: number;
  readonly capacityReconfigurations: number;
  readonly lateAllocationRefusals: number;
}

type Rgba = { r: number; g: number; b: number; a: number };
type Mask = { shape: "rect" | "ellipse" | "triangle"; x: number; y: number; width: number; height: number; radius: number; rotationDeg: number; pivotX: number; pivotY: number; inverted: boolean; opacity: number; featherPx: number };
type Source = { kind: "radial" | "vortex"; centerX: number; centerY: number; strength: number; softening: number } | { kind: "flow"; angleDeg: number; strength: number } | { kind: "turbulence"; scale: number; strength: number } | { kind: "impact"; centerX: number; centerY: number; radius: number; strength: number; startProgress: number; durationProgress: number } | { kind: "collision"; axis: "x" | "y"; position: number; restitution: number };
export type GpuPageParticleV2Draw = { kind: "particleCompute"; id: string; blendMode: "normal"; effects: null; mask?: Mask; schema: "shellx-motion/gpu-compute-particle-field@2"; seed: number; count: number; atMs: number; startMs: number; lifetimeMs: number; width: number; height: number; x: number; y: number; scale: number; originX: number; originY: number; rotationDeg: number; opacity: number; color: Rgba; secondaryColor: Rgba; minSize: number; maxSize: number; minSpeed: number; maxSpeed: number; direction: number; spread: number; gravity: number; fadeOut: boolean; sources: ReadonlyArray<Source>; origins: ReadonlyArray<{x:number;y:number;weight:number;directionOffsetDeg:number;speedScale:number}>; trail: {durationMs:number;samples:number;opacity:number}|null; shading: {mode:"flat"|"soft"|"glow";sizeJitter:number;opacityJitter:number;glow:number}; computeDispatchCount: 1; rasterPassCount: 1|2; instanceBytes: 64; retainedBufferCount: 2; retainedInstanceBytes: number };
type Draw = GpuPageParticleV2Draw;
type BufferFacade = { destroy?(): void };
type TextureFacade = { createView(): unknown };
type Pipeline = { getBindGroupLayout(index: number): unknown };
type ShaderModule = { getCompilationInfo?(): Promise<{ messages?: Array<{ type?: string; message?: string; lineNum?: number; linePos?: number }> }> };
type Device = { createBuffer(value: unknown): BufferFacade; createShaderModule(value: unknown): ShaderModule; createComputePipeline(value: unknown): Pipeline; createRenderPipeline(value: unknown): Pipeline; createComputePipelineAsync?(value: unknown): Promise<Pipeline>; createRenderPipelineAsync?(value: unknown): Promise<Pipeline>; createBindGroup(value: unknown): unknown; queue: { writeBuffer(buffer: BufferFacade, offset: number, data: ArrayBuffer): void } };
type Encoder = { beginComputePass(): { setPipeline(value: unknown): void; setBindGroup(index: number, value: unknown): void; dispatchWorkgroups(count: number): void; end(): void }; beginRenderPass(value: unknown): { setPipeline(value: unknown): void; setBindGroup(index: number, value: unknown): void; setVertexBuffer(index: number, value: unknown): void; draw(vertices: number, instances: number): void; end(): void } };

export type GpuPageComputeParticleV2InstallOutput = { ok: true } | { ok: false; failure: GpuRuntimeFailure };

/** Installs Motion-owned deterministic WGSL; descriptors can select data, never shader code. */
export async function installWebGpuPageSessionParticleComputeV2(): Promise<GpuPageComputeParticleV2InstallOutput> {
  const fail = (message: string): GpuPageComputeParticleV2InstallOutput => ({ ok: false, failure: { code: "gpu_render_failed", message } });
  const MAX_PARTICLES = 131_072, MIN_PARTICLES = 100_000, INSTANCE_BYTES = 64, BUFFER_COUNT = 2, WORKGROUP_SIZE = 256, MAX_RETAINED_BYTES = 16 * 1024 * 1024, UNIFORM_BYTES = 432;
  // This installer crosses Playwright by function source. Keep every render-time
  // helper in this closure: imported/module helpers would be absent in the page.
  const record = (value: unknown): value is Record<string,unknown> => Boolean(value)&&typeof value==="object"&&!Array.isArray(value)&&(Object.getPrototypeOf(value)===Object.prototype||Object.getPrototypeOf(value)===null);
  const only = (value: Record<string,unknown>, keys: readonly string[]): boolean => Object.keys(value).length===keys.length&&Object.keys(value).every((key)=>keys.includes(key));
  const color = (value: unknown): boolean => record(value)&&only(value,["r","g","b","a"])&&[value.r,value.g,value.b,value.a].every((x)=>typeof x==="number"&&Number.isFinite(x)&&x>=0&&x<=1);
  const source = (value: unknown): boolean => { if(!record(value)||typeof value.kind!=="string")return false;const n=(x:unknown,a:number,b:number)=>typeof x==="number"&&Number.isFinite(x)&&x>=a&&x<=b;if(value.kind==="radial"||value.kind==="vortex")return only(value,["kind","centerX","centerY","strength","softening"])&&n(value.centerX,0,1)&&n(value.centerY,0,1)&&n(value.strength,-1,1)&&n(value.softening,.01,1);if(value.kind==="flow")return only(value,["kind","angleDeg","strength"])&&n(value.angleDeg,-360,360)&&n(value.strength,-1,1);if(value.kind==="turbulence")return only(value,["kind","scale","strength"])&&n(value.scale,.01,4)&&n(value.strength,-1,1);if(value.kind==="impact")return only(value,["kind","centerX","centerY","radius","strength","startProgress","durationProgress"])&&n(value.centerX,0,1)&&n(value.centerY,0,1)&&n(value.radius,.01,1)&&n(value.strength,-1,1)&&n(value.startProgress,0,1)&&n(value.durationProgress,.01,1)&&(value.startProgress as number)+(value.durationProgress as number)<=1;return value.kind==="collision"&&only(value,["kind","axis","position","restitution"])&&(value.axis==="x"||value.axis==="y")&&n(value.position,0,1)&&n(value.restitution,0,1); };
  const mask = (value: unknown): boolean => { if(value===undefined)return true;if(!record(value)||!only(value,["shape","x","y","width","height","radius","rotationDeg","pivotX","pivotY","inverted","opacity","featherPx"]))return false;const n=(x:unknown,a:number,b:number)=>typeof x==="number"&&Number.isFinite(x)&&x>=a&&x<=b;return (value.shape==="rect"||value.shape==="ellipse"||value.shape==="triangle")&&n(value.x,-1_000_000,1_000_000)&&n(value.y,-1_000_000,1_000_000)&&n(value.width,Number.MIN_VALUE,4_096)&&n(value.height,Number.MIN_VALUE,4_096)&&n(value.radius,0,Math.min(value.width as number,value.height as number)/2)&&n(value.rotationDeg,-1_000_000,1_000_000)&&n(value.pivotX,-1_000_000,1_000_000)&&n(value.pivotY,-1_000_000,1_000_000)&&typeof value.inverted==="boolean"&&n(value.opacity,0,1)&&n(value.featherPx,0,128)&&!(value.shape==="triangle"&&value.radius!==0); };
  const origin = (value: unknown): boolean => record(value)&&only(value,["x","y","weight","directionOffsetDeg","speedScale"])&&[value.x,value.y,value.weight,value.directionOffsetDeg,value.speedScale].every((x)=>typeof x==="number"&&Number.isFinite(x))&&(value.x as number)>=0&&(value.x as number)<=1&&(value.y as number)>=0&&(value.y as number)<=1&&(value.weight as number)>=.01&&(value.weight as number)<=1&&Math.abs(value.directionOffsetDeg as number)<=360&&(value.speedScale as number)>=.25&&(value.speedScale as number)<=4;
  const admitTrail = (value: unknown): boolean => value===null||(record(value)&&only(value,["durationMs","samples","opacity"])&&typeof value.durationMs==="number"&&Number.isFinite(value.durationMs)&&value.durationMs>=1&&value.durationMs<=1000&&Number.isInteger(value.samples)&&(value.samples as number)>=2&&(value.samples as number)<=4&&typeof value.opacity==="number"&&Number.isFinite(value.opacity)&&value.opacity>=.05&&value.opacity<=1);
  const shading = (value: unknown): boolean => record(value)&&only(value,["mode","sizeJitter","opacityJitter","glow"])&&(value.mode==="flat"||value.mode==="soft"||value.mode==="glow")&&[value.sizeJitter,value.opacityJitter,value.glow].every((x)=>typeof x==="number"&&Number.isFinite(x)&&x>=0&&x<=1);
  const admit = (input: Draw): boolean => { const v=input as unknown as Record<string,unknown>,n=(x:unknown,a:number,b:number)=>typeof x==="number"&&Number.isFinite(x)&&x>=a&&x<=b,common=[v.seed,v.atMs,v.startMs,v.lifetimeMs,v.width,v.height,v.x,v.y,v.scale,v.originX,v.originY,v.rotationDeg,v.opacity,v.minSize,v.maxSize,v.minSpeed,v.maxSpeed,v.direction,v.spread,v.gravity],required=["kind","id","blendMode","effects","schema","seed","count","atMs","startMs","lifetimeMs","width","height","x","y","scale","originX","originY","rotationDeg","opacity","color","secondaryColor","minSize","maxSize","minSpeed","maxSpeed","direction","spread","gravity","fadeOut","sources","origins","trail","shading","computeDispatchCount","rasterPassCount","instanceBytes","retainedBufferCount","retainedInstanceBytes"],keys=Object.keys(v);return record(v)&&keys.every((key)=>required.includes(key)||key==="mask")&&required.every((key)=>keys.includes(key))&&mask(v.mask)&&v.kind==="particleCompute"&&typeof v.id==="string"&&/^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$/.test(v.id)&&v.blendMode==="normal"&&v.effects===null&&v.schema==="shellx-motion/gpu-compute-particle-field@2"&&Number.isInteger(v.seed)&&n(v.seed,0,0xffffffff)&&Number.isInteger(v.count)&&n(v.count,100000,131072)&&common.every((x)=>typeof x==="number"&&Number.isFinite(x))&&(v.atMs as number)>=0&&(v.startMs as number)>=0&&n(v.lifetimeMs,0.000001,60000)&&n(v.width,0.000001,4096)&&n(v.height,0.000001,4096)&&n(v.x,-1000000,1000000)&&n(v.y,-1000000,1000000)&&n(v.scale,Number.MIN_VALUE,64)&&n(v.originX,-1000000,1000000)&&n(v.originY,-1000000,1000000)&&n(v.rotationDeg,-1000000,1000000)&&n(v.opacity,0,1)&&n(v.minSize,0.000001,4096)&&n(v.maxSize,v.minSize as number,4096)&&n(v.minSpeed,0,2000)&&n(v.maxSpeed,v.minSpeed as number,2000)&&n(v.direction,-1000000,1000000)&&n(v.spread,0,360)&&n(v.gravity,-5000,5000)&&typeof v.fadeOut==="boolean"&&color(v.color)&&color(v.secondaryColor)&&Array.isArray(v.sources)&&v.sources.length>=1&&v.sources.length<=4&&v.sources.every(source)&&Array.isArray(v.origins)&&v.origins.length>=1&&v.origins.length<=4&&v.origins.every(origin)&&admitTrail(v.trail)&&shading(v.shading)&&v.computeDispatchCount===1&&v.rasterPassCount===(v.trail===null?1:2)&&v.instanceBytes===64&&v.retainedBufferCount===2&&v.retainedInstanceBytes===(v.count as number)*128; };
  const encode = (input: Draw, frameWidth: number, frameHeight: number): ArrayBuffer => { const f = new Float32Array(108), u = new Uint32Array(f.buffer), rad = Math.PI / 180; u.set([input.seed, input.count, input.sources.length, input.origins.length]); f.set([input.atMs,input.startMs,input.lifetimeMs,input.fadeOut?1:0],4);f.set([input.width,input.height,frameWidth,frameHeight],8);f.set([input.x,input.y,input.scale,input.rotationDeg*rad],12);f.set([input.originX,input.originY,input.opacity,input.direction*rad],16);f.set([input.minSize,input.maxSize,input.minSpeed,input.maxSpeed],20);f.set([input.spread*rad,input.gravity,input.trail?.durationMs??0,input.trail?.samples??0],24);f.set([input.shading.mode==="flat"?0:input.shading.mode==="soft"?1:2,input.shading.sizeJitter,input.shading.opacityJitter,input.shading.glow],28);f.set([input.color.r,input.color.g,input.color.b,input.color.a],32);f.set([input.secondaryColor.r,input.secondaryColor.g,input.secondaryColor.b,input.secondaryColor.a],36);input.sources.forEach((s: Source,i: number)=>{const o=40+i*8;if(s.kind==="radial"||s.kind==="vortex")f.set([s.kind==="radial"?0:1,s.centerX,s.centerY,s.strength,s.softening,0,0,0],o);else if(s.kind==="flow")f.set([2,s.angleDeg*rad,s.strength,0,0,0,0,0],o);else if(s.kind==="turbulence")f.set([3,s.scale,s.strength,0,0,0,0,0],o);else if(s.kind==="impact")f.set([4,s.centerX,s.centerY,s.radius,s.strength,s.startProgress,s.durationProgress,0],o);else if(s.kind==="collision")f.set([5,s.axis==="x"?0:1,s.position,s.restitution,0,0,0,0],o);});input.origins.forEach((o: Draw["origins"][number],i: number)=>f.set([o.x,o.y,o.weight,o.directionOffsetDeg*rad,o.speedScale,0,0,0],72+i*8));f[104]=input.trail?.opacity??0;return f.buffer; };
  const browserGlobal = globalThis as unknown as { GPUBufferUsage?: Record<string, number>; GPUTextureFormat?: unknown; __shellxMotionGpuSessionV1?: unknown };
  const usage = browserGlobal.GPUBufferUsage;
  const state = browserGlobal.__shellxMotionGpuSessionV1 as { device?: Device; limits?: { maxBufferSize?: number; maxStorageBufferBindingSize?: number }; computeParticlesV2?: unknown } | undefined;
  if (!state?.device || !usage) return fail("The persistent GPU page session cannot install fixed v2 particle compute.");
  if (state.computeParticlesV2) return { ok: true };
  if (![usage.STORAGE, usage.VERTEX, usage.COPY_DST, usage.UNIFORM].every((value) => typeof value === "number")) return fail("The persistent GPU page session does not expose fixed v2 particle buffer usages.");
  const maxBufferSize = state.limits?.maxBufferSize, maxStorage = state.limits?.maxStorageBufferBindingSize;
  const adapterComputeParticleInstanceLimit = typeof maxBufferSize === "number" && typeof maxStorage === "number" ? Math.min(MAX_PARTICLES, Math.floor(maxBufferSize / INSTANCE_BYTES), Math.floor(maxStorage / INSTANCE_BYTES), Math.floor(MAX_RETAINED_BYTES / (INSTANCE_BYTES * BUFFER_COUNT))) : 0;
  if (adapterComputeParticleInstanceLimit < MIN_PARTICLES) return fail("The persistent GPU adapter cannot retain the minimum fixed v2 particle field.");
  const computeShader = `
struct Params { header: vec4<u32>, values: array<vec4<f32>, 26> }
@group(0) @binding(0) var<uniform> p: Params;
@group(0) @binding(1) var<storage, read_write> out: array<vec4<f32>>;
fn rnd(seed:u32,index:u32,channel:u32)->f32 { var v=seed^((index+1u)*0x9e3779b1u)^((channel+1u)*0x85ebca6bu);v=v^(v>>16u);v=v*0x7feb352du;v=v^(v>>15u);v=v*0x846ca68bu;v=v^(v>>16u);return f32(v)/4294967296.0; }
fn noise(seed:u32,index:u32,x:f32,y:f32,t:f32)->f32 { let m=(bitcast<u32>(i32(floor(x*4096.0)))*0x9e3779b1u)^(bitcast<u32>(i32(floor(y*4096.0)))*0x85ebca6bu)^(bitcast<u32>(i32(floor(t*4096.0)))*0xc2b2ae35u);return rnd(seed^m,index,8u); }
fn origin(index:u32)->vec4<f32> { var total=0.0;for(var i=0u;i<4u;i=i+1u){if(i<p.header.w){total=total+p.values[17u+i*2u].z;}}let threshold=rnd(p.header.x,index,5u)*total;var sum=0.0;var picked=0u;for(var i=0u;i<4u;i=i+1u){if(i<p.header.w){sum=sum+p.values[17u+i*2u].z;if(threshold<sum){picked=i;break;}}}return vec4<f32>(p.values[17u+picked*2u].xy,p.values[17u+picked*2u].w,p.values[18u+picked*2u].x); }
fn position(index:u32,time:f32)->vec4<f32> { let timing=p.values[0];let d=p.values[1];let transform=p.values[2];let setup=p.values[3];let range=p.values[4];let physics=p.values[5];let o=origin(index);let phase=rnd(p.header.x,index,0u)*timing.z;let age=(max(0.0,time-timing.y)+phase)%timing.z;let progress=age/timing.z;let globalProgress=clamp((time-timing.y)/timing.z,0.0,1.0);let angle=setup.w+o.z+(rnd(p.header.x,index,1u)-0.5)*physics.x;let speed=(range.z+rnd(p.header.x,index,2u)*(range.w-range.z))*o.w;let size=(range.x+rnd(p.header.x,index,3u)*(range.y-range.x))*(1.0+(rnd(p.header.x,index,6u)*2.0-1.0)*p.values[6].y);let seconds=age/1000.0;let base=vec2<f32>(o.x*d.x+cos(angle)*speed*seconds,o.y*d.y+sin(angle)*speed*seconds+0.5*physics.y*seconds*seconds);var n=base/vec2<f32>(d.x,d.y);let p2=progress*progress;for(var i=0u;i<4u;i=i+1u){if(i>=p.header.z){break;}let a=p.values[9u+i*2u];let b=p.values[10u+i*2u];if(a.x<1.5){let delta=vec2<f32>(a.y,a.z)-n;let r2=dot(delta,delta);if(r2>0.0){let unit=delta/sqrt(r2);let mag=a.w*p2*(b.x*b.x/(r2+b.x*b.x));n=n+select(unit,vec2<f32>(-unit.y,unit.x),a.x>0.5)*mag;}}else if(a.x<2.5){n=n+vec2<f32>(cos(a.y),sin(a.y))*a.z*p2;}else if(a.x<3.5){let angle2=noise(p.header.x,index,n.x*a.y,n.y*a.y,progress)*6.2831853;n=n+vec2<f32>(cos(angle2),sin(angle2))*a.z*p2;}else if(a.x<4.5){let delta=vec2<f32>(a.y,a.z)-n;let dist=length(delta);let local=(globalProgress-b.y)/b.z;if(local>=0.0&&local<=1.0&&dist>0.0){let ring=clamp(1.0-abs(dist-a.w)/a.w,0.0,1.0);n=n-(delta/dist)*(b.x*sin(3.1415926*local)*ring);}}else{if(a.y<0.5&&n.x>a.z){n.x=a.z-(n.x-a.z)*a.w;}if(a.y>=0.5&&n.y>a.z){n.y=a.z-(n.y-a.z)*a.w;}}}let center=base+clamp(n-base/vec2<f32>(d.x,d.y),vec2<f32>(-2.0),vec2<f32>(2.0))*vec2<f32>(d.x,d.y);let pivot=vec2<f32>(transform.x+setup.x,transform.y+setup.y);let placed=vec2<f32>(transform.x+setup.x+(center.x-setup.x)*transform.z,transform.y+setup.y+(center.y-setup.y)*transform.z);let rel=placed-pivot;let rotated=pivot+vec2<f32>(rel.x*cos(transform.w)-rel.y*sin(transform.w),rel.x*sin(transform.w)+rel.y*cos(transform.w));return vec4<f32>(rotated.x/d.z*2.0-1.0,1.0-rotated.y/d.w*2.0,size*transform.z/d.z*2.0,size*transform.z/d.w*2.0); }
@compute @workgroup_size(256) fn main(@builtin(global_invocation_id) id:vec3<u32>){let i=id.x;if(i>=p.header.y){return;}let h=position(i,p.values[0].x);let trail=p.values[5];var t1=position(i,max(p.values[0].y,p.values[0].x-trail.z/max(1.0,trail.w-1.0)));var t2=position(i,max(p.values[0].y,p.values[0].x-trail.z*2.0/max(1.0,trail.w-1.0)));var t3=position(i,max(p.values[0].y,p.values[0].x-trail.z));let s=u32(trail.w);if(s<3u){t2=t1;t3=t1;}else if(s<4u){t3=t2;}if(s<2u){t1=h;t2=h;t3=h;}let c=select(p.values[7],p.values[8],rnd(p.header.x,i,4u)>=0.5);let phase=rnd(p.header.x,i,0u)*p.values[0].z;let progress=((max(0.0,p.values[0].x-p.values[0].y)+phase)%p.values[0].z)/p.values[0].z;let alpha=c.w*p.values[3].z*select(1.0,max(0.0,1.0-progress),p.values[0].w>0.5)*(1.0-rnd(p.header.x,i,7u)*p.values[6].z);let at=i*4u;out[at]=h;out[at+1u]=vec4<f32>(t1.xy,t2.xy);out[at+2u]=vec4<f32>(t3.xy,p.values[25].x,p.values[6].x+p.values[6].w*0.25);out[at+3u]=vec4<f32>(c.xyz*alpha,alpha); }
`;
  const drawShader = `
struct In { @location(0) head:vec4<f32>, @location(1) tails:vec4<f32>, @location(2) tail:vec4<f32>, @location(3) color:vec4<f32> }
struct Out { @builtin(position) pos:vec4<f32>, @location(0) uv:vec2<f32>, @location(1) color:vec4<f32>, @location(2) present:vec2<f32> }
@vertex fn headVs(input:In,@builtin(vertex_index) v:u32)->Out { var q=array<vec2<f32>,6>(vec2(-1.,-1.),vec2(1.,-1.),vec2(1.,1.),vec2(-1.,-1.),vec2(1.,1.),vec2(-1.,1.));let a=q[v];let glowAmount=fract(input.tail.w)*4.;let halo=select(1.,1.+glowAmount*.8,floor(input.tail.w)>1.5);var o:Out;o.pos=vec4(input.head.xy+a*input.head.zw*halo,0.,1.);o.uv=a;o.color=input.color;o.present=input.tail.zw;return o; }
@fragment fn headFs(i:Out)->@location(0) vec4<f32>{let r=dot(i.uv,i.uv);if(r>1.){discard;}let mode=floor(i.present.y);let soft=1.-smoothstep(0.45,1.,r);let fall=select(1.,soft,mode>0.5);let coverage=select(fall,max(soft,1.-sqrt(r)),mode>1.5);return clamp(i.color*coverage,vec4<f32>(0.),vec4<f32>(1.));}
@vertex fn trailVs(input:In,@builtin(vertex_index) v:u32)->Out { let segment=v/6u;let corner=v%6u;var a=input.head.xy;var b=input.tails.xy;if(segment==1u){a=input.tails.xy;b=input.tails.zw;}if(segment==2u){a=input.tails.zw;b=input.tail.xy;}let delta=b-a;let local=delta/input.head.zw;let len=length(local);var o:Out;if(len<0.000001){o.pos=vec4(2.,2.,0.,1.);}else{let n=vec2(-local.y,local.x)/len*input.head.zw*0.45;let q=array<vec2<f32>,6>(vec2(0.,-1.),vec2(0.,1.),vec2(1.,1.),vec2(0.,-1.),vec2(1.,1.),vec2(1.,-1.))[corner];o.pos=vec4(mix(a,b,q.x)+n*q.y,0.,1.);}o.uv=vec2(0.);o.color=input.color*input.tail.z;o.present=input.tail.zw;return o; }
@fragment fn trailFs(i:Out)->@location(0) vec4<f32>{return i.color;}
`;
  let compute: Pipeline, head: Pipeline, trailPipeline: Pipeline;
  try {
    const cm = state.device.createShaderModule({ code: computeShader }), dm = state.device.createShaderModule({ code: drawShader });
    for (const [label, module] of [["compute", cm], ["draw", dm]] as const) {
      const compilation = await module.getCompilationInfo?.();
      const shaderError = compilation?.messages?.find((message) => message.type === "error");
      if (shaderError) throw new Error(`${label} WGSL ${shaderError.lineNum ?? 0}:${shaderError.linePos ?? 0}: ${shaderError.message ?? "validation failed"}`);
    }
    const cp = { layout: "auto", compute: { module: cm, entryPoint: "main" } }, hp = { layout: "auto", vertex: { module: dm, entryPoint: "headVs", buffers: [{ arrayStride: INSTANCE_BYTES, stepMode: "instance", attributes: [{ shaderLocation: 0, offset: 0, format: "float32x4" }, { shaderLocation: 1, offset: 16, format: "float32x4" }, { shaderLocation: 2, offset: 32, format: "float32x4" }, { shaderLocation: 3, offset: 48, format: "float32x4" }] }] }, fragment: { module: dm, entryPoint: "headFs", targets: [{ format: "rgba8unorm", blend: { color: { srcFactor: "one", dstFactor: "one-minus-src-alpha" }, alpha: { srcFactor: "one", dstFactor: "one-minus-src-alpha" } } }] }, primitive: { topology: "triangle-list" } }, tp = { ...hp, vertex: { ...hp.vertex, entryPoint: "trailVs" }, fragment: { ...hp.fragment, entryPoint: "trailFs" } };
    compute = state.device.createComputePipelineAsync ? await state.device.createComputePipelineAsync(cp) : state.device.createComputePipeline(cp);
    head = state.device.createRenderPipelineAsync ? await state.device.createRenderPipelineAsync(hp) : state.device.createRenderPipeline(hp);
    trailPipeline = state.device.createRenderPipelineAsync ? await state.device.createRenderPipelineAsync(tp) : state.device.createRenderPipeline(tp);
  } catch (error) { return fail(`The persistent GPU page session fixed v2 particle shader is invalid: ${error instanceof Error ? error.message.slice(0, 512) : "unknown error"}`); }
  const uniform = state.device.createBuffer({ size: UNIFORM_BYTES, usage: usage.UNIFORM | usage.COPY_DST }); const buffers: BufferFacade[] = [], bindGroups: unknown[] = [];
  let count = 0, active = 0, dispatches = 0, highWaterSlots = 0, highWaterBytes = 0, rasterCalls = 0, headRasterCalls = 0, trailRasterCalls = 0, capacityReconfigurations = 0, lateAllocationRefusals = 0;
  const snapshot = (): GpuPageComputeParticleV2Metrics => Object.freeze({ schema: "shellx-motion/gpu-page-particle-compute-v2@1", abi: "shellx-motion/gpu-compute-particle-field@2", pointRaster: "gpu-native-instanced", positionEvaluation: dispatches ? "gpu-fixed-analytic-time" : "core-cpu-exact-time", computeField: dispatches ? "fixed-analytic-v2" : "not-used", computeParticleBufferSlots: buffers.length, computeParticleBufferBytes: count * INSTANCE_BYTES * buffers.length, computeParticleBufferHighWaterSlots: highWaterSlots, computeParticleBufferHighWaterBytes: highWaterBytes, adapterComputeParticleInstanceLimit, computeParticleDispatches: dispatches, instanceBytes: 64, retainedBufferCount: 2, uniformBytes: 432, rasterCalls, headRasterCalls, trailRasterCalls, capacityReconfigurations, lateAllocationRefusals });
  const render = (input: Draw, frameWidth: number, frameHeight: number, encoder: Encoder, target: TextureFacade): void => {
    if (!admit(input) || input.count > adapterComputeParticleInstanceLimit || input.retainedInstanceBytes > MAX_RETAINED_BYTES) { lateAllocationRefusals += 1; throw new Error("The v2 particle descriptor exceeds the fixed browser ABI or adapter budget."); }
    if (count !== 0 && count !== input.count) { lateAllocationRefusals += 1; capacityReconfigurations += 1; throw new Error("The retained v2 particle buffers cannot grow or change capacity in a live page session."); }
    if (count === 0) { count = input.count; const size = count * INSTANCE_BYTES; for (let i = 0; i < BUFFER_COUNT; i += 1) { const buffer = state.device!.createBuffer({ size, usage: usage.STORAGE | usage.VERTEX | usage.COPY_DST }); buffers.push(buffer); bindGroups.push(state.device!.createBindGroup({ layout: compute.getBindGroupLayout(0), entries: [{ binding: 0, resource: { buffer: uniform } }, { binding: 1, resource: { buffer } }] })); } highWaterSlots = buffers.length; highWaterBytes = size * buffers.length; }
    const bytes = encode(input, frameWidth, frameHeight); state.device!.queue.writeBuffer(uniform, 0, bytes); active = 1 - active;
    const pass = encoder.beginComputePass(); pass.setPipeline(compute); pass.setBindGroup(0, bindGroups[active]); pass.dispatchWorkgroups(Math.ceil(count / WORKGROUP_SIZE)); pass.end(); dispatches += 1;
    if (input.trail) { const present = encoder.beginRenderPass({ colorAttachments: [{ view: target.createView(), loadOp: "load", storeOp: "store" }] }); present.setPipeline(trailPipeline); present.setVertexBuffer(0, buffers[active]); present.draw(18, count); present.end(); rasterCalls += 1; trailRasterCalls += 1; }
    const present = encoder.beginRenderPass({ colorAttachments: [{ view: target.createView(), loadOp: "load", storeOp: "store" }] }); present.setPipeline(head); present.setVertexBuffer(0, buffers[active]); present.draw(6, count); present.end(); rasterCalls += 1; headRasterCalls += 1;
  };
  const destroy = (): void => { uniform.destroy?.(); for (const buffer of buffers) buffer.destroy?.(); buffers.length = 0; bindGroups.length = 0; count = 0; };
  (state as { computeParticlesV2?: unknown }).computeParticlesV2 = { render, snapshot, destroy };
  return { ok: true };
}
