import type { GpuPageScene3dGltfPbrResourceInput } from "./gpu-page-scene3d-gltf-pbr-resources";
import type { GpuPageScene3dGltfPbrHdr10PipelineIdentity } from "./gpu-page-scene3d-gltf-pbr-hdr10-pipeline";
import type { GpuRuntimeFailure } from "./gpu-runtime-types";

export const GPU_PAGE_SCENE3D_GLTF_PBR_HDR10_RESOURCE_SCHEMA = "shellx-motion/gpu-page-scene3d-gltf-pbr-hdr10-resources@1" as const;
export interface GpuPageScene3dGltfPbrHdr10ResourceInput {
  readonly schema: typeof GPU_PAGE_SCENE3D_GLTF_PBR_HDR10_RESOURCE_SCHEMA; readonly staticFingerprint: string; readonly sdrStaticFingerprint: string; readonly frameFingerprint: string; readonly sourceSha256: string;
  readonly pbr: GpuPageScene3dGltfPbrResourceInput["pbr"]; readonly pipeline: GpuPageScene3dGltfPbrHdr10PipelineIdentity;
  readonly textures: GpuPageScene3dGltfPbrResourceInput["textures"]; readonly primitives: GpuPageScene3dGltfPbrResourceInput["primitives"]; readonly camera: GpuPageScene3dGltfPbrResourceInput["camera"];
  readonly budget: { readonly staticGpuBytes: number; readonly renderTargetBytes: 7_372_800; readonly depthTargetBytes: 3_686_400; readonly readbackBytes: 7_372_800; readonly frameGpuBytes: number; readonly peakGpuBytes: number; };
}
export interface GpuPageScene3dGltfPbrHdr10ResourceMetrics { readonly schema: "shellx-motion/gpu-page-scene3d-gltf-pbr-hdr10-resource-metrics@1"; readonly staticFingerprint: string; readonly textureSlots: number; readonly primitiveSlots: number; readonly staticGpuBytes: number; readonly renderTargetBytes: 7_372_800; readonly depthTargetBytes: 3_686_400; readonly readbackBytes: 7_372_800; readonly frameGpuBytes: number; readonly peakGpuBytes: number; readonly mipGenerationPasses: number; readonly preparationOperations: 1; readonly renderedFrames: number; readonly retainedFrameAllocations: 0; }
export interface GpuPageScene3dGltfPbrHdr10ReleaseEvidence { readonly schema: "shellx-motion/gpu-page-scene3d-gltf-pbr-hdr10-release@1"; readonly reason: "terminal" | "cancelled"; readonly hadResources: boolean; readonly destroyedTextures: number; readonly destroyedVertexBuffers: number; readonly destroyedIndexBuffers: number; readonly destroyedUniformBuffers: number; readonly destroyedRenderTargets: 0 | 2; readonly releasedGpuBytes: number; readonly remainingGpuBytes: 0; }
export type GpuPageScene3dGltfPbrHdr10ResourceOutput = { readonly ok: true; readonly metrics: GpuPageScene3dGltfPbrHdr10ResourceMetrics } | { readonly ok: false; readonly failure: GpuRuntimeFailure };

/** Validates every byte, factor, limit, identity, and opaque alpha before creating any GPU object. */
export async function prepareWebGpuPageSessionScene3dGltfPbrHdr10Resources(input: GpuPageScene3dGltfPbrHdr10ResourceInput): Promise<GpuPageScene3dGltfPbrHdr10ResourceOutput> {
  const WIDTH = 1280, HEIGHT = 720, TARGET = 7_372_800, DEPTH = 3_686_400, READBACK = 7_372_800, MAX_STATIC = 48 * 1024 * 1024, MAX_PEAK = 72 * 1024 * 1024;
  type Texture = { createView(value?: unknown): unknown; destroy?(): void }; type Buffer = { destroy?(): void }; type Pipeline = { getBindGroupLayout(index: number): unknown };
  type State = { device?: { createTexture(value: unknown): Texture; createBuffer(value: unknown): Buffer; createSampler(value: unknown): unknown; createBindGroup(value: unknown): unknown; createCommandEncoder(): { beginRenderPass(value: unknown): { setPipeline(value: unknown): void; setBindGroup(index: number, value: unknown): void; draw(count: number): void; end(): void }; finish(): unknown }; queue: { writeTexture(...value: unknown[]): void; writeBuffer(...value: unknown[]): void; submit(value: readonly unknown[]): void; onSubmittedWorkDone?(): Promise<void> } }; limits?: { maxTextureDimension2D: number; maxBufferSize: number }; hdr10PbrPipeline?: Pipeline; hdr10PbrMipPipeline?: Pipeline; hdr10PbrPipelineIdentity?: GpuPageScene3dGltfPbrHdr10PipelineIdentity; resources?: { staticFingerprint: string; sdrStaticFingerprint: string; frameFingerprint: string; textures: Texture[]; primitives: Array<{ vertex: Buffer; index: Buffer; uniform: Buffer; bindGroup: unknown; indexCount: number }>; target: Texture; depth: Texture; metrics: GpuPageScene3dGltfPbrHdr10ResourceMetrics; renderedFrames: number }; lost?: boolean };
  const global = globalThis as unknown as { GPUBufferUsage?: Record<string, number>; GPUTextureUsage?: Record<string, number>; __shellxMotionGpuHdr10PbrSessionV1?: State }, state = global.__shellxMotionGpuHdr10PbrSessionV1, usage = global.GPUBufferUsage, textureUsage = global.GPUTextureUsage;
  if (!state?.device || !state.limits || !usage || !textureUsage || !state.hdr10PbrPipeline || !state.hdr10PbrMipPipeline || !state.hdr10PbrPipelineIdentity) return fail("gpu_device_unavailable", "The HDR10 PBR page session has no admitted pipeline.");
  if (state.lost) return fail("gpu_device_lost", "The HDR10 PBR device was lost before preparation.");
  if (state.resources) return sameResources(state.resources, input) ? { ok: true, metrics: state.resources.metrics } : fail("gpu_resource_refused", "The HDR10 PBR page permits one immutable resource identity.");
  if (!await admit(input, state.hdr10PbrPipelineIdentity, state.limits)) return fail("gpu_resource_refused", "The HDR10 PBR page refused its pre-allocation contract.");
  const textures: Texture[] = [], primitives: Array<{ vertex: Buffer; index: Buffer; uniform: Buffer; bindGroup: unknown; indexCount: number }> = []; let target: Texture | undefined, depth: Texture | undefined, mipGenerationPasses = 0;
  try {
    const sampler = state.device.createSampler({ addressModeU: "repeat", addressModeV: "repeat", magFilter: "linear", minFilter: "linear", mipmapFilter: "linear" }), byId = new Map<string, Texture>();
    for (const texture of input.textures) {
      const rgba = decode(texture.rgbaBase64, texture.decodedRgbaByteLength), resource = state.device.createTexture({ size: { width: texture.width, height: texture.height, depthOrArrayLayers: 1 }, format: "rgba8unorm-srgb", mipLevelCount: texture.mipLevelCount, usage: textureUsage.COPY_DST! | textureUsage.TEXTURE_BINDING! | textureUsage.RENDER_ATTACHMENT! });
      textures.push(resource); state.device.queue.writeTexture({ texture: resource, mipLevel: 0 }, rgba, { bytesPerRow: texture.width * 4, rowsPerImage: texture.height }, { width: texture.width, height: texture.height, depthOrArrayLayers: 1 });
      for (let level = 1; level < texture.mipLevelCount; level += 1) { const bindGroup = state.device.createBindGroup({ layout: state.hdr10PbrMipPipeline.getBindGroupLayout(0), entries: [{ binding: 0, resource: resource.createView({ baseMipLevel: level - 1, mipLevelCount: 1 }) }, { binding: 1, resource: sampler }] }), encoder = state.device.createCommandEncoder(), pass = encoder.beginRenderPass({ colorAttachments: [{ view: resource.createView({ baseMipLevel: level, mipLevelCount: 1 }), loadOp: "clear", storeOp: "store" }] }); pass.setPipeline(state.hdr10PbrMipPipeline); pass.setBindGroup(0, bindGroup); pass.draw(3); pass.end(); state.device.queue.submit([encoder.finish()]); mipGenerationPasses += 1; }
      byId.set(texture.resourceId, resource);
    }
    for (const primitive of input.primitives) {
      const texture = byId.get(primitive.textureResourceId); if (!texture) throw new Error("missing texture");
      const vertex = state.device.createBuffer({ size: primitive.vertexBufferByteLength, usage: usage.COPY_DST! | usage.VERTEX! }), index = state.device.createBuffer({ size: primitive.indexBufferByteLength, usage: usage.COPY_DST! | usage.INDEX! }), uniform = state.device.createBuffer({ size: 256, usage: usage.COPY_DST! | usage.UNIFORM! });
      state.device.queue.writeBuffer(vertex, 0, decode(primitive.verticesBase64, primitive.vertexBufferByteLength).buffer); state.device.queue.writeBuffer(index, 0, decode(primitive.indicesBase64, primitive.indexBufferByteLength).buffer); state.device.queue.writeBuffer(uniform, 0, uniformData(primitive, input).buffer);
      primitives.push({ vertex, index, uniform, indexCount: primitive.indexCount, bindGroup: state.device.createBindGroup({ layout: state.hdr10PbrPipeline.getBindGroupLayout(0), entries: [{ binding: 0, resource: { buffer: uniform } }, { binding: 1, resource: texture.createView() }, { binding: 2, resource: sampler }] }) });
    }
    target = state.device.createTexture({ size: { width: WIDTH, height: HEIGHT, depthOrArrayLayers: 1 }, format: "rgba16float", usage: textureUsage.RENDER_ATTACHMENT! | textureUsage.COPY_SRC! }); depth = state.device.createTexture({ size: { width: WIDTH, height: HEIGHT, depthOrArrayLayers: 1 }, format: "depth24plus", usage: textureUsage.RENDER_ATTACHMENT! });
    const metrics: GpuPageScene3dGltfPbrHdr10ResourceMetrics = Object.freeze({ schema: "shellx-motion/gpu-page-scene3d-gltf-pbr-hdr10-resource-metrics@1", staticFingerprint: input.staticFingerprint, textureSlots: textures.length, primitiveSlots: primitives.length, staticGpuBytes: input.budget.staticGpuBytes, renderTargetBytes: TARGET, depthTargetBytes: DEPTH, readbackBytes: READBACK, frameGpuBytes: input.budget.frameGpuBytes, peakGpuBytes: input.budget.peakGpuBytes, mipGenerationPasses, preparationOperations: 1, renderedFrames: 0, retainedFrameAllocations: 0 });
    state.resources = { staticFingerprint: input.staticFingerprint, sdrStaticFingerprint: input.sdrStaticFingerprint, frameFingerprint: input.frameFingerprint, textures, primitives, target, depth, metrics, renderedFrames: 0 }; return { ok: true, metrics };
  } catch { for (const primitive of primitives) { primitive.vertex.destroy?.(); primitive.index.destroy?.(); primitive.uniform.destroy?.(); } for (const texture of textures) texture.destroy?.(); target?.destroy?.(); depth?.destroy?.(); return fail("gpu_render_failed", "HDR10 PBR resource preparation failed closed."); }
  function fail(code: GpuRuntimeFailure["code"], message: string): GpuPageScene3dGltfPbrHdr10ResourceOutput { return { ok: false, failure: { code, message } }; }
  function sameResources(current: NonNullable<State["resources"]>, value: GpuPageScene3dGltfPbrHdr10ResourceInput): boolean { return current.staticFingerprint === value.staticFingerprint && current.sdrStaticFingerprint === value.sdrStaticFingerprint && current.frameFingerprint === value.frameFingerprint; }
  function decode(value: string, expected: number): Uint8Array { if (typeof value !== "string" || !/^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$/.test(value) || value.length !== Math.ceil(expected / 3) * 4) throw new Error("base64"); const binary = atob(value), bytes = new Uint8Array(binary.length); if (bytes.byteLength !== expected) throw new Error("base64 length"); for (let i = 0; i < bytes.length; i += 1) bytes[i] = binary.charCodeAt(i); return bytes; }
  function uniformData(primitive: GpuPageScene3dGltfPbrHdr10ResourceInput["primitives"][number], plan: GpuPageScene3dGltfPbrHdr10ResourceInput): Float32Array { const values = new Float32Array(64); values.set(primitive.modelMatrix, 0); values.set(plan.camera.viewProjection, 16); values.set(primitive.material.baseColorFactor, 32); values.set([...primitive.material.emissiveFactor, primitive.material.metallicFactor], 36); values.set([primitive.material.roughnessFactor, plan.pbr.directionalLight.ambientDiffuse, 0, 0], 40); values.set([...plan.pbr.directionalLight.direction, plan.pbr.directionalLight.intensity], 44); values.set([...plan.pbr.directionalLight.color, 0], 48); values.set([...plan.camera.position, 0], 52); return values; }
  async function admit(value: unknown, identity: GpuPageScene3dGltfPbrHdr10PipelineIdentity, limits: NonNullable<State["limits"]>): Promise<boolean> {
    if (!value || typeof value !== "object") return false; const plan = value as GpuPageScene3dGltfPbrHdr10ResourceInput;
    if (!keys(plan, ["schema", "staticFingerprint", "sdrStaticFingerprint", "frameFingerprint", "sourceSha256", "pbr", "pipeline", "textures", "primitives", "camera", "budget"]) || plan.schema !== "shellx-motion/gpu-page-scene3d-gltf-pbr-hdr10-resources@1" || !hash(plan.staticFingerprint) || !hash(plan.sdrStaticFingerprint) || !hash(plan.frameFingerprint) || !hash(plan.sourceSha256) || !same(plan.pipeline, identity) || !pbr(plan.pbr) || !camera(plan.camera) || !Array.isArray(plan.textures) || !Array.isArray(plan.primitives) || plan.textures.length < 1 || plan.textures.length > 16 || plan.primitives.length < 1 || plan.primitives.length > 16) return false;
    const textureIds = new Set<string>(), primitiveIds = new Set<string>(); let staticBytes = 0;
    for (const texture of plan.textures) { if (!textureShape(texture, limits) || textureIds.has(texture.resourceId) || !await imageIdentity(texture)) return false; textureIds.add(texture.resourceId); staticBytes += texture.mipmappedRgbaByteLength; }
    for (const primitive of plan.primitives) { if (!primitiveShape(primitive, limits, textureIds) || primitiveIds.has(primitive.id) || primitive.sourceSha256 !== plan.sourceSha256 || !await geometryIdentity(primitive)) return false; primitiveIds.add(primitive.id); staticBytes += primitive.vertexBufferByteLength + primitive.indexBufferByteLength + 256; }
    return fixedViewportFits(limits) && staticBytes === plan.budget.staticGpuBytes && Number.isSafeInteger(staticBytes) && staticBytes <= MAX_STATIC && plan.budget.renderTargetBytes === TARGET && plan.budget.depthTargetBytes === DEPTH && plan.budget.readbackBytes === READBACK && plan.budget.frameGpuBytes === staticBytes + TARGET + DEPTH && plan.budget.peakGpuBytes === plan.budget.frameGpuBytes + READBACK && plan.budget.peakGpuBytes <= MAX_PEAK;
  }
  async function imageIdentity(texture: GpuPageScene3dGltfPbrHdr10ResourceInput["textures"][number]): Promise<boolean> { try { const bytes = decode(texture.rgbaBase64, texture.decodedRgbaByteLength); for (let i = 3; i < bytes.length; i += 4) if (bytes[i] !== 255) return false; return await sha(bytes) === texture.decodedRgbaSha256; } catch { return false; } }
  async function geometryIdentity(primitive: GpuPageScene3dGltfPbrHdr10ResourceInput["primitives"][number]): Promise<boolean> { try { const vertices = decode(primitive.verticesBase64, primitive.vertexBufferByteLength), indices = decode(primitive.indicesBase64, primitive.indexBufferByteLength); if (await sha(vertices) !== primitive.vertexBufferSha256 || await sha(indices) !== primitive.indexBufferSha256 || !Array.from(new Float32Array(vertices.buffer)).every(Number.isFinite)) return false; return Array.from(new Uint32Array(indices.buffer)).every((index) => index < primitive.vertexCount); } catch { return false; } }
  async function sha(bytes: Uint8Array): Promise<string> { const digest = new Uint8Array(await globalThis.crypto.subtle.digest("SHA-256", bytes as unknown as BufferSource)); return Array.from(digest).map((byte) => byte.toString(16).padStart(2, "0")).join(""); }
  function textureShape(value: unknown, limits: NonNullable<State["limits"]>): value is GpuPageScene3dGltfPbrHdr10ResourceInput["textures"][number] { if (!value || typeof value !== "object") return false; const t = value as GpuPageScene3dGltfPbrHdr10ResourceInput["textures"][number], decoded = t.width * t.height * 4; return keys(t, ["resourceId", "assetRef", "encodedSha256", "decodedRgbaSha256", "width", "height", "decodedRgbaByteLength", "mipLevelCount", "mipmappedRgbaByteLength", "rgbaBase64"]) && id(t.resourceId) && local(t.assetRef) && hash(t.encodedSha256) && hash(t.decodedRgbaSha256) && integer(t.width, 1, limits.maxTextureDimension2D) && integer(t.height, 1, limits.maxTextureDimension2D) && decoded === t.decodedRgbaByteLength && decoded <= 16 * 1024 * 1024 && t.mipLevelCount === mips(t.width, t.height).levels && t.mipmappedRgbaByteLength === mips(t.width, t.height).bytes; }
  function primitiveShape(value: unknown, limits: NonNullable<State["limits"]>, textures: ReadonlySet<string>): value is GpuPageScene3dGltfPbrHdr10ResourceInput["primitives"][number] { if (!value || typeof value !== "object") return false; const p = value as GpuPageScene3dGltfPbrHdr10ResourceInput["primitives"][number]; return keys(p, ["id", "sourceSha256", "textureResourceId", "vertexCount", "indexCount", "vertexBufferSha256", "vertexBufferByteLength", "indexBufferSha256", "indexBufferByteLength", "verticesBase64", "indicesBase64", "modelMatrix", "material"]) && id(p.id) && hash(p.sourceSha256) && textures.has(p.textureResourceId) && integer(p.vertexCount, 3, 1_048_576) && integer(p.indexCount, 3, 3_145_728) && p.indexCount % 3 === 0 && p.vertexBufferByteLength === p.vertexCount * 32 && p.indexBufferByteLength === p.indexCount * 4 && p.vertexBufferByteLength <= limits.maxBufferSize && p.indexBufferByteLength <= limits.maxBufferSize && hash(p.vertexBufferSha256) && hash(p.indexBufferSha256) && list(p.modelMatrix, 16, -10_000, 10_000) && material(p.material); }
  function pbr(value: GpuPageScene3dGltfPbrHdr10ResourceInput["pbr"]): boolean { return !!value && keys(value, ["abi", "baseColorTextureFormat", "baseColorTextureTransfer", "factorSpace", "brdf", "ambient", "directionalLight", "outputTransfer"]) && value.abi === "shellx-motion/browser-scene3d-gltf-pbr-sdr@1" && value.baseColorTextureFormat === "rgba8unorm-srgb" && value.baseColorTextureTransfer === "srgb-to-linear-hardware" && value.factorSpace === "linear-gltf" && value.brdf === "ggx-smith-schlick-directional@1" && value.ambient === "bounded-diffuse@1" && value.outputTransfer === "linear-to-srgb-explicit" && JSON.stringify(value.directionalLight) === JSON.stringify({ direction: [-0.4, -0.8, -0.4], color: [1, 1, 1], intensity: 1, ambientDiffuse: 0.15 }); }
  function camera(value: unknown): boolean { const c = value as GpuPageScene3dGltfPbrHdr10ResourceInput["camera"]; return !!c && keys(c, ["viewport", "projection", "fovDeg", "near", "far", "position", "target", "viewProjection"]) && keys(c.viewport, ["width", "height"]) && c.viewport.width === WIDTH && c.viewport.height === HEIGHT && c.projection === "perspective@1" && c.fovDeg === 42 && finite(c.near, 0.01, 100) && finite(c.far, c.near + 0.001, 10_000) && list(c.position, 3, -10_000, 10_000) && list(c.target, 3, -10_000, 10_000) && list(c.viewProjection, 16, -1_000_000, 1_000_000); }
  function material(value: unknown): boolean { const m = value as GpuPageScene3dGltfPbrHdr10ResourceInput["primitives"][number]["material"]; return !!m && keys(m, ["baseColorFactor", "metallicFactor", "roughnessFactor", "emissiveFactor"]) && list(m.baseColorFactor, 4, 0, 1) && m.baseColorFactor[3] === 1 && list(m.emissiveFactor, 3, 0, 64) && finite(m.metallicFactor, 0, 1) && finite(m.roughnessFactor, 0, 1); }
  function fixedViewportFits(limits: NonNullable<State["limits"]>): boolean { return integer(limits.maxTextureDimension2D, Math.max(WIDTH, HEIGHT), Number.MAX_SAFE_INTEGER) && integer(limits.maxBufferSize, READBACK, Number.MAX_SAFE_INTEGER); }
  function mips(w: number, h: number): { levels: number; bytes: number } { let levels = 0, bytes = 0; while (true) { levels += 1; bytes += w * h * 4; if (w === 1 && h === 1) return { levels, bytes }; w = Math.max(1, Math.floor(w / 2)); h = Math.max(1, Math.floor(h / 2)); } }
  function same(left: GpuPageScene3dGltfPbrHdr10PipelineIdentity, right: GpuPageScene3dGltfPbrHdr10PipelineIdentity): boolean { return !!left && left.abi === right.abi && left.pipelineImplementationSha256 === right.pipelineImplementationSha256 && left.resourceCeilingSha256 === right.resourceCeilingSha256; }
  function list(value: unknown, length: number, min: number, max: number): boolean { return Array.isArray(value) && value.length === length && value.every((entry) => finite(entry, min, max)); }
  function finite(value: unknown, min: number, max: number): value is number { return typeof value === "number" && Number.isFinite(value) && value >= min && value <= max; }
  function integer(value: unknown, min: number, max: number): value is number { return typeof value === "number" && Number.isSafeInteger(value) && value >= min && value <= max; }
  function keys(value: object, expected: readonly string[]): boolean { const actual = Object.keys(value).sort(), wanted = [...expected].sort(); return actual.length === wanted.length && actual.every((key, index) => key === wanted[index]); }
  function hash(value: unknown): value is string { return typeof value === "string" && /^[a-f0-9]{64}$/.test(value); }
  function id(value: unknown): value is string { return typeof value === "string" && /^[a-z][a-z0-9-]{0,127}$/.test(value); }
  function local(value: unknown): value is string { return typeof value === "string" && /^(?:[a-z0-9][a-z0-9._-]{0,127}\/){0,7}[a-z0-9][a-z0-9._-]{0,127}$/.test(value); }
}

export function releaseWebGpuPageSessionScene3dGltfPbrHdr10Resources(reason: "terminal" | "cancelled" = "terminal"): GpuPageScene3dGltfPbrHdr10ReleaseEvidence {
  type Resource = { metrics: GpuPageScene3dGltfPbrHdr10ResourceMetrics; textures: Array<{ destroy?(): void }>; primitives: Array<{ vertex: { destroy?(): void }; index: { destroy?(): void }; uniform: { destroy?(): void } }>; target: { destroy?(): void }; depth: { destroy?(): void } };
  const state = (globalThis as unknown as { __shellxMotionGpuHdr10PbrSessionV1?: { resources?: Resource } }).__shellxMotionGpuHdr10PbrSessionV1, resources = state?.resources;
  if (!resources) return { schema: "shellx-motion/gpu-page-scene3d-gltf-pbr-hdr10-release@1", reason, hadResources: false, destroyedTextures: 0, destroyedVertexBuffers: 0, destroyedIndexBuffers: 0, destroyedUniformBuffers: 0, destroyedRenderTargets: 0, releasedGpuBytes: 0, remainingGpuBytes: 0 };
  for (const texture of resources.textures) texture.destroy?.(); for (const primitive of resources.primitives) { primitive.vertex.destroy?.(); primitive.index.destroy?.(); primitive.uniform.destroy?.(); } resources.target.destroy?.(); resources.depth.destroy?.(); delete state!.resources;
  return { schema: "shellx-motion/gpu-page-scene3d-gltf-pbr-hdr10-release@1", reason, hadResources: true, destroyedTextures: resources.textures.length, destroyedVertexBuffers: resources.primitives.length, destroyedIndexBuffers: resources.primitives.length, destroyedUniformBuffers: resources.primitives.length, destroyedRenderTargets: 2, releasedGpuBytes: resources.metrics.frameGpuBytes, remainingGpuBytes: 0 };
}

/** Page-evaluate compatible terminal release entrypoint for persistent final sessions. */
export function terminalReleaseWebGpuPageSessionScene3dGltfPbrHdr10Resources(): GpuPageScene3dGltfPbrHdr10ReleaseEvidence {
  return releaseWebGpuPageSessionScene3dGltfPbrHdr10Resources("terminal");
}
