/**
 * version.ts — canonical ShellX Motion engine version.
 *
 * GENERATED FILE — do not edit by hand. Generated by `scripts/version-parity.ts` from the
 * `version` field of the repository root `package.json`, which is the single source of truth
 * for every version ShellX Motion reports. Regenerate with `pnpm run version:sync`;
 * `pnpm run version:check` (part of `pnpm test`) fails when this file, the workspace
 * manifests, the CLI, the SDK, the debug server or the docs disagree.
 *
 * Role: the constant every runtime surface reads, so a version reported to a user or an agent
 * can never differ between transports — the CLI banner, `GET /health`, `GET /debug/contracts`,
 * the MCP `serverInfo` handshake, the local SDK capability contract, and the Engine Room
 * update comparison against the GitHub release feed all resolve to this one string.
 *
 * Dependencies: none (a leaf constant module, safe to import anywhere).
 *
 * Primary callers: `@shellx-motion/debug-server` (transport payloads and the
 * `/workbench/update-check` / `/workbench/update-apply` comparison), `@shellx-motion/sdk`
 * (`createLocalMotionSdk().capabilities().sdkVersion`).
 *
 * Releasing: bump the root `package.json` version, run `pnpm run version:sync`, commit the
 * regenerated manifests and this file together.
 */
export const MOTION_ENGINE_VERSION = "0.1.0";
