/** Fixed C6B7b sidecar/receipt bytes. No command, renderer, or GPU wrapper imports this module. */
import { canonicalJson, canonicalJsonSha256, hashBuffer, readBoundedStableFile, writeVerifiedBoundedFile } from "@shellx-motion/core";
import { readCheckpointStoryboard } from "@shellx-motion/core/internal/checkpoint-storyboard-scalar-spatial-materializer";
import { join } from "node:path";
import { PackageEditTransactionError } from "../package-edit-transaction.js";
import { C6B7B_RECEIPT_PATH, C6B7B_SIDECAR_PATH, type C6B7bInventory, type C6B7bPackageIdentity } from "./checkpoint-storyboard-retained-trace-materialize-facts-private.js";

export const C6B7B_SIDECAR_SCHEMA = "shellx-motion/private-checkpoint-storyboard-retained-trace-profile-plan@1" as const;
export const C6B7B_RECEIPT_SCHEMA = "shellx-motion/private-checkpoint-storyboard-retained-trace-materialization-receipt@1" as const;
export const C6B7B_RECEIPT_OPERATION = "checkpoint-storyboard.retained-trace.materialize" as const;
export const C6B7B_MAX_PLAN_BYTES = 512 * 1024;
const MAX_RECEIPT_BYTES = 1024 * 1024, HASH = /^[a-f0-9]{64}$/u;
export interface C6B7bArtifactIdentity { readonly path: string; readonly rawSha256: string; readonly byteLength: number; readonly canonicalSha256: string; }
export interface C6B7bExactBase { readonly source: C6B7bPackageIdentity; readonly planFingerprint: string; readonly profileFingerprint: string; readonly storyboardId: string; readonly storyboardSha256: string; readonly storyboardRevision: number; readonly sourceLayerId: string; readonly sourceLayerIndex: 0; readonly staticOpacity: number; readonly traceSourceSha256: string; readonly tracePlanFingerprint: string; readonly scheduleSha256: string; readonly sourceArtifacts: { readonly sidecar: "absent"; readonly receipt: "absent"; }; }
export interface CheckpointStoryboardRetainedTraceMaterializationReceipt {
  readonly schema: typeof C6B7B_RECEIPT_SCHEMA; readonly operation: typeof C6B7B_RECEIPT_OPERATION; readonly status: "passed";
  readonly approval: { readonly storyboard: ReturnType<typeof readCheckpointStoryboard>; readonly plan: unknown; readonly base: C6B7bExactBase; };
  readonly output: { readonly package: C6B7bPackageIdentity; readonly virtualSourceInventory: C6B7bInventory; readonly nonMaterializationInventory: C6B7bInventory; readonly preservedLeaves: { readonly sha256: string; readonly count: number }; readonly createdDirectories: readonly string[]; readonly changed: { readonly paths: readonly [typeof C6B7B_SIDECAR_PATH, typeof C6B7B_RECEIPT_PATH]; readonly count: 2; readonly motionAndManifest: "unchanged" }; readonly sidecar: C6B7bArtifactIdentity; };
  readonly transaction: { readonly cow: "closed-inventory-finalize-after-edit"; readonly installed: true; readonly exclusiveArtifacts: true; readonly workspaceCleanup: "not-attested" };
  readonly renderer: { readonly invoked: false; readonly pixels: false; readonly gpuAbi: "none"; readonly upload: "none" }; readonly fingerprint: string;
}

export function sidecarBytes(plan: unknown): Buffer { const bytes = Buffer.from(`${canonicalJson(plan)}\n`, "utf8"); if (bytes.byteLength > C6B7B_MAX_PLAN_BYTES) throw new PackageEditTransactionError("package_limit_exceeded", "C6B7b exact C6B7a plan exceeds the 512 KiB sidecar ceiling."); return bytes; }
export function sidecarIdentity(plan: unknown): C6B7bArtifactIdentity { const bytes = sidecarBytes(plan); return Object.freeze({ path: C6B7B_SIDECAR_PATH, rawSha256: hashBuffer(bytes), byteLength: bytes.byteLength, canonicalSha256: canonicalJsonSha256(plan) }); }
export async function writeC6B7bSidecar(root: string, plan: unknown): Promise<C6B7bArtifactIdentity> { const identity = sidecarIdentity(plan); try { await writeVerifiedBoundedFile(join(root, C6B7B_SIDECAR_PATH), sidecarBytes(plan), { label: "C6B7b retained-trace sidecar", maxBytes: C6B7B_MAX_PLAN_BYTES, withinRoot: root }); } catch { throw new PackageEditTransactionError("copy_mismatch", "C6B7b sidecar could not be exclusively published."); } return identity; }
export async function readC6B7bSidecar(root: string): Promise<unknown> { const file = await readBoundedStableFile(join(root, C6B7B_SIDECAR_PATH), { label: "C6B7b retained-trace sidecar", maxBytes: C6B7B_MAX_PLAN_BYTES, withinRoot: root, requireSingleLink: true }); let plan: unknown; try { plan = JSON.parse(file.bytes.toString("utf8")); } catch { throw new PackageEditTransactionError("copy_mismatch", "C6B7b sidecar is not JSON."); } const expected = sidecarBytes(plan); if (!file.bytes.equals(expected)) throw new PackageEditTransactionError("copy_mismatch", "C6B7b sidecar bytes are not canonical."); return plan; }
export function createC6B7bReceipt(input: Omit<CheckpointStoryboardRetainedTraceMaterializationReceipt, "schema" | "operation" | "status" | "fingerprint">): CheckpointStoryboardRetainedTraceMaterializationReceipt { const payload = { schema: C6B7B_RECEIPT_SCHEMA, operation: C6B7B_RECEIPT_OPERATION, status: "passed" as const, ...input }; return readC6B7bReceiptValue({ ...payload, fingerprint: canonicalJsonSha256(payload) }); }
export async function writeC6B7bReceipt(root: string, receipt: CheckpointStoryboardRetainedTraceMaterializationReceipt): Promise<void> { const accepted = readC6B7bReceiptValue(receipt), bytes = Buffer.from(`${canonicalJson(accepted)}\n`, "utf8"); if (bytes.byteLength > MAX_RECEIPT_BYTES) throw new PackageEditTransactionError("package_limit_exceeded", "C6B7b receipt exceeds 1 MiB."); try { await writeVerifiedBoundedFile(join(root, C6B7B_RECEIPT_PATH), bytes, { label: "C6B7b retained-trace receipt", maxBytes: MAX_RECEIPT_BYTES, withinRoot: root }); } catch { throw new PackageEditTransactionError("copy_mismatch", "C6B7b receipt could not be exclusively published."); } }
export async function readC6B7bReceipt(root: string): Promise<CheckpointStoryboardRetainedTraceMaterializationReceipt> { const file = await readBoundedStableFile(join(root, C6B7B_RECEIPT_PATH), { label: "C6B7b retained-trace receipt", maxBytes: MAX_RECEIPT_BYTES, withinRoot: root, requireSingleLink: true }); let value: unknown; try { value = JSON.parse(file.bytes.toString("utf8")); } catch { throw new PackageEditTransactionError("copy_mismatch", "C6B7b receipt is not JSON."); } const receipt = readC6B7bReceiptValue(value); if (!file.bytes.equals(Buffer.from(`${canonicalJson(receipt)}\n`, "utf8"))) throw new PackageEditTransactionError("copy_mismatch", "C6B7b receipt bytes are not canonical."); return receipt; }
export function readC6B7bReceiptValue(value: unknown): CheckpointStoryboardRetainedTraceMaterializationReceipt {
  const root = record(value, ["schema", "operation", "status", "approval", "output", "transaction", "renderer", "fingerprint"], "C6B7b receipt"), { fingerprint, ...payload } = root;
  if (root.schema !== C6B7B_RECEIPT_SCHEMA || root.operation !== C6B7B_RECEIPT_OPERATION || root.status !== "passed" || !hash(fingerprint) || canonicalJsonSha256(payload) !== fingerprint) fail("C6B7b receipt identity or fingerprint is invalid.");
  const approval = object(root.approval, "C6B7b receipt approval"), output = object(root.output, "C6B7b receipt output"), transaction = object(root.transaction, "C6B7b receipt transaction"), renderer = object(root.renderer, "C6B7b receipt renderer");
  const storyboard = readCheckpointStoryboard(field(approval, "storyboard", "C6B7b receipt approval")); const plan = field(approval, "plan", "C6B7b receipt approval"), base = readC6B7bExactBase(field(approval, "base", "C6B7b receipt approval"));
  if (!plan || typeof plan !== "object" || Array.isArray(plan) || (plan as { readonly fingerprint?: unknown }).fingerprint !== base.planFingerprint || storyboard.id !== base.storyboardId || storyboard.sha256 !== base.storyboardSha256 || storyboard.revision !== base.storyboardRevision) fail("C6B7b receipt does not bind its sealed C6B7a plan/storyboard.");
  const packageIdentity = readIdentity(field(output, "package", "C6B7b receipt output")), virtualSourceInventory = readInventory(field(output, "virtualSourceInventory", "C6B7b receipt output")), nonMaterializationInventory = readInventory(field(output, "nonMaterializationInventory", "C6B7b receipt output")), sidecar = readArtifact(field(output, "sidecar", "C6B7b receipt output"));
  const createdDirectories = strings(field(output, "createdDirectories", "C6B7b receipt output")); const changed = object(field(output, "changed", "C6B7b receipt output"), "C6B7b changed paths");
  if (!sameKeys(approval, ["storyboard", "plan", "base"]) || !sameKeys(output, ["package", "virtualSourceInventory", "nonMaterializationInventory", "preservedLeaves", "createdDirectories", "changed", "sidecar"]) || !same(base.source.inventory, virtualSourceInventory) || sidecar.path !== C6B7B_SIDECAR_PATH || !validCreatedDirectories(createdDirectories) || !same(changed, { paths: [C6B7B_SIDECAR_PATH, C6B7B_RECEIPT_PATH], count: 2, motionAndManifest: "unchanged" }) || !same(transaction, { cow: "closed-inventory-finalize-after-edit", installed: true, exclusiveArtifacts: true, workspaceCleanup: "not-attested" }) || !same(renderer, { invoked: false, pixels: false, gpuAbi: "none", upload: "none" })) fail("C6B7b receipt has widened artifacts, changes, inventory, transaction, or renderer authority.");
  return freeze({ schema: C6B7B_RECEIPT_SCHEMA, operation: C6B7B_RECEIPT_OPERATION, status: "passed" as const, approval: freeze({ storyboard, plan, base }), output: freeze({ package: packageIdentity, virtualSourceInventory, nonMaterializationInventory, preservedLeaves: readPreserved(field(output, "preservedLeaves", "C6B7b receipt output")), createdDirectories, changed: freeze({ paths: [C6B7B_SIDECAR_PATH, C6B7B_RECEIPT_PATH] as const, count: 2 as const, motionAndManifest: "unchanged" as const }), sidecar }), transaction: freeze({ cow: "closed-inventory-finalize-after-edit" as const, installed: true as const, exclusiveArtifacts: true as const, workspaceCleanup: "not-attested" as const }), renderer: freeze({ invoked: false as const, pixels: false as const, gpuAbi: "none" as const, upload: "none" as const }), fingerprint: fingerprint as string });
}
export function readC6B7bExactBase(value: unknown): C6B7bExactBase { const base = object(value, "C6B7b exact base"), source = readIdentity(field(base, "source", "C6B7b exact base")), artifacts = object(field(base, "sourceArtifacts", "C6B7b exact base"), "C6B7b source artifacts"); if (!sameKeys(base, ["source", "planFingerprint", "profileFingerprint", "storyboardId", "storyboardSha256", "storyboardRevision", "sourceLayerId", "sourceLayerIndex", "staticOpacity", "traceSourceSha256", "tracePlanFingerprint", "scheduleSha256", "sourceArtifacts"]) || ![base.planFingerprint, base.profileFingerprint, base.storyboardSha256, base.traceSourceSha256, base.tracePlanFingerprint, base.scheduleSha256].every(hash) || typeof base.storyboardId !== "string" || typeof base.sourceLayerId !== "string" || base.sourceLayerId.length < 1 || base.sourceLayerIndex !== 0 || typeof base.staticOpacity !== "number" || !Number.isFinite(base.staticOpacity) || base.staticOpacity < 0 || base.staticOpacity > 1 || typeof base.storyboardRevision !== "number" || !Number.isSafeInteger(base.storyboardRevision) || base.storyboardRevision < 1 || !same(artifacts, { sidecar: "absent", receipt: "absent" })) fail("C6B7b exact base is invalid."); return freeze({ source, planFingerprint: base.planFingerprint as string, profileFingerprint: base.profileFingerprint as string, storyboardId: base.storyboardId as string, storyboardSha256: base.storyboardSha256 as string, storyboardRevision: base.storyboardRevision, sourceLayerId: base.sourceLayerId as string, sourceLayerIndex: 0, staticOpacity: base.staticOpacity, traceSourceSha256: base.traceSourceSha256 as string, tracePlanFingerprint: base.tracePlanFingerprint as string, scheduleSha256: base.scheduleSha256 as string, sourceArtifacts: freeze({ sidecar: "absent" as const, receipt: "absent" as const }) }); }
function readIdentity(value: unknown): C6B7bPackageIdentity { const item = object(value, "C6B7b package identity"); if (!sameKeys(item, ["packageId", "manifestRawSha256", "manifestCanonicalSha256", "motionRawSha256", "motionCanonicalSha256", "inventory"]) || typeof item.packageId !== "string" || ![item.manifestRawSha256, item.manifestCanonicalSha256, item.motionRawSha256, item.motionCanonicalSha256].every(hash)) fail("C6B7b package identity is invalid."); return freeze({ packageId: item.packageId as string, manifestRawSha256: item.manifestRawSha256 as string, manifestCanonicalSha256: item.manifestCanonicalSha256 as string, motionRawSha256: item.motionRawSha256 as string, motionCanonicalSha256: item.motionCanonicalSha256 as string, inventory: readInventory(item.inventory, "C6B7b package inventory") }); }
function readInventory(value: unknown, label = "C6B7b inventory"): C6B7bInventory { const item = object(value, label); if (!sameKeys(item, ["sha256", "entryCount", "leafCount"]) || !hash(item.sha256) || typeof item.entryCount !== "number" || !Number.isSafeInteger(item.entryCount) || item.entryCount < 0 || typeof item.leafCount !== "number" || !Number.isSafeInteger(item.leafCount) || item.leafCount < 0) fail("C6B7b inventory is invalid."); return freeze({ sha256: item.sha256, entryCount: item.entryCount, leafCount: item.leafCount }); }
function readArtifact(value: unknown): C6B7bArtifactIdentity { const item = object(value, "C6B7b sidecar identity"); if (!sameKeys(item, ["path", "rawSha256", "byteLength", "canonicalSha256"]) || typeof item.path !== "string" || !hash(item.rawSha256) || !hash(item.canonicalSha256) || typeof item.byteLength !== "number" || !Number.isSafeInteger(item.byteLength) || item.byteLength < 1 || item.byteLength > C6B7B_MAX_PLAN_BYTES) fail("C6B7b sidecar identity is invalid."); return freeze({ path: item.path, rawSha256: item.rawSha256, byteLength: item.byteLength, canonicalSha256: item.canonicalSha256 }); }
function readPreserved(value: unknown): { readonly sha256: string; readonly count: number } { const item = object(value, "C6B7b preserved leaves"); if (!sameKeys(item, ["sha256", "count"]) || !hash(item.sha256) || typeof item.count !== "number" || !Number.isSafeInteger(item.count) || item.count < 0) fail("C6B7b preserved leaves are invalid."); return freeze({ sha256: item.sha256, count: item.count }); }
function record(value: unknown, keys: readonly string[], label: string): Record<string, unknown> { const item = object(value, label); if (!sameKeys(item, keys)) fail(`${label} has unsupported fields.`); return item; }
function object(value: unknown, label: string): Record<string, unknown> { if (!value || typeof value !== "object" || Array.isArray(value) || Object.getPrototypeOf(value) !== Object.prototype) fail(`${label} must be a plain object.`); return value as Record<string, unknown>; }
function field(value: Record<string, unknown>, key: string, label: string): unknown { const descriptor = Object.getOwnPropertyDescriptor(value, key); if (!descriptor || !("value" in descriptor) || !descriptor.enumerable) fail(`${label}.${key} must be an enumerable data field.`); return descriptor.value; }
function strings(value: unknown): readonly string[] { if (!Array.isArray(value) || value.some((item) => typeof item !== "string" || item.length < 1 || item.length > 512)) fail("C6B7b created directories are invalid."); return freeze([...value] as string[]); }
function validCreatedDirectories(value: readonly string[]): boolean { const allowed = ["analysis", "analysis/checkpoint-storyboard", "receipts"]; return value.length <= allowed.length && value.every((item, index) => allowed.includes(item) && (index === 0 || value[index - 1]! < item)); }
function hash(value: unknown): value is string { return typeof value === "string" && HASH.test(value); }
function same(left: unknown, right: unknown): boolean { return canonicalJsonSha256(left) === canonicalJsonSha256(right); }
function sameKeys(value: Record<string, unknown>, keys: readonly string[]): boolean { const actual = Reflect.ownKeys(value); return actual.length === keys.length && actual.every((key) => typeof key === "string" && keys.includes(key) && (() => { const descriptor = Object.getOwnPropertyDescriptor(value, key); return !!descriptor && "value" in descriptor && descriptor.enumerable; })()) && keys.every((key) => Object.hasOwn(value, key)); }
function fail(message: string): never { throw new PackageEditTransactionError("copy_mismatch", message); }
function freeze<T>(value: T): T { if (value && typeof value === "object" && !Object.isFrozen(value)) { for (const child of Object.values(value as object)) freeze(child); Object.freeze(value); } return value; }
