/**
 * The `shellx-motion debug <subcommand>` name map.
 *
 * Role: the terminal-facing short names for the typed debug commands. Kept beside the modular
 * command map in `modular-debug-cli.ts` rather than inline in `main.ts`, because it is a lookup
 * table that grows with every command and has no other logic in it.
 *
 * Primary caller: `debugCommand` in `packages/cli/src/main.ts`.
 */
import type { MotionDebugCommand } from "@shellx-motion/debug-api";
import { MODULAR_DEBUG_COMMANDS } from "./modular-debug-cli";

/**
 * Debug commands with a one-to-one `shellx-motion debug <subcommand>` route.
 *
 * This is exported because the public surface matrix is a contract: adding a Debug/MCP command
 * must explicitly classify its CLI availability instead of letting a broad "CLI parity" claim
 * drift past a missing terminal route.
 */
export const CLI_DIRECT_DEBUG_COMMANDS: Readonly<Record<string, MotionDebugCommand>> = Object.freeze({
    state: "motion.state",
    open: "motion.open",
    select: "motion.select",
    highlight: "motion.highlight",
    "render-final": "motion.render.final",
    "render-cache-plan": "motion.render.cache.plan",
    "preview-panel": "motion.preview.panel",
    "preview-frame": "motion.preview.frame",
    "preview-playhead": "motion.preview.playhead",
    "preview-strip": "motion.preview.strip",
    "export-presets": "motion.export.presets",
    "export-panel": "motion.export.panel",
    "export-plan": "motion.export.plan",
    "receipts-list": "motion.receipts.list",
    "receipts-read": "motion.receipts.read",
    "receipts-panel": "motion.receipts.panel",
    "platform-verification-panel": "motion.platform.verification.panel",
    "assets-panel": "motion.assets.panel",
    "brand-panel": "motion.brand.panel",
    "audio-panel": "motion.audio.panel",
    "audio-master-set": "motion.audio.master.set",
    "audio-crossfade-set": "motion.audio.crossfade.set",
    "audio-envelope-produce": "motion.procedural.audio-envelope.produce",
    "media-panel": "motion.media.panel",
    "actions-find": "motion.actions.find",
    "actions-guide": "motion.actions.guide",
    "actions-plan": "motion.actions.plan",
    "actions-panel": "motion.actions.panel",
    "agent-panel": "motion.agent.panel",
    "agent-health": "motion.agent.health",
    "agent-transcript": "motion.agent.transcript",
    "agent-revision-plan": "motion.agent.revision.plan",
    "prompt-run": "motion.prompt.run",
    "prompt-queue": "motion.prompt.queue",
    "prompt-cancel": "motion.prompt.cancel",
    "prompt-retry": "motion.prompt.retry",
    "storyboard-panel": "motion.storyboard.panel",
    "storyboard-graph": "motion.storyboard.graph",
    "script-compile": "motion.script.compile",
    "tracking-request": "motion.analysis.tracking.request",
    "tracking-inspect": "motion.analysis.tracking.inspect",
    "tracking-apply": "motion.analysis.tracking.apply",
    "tracking-detach": "motion.analysis.tracking.detach",
    "tracking-verify": "motion.analysis.tracking.verify",
    "browser-workflow-capture": "motion.browser.workflow.capture",
    "render-batch": "motion.render.batch",
    "render-cancel": "motion.render.cancel",
    "render-retry": "motion.render.retry",
    "render-status": "motion.render.status",
    "render-queue": "motion.render.queue",
    "canvas-bridge-export": "motion.canvas.bridge_export",
    "connector-panel": "motion.connector.panel",
    "connector-canvas-to-mp4": "motion.connector.canvas_to_mp4",
    "connector-canvas-to-cut": "motion.connector.canvas_to_cut",
    "connector-script-to-cut": "motion.connector.script_to_cut",
    "connector-source-to-cut": "motion.connector.source_to_cut",
    "connector-cut-generate-to-cut": "motion.connector.cut_generate_to_cut",
    "connector-template-to-cut": "motion.connector.template_to_cut",
    "canvas-package": "motion.canvas.package",
    "quality-panel": "motion.quality.panel",
    "quality-check": "motion.quality.check",
    "packages-browse": "motion.packages.browse",
    "package-patch": "motion.package.patch",
    "package-asset-import": "motion.package.asset.import",
    "revision-transaction-plan": "motion.revision.transaction.plan",
    "revision-transaction": "motion.revision.transaction",
    "timeline-inspect": "motion.timeline.inspect",
    "timeline-panel": "motion.timeline.panel",
    "keyframes-panel": "motion.timeline.keyframes.panel",
    "transitions-panel": "motion.timeline.transitions.panel",
    "easing-panel": "motion.timeline.easing.panel",
    "timeline-playhead-set": "motion.timeline.playhead.set",
    "timeline-range-select": "motion.timeline.range.select",
    "timeline-viewport-set": "motion.timeline.viewport.set",
    "duration-policy": "motion.timeline.duration.policy",
    "duration-policy-set": "motion.timeline.duration.policy.set",
    "marker-upsert": "motion.timeline.marker.upsert",
    "marker-delete": "motion.timeline.marker.delete",
    "scene-create": "motion.timeline.scene.create",
    "scene-delete": "motion.timeline.scene.delete",
    "scene-reorder": "motion.timeline.scene.reorder",
    "scene-resize": "motion.timeline.scene.resize",
    "scene-name-set": "motion.timeline.scene.name.set",
    "keyframe-upsert": "motion.timeline.keyframe.upsert",
    "keyframe-delete": "motion.timeline.keyframe.delete",
    "keyframe-range-delete": "motion.timeline.keyframe.range.delete",
    "keyframe-move": "motion.timeline.keyframe.move",
    "keyframe-easing-apply": "motion.timeline.keyframe.easing.apply",
    "keyframe-shift": "motion.timeline.keyframe.shift",
    "keyframe-scale": "motion.timeline.keyframe.scale",
    "keyframe-duplicate": "motion.timeline.keyframe.duplicate",
    "keyframe-distribute": "motion.timeline.keyframe.distribute",
    "keyframe-reverse": "motion.timeline.keyframe.reverse",
    "keyframe-snap": "motion.timeline.keyframe.snap",
    ...MODULAR_DEBUG_COMMANDS,
    "easing-presets": "motion.timeline.easing.presets",
    "animation-presets": "motion.timeline.animation.presets",
    "animation-preset-apply": "motion.timeline.animation.preset.apply",
    "transition-presets": "motion.timeline.transition.presets",
    "transition-preset-apply": "motion.timeline.transition.preset.apply",
    "layer-create": "motion.timeline.layer.create",
    "layer-trim": "motion.timeline.layer.trim",
    "layer-split": "motion.timeline.layer.split",
    "layer-text-set": "motion.timeline.layer.text.set",
    "layer-style-set": "motion.timeline.layer.style.set",
    "layer-transform-set": "motion.timeline.layer.transform.set",
    "layer-effect-set": "motion.timeline.layer.effect.set",
    "layer-rich-set": "motion.timeline.layer.rich.set",
    "behaviors-inspect": "motion.timeline.behaviors.inspect",
    "behaviors-upsert": "motion.timeline.behaviors.upsert",
    "behaviors-remove": "motion.timeline.behaviors.remove",
    "layer-text-runs-inspect": "motion.timeline.layer.text-runs.inspect",
    "layer-text-runs-replace": "motion.timeline.layer.text-runs.replace",
    "layer-text-runs-remove": "motion.timeline.layer.text-runs.remove",
    "group-create": "motion.timeline.group.create",
    "group-child-add": "motion.timeline.group.child.add",
    "group-child-remove": "motion.timeline.group.child.remove",
    "group-child-move": "motion.timeline.group.child.move",
    "group-child-reorder": "motion.timeline.group.child.reorder",
    "group-wrap": "motion.timeline.group.wrap",
    "group-unwrap": "motion.timeline.group.unwrap",
    "group-delete": "motion.timeline.group.delete",
    "group-duplicate": "motion.timeline.group.duplicate",
    "group-trim": "motion.timeline.group.trim",
    "group-root-reorder": "motion.timeline.group.root.reorder",
    "group-split": "motion.timeline.group.split",
    "layout-inspect": "motion.timeline.layout.inspect",
    "layout-compile": "motion.timeline.layout.compile",
    "layout-apply": "motion.timeline.layout.apply",
    "layout-remove": "motion.timeline.layout.remove",
    "adjustment-fixed-inspect": "motion.timeline.adjustment.fixed.inspect",
    "adjustment-fixed-set": "motion.timeline.adjustment.fixed.set",
    "adjustment-fixed-remove": "motion.timeline.adjustment.fixed.remove",
    "gradient-color-keyframes-inspect": "motion.timeline.gradient.color-keyframes.inspect",
    "gradient-color-keyframes-upsert": "motion.timeline.gradient.color-keyframes.upsert",
    "gradient-color-keyframes-delete": "motion.timeline.gradient.color-keyframes.delete",
    "gradient-color-keyframes-move": "motion.timeline.gradient.color-keyframes.move",
    "shape-geometry-keyframes-inspect": "motion.timeline.shape.geometry-keyframes.inspect",
    "shape-geometry-keyframes-upsert": "motion.timeline.shape.geometry-keyframes.upsert",
    "shape-geometry-keyframes-delete": "motion.timeline.shape.geometry-keyframes.delete",
    "shape-geometry-keyframes-move": "motion.timeline.shape.geometry-keyframes.move",
    "points-range-inspect": "motion.timeline.points.range.inspect",
    "points-trajectory-inspect": "motion.timeline.points.trajectory.inspect",
    "points-point-upsert": "motion.timeline.points.point.upsert",
    "points-point-move": "motion.timeline.points.point.move",
    "points-point-delete": "motion.timeline.points.point.delete",
    "points-point-range-delete": "motion.timeline.points.point.range.delete",
    "particles-structural-inspect": "motion.timeline.particles.structural.inspect",
    "particles-field-source-insert": "motion.timeline.particles.field.source.insert",
    "particles-field-source-replace": "motion.timeline.particles.field.source.replace",
    "particles-field-source-move": "motion.timeline.particles.field.source.move",
    "particles-field-source-delete": "motion.timeline.particles.field.source.delete",
    "particles-emitter-origin-insert": "motion.timeline.particles.emitter.origin.insert",
    "particles-emitter-origin-replace": "motion.timeline.particles.emitter.origin.replace",
    "particles-emitter-origin-move": "motion.timeline.particles.emitter.origin.move",
    "particles-emitter-origin-delete": "motion.timeline.particles.emitter.origin.delete",
    "particles-field-collision-axis-update": "motion.timeline.particles.field.collision.axis.update",
    "particles-emitter-trail-add": "motion.timeline.particles.emitter.trail.add",
    "particles-emitter-trail-replace": "motion.timeline.particles.emitter.trail.replace",
    "particles-emitter-trail-remove": "motion.timeline.particles.emitter.trail.remove",
    "particles-emitter-shading-add": "motion.timeline.particles.emitter.shading.add",
    "particles-emitter-shading-replace": "motion.timeline.particles.emitter.shading.replace",
    "particles-emitter-shading-remove": "motion.timeline.particles.emitter.shading.remove",
    "shape-geometry-inspect": "motion.timeline.shape.geometry.inspect",
    "shape-geometry-replace": "motion.timeline.shape.geometry.replace",
    "shape-geometry-point-update": "motion.timeline.shape.geometry.point.update",
    "shape-geometry-point-insert": "motion.timeline.shape.geometry.point.insert",
    "shape-geometry-point-move": "motion.timeline.shape.geometry.point.move",
    "shape-geometry-point-range-delete": "motion.timeline.shape.geometry.point.range.delete",
    "shape-geometry-arc-update": "motion.timeline.shape.geometry.arc.update",
    "shape-geometry-path-replace": "motion.timeline.shape.geometry.path.replace",
    "shape-geometry-legacy-migrate": "motion.timeline.shape.geometry.legacy.migrate",
    "shape-geometry-dash-set": "motion.timeline.shape.geometry.dash.set",
    "shape-geometry-dash-remove": "motion.timeline.shape.geometry.dash.remove",
    "layer-blend-set": "motion.timeline.layer.blend.set",
    "layer-crop-set": "motion.timeline.layer.crop.set",
    "layer-mask-set": "motion.timeline.layer.mask.set",
    "layer-fit-set": "motion.timeline.layer.fit.set",
    "layer-media-set": "motion.timeline.layer.media.set",
    "layer-name-set": "motion.timeline.layer.name.set",
    "layer-visibility-set": "motion.timeline.layer.visibility.set",
    "layer-lock": "motion.timeline.layer.lock",
    "layer-delete": "motion.timeline.layer.delete",
    "layer-duplicate": "motion.timeline.layer.duplicate",
    "layer-reorder": "motion.timeline.layer.reorder",
    "timeline-cleanup": "motion.timeline.cleanup",
    "track-create": "motion.timeline.track.create",
    "track-reorder": "motion.timeline.track.reorder",
    "track-delete": "motion.timeline.track.delete",
    "track-rename": "motion.timeline.track.rename",
    "track-lock": "motion.timeline.track.lock",
    "track-mute": "motion.timeline.track.mute",
    "track-solo": "motion.timeline.track.solo",
    "track-volume": "motion.timeline.track.volume",
    "track-fade": "motion.timeline.track.fade",
    "track-pan": "motion.timeline.track.pan",
    "layer-ducking": "motion.timeline.layer.ducking.set",
    "layer-track-assign": "motion.timeline.layer.track.assign",
    "caption-import": "motion.timeline.caption.import",
    "caption-upsert": "motion.timeline.caption.upsert",
    "transition-upsert": "motion.timeline.transition.upsert",
    "transition-delete": "motion.timeline.transition.delete",
    "template-catalog": "motion.template.catalog",
    "template-plan": "motion.template.plan",
    "template-panel": "motion.template.panel",
    "template-controls": "motion.template.controls",
    "template-apply": "motion.template.apply",
    "template-media-replace": "motion.template.media.replace",
    "capabilities-match": "motion.capabilities.match",
    "capabilities-panel": "motion.capabilities.panel",
    "package-archive": "motion.package.archive",
    "package-extract": "motion.package.extract",
    "review-html-bundle": "motion.review.html.bundle",
    "source-import": "motion.source.import",
    "source-storyboard": "motion.source.to_scripted_video",
    "html-snippet-export": "motion.html.snippet.export",
    "html-snippet-import": "motion.html.snippet.import",
    "otio-export": "motion.otio.export",
    "otio-import": "motion.otio.import",
    "support-bundle": "motion.support.bundle"
});

/** Debug commands reached by a dedicated CLI command rather than `debug <subcommand>`. */
export const CLI_SEMANTIC_DEBUG_EQUIVALENTS = Object.freeze({
  "motion.connector.catalog": "connector catalog",
  "motion.package.create": "package-create",
  "motion.package.validate": "validate",
  "motion.platform.requirements": "doctor",
  "motion.platform.gpu.probe": "doctor --probe-gpu",
  "motion.job.get": "job get",
  "motion.job.list": "job list"
} as const satisfies Partial<Record<MotionDebugCommand, string>>);

/**
 * Named Debug/MCP commands intentionally without a CLI route.
 *
 * Keep this list explicit. It lets a CLI omission be a reviewed product decision rather than an
 * accidental gap hidden by a universal parity claim.
 */
export const CLI_NAMED_DEBUG_NO_ROUTE = Object.freeze([
  "motion.agent.snapshot",
  "motion.connector.submit",
  "motion.job.submit",
  "motion.job.events",
  "motion.job.cancel",
  "motion.job.retry",
  "motion.keying.inspect",
  "motion.keying.apply",
  "motion.keying.remove",
  "motion.roto.upsert",
  "motion.roto.tracking.detach",
  "motion.roto.remove",
  "motion.package.script.author",
  "motion.timeline.checkpoint-storyboard.create",
  "motion.timeline.checkpoint-storyboard.inspect",
  "motion.timeline.checkpoint-storyboard.revise",
  "motion.timeline.checkpoint-storyboard.remove",
  "motion.timeline.checkpoint-storyboard.archive",
  "motion.timeline.checkpoint-storyboard.materialize",
  "motion.timeline.checkpoint-storyboard.preview",
  "motion.timeline.checkpoint-storyboard.detach",
  "motion.timeline.checkpoint-storyboard.behavior.resolve",
  "motion.timeline.checkpoint-storyboard.behavior.detach",
  "motion.timeline.checkpoint-storyboard.relation.resolve",
  "motion.timeline.checkpoint-storyboard.relation.detach",
  "motion.timeline.checkpoint-storyboard.relation-action.resolve",
  "motion.timeline.checkpoint-storyboard.relation-action.detach",
  "motion.timeline.checkpoint-storyboard.lifecycle.resolve",
  "motion.timeline.checkpoint-storyboard.lifecycle.detach",
  "motion.timeline.checkpoint-storyboard.geometry-morph.resolve",
  "motion.timeline.checkpoint-storyboard.geometry-morph.detach",
  "motion.timeline.checkpoint-storyboard.retained-trace.resolve",
  "motion.timeline.checkpoint-storyboard.retained-trace.detach",
  "motion.timeline.checkpoint-storyboard.retained-trace.preview",
  "motion.timeline.checkpoint-storyboard.retained-trace.review.bind",
  "motion.timeline.checkpoint-storyboard.creative-review.bind",
  "motion.timeline.checkpoint-storyboard.preview-quality.review",
  "motion.timeline.relations.inspect",
  "motion.timeline.relations.upsert",
  "motion.timeline.relations.enabled.set",
  "motion.timeline.relations.remove",
  "motion.timeline.relations.detach",
  "motion.timeline.relations.bake",
  "motion.timeline.relation-actions.inspect",
  "motion.timeline.relation-actions.upsert",
  "motion.timeline.relation-actions.remove",
  "motion.timeline.relation-actions.apply",
  "motion.timeline.scene3d-animation.inspect",
  "motion.timeline.scene3d-animation.track.upsert",
  "motion.timeline.scene3d-animation.track.remove",
  "motion.timeline.scene3d-animation.keyframe.upsert",
  "motion.timeline.scene3d-animation.keyframe.delete",
  "motion.timeline.scene3d-animation.keyframe.move",
  "motion.timeline.layout-gap-animation.inspect",
  "motion.timeline.layout-gap-animation.track.upsert",
  "motion.timeline.layout-gap-animation.track.remove",
  "motion.timeline.layout-gap-animation.keyframe.upsert",
  "motion.timeline.layout-gap-animation.keyframe.delete",
  "motion.timeline.layout-gap-animation.keyframe.move",
] as const satisfies readonly MotionDebugCommand[]);

export function debugCommandName(subcommand: string | undefined): MotionDebugCommand | null {
  return subcommand ? CLI_DIRECT_DEBUG_COMMANDS[subcommand] ?? null : null;
}
