/**
 * The `shellx-motion debug <subcommand>` name map.
 *
 * Role: the terminal-facing short names for the typed debug commands. Kept beside the modular
 * command map in `modular-debug-cli.ts` rather than inline in `main.ts`, because it is a lookup
 * table that grows with every command and has no other logic in it.
 *
 * Primary caller: `debugCommand` in `packages/cli/src/main.ts`.
 */
import type { MotionDebugCommand } from "@shellx-motion/debug-api";
import { MODULAR_DEBUG_COMMANDS } from "./modular-debug-cli";

export function debugCommandName(subcommand: string | undefined): MotionDebugCommand | null {
  const names: Record<string, MotionDebugCommand> = {
    state: "motion.state",
    open: "motion.open",
    select: "motion.select",
    highlight: "motion.highlight",
    "render-final": "motion.render.final",
    "preview-panel": "motion.preview.panel",
    "preview-frame": "motion.preview.frame",
    "preview-playhead": "motion.preview.playhead",
    "preview-strip": "motion.preview.strip",
    "export-presets": "motion.export.presets",
    "export-panel": "motion.export.panel",
    "export-plan": "motion.export.plan",
    "receipts-list": "motion.receipts.list",
    "receipts-read": "motion.receipts.read",
    "receipts-panel": "motion.receipts.panel",
    "platform-verification-panel": "motion.platform.verification.panel",
    "assets-panel": "motion.assets.panel",
    "brand-panel": "motion.brand.panel",
    "audio-panel": "motion.audio.panel",
    "media-panel": "motion.media.panel",
    "actions-find": "motion.actions.find",
    "actions-guide": "motion.actions.guide",
    "actions-plan": "motion.actions.plan",
    "actions-panel": "motion.actions.panel",
    "agent-panel": "motion.agent.panel",
    "agent-health": "motion.agent.health",
    "agent-transcript": "motion.agent.transcript",
    "agent-revision-plan": "motion.agent.revision.plan",
    "prompt-run": "motion.prompt.run",
    "prompt-queue": "motion.prompt.queue",
    "prompt-cancel": "motion.prompt.cancel",
    "prompt-retry": "motion.prompt.retry",
    "storyboard-panel": "motion.storyboard.panel",
    "storyboard-graph": "motion.storyboard.graph",
    "script-compile": "motion.script.compile",
    "tracking-request": "motion.analysis.tracking.request",
    "tracking-inspect": "motion.analysis.tracking.inspect",
    "tracking-apply": "motion.analysis.tracking.apply",
    "tracking-detach": "motion.analysis.tracking.detach",
    "tracking-verify": "motion.analysis.tracking.verify",
    "browser-workflow-capture": "motion.browser.workflow.capture",
    "render-batch": "motion.render.batch",
    "render-cancel": "motion.render.cancel",
    "render-retry": "motion.render.retry",
    "render-status": "motion.render.status",
    "render-queue": "motion.render.queue",
    "canvas-bridge-export": "motion.canvas.bridge_export",
    "connector-panel": "motion.connector.panel",
    "connector-canvas-to-mp4": "motion.connector.canvas_to_mp4",
    "connector-canvas-to-cut": "motion.connector.canvas_to_cut",
    "connector-script-to-cut": "motion.connector.script_to_cut",
    "connector-source-to-cut": "motion.connector.source_to_cut",
    "connector-cut-generate-to-cut": "motion.connector.cut_generate_to_cut",
    "connector-template-to-cut": "motion.connector.template_to_cut",
    "canvas-package": "motion.canvas.package",
    "quality-panel": "motion.quality.panel",
    "quality-check": "motion.quality.check",
    "packages-browse": "motion.packages.browse",
    "package-patch": "motion.package.patch",
    "timeline-inspect": "motion.timeline.inspect",
    "timeline-panel": "motion.timeline.panel",
    "keyframes-panel": "motion.timeline.keyframes.panel",
    "transitions-panel": "motion.timeline.transitions.panel",
    "easing-panel": "motion.timeline.easing.panel",
    "timeline-playhead-set": "motion.timeline.playhead.set",
    "timeline-range-select": "motion.timeline.range.select",
    "timeline-viewport-set": "motion.timeline.viewport.set",
    "duration-policy": "motion.timeline.duration.policy",
    "duration-policy-set": "motion.timeline.duration.policy.set",
    "marker-upsert": "motion.timeline.marker.upsert",
    "marker-delete": "motion.timeline.marker.delete",
    "scene-create": "motion.timeline.scene.create",
    "scene-delete": "motion.timeline.scene.delete",
    "scene-reorder": "motion.timeline.scene.reorder",
    "scene-resize": "motion.timeline.scene.resize",
    "scene-name-set": "motion.timeline.scene.name.set",
    "keyframe-upsert": "motion.timeline.keyframe.upsert",
    "keyframe-delete": "motion.timeline.keyframe.delete",
    "keyframe-range-delete": "motion.timeline.keyframe.range.delete",
    "keyframe-move": "motion.timeline.keyframe.move",
    "keyframe-easing-apply": "motion.timeline.keyframe.easing.apply",
    "keyframe-shift": "motion.timeline.keyframe.shift",
    "keyframe-scale": "motion.timeline.keyframe.scale",
    "keyframe-duplicate": "motion.timeline.keyframe.duplicate",
    "keyframe-distribute": "motion.timeline.keyframe.distribute",
    "keyframe-reverse": "motion.timeline.keyframe.reverse",
    "keyframe-snap": "motion.timeline.keyframe.snap",
    ...MODULAR_DEBUG_COMMANDS,
    "easing-presets": "motion.timeline.easing.presets",
    "animation-presets": "motion.timeline.animation.presets",
    "animation-preset-apply": "motion.timeline.animation.preset.apply",
    "layer-create": "motion.timeline.layer.create",
    "layer-trim": "motion.timeline.layer.trim",
    "layer-split": "motion.timeline.layer.split",
    "layer-text-set": "motion.timeline.layer.text.set",
    "layer-style-set": "motion.timeline.layer.style.set",
    "layer-transform-set": "motion.timeline.layer.transform.set",
    "layer-effect-set": "motion.timeline.layer.effect.set",
    "layer-rich-set": "motion.timeline.layer.rich.set",
    "layer-blend-set": "motion.timeline.layer.blend.set",
    "layer-crop-set": "motion.timeline.layer.crop.set",
    "layer-mask-set": "motion.timeline.layer.mask.set",
    "layer-fit-set": "motion.timeline.layer.fit.set",
    "layer-media-set": "motion.timeline.layer.media.set",
    "layer-name-set": "motion.timeline.layer.name.set",
    "layer-visibility-set": "motion.timeline.layer.visibility.set",
    "layer-lock": "motion.timeline.layer.lock",
    "layer-delete": "motion.timeline.layer.delete",
    "layer-duplicate": "motion.timeline.layer.duplicate",
    "layer-reorder": "motion.timeline.layer.reorder",
    "timeline-cleanup": "motion.timeline.cleanup",
    "track-create": "motion.timeline.track.create",
    "track-reorder": "motion.timeline.track.reorder",
    "track-delete": "motion.timeline.track.delete",
    "track-rename": "motion.timeline.track.rename",
    "track-lock": "motion.timeline.track.lock",
    "track-mute": "motion.timeline.track.mute",
    "track-solo": "motion.timeline.track.solo",
    "track-volume": "motion.timeline.track.volume",
    "track-fade": "motion.timeline.track.fade",
    "track-pan": "motion.timeline.track.pan",
    "layer-ducking": "motion.timeline.layer.ducking.set",
    "layer-track-assign": "motion.timeline.layer.track.assign",
    "caption-import": "motion.timeline.caption.import",
    "caption-upsert": "motion.timeline.caption.upsert",
    "transition-upsert": "motion.timeline.transition.upsert",
    "transition-delete": "motion.timeline.transition.delete",
    "template-catalog": "motion.template.catalog",
    "template-plan": "motion.template.plan",
    "template-panel": "motion.template.panel",
    "template-controls": "motion.template.controls",
    "template-apply": "motion.template.apply",
    "template-media-replace": "motion.template.media.replace",
    "capabilities-match": "motion.capabilities.match",
    "capabilities-panel": "motion.capabilities.panel",
    "package-archive": "motion.package.archive",
    "package-extract": "motion.package.extract",
    "review-html-bundle": "motion.review.html.bundle",
    "source-import": "motion.source.import",
    "source-storyboard": "motion.source.to_scripted_video",
    "html-snippet-export": "motion.html.snippet.export",
    "html-snippet-import": "motion.html.snippet.import",
    "otio-export": "motion.otio.export",
    "otio-import": "motion.otio.import",
    "support-bundle": "motion.support.bundle"
  };
  return subcommand ? names[subcommand] ?? null : null;
}
