#!/usr/bin/env node
/**
 * Local verification for the SBOM contract. It proves the generated bytes are
 * reproducible and that the inventory stays lockfile/workspace-only, without an
 * install, network access, lifecycle hook, or checked-in generated artifact.
 */
import { mkdtempSync, readFileSync, rmSync } from "node:fs";
import { join, resolve } from "node:path";
import { tmpdir } from "node:os";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const ROOT = resolve(fileURLToPath(new URL("..", import.meta.url)));
const GENERATOR = join(ROOT, "scripts", "generate-sbom.mjs");

function compareCodeUnits(left, right) {
  return left < right ? -1 : left > right ? 1 : 0;
}

function assert(condition, message) {
  if (!condition) throw new Error(`SBOM gate failed: ${message}`);
}

function generate(out, options = {}) {
  const separator = options.pnpmSeparator ? ["--"] : [];
  const result = spawnSync(process.execPath, [GENERATOR, ...separator, "--out", out], {
    cwd: ROOT,
    encoding: "utf8"
  });
  assert(result.status === 0, `generator exited ${result.status}: ${result.stderr.trim()}`);
  return readFileSync(out, "utf8");
}

const temporaryRoot = mkdtempSync(join(tmpdir(), "shellx-motion-sbom-"));
try {
  const first = generate(join(temporaryRoot, "first.cdx.json"));
  const second = generate(join(temporaryRoot, "second.cdx.json"));
  const pnpmSeparated = generate(join(temporaryRoot, "pnpm-separated.cdx.json"), { pnpmSeparator: true });
  assert(first === second, "identical source inputs must produce byte-for-byte identical SBOM files");
  assert(first === pnpmSeparated, "pnpm's leading argument separator must preserve the generated SBOM bytes");

  const bom = JSON.parse(first);
  const serialized = JSON.stringify(bom);
  assert(bom.$schema === "https://cyclonedx.org/schema/bom-1.6.schema.json", "must declare the CycloneDX 1.6 JSON schema");
  assert(bom.bomFormat === "CycloneDX" && bom.specVersion === "1.6" && bom.version === 1, "must use CycloneDX 1.6 JSON BOM version 1");
  assert(bom.serialNumber === undefined && bom.metadata.timestamp === undefined, "must omit non-deterministic serial and timestamp fields");
  assert(bom.metadata.component.type === "application" && bom.metadata.component.name === "shellx-motion", "must identify the product root");
  assert(Array.isArray(bom.components) && bom.components.length > 0, "must inventory resolved components");
  assert(!serialized.includes(ROOT) && !serialized.includes("/home/") && !serialized.includes("node_modules"), "must not expose host paths or scan installed packages");

  const refs = bom.components.map((entry) => entry["bom-ref"]);
  assert(new Set(refs).size === refs.length, "component BOM references must be unique");
  assert(refs.every((ref, index) => index === 0 || compareCodeUnits(refs[index - 1], ref) <= 0), "components must have stable ordering");
  assert(bom.components.every((entry) => entry.type === "library" && entry.purl === entry["bom-ref"]), "components must be package libraries with stable PURLs");

  const lockfileComponents = bom.components.filter((entry) => entry.properties.some((property) => property.value === "pnpm-lock.yaml"));
  assert(lockfileComponents.length > 0, "must include resolved pnpm-lock.yaml packages");
  assert(lockfileComponents.every((entry) => entry.hashes?.length === 1 && entry.hashes[0].alg.startsWith("SHA-")), "resolved packages must retain their SRI-derived hash");

  const generatorSource = readFileSync(GENERATOR, "utf8");
  const imports = [...generatorSource.matchAll(/from "([^"]+)"/g)].map((match) => match[1]);
  assert(!generatorSource.includes("child_process") && imports.every((specifier) => specifier.startsWith("node:")), "generator must remain a built-in-only, no-install surface");
  console.log(`PASS SBOM gate: ${bom.components.length} deterministic lockfile/workspace components, no host paths or runtime-binary claims`);
} finally {
  rmSync(temporaryRoot, { recursive: true, force: true });
}
