import { createHash } from "node:crypto";
import { mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { canonicalJson, canonicalJsonSha256 } from "@shellx-motion/core";
import { GPU_PAGE_SCENE3D_GLTF_PBR_HDR10_CATALOG, GPU_PAGE_SCENE3D_GLTF_PBR_HDR10_PIPELINE_IDENTITY } from "@shellx-motion/renderer-browser/internal/scene3d-gltf-pbr-hdr10-streaming";
import { describe, expect, it } from "vitest";
import { HDR10_PQ_CONVERSION_CONTRACT } from "./hdr10-pq-conversion-contract.js";
import { HDR10_PQ_C1_FFMPEG_ARGS } from "./hdr10-pq-ffmpeg-command.js";
import { HDR10_PQ_DIRECT_FINAL_MAX_FFPROBE_BYTES, HDR10_PQ_DIRECT_FINAL_MAX_OUTPUT_BYTES, HDR10_PQ_DIRECT_FINAL_MAX_PROCESS_TREE_RSS_BYTES, HDR10_PQ_DIRECT_FINAL_SCHEMA, HDR10_PQ_DIRECT_FINAL_TIMEOUT_MS, createHdr10PqDirectFinalReceipt, verifyHdr10PqDirectFinalReceiptStructure } from "./hdr10-pq-direct-final-contract.js";
import { inspectHdr10PqPublishedDirectFinalTrustedHostConsistencyForTest } from "./hdr10-pq-direct-final-verify.js";
import { HDR10_PQ_FFPROBE_QUERY, verifyHdr10PqFfprobeObservation } from "./hdr10-pq-ffprobe.js";

const HASH = "a".repeat(64), PACKAGE_ID = "pkg_hdr10";
describe("HDR10 published receipt cross-binding", () => {
  it("accepts only the current authenticated route, pinned output, and re-probed fixed contract", async () => {
    await fixture(async (root) => { const output = Buffer.from("mp4"), receipt = record(output), starts = { value: 0 }; await writeBundle(root, output, receipt); const result = await inspectHdr10PqPublishedDirectFinalTrustedHostConsistencyForTest(pkg(), root, job(), services(starts)); expect(result).toMatchObject({ ok: true, authority: "trusted-host-receipt-not-cryptographically-authenticated", receipt: { packageId: PACKAGE_ID } }); expect(starts.value).toBe(1); });
  });

  it("refuses self-consistent forged route, cross-package receipt, and output replay before probe", async () => {
    await fixture(async (root) => { const output = Buffer.from("mp4"), starts = { value: 0 }; const forgedRoute = record(output, { route: { fingerprint: "b".repeat(64) } }); expect(verifyHdr10PqDirectFinalReceiptStructure(forgedRoute)).toEqual(forgedRoute); await writeBundle(root, output, forgedRoute); expect((await inspectHdr10PqPublishedDirectFinalTrustedHostConsistencyForTest(pkg(), root, job(), services(starts))).ok).toBe(false); const otherPackage = record(output, { packageId: "pkg_other" }); await writeBundle(root, output, otherPackage); expect((await inspectHdr10PqPublishedDirectFinalTrustedHostConsistencyForTest(pkg(), root, job(), services(starts))).ok).toBe(false); await writeBundle(root, Buffer.from("replay"), record(output)); expect((await inspectHdr10PqPublishedDirectFinalTrustedHostConsistencyForTest(pkg(), root, job(), services(starts))).ok).toBe(false); expect(starts.value).toBe(0); });
  });

  it("labels arbitrary self-consistent historical hashes as non-authoritative metadata", async () => {
    await fixture(async (root) => { const output = Buffer.from("mp4"), receipt = record(output, { producerEvidenceSha256: "b".repeat(64) }), starts = { value: 0 }; expect(verifyHdr10PqDirectFinalReceiptStructure(receipt)).toEqual(receipt); await writeBundle(root, output, receipt); const result = await inspectHdr10PqPublishedDirectFinalTrustedHostConsistencyForTest(pkg(), root, job(), services(starts)); expect(result).toMatchObject({ ok: true, authority: "trusted-host-receipt-not-cryptographically-authenticated" }); expect(result).not.toHaveProperty("authorized"); });
  });

  it("refuses an extra published child after pinning the two expected regular files", async () => {
    await fixture(async (root) => { const output = Buffer.from("mp4"), starts = { value: 0 }; await writeBundle(root, output, record(output)); await writeFile(join(root, "unexpected"), "sidecar"); expect((await inspectHdr10PqPublishedDirectFinalTrustedHostConsistencyForTest(pkg(), root, job(), services(starts))).ok).toBe(false); expect(starts.value).toBe(1); });
  });

  it("refuses invalid, over-ceiling, or cancelled jobs before route and probe work", async () => {
    await fixture(async (root) => { const output = Buffer.from("mp4"), counters = { value: 0, routes: 0 }; await writeBundle(root, output, record(output)); expect((await inspectHdr10PqPublishedDirectFinalTrustedHostConsistencyForTest(pkg(), root, { ...job(), maxProcessTreeRssBytes: 2 * 1024 * 1024 * 1024 + 1 }, services(counters))).ok).toBe(false); expect((await inspectHdr10PqPublishedDirectFinalTrustedHostConsistencyForTest(pkg(), root, { ...job(), scratchRoot: "" }, services(counters))).ok).toBe(false); const cancelled = new AbortController(); cancelled.abort(new Error("cancelled")); expect((await inspectHdr10PqPublishedDirectFinalTrustedHostConsistencyForTest(pkg(), root, job(cancelled.signal), services(counters))).ok).toBe(false); expect(counters).toEqual({ value: 0, routes: 0 }); });
  });
});

function record(output: Buffer, change: { packageId?: string; route?: { fingerprint: string }; producerEvidenceSha256?: string } = {}) { const observation = verifyHdr10PqFfprobeObservation(probe())!; return createHdr10PqDirectFinalReceipt({ packageId: change.packageId ?? PACKAGE_ID, route: { fingerprint: change.route?.fingerprint ?? HASH, sourceInputHashes: hashes(), sceneStateSha256: HASH, staticFingerprint: HASH, sdrStaticFingerprint: HASH, frameFingerprint: HASH }, browser: { catalogSha256: GPU_PAGE_SCENE3D_GLTF_PBR_HDR10_CATALOG.sha256, pipelineSha256: GPU_PAGE_SCENE3D_GLTF_PBR_HDR10_PIPELINE_IDENTITY.pipelineImplementationSha256, producerEvidenceSha256: change.producerEvidenceSha256 ?? HASH, rawFrameSequenceSha256: HASH, framesRendered: 90 }, conversion: { contractSha256: canonicalJsonSha256(HDR10_PQ_CONVERSION_CONTRACT), sequenceFingerprint: HASH, generatedReceiptSha256: HASH, generatedFrameSequenceSha256: HASH, frameCount: 90, generatedYuvFrameByteLength: 2_764_800 }, command: { c1InertPlanSha256: HASH, c2TokenizedCommandSha256: canonicalJsonSha256({ schema: HDR10_PQ_DIRECT_FINAL_SCHEMA, c1Args: HDR10_PQ_C1_FFMPEG_ARGS, maxOutputBytes: HDR10_PQ_DIRECT_FINAL_MAX_OUTPUT_BYTES }), softwareEncoder: "libx265", hardware: "refused" }, probe: { querySha256: canonicalJsonSha256(HDR10_PQ_FFPROBE_QUERY), observedJsonSha256: canonicalJsonSha256(probe()), observedStreamSha256: observation.streamSha256, validationFingerprint: observation.fingerprint }, output: { file: "video.mp4", sha256: createHash("sha256").update(output).digest("hex"), byteLength: output.byteLength }, limits: { maxOutputBytes: HDR10_PQ_DIRECT_FINAL_MAX_OUTPUT_BYTES, timeoutMs: HDR10_PQ_DIRECT_FINAL_TIMEOUT_MS, maxFfprobeBytes: HDR10_PQ_DIRECT_FINAL_MAX_FFPROBE_BYTES, maximumProcessTreeRssBytes: HDR10_PQ_DIRECT_FINAL_MAX_PROCESS_TREE_RSS_BYTES, governedProcessTreeRssBytes: 64 * 1024 * 1024 }, cleanup: { browserTerminal: true, encoderExitCode: 0, ffprobeExitCode: 0 } }); }
function hashes() { return Object.fromEntries(Array.from({ length: 9 }, (_, index) => [`source-${index}`, HASH])); }
function pkg() { return { root: "/not-opened", manifest: { id: PACKAGE_ID }, motion: {} } as never; }
function job(signal = new AbortController().signal) { return { admission: "pre-acquired" as const, signal, scratchRoot: "/tmp/hdr10-verify", maxProcessTreeRssBytes: 64 * 1024 * 1024, watchProcess: () => {}, reportProcessContainment: () => {} }; }
function services(starts: { value: number; routes?: number }) { return { resolveRoute: async () => { if (starts.routes !== undefined) starts.routes += 1; return { kind: "present", hdrRoute: { packageId: PACKAGE_ID, fingerprint: HASH, inputHashes: hashes(), staticPlan: { inheritedSdr: { sceneStateSha256: HASH }, fingerprint: HASH } }, sdrRoute: { renderPlan: { staticPlan: { fingerprint: HASH }, framePlan: { fingerprint: HASH } } } } as never; }, startProcess: async () => { starts.value += 1; return { closed: Promise.resolve({ exitCode: 0, stdout: "", stderr: "" }), write: async () => ({ backpressured: false, bufferedInputBytes: 0, inputHighWaterMarkBytes: 1 }), end: async () => ({ exitCode: 0, stdout: JSON.stringify(probe()), stderr: "" }), abort: async () => ({ exitCode: 1, stdout: "", stderr: "" }) }; } }; }
async function writeBundle(root: string, output: Buffer, receipt: unknown) { await writeFile(join(root, "video.mp4"), output); await writeFile(join(root, "receipt.json"), Buffer.from(canonicalJson(receipt), "utf8")); }
async function fixture(run: (root: string) => Promise<void>) { const root = await mkdtemp(join(tmpdir(), "shellx-motion-hdr10-verify-")); try { await run(root); } finally { await rm(root, { recursive: true, force: true }); } }
function probe() { return { streams: [{ codec_name: "hevc", profile: "Main 10", codec_tag_string: "hvc1", pix_fmt: "yuv420p10le", width: 1280, height: 720, color_range: "tv", color_space: "bt2020nc", color_transfer: "smpte2084", color_primaries: "bt2020", chroma_location: "topleft", r_frame_rate: "30/1", avg_frame_rate: "30/1", nb_read_frames: "90", nb_frames: "90", side_data_list: [{ side_data_type: "Mastering display metadata", red_x: "35400/50000", red_y: "14600/50000", green_x: "8500/50000", green_y: "39850/50000", blue_x: "6550/50000", blue_y: "2300/50000", white_point_x: "15635/50000", white_point_y: "16450/50000", min_luminance: "1/10000", max_luminance: "10000000/10000" }] }], format: { format_name: "mov,mp4,m4a,3gp,3g2,mj2" } }; }
