/** C6C B5a private resolver. Debug/MCP owns host authority and the signed durable link. */
import { lstat } from "node:fs/promises";
import { canonicalJson, isPublicationCommitUncertain } from "@shellx-motion/core";
import { materializeCheckpointStoryboardLifecycle, prepareCheckpointStoryboardLifecycleMaterialization, reopenCheckpointStoryboardLifecycleMaterializationOutput } from "./checkpoint-storyboard-lifecycle-materialize-private/checkpoint-storyboard-lifecycle-materialize-private.js";
import { readC6B5bReceipt, type C6B5bExactBase } from "./checkpoint-storyboard-lifecycle-materialize-private/checkpoint-storyboard-lifecycle-materialize-receipt-private.js";
import { assertCheckpointStoryboardLifecycleResolutionAuthorityStore, checkpointStoryboardLifecycleResolutionOutputHandle, checkedCheckpointStoryboardLifecycleResolutionAuthority, withCheckpointStoryboardLifecycleResolutionAuthority, withCheckpointStoryboardLifecycleResolutionOutputAuthority, type CheckpointStoryboardLifecycleResolutionAuthority } from "./checkpoint-storyboard-lifecycle-resolution-authority.js";
import { createLifecycleAbandon, createLifecycleBinding, createLifecycleCowStart, createLifecycleDetach, createLifecycleIntent, publishLifecycleAbandon, publishLifecycleBinding, publishLifecycleCowStart, publishLifecycleDetach, publishLifecycleIntent, publishLifecycleStateHead, readLifecycleBinding, readLifecycleCowStart, readLifecycleIntent, readLifecycleResolutionState, lifecycleStateHead, type LifecycleBinding, type LifecycleIntent, type LifecyclePlanIdentity } from "./checkpoint-storyboard-lifecycle-resolution-journal.js";
import { assertNoLegacyMaterializationEvidence } from "./checkpoint-storyboard-materialization-bindings.js";
import { assertNoBehaviorResolutionEvidence } from "./checkpoint-storyboard-behavior-resolution-journal.js";
import { assertNoRelationResolutionEvidence } from "./checkpoint-storyboard-relation-resolution-journal.js";
import { assertNoRelationActionResolutionEvidence } from "./checkpoint-storyboard-relation-action-resolution-journal.js";
import { assertNoGeometryMorphResolutionEvidence } from "./checkpoint-storyboard-geometry-morph-resolution-journal.js";
import { assertNoRetainedTraceResolutionEvidence } from "./checkpoint-storyboard-retained-trace-resolution-journal.js";
import { checkedAuthority, withLineageLock } from "./checkpoint-storyboard-record-store-authority.js";
import { readImmutableRecordRoot, readStoredRecordUnlocked } from "./checkpoint-storyboard-record-store-state.js";
import { CheckpointStoryboardRecordStoreError, sameIdentity, storeError, type CheckpointStoryboardRecordIdentity } from "./checkpoint-storyboard-record-store-types.js";

type FaultPhase = "while-lineage-lock-held" | "after-intent-before-state-head" | "after-intent" | "after-cow-start-before-state-head" | "after-cow-start" | "before-c6b5b" | "after-c6b5b-commit" | "after-binding" | "after-bound-state-head-rename" | "after-detach" | "after-detached-state-head-rename" | "after-abandon";
type FaultHooks = Partial<Record<FaultPhase, () => void | Promise<void>>>;
const hooks = new WeakMap<CheckpointStoryboardLifecycleResolutionAuthority, FaultHooks>();
/** Test-only seam; it is intentionally absent from command registry and public exports. */
export function setCheckpointStoryboardLifecycleResolutionFaultHooksForTest(authority: CheckpointStoryboardLifecycleResolutionAuthority, value: FaultHooks | undefined): void { checkedCheckpointStoryboardLifecycleResolutionAuthority(authority); if (value) hooks.set(authority, Object.freeze({ ...value })); else hooks.delete(authority); }
async function fault(authority: CheckpointStoryboardLifecycleResolutionAuthority, phase: FaultPhase): Promise<void> { await hooks.get(authority)?.[phase]?.(); }

export interface CheckpointStoryboardLifecycleResolutionResult { readonly identity: CheckpointStoryboardRecordIdentity; readonly binding: { readonly state: "bound" | "detached"; readonly active: 0 | 1; readonly bindingId: string; readonly outputHandle: string; readonly receiptFingerprint: string }; readonly renderer: { readonly invoked: false; readonly pixels: false }; readonly replayed: boolean; }

export async function resolveCheckpointStoryboardLifecycleStoredRecord(authority: CheckpointStoryboardLifecycleResolutionAuthority, identity: CheckpointStoryboardRecordIdentity): Promise<CheckpointStoryboardLifecycleResolutionResult> {
  try { return await withCheckpointStoryboardLifecycleResolutionOutputAuthority(authority, async (host) => {
    const store = checkedAuthority(host.store), root = await readImmutableRecordRoot(store, identity);
    return await withLineageLock(store, root.id, async () => {
      const record = await readStoredRecordUnlocked(store, identity); assertB5Record(record); assertCheckpointStoryboardLifecycleResolutionAuthorityStore(authority, host.store); await assertForeignPartitionEvidenceAbsent(store, identity);
      const outputHandle = checkpointStoryboardLifecycleResolutionOutputHandle(authority, identity); const state = await readLifecycleResolutionState(store, identity, root, { requireHead: true, allowForwardRecovery: true }); await fault(authority, "while-lineage-lock-held");
      if (state.state === "abandoned") throw storeError("materialization_binding_conflict", "Checkpoint storyboard lifecycle resolution was terminally abandoned after a proved no-install outcome.");
      if (state.state === "detached") throw storeError("materialization_detached", "Checkpoint storyboard lifecycle resolution has terminally detached its link and cannot resolve again.");
      if (state.state === "bound") return await replayBound(store, host, identity, root, state.bindingId!, outputHandle);
      const prior = await readLifecycleIntent(store, identity);
      if (prior) { const recovered = await recognizeInstalledOutput(host, record.identity, prior.expectedBase, prior.plan); if (recovered) return await publishAndReopen(store, host, authority, identity, root, prior, recovered, outputHandle, true); if (await outputExists(host.outputPackageRoot) || await readLifecycleCowStart(store, identity)) throw storeError("materialization_binding_uncertain", "Checkpoint storyboard lifecycle resolution retains an occupied or COW-uncertain output for exact recovery and will not repeat COW."); }
      else if (await outputExists(host.outputPackageRoot)) throw storeError("materialization_binding_uncertain", "Checkpoint storyboard lifecycle output is occupied without a durable intent and was retained without replacement.");
      return await withCheckpointStoryboardLifecycleResolutionAuthority(authority, async (sourceHost) => {
        const c6bHost = { sourcePackageRoot: sourceHost.sourcePackageRoot, outputPackageRoot: sourceHost.outputPackageRoot, packageWorkspaceRoot: sourceHost.packageWorkspaceRoot, packageWorkspaceAuthority: sourceHost.packageWorkspaceAuthority };
        // B5b canonicalizes source and absent output, including intermediate aliases, before
        // it mints approval or B5a publishes a durable output intent.
        const prepared = await prepareCheckpointStoryboardLifecycleMaterialization(c6bHost, record.storyboard), plan = planIdentity(prepared), intent = createLifecycleIntent({ identity, root, plan, expectedBase: prepared.expected, outputHandle });
        if (prior && canonicalJson(prior) !== canonicalJson(intent)) throw storeError("materialization_binding_conflict", "Checkpoint storyboard lifecycle intent conflicts with exact host-selected C6B5 facts.");
        if (!prior) { await publishLifecycleIntent(store, intent); await fault(authority, "after-intent-before-state-head"); await publishLifecycleStateHead(store, lifecycleStateHead(identity, root, "preparing", 0, { intent: ref(intent) })); await fault(authority, "after-intent"); }
        if (await outputExists(sourceHost.outputPackageRoot)) throw storeError("materialization_binding_uncertain", "Checkpoint storyboard lifecycle output appeared after intent publication and was retained without replacement.");
        const start = createLifecycleCowStart({ identity, root, intent: ref(intent) }); await publishLifecycleCowStart(store, start); await fault(authority, "after-cow-start-before-state-head"); await publishLifecycleStateHead(store, lifecycleStateHead(identity, root, "preparing", 0, { intent: ref(intent), cowStart: ref(start) })); await fault(authority, "after-cow-start");
        try { await fault(authority, "before-c6b5b"); await materializeCheckpointStoryboardLifecycle(c6bHost, prepared.approval, { schema: "shellx-motion/private-checkpoint-storyboard-lifecycle-materialization-request@1", expected: prepared.expected }); }
        catch (error) { const recovered = await recognizeInstalledOutput(sourceHost, record.identity, prepared.expected, plan); if (recovered) return await publishAndReopen(store, sourceHost, authority, identity, root, intent, recovered, outputHandle, true); if (isPublicationCommitUncertain(error) || await outputExists(sourceHost.outputPackageRoot)) throw storeError("materialization_binding_uncertain", "Checkpoint storyboard lifecycle publication may have committed; output was retained for exact recovery."); const abandon = createLifecycleAbandon({ identity, root, intent: ref(intent), reason: "proven-no-install" }); await publishLifecycleAbandon(store, abandon); await fault(authority, "after-abandon"); await publishLifecycleStateHead(store, lifecycleStateHead(identity, root, "abandoned", 0, { intent: ref(intent), cowStart: ref(start), abandon: ref(abandon) })); throw storeError("materialization_binding_conflict", "Checkpoint storyboard lifecycle COW refused before a recognized output was installed."); }
        await fault(authority, "after-c6b5b-commit"); const installed = await recognizeInstalledOutput(sourceHost, record.identity, prepared.expected, plan); if (!installed) throw storeError("materialization_binding_uncertain", "Checkpoint storyboard lifecycle COW completed without an exact output reopen; output was retained."); return await publishAndReopen(store, sourceHost, authority, identity, root, intent, installed, outputHandle, false);
      });
    });
  }); } catch (error) { throw sanitized(error); }
}

export async function detachCheckpointStoryboardLifecycleStoredRecord(authority: CheckpointStoryboardLifecycleResolutionAuthority, identity: CheckpointStoryboardRecordIdentity): Promise<CheckpointStoryboardLifecycleResolutionResult> {
  try { return await withCheckpointStoryboardLifecycleResolutionOutputAuthority(authority, async (host) => {
    const store = checkedAuthority(host.store), root = await readImmutableRecordRoot(store, identity);
    return await withLineageLock(store, root.id, async () => {
      const record = await readStoredRecordUnlocked(store, identity); assertB5Record(record); assertCheckpointStoryboardLifecycleResolutionAuthorityStore(authority, host.store); await assertForeignPartitionEvidenceAbsent(store, identity);
      const outputHandle = checkpointStoryboardLifecycleResolutionOutputHandle(authority, identity); let state = await readLifecycleResolutionState(store, identity, root, { requireHead: true, allowForwardRecovery: true });
      if (state.state === "unbound" || state.state === "abandoned") throw storeError("materialization_not_bound", "Checkpoint storyboard lifecycle record has no bound output to detach.");
      if (state.state === "preparing") { const intent = await readLifecycleIntent(store, identity), start = await readLifecycleCowStart(store, identity); if (intent) { const recovered = await recognizeInstalledOutput(host, record.identity, intent.expectedBase, intent.plan); if (recovered) { await publishAndReopen(store, host, authority, identity, root, intent, recovered, outputHandle, true); state = await readLifecycleResolutionState(store, identity, root, { requireHead: true, allowForwardRecovery: true }); } } if (state.state === "preparing" && intent && !start && !(await outputExists(host.outputPackageRoot))) { const abandon = createLifecycleAbandon({ identity, root, intent: ref(intent), reason: "no-cow-start" }); await publishLifecycleAbandon(store, abandon); await publishLifecycleStateHead(store, lifecycleStateHead(identity, root, "abandoned", 0, { intent: ref(intent), abandon: ref(abandon) })); throw storeError("materialization_not_bound", "Checkpoint storyboard lifecycle intent was abandoned before COW start; no output was deleted."); } if (state.state === "preparing") throw storeError("materialization_binding_uncertain", "Checkpoint storyboard lifecycle resolution is COW-uncertain; output was retained and cannot be detached yet."); }
      const binding = await readLifecycleBinding(store, identity); if (!binding) throw storeError("store_integrity_failed", "Checkpoint storyboard lifecycle state lost immutable binding.");
      if (state.state === "detached") { await verifyBinding(host, binding, identity, outputHandle); return result(identity, binding, "detached", true); }
      await verifyBinding(host, binding, identity, outputHandle); const detach = createLifecycleDetach({ identity, root, binding: ref(binding) }); await publishLifecycleDetach(store, detach); await fault(authority, "after-detach"); const intent = await readLifecycleIntent(store, identity), start = await readLifecycleCowStart(store, identity); if (!intent || !start) throw storeError("store_integrity_failed", "Checkpoint storyboard lifecycle detach lost required intent or COW start."); await publishLifecycleStateHead(store, lifecycleStateHead(identity, root, "detached", 0, { intent: ref(intent), cowStart: ref(start), binding: ref(binding), detach: ref(detach) }), async () => await fault(authority, "after-detached-state-head-rename")); const final = await readLifecycleResolutionState(store, identity, root, { requireHead: true, allowForwardRecovery: true }); if (final.state !== "detached" || final.bindingId !== binding.id) throw storeError("materialization_binding_uncertain", "Checkpoint storyboard lifecycle detach publication could not be reopened exactly."); return result(identity, binding, "detached", false);
    });
  }); } catch (error) { throw sanitized(error); }
}

function assertB5Record(record: Awaited<ReturnType<typeof readStoredRecordUnlocked>>): void { if (record.archive.terminal) throw storeError("lineage_archived", "Checkpoint storyboard lineage is terminally archived."); if (record.target.state === "tombstoned") throw storeError("record_tombstoned", "A tombstoned checkpoint storyboard record cannot resolve lifecycles."); if (record.admission.profile !== "c6b5-lifecycle@1") throw storeError("materialization_profile_refused", "C6C B5 lifecycle resolution accepts only a sealed C6B5 lifecycle profile record."); }
async function assertForeignPartitionEvidenceAbsent(store: ReturnType<typeof checkedAuthority>, identity: CheckpointStoryboardRecordIdentity): Promise<void> {
  await assertNoLegacyMaterializationEvidence(store, identity);
  await assertNoBehaviorResolutionEvidence(store, identity);
  await assertNoRelationResolutionEvidence(store, identity);
  await assertNoRelationActionResolutionEvidence(store, identity);
  await assertNoGeometryMorphResolutionEvidence(store, identity);
  await assertNoRetainedTraceResolutionEvidence(store, identity);
}
function planIdentity(prepared: Awaited<ReturnType<typeof prepareCheckpointStoryboardLifecycleMaterialization>>): LifecyclePlanIdentity {
  const { expected } = prepared;
  return Object.freeze({
    planFingerprint: expected.planFingerprint, profileFingerprint: expected.profileFingerprint, storyboardId: expected.storyboardId, storyboardSha256: expected.storyboardSha256, storyboardRevision: expected.storyboardRevision,
    sourceLayerPrefixCount: expected.sourceLayerPrefixCount, sourceLayerPrefixSha256: expected.sourceLayerPrefixSha256, generatedLayerIds: expected.generatedLayerIds, generatedLayerIdsSha256: expected.generatedLayerIdsSha256,
    generatedLayersSha256: expected.generatedLayersSha256, timingSha256: expected.timingSha256, outputCanonicalMotionSha256: expected.outputCanonicalMotionSha256,
  });
}
function ref(value: { readonly id: string; readonly sha256: string }) { return Object.freeze({ id: value.id, sha256: value.sha256 }); }
type Recognized = Readonly<{ output: Awaited<ReturnType<typeof reopenCheckpointStoryboardLifecycleMaterializationOutput>>; receipt: Awaited<ReturnType<typeof readC6B5bReceipt>>; plan: LifecyclePlanIdentity }>;
async function recognizeInstalledOutput(host: { readonly outputPackageRoot: string; readonly packageWorkspaceRoot: string; readonly packageWorkspaceAuthority: Parameters<typeof reopenCheckpointStoryboardLifecycleMaterializationOutput>[0]["packageWorkspaceAuthority"] }, identity: CheckpointStoryboardRecordIdentity, expected: C6B5bExactBase, plan: LifecyclePlanIdentity): Promise<Recognized | null> {
  try {
    const output = await reopenCheckpointStoryboardLifecycleMaterializationOutput(host), receipt = await readC6B5bReceipt(host.outputPackageRoot);
    if (output.storyboard.id !== identity.id || output.storyboard.sha256 !== identity.sha256 || output.storyboard.revision !== identity.revision || !samePlanIdentity(plan, output) || output.receipt.fingerprint !== receipt.fingerprint || canonicalJson(receipt.base.expected) !== canonicalJson(expected) || canonicalJson(receipt.base.reopened) !== canonicalJson(expected) || receipt.approval.storyboard.id !== identity.id || receipt.approval.storyboard.sha256 !== identity.sha256 || receipt.approval.storyboard.revision !== identity.revision || receipt.approval.plan.fingerprint !== plan.planFingerprint || receipt.approval.plan.lowererProfile.fingerprint !== plan.profileFingerprint || receipt.approval.projection.sourceLayerPrefixCount !== plan.sourceLayerPrefixCount || receipt.approval.projection.sourceLayerPrefixSha256 !== plan.sourceLayerPrefixSha256 || canonicalJson(receipt.approval.projection.generatedLayerIds) !== canonicalJson(plan.generatedLayerIds) || receipt.approval.projection.generatedLayerIdsSha256 !== plan.generatedLayerIdsSha256 || receipt.approval.projection.generatedLayersSha256 !== plan.generatedLayersSha256 || receipt.approval.projection.timingSha256 !== plan.timingSha256 || receipt.approval.projection.outputCanonicalMotionSha256 !== plan.outputCanonicalMotionSha256 || receipt.output.canonicalMotionSha256 !== plan.outputCanonicalMotionSha256 || receipt.renderer.invoked !== false || receipt.renderer.pixels !== false) return null;
    return Object.freeze({ output, receipt, plan });
  } catch { return null; }
}
function samePlanIdentity(plan: LifecyclePlanIdentity, output: Awaited<ReturnType<typeof reopenCheckpointStoryboardLifecycleMaterializationOutput>>): boolean {
  return plan.planFingerprint === output.plan.fingerprint && plan.profileFingerprint === output.profile.fingerprint && plan.storyboardId === output.storyboard.id && plan.storyboardSha256 === output.storyboard.sha256 && plan.storyboardRevision === output.storyboard.revision && plan.sourceLayerPrefixCount === output.layers.sourcePrefix.count && plan.sourceLayerPrefixSha256 === output.layers.sourcePrefix.sha256 && canonicalJson(plan.generatedLayerIds) === canonicalJson(output.layers.ids) && plan.generatedLayerIdsSha256 === output.layers.idsSha256 && plan.generatedLayersSha256 === output.layers.generatedSha256 && plan.timingSha256 === output.layers.timingSha256 && plan.outputCanonicalMotionSha256 === output.package.motion.canonicalSha256 && output.materialization.renderer.invoked === false && output.materialization.renderer.pixels === false;
}
async function publishAndReopen(store: ReturnType<typeof checkedAuthority>, host: Parameters<typeof recognizeInstalledOutput>[0], authority: CheckpointStoryboardLifecycleResolutionAuthority, identity: CheckpointStoryboardRecordIdentity, root: CheckpointStoryboardRecordIdentity, intent: LifecycleIntent, recognized: Recognized, outputHandle: string, replayed: boolean): Promise<CheckpointStoryboardLifecycleResolutionResult> { const start = await readLifecycleCowStart(store, identity); if (!start || !sameIdentity(start.identity, identity) || !sameIdentity(start.root, root) || start.intent.id !== intent.id || start.intent.sha256 !== intent.sha256) throw storeError("store_integrity_failed", "Checkpoint storyboard lifecycle binding lost durable COW-start evidence."); const binding = createLifecycleBinding({ identity, root, intent: ref(intent), plan: recognized.plan, source: Object.freeze({ expected: recognized.receipt.base.expected, reopened: recognized.receipt.base.reopened }), output: Object.freeze({ expected: recognized.output, reopened: recognized.output }), receiptFingerprint: recognized.receipt.fingerprint, outputHandle }); await publishLifecycleBinding(store, binding); await fault(authority, "after-binding"); await publishLifecycleStateHead(store, lifecycleStateHead(identity, root, "bound", 1, { intent: ref(intent), cowStart: ref(start), binding: ref(binding) }), async () => await fault(authority, "after-bound-state-head-rename")); const reopened = await readLifecycleBinding(store, identity); if (!reopened || canonicalJson(reopened) !== canonicalJson(binding)) throw storeError("materialization_binding_uncertain", "Checkpoint storyboard lifecycle binding publication could not be reopened exactly."); await verifyBinding(host, reopened, identity, outputHandle); return result(identity, reopened, "bound", replayed); }
async function replayBound(store: ReturnType<typeof checkedAuthority>, host: Parameters<typeof recognizeInstalledOutput>[0], identity: CheckpointStoryboardRecordIdentity, root: CheckpointStoryboardRecordIdentity, bindingId: string, outputHandle: string): Promise<CheckpointStoryboardLifecycleResolutionResult> { const binding = await readLifecycleBinding(store, identity); if (!binding || binding.id !== bindingId || !sameIdentity(binding.root, root)) throw storeError("store_integrity_failed", "Checkpoint storyboard bound lifecycle state does not match immutable binding."); await verifyBinding(host, binding, identity, outputHandle); return result(identity, binding, "bound", true); }
async function verifyBinding(host: Parameters<typeof recognizeInstalledOutput>[0], binding: LifecycleBinding, identity: CheckpointStoryboardRecordIdentity, outputHandle: string): Promise<void> { if (binding.outputHandle !== outputHandle) throw storeError("materialization_binding_conflict", "Checkpoint storyboard lifecycle binding belongs to a different authority-store output handle."); const output = await reopenCheckpointStoryboardLifecycleMaterializationOutput(host), receipt = await readC6B5bReceipt(host.outputPackageRoot); const recognized = await recognizeInstalledOutput(host, identity, binding.source.expected, binding.plan); if (!recognized || output.receipt.fingerprint !== binding.receiptFingerprint || receipt.fingerprint !== binding.receiptFingerprint || canonicalJson(output) !== canonicalJson(binding.output.expected) || canonicalJson(output) !== canonicalJson(binding.output.reopened) || canonicalJson(receipt.base.expected) !== canonicalJson(binding.source.expected) || canonicalJson(receipt.base.reopened) !== canonicalJson(binding.source.reopened)) throw storeError("materialization_binding_conflict", "Checkpoint storyboard lifecycle binding no longer reopens its complete B5b base, output, receipt, prefix, catalog suffix, timing, inventory, and renderer identity."); }
function result(identity: CheckpointStoryboardRecordIdentity, binding: LifecycleBinding, state: "bound" | "detached", replayed: boolean): CheckpointStoryboardLifecycleResolutionResult { return Object.freeze({ identity, binding: Object.freeze({ state, active: state === "bound" ? 1 as const : 0 as const, bindingId: binding.id, outputHandle: binding.outputHandle, receiptFingerprint: binding.receiptFingerprint }), renderer: Object.freeze({ invoked: false as const, pixels: false as const }), replayed }); }
async function outputExists(file: string): Promise<boolean> { try { await lstat(file); return true; } catch (error) { if (error && typeof error === "object" && "code" in error && (error as { code?: unknown }).code === "ENOENT") return false; throw storeError("materialization_binding_uncertain", "Checkpoint storyboard lifecycle output could not be safely classified as absent and was not recreated."); } }
function sanitized(error: unknown): never { if (error instanceof CheckpointStoryboardRecordStoreError) throw error; throw storeError("materialization_binding_uncertain", "Checkpoint storyboard lifecycle resolution did not complete exact host/package verification; output was retained and no path evidence was returned."); }
