/** Output-only C6B reopen: a committed COW remains verifiable after its source is unavailable. */
import { lstat } from "node:fs/promises";
import { isAbsolute, relative, resolve, sep } from "node:path";
import { compareCodeUnits, hashBuffer } from "@shellx-motion/core";
import { assertTrustedWorkspaceAnchorPath, withTrustedWorkspaceAnchor } from "@shellx-motion/core/internal/trusted-host-workspace";
import { snapshotPackageEditTree } from "./package-edit-tree-snapshot.js";
import { PackageEditTransactionError } from "./package-edit-transaction.js";
import { C6B1B_RECEIPT_PATH, readC6B1bReceipt, type CheckpointStoryboardScalarSpatialMaterializationReceipt } from "./checkpoint-storyboard-scalar-spatial-materialize-receipt-private.js";
import { closedInventoryFor, observePackage, preservedLeaves, same, type CheckpointStoryboardScalarSpatialMaterializationHost } from "./checkpoint-storyboard-scalar-spatial-materialize-facts-private.js";
export async function reopenCheckpointStoryboardScalarSpatialMaterializationOutput(host: CheckpointStoryboardScalarSpatialMaterializationHost, receiptValue: CheckpointStoryboardScalarSpatialMaterializationReceipt): Promise<CheckpointStoryboardScalarSpatialMaterializationReceipt> { return await withOutputWorkspaceAuthority(host, async () => { const receipt = await readC6B1bReceipt(host.outputPackageRoot); if (!same(receipt, receiptValue)) throw new PackageEditTransactionError("copy_mismatch", "C6B1b receipt changed during output reopen."); const output = await observePackage(host.outputPackageRoot, host); if (output.base.packageId !== receipt.output.packageId || output.base.manifestRawSha256 !== receipt.output.manifestRawSha256 || output.base.motionRawSha256 !== receipt.output.motionRawSha256 || output.base.motionCanonicalSha256 !== receipt.output.canonicalMotionSha256) throw new PackageEditTransactionError("copy_mismatch", "C6B1b reopened package identity differs from its receipt output."); const inventory = await closedInventoryFor(host.outputPackageRoot, host), snapshot = await snapshotPackageEditTree(host.outputPackageRoot); const entries = [...snapshot.entries].filter(([path, value]) => path !== C6B1B_RECEIPT_PATH && value.startsWith("file:")).map(([path, value]) => { const match = /^file:([0-9]+):([a-f0-9]{64})$/u.exec(value); if (!match) throw new PackageEditTransactionError("copy_mismatch", "C6B1b output inventory contains a non-file leaf."); return { path, byteLength: Number(match[1]), sha256: match[2] }; }).sort((left, right) => compareCodeUnits(left.path, right.path)); const nonReceiptInventory = Object.freeze({ sha256: hashBuffer(Buffer.from(entries.map((entry) => `${entry.path}\u0000${entry.byteLength}\u0000${entry.sha256}\n`).join(""), "utf8")), entryCount: entries.length, leafCount: entries.length }); if (!same(nonReceiptInventory, receipt.output.nonReceiptInventory) || inventory.entryCount !== entries.length + 1 || !same(receipt.output.preservedLeaves, preservedLeaves(snapshot, output.pkg.manifest.motion)) || !same(receipt.output.changed.paths, [output.pkg.manifest.motion, C6B1B_RECEIPT_PATH].sort(compareCodeUnits))) throw new PackageEditTransactionError("copy_mismatch", "C6B1b reopened package tree differs from its receipt inventory evidence."); const finalReceipt = await readC6B1bReceipt(host.outputPackageRoot); if (!same(finalReceipt, receipt)) throw new PackageEditTransactionError("copy_mismatch", "C6B1b receipt changed after live package inventory reopen."); return finalReceipt; }); }
async function withOutputWorkspaceAuthority<T>(host: CheckpointStoryboardScalarSpatialMaterializationHost, operation: () => Promise<T>): Promise<T> { const workspace = resolve(host.packageWorkspaceRoot); if (!strictDescendant(workspace, resolve(host.outputPackageRoot))) throw new PackageEditTransactionError("unsafe_output", "C6B1b output must be a strict descendant of the host workspace."); try { await assertTrustedWorkspaceAnchorPath(host.packageWorkspaceAuthority, workspace); return await withTrustedWorkspaceAnchor(host.packageWorkspaceAuthority, async () => { const output = await lstat(host.outputPackageRoot); if (!output.isDirectory() || output.isSymbolicLink()) throw new PackageEditTransactionError("unsafe_output", "C6B1b output package root is not a trusted directory."); return await operation(); }); } catch (error) { if (error instanceof PackageEditTransactionError) throw error; throw new PackageEditTransactionError("unsafe_output", "C6B1b output workspace authority changed."); } }
function strictDescendant(root: string, path: string): boolean { const suffix = relative(root, path); return suffix !== "" && suffix !== ".." && !suffix.startsWith(`..${sep}`) && !isAbsolute(suffix); }
