/** Signed append-only C6C B4a action-resolution journal. B4b receipts remain diagnostic only. */
import { createHash } from "node:crypto";
import { opendir } from "node:fs/promises";
import { join } from "node:path";
import { canonicalJson, canonicalJsonSha256, validateMotionRelations } from "@shellx-motion/core";
import type { C6B4bExactBase } from "./checkpoint-storyboard-relation-action-materialize-private/checkpoint-storyboard-relation-action-materialize-receipt-private.js";
import type { CheckpointStoryboardRelationActionMaterializationInstalledOutput } from "./checkpoint-storyboard-relation-action-materialize-private/checkpoint-storyboard-relation-action-materialize-output-private.js";
import { readSignedFile, replaceSignedFile, syncPrivateDirectory, writeExclusiveSignedFile } from "./checkpoint-storyboard-record-store-signed-files.js";
import { readLineageMembers } from "./checkpoint-storyboard-materialization-bindings.js";
import { readStoredRecordUnlocked } from "./checkpoint-storyboard-record-store-state.js";
import { MAX_STATE_BYTES, SHA256, exact, readIdentity, sameIdentity, storeError, type AuthorityFacts, type CheckpointStoryboardRecordIdentity } from "./checkpoint-storyboard-record-store-types.js";

const MAX_JOURNAL_BYTES = 192 * 1024;
const HANDLE = /^checkpoint_storyboard_relation_action_output_[a-f0-9]{32}$/u;
const FILE = /^checkpoint_storyboard_[a-f0-9]{32}\.(?:state|intent|binding|cow-start|detach|abandon)\.json$/u;
const PREFIX = { intent: "checkpoint_storyboard_relation_action_resolution_intent_", cowStart: "checkpoint_storyboard_relation_action_resolution_cow_start_", binding: "checkpoint_storyboard_relation_action_resolution_binding_", detach: "checkpoint_storyboard_relation_action_resolution_detach_", abandon: "checkpoint_storyboard_relation_action_resolution_abandon_" } as const;
type Ref = Readonly<{ id: string; sha256: string }>;
export type CheckpointStoryboardRelationActionResolutionState = "unbound" | "preparing" | "bound" | "detached" | "abandoned";
export type RelationActionPlanIdentity = Readonly<{ planFingerprint: string; profileFingerprint: string; actionStoreSchema: "shellx-motion/relation-actions@2"; actionStoreSha256: string; actionDefinitionId: string; actionDefinitionSha256: string; actionRequestInstanceId: string; actionRequestSha256: string; actionApplyPlanFingerprint: string; actionObjects: 0; actionRelations: 1; actionKeyframeWrites: 0; actionChangedPath: string; actionOutputCanonicalMotionSha256: string; relationId: string; storeSha256: string; staticFingerprint: string; gpuStaticFingerprint: string; startFramePlanFingerprint: string; endFramePlanFingerprint: string }>;
export type RelationActionOutputIdentity = CheckpointStoryboardRelationActionMaterializationInstalledOutput;
export type RelationActionIntent = Readonly<{ schema: "shellx-motion/private-checkpoint-storyboard-relation-action-resolution-intent@1"; id: string; sha256: string; identity: CheckpointStoryboardRecordIdentity; root: CheckpointStoryboardRecordIdentity; plan: RelationActionPlanIdentity; expectedBase: C6B4bExactBase; outputHandle: string }>;
export type RelationActionCowStart = Readonly<{ schema: "shellx-motion/private-checkpoint-storyboard-relation-action-resolution-cow-start@1"; id: string; sha256: string; identity: CheckpointStoryboardRecordIdentity; root: CheckpointStoryboardRecordIdentity; intent: Ref }>;
export type RelationActionBinding = Readonly<{ schema: "shellx-motion/private-checkpoint-storyboard-relation-action-resolution-binding@1"; id: string; sha256: string; identity: CheckpointStoryboardRecordIdentity; root: CheckpointStoryboardRecordIdentity; intent: Ref; plan: RelationActionPlanIdentity; source: Readonly<{ expected: C6B4bExactBase; reopened: C6B4bExactBase }>; output: Readonly<{ expected: RelationActionOutputIdentity; reopened: RelationActionOutputIdentity }>; receiptFingerprint: string; outputHandle: string }>;
export type RelationActionDetach = Readonly<{ schema: "shellx-motion/private-checkpoint-storyboard-relation-action-resolution-detach@1"; id: string; sha256: string; identity: CheckpointStoryboardRecordIdentity; root: CheckpointStoryboardRecordIdentity; binding: Ref }>;
export type RelationActionAbandon = Readonly<{ schema: "shellx-motion/private-checkpoint-storyboard-relation-action-resolution-abandon@1"; id: string; sha256: string; identity: CheckpointStoryboardRecordIdentity; root: CheckpointStoryboardRecordIdentity; intent: Ref; reason: "proven-no-install" | "no-cow-start" }>;
export type RelationActionStateHead = Readonly<{ schema: "shellx-motion/private-checkpoint-storyboard-relation-action-resolution-state@1"; identity: CheckpointStoryboardRecordIdentity; root: CheckpointStoryboardRecordIdentity; state: CheckpointStoryboardRelationActionResolutionState; active: 0 | 1; intent?: Ref; cowStart?: Ref; binding?: Ref; detach?: Ref; abandon?: Ref }>;
export type RelationActionResolutionBindingState = Readonly<{ state: CheckpointStoryboardRelationActionResolutionState; active: 0 | 1; bindingId?: string; outputHandle?: string; receiptFingerprint?: string }>;

export function createRelationActionIntent(input: Omit<RelationActionIntent, "schema" | "id" | "sha256">): RelationActionIntent { return seal("intent", "shellx-motion/private-checkpoint-storyboard-relation-action-resolution-intent@1", input); }
export function createRelationActionCowStart(input: Omit<RelationActionCowStart, "schema" | "id" | "sha256">): RelationActionCowStart { return seal("cowStart", "shellx-motion/private-checkpoint-storyboard-relation-action-resolution-cow-start@1", input); }
export function createRelationActionBinding(input: Omit<RelationActionBinding, "schema" | "id" | "sha256">): RelationActionBinding { return seal("binding", "shellx-motion/private-checkpoint-storyboard-relation-action-resolution-binding@1", input); }
export function createRelationActionDetach(input: Omit<RelationActionDetach, "schema" | "id" | "sha256">): RelationActionDetach { return seal("detach", "shellx-motion/private-checkpoint-storyboard-relation-action-resolution-detach@1", input); }
export function createRelationActionAbandon(input: Omit<RelationActionAbandon, "schema" | "id" | "sha256">): RelationActionAbandon { return seal("abandon", "shellx-motion/private-checkpoint-storyboard-relation-action-resolution-abandon@1", input); }
export function relationActionStateHead(identity: CheckpointStoryboardRecordIdentity, root: CheckpointStoryboardRecordIdentity, state: CheckpointStoryboardRelationActionResolutionState, active: 0 | 1, refs: Partial<Pick<RelationActionStateHead, "intent" | "cowStart" | "binding" | "detach" | "abandon">> = {}): RelationActionStateHead { return Object.freeze({ schema: "shellx-motion/private-checkpoint-storyboard-relation-action-resolution-state@1", identity, root, state, active, ...refs }); }
export async function initializeRelationActionStateHead(facts: AuthorityFacts, identity: CheckpointStoryboardRecordIdentity, root: CheckpointStoryboardRecordIdentity): Promise<void> { await publishExact(statePath(facts, identity), relationActionStateHead(identity, root, "unbound", 0), facts); }
export async function publishRelationActionIntent(facts: AuthorityFacts, value: RelationActionIntent): Promise<void> { await publishExact(path(facts, value.identity, "intent"), value, facts); }
export async function publishRelationActionCowStart(facts: AuthorityFacts, value: RelationActionCowStart): Promise<void> { await publishExact(path(facts, value.identity, "cow-start"), value, facts); }
export async function publishRelationActionBinding(facts: AuthorityFacts, value: RelationActionBinding): Promise<void> { await publishExact(path(facts, value.identity, "binding"), value, facts); }
export async function publishRelationActionDetach(facts: AuthorityFacts, value: RelationActionDetach): Promise<void> { await publishExact(path(facts, value.identity, "detach"), value, facts); }
export async function publishRelationActionAbandon(facts: AuthorityFacts, value: RelationActionAbandon): Promise<void> { await publishExact(path(facts, value.identity, "abandon"), value, facts); }
export async function publishRelationActionStateHead(facts: AuthorityFacts, value: RelationActionStateHead, afterRename?: () => void | Promise<void>): Promise<void> { await replaceSignedFile(statePath(facts, value.identity), value, facts, MAX_STATE_BYTES, afterRename); }
export async function readRelationActionIntent(facts: AuthorityFacts, identity: CheckpointStoryboardRecordIdentity): Promise<RelationActionIntent | null> { return await optional(path(facts, identity, "intent"), facts, readIntent); }
export async function readRelationActionCowStart(facts: AuthorityFacts, identity: CheckpointStoryboardRecordIdentity): Promise<RelationActionCowStart | null> { return await optional(path(facts, identity, "cow-start"), facts, readStart); }
export async function readRelationActionBinding(facts: AuthorityFacts, identity: CheckpointStoryboardRecordIdentity): Promise<RelationActionBinding | null> { return await optional(path(facts, identity, "binding"), facts, readBinding); }
export async function readRelationActionStateHead(facts: AuthorityFacts, identityId: string): Promise<RelationActionStateHead | null> { if (!/^checkpoint_storyboard_[a-f0-9]{32}$/u.test(identityId)) throw storeError("store_integrity_failed", "Checkpoint storyboard relation-action state filename identity is invalid."); return await optional(join(facts.relationActionResolutions.path, `${identityId}.state.json`), facts, readHead); }
export async function assertNoRelationActionResolutionEvidence(facts: AuthorityFacts, identity: CheckpointStoryboardRecordIdentity): Promise<void> { if (await readRelationActionStateHead(facts, identity.id) || await readRelationActionIntent(facts, identity) || await readRelationActionCowStart(facts, identity) || await readRelationActionBinding(facts, identity) || await optional(path(facts, identity, "detach"), facts, readDetach) || await optional(path(facts, identity, "abandon"), facts, readAbandon)) throw storeError("store_integrity_failed", "Checkpoint storyboard non-action record has forbidden C6B4a action-resolution evidence."); }

/** Reads all signed phases. Forward head repair is legal only while a resolver holds the lineage lock. */
export async function readRelationActionResolutionState(facts: AuthorityFacts, identity: CheckpointStoryboardRecordIdentity, root: CheckpointStoryboardRecordIdentity, options: { readonly requireHead?: boolean; readonly allowForwardRecovery?: boolean } = {}): Promise<RelationActionResolutionBindingState> {
  await syncActionDirectory(facts); const repair = options.allowForwardRecovery ?? false;
  const head = await optional(statePath(facts, identity), facts, readHead), intent = await readRelationActionIntent(facts, identity), start = await readRelationActionCowStart(facts, identity), binding = await readRelationActionBinding(facts, identity), detach = await optional(path(facts, identity, "detach"), facts, readDetach), abandon = await optional(path(facts, identity, "abandon"), facts, readAbandon);
  if (!head) {
    if (!options.requireHead && !intent && !start && !binding && !detach && !abandon) return Object.freeze({ state: "unbound" as const, active: 0 as const });
    if (intent && !start && !binding && !detach && !abandon && repair) { const next = relationActionStateHead(identity, root, "preparing", 0, { intent: ref(intent) }); await publishRelationActionStateHead(facts, next); return await reopenPromoted(facts, identity, root, next, Object.freeze({ state: "preparing" as const, active: 0 as const, outputHandle: intent.outputHandle })); }
    throw storeError(intent ? "record_commit_uncertain" : "store_integrity_failed", "Checkpoint storyboard relation-action resolution is missing its required signed state head.");
  }
  if (!sameIdentity(head.identity, identity) || !sameIdentity(head.root, root)) throw storeError("store_integrity_failed", "Checkpoint storyboard relation-action state head does not bind this record lineage.");
  if (!intent) { if (start || binding || detach || abandon) throw storeError("store_integrity_failed", "Checkpoint storyboard action unbound state has phase evidence."); return await checkedHead(facts, head, Object.freeze({ state: "unbound" as const, active: 0 as const }), repair); }
  if (!sameIdentity(intent.identity, identity) || !sameIdentity(intent.root, root)) throw storeError("store_integrity_failed", "Checkpoint storyboard relation-action intent does not bind this record lineage.");
  if (!binding) {
    if (detach) throw storeError("store_integrity_failed", "Checkpoint storyboard relation-action detach has no immutable binding.");
    if (start && (!sameIdentity(start.identity, identity) || !sameIdentity(start.root, root) || !sameRef(start.intent, intent))) throw storeError("store_integrity_failed", "Checkpoint storyboard relation-action COW start does not bind intent.");
    if (abandon) { if (!sameIdentity(abandon.identity, identity) || !sameIdentity(abandon.root, root) || !sameRef(abandon.intent, intent) || (abandon.reason === "no-cow-start" && start) || (abandon.reason === "proven-no-install" && !start)) throw storeError("store_integrity_failed", "Checkpoint storyboard relation-action abandonment is inconsistent."); return await checkedHead(facts, head, Object.freeze({ state: "abandoned" as const, active: 0 as const, outputHandle: intent.outputHandle }), repair, intent, start ?? undefined, undefined, undefined, abandon); }
    return await checkedHead(facts, head, Object.freeze({ state: "preparing" as const, active: 0 as const, outputHandle: intent.outputHandle }), repair, intent, start ?? undefined);
  }
  if (!start || abandon || !sameIdentity(binding.identity, identity) || !sameIdentity(binding.root, root) || !sameRef(binding.intent, intent) || binding.outputHandle !== intent.outputHandle || !samePlan(binding.plan, intent.expectedBase) || !samePlan(binding.plan, binding.output.expected) || canonicalJson(binding.plan) !== canonicalJson(intent.plan) || canonicalJson(binding.source.expected) !== canonicalJson(intent.expectedBase) || !sameIdentity(binding.output.expected.storyboard, identity) || !sameIdentity(binding.output.reopened.storyboard, identity) || !sameIdentity(start.identity, identity) || !sameIdentity(start.root, root) || !sameRef(start.intent, intent)) throw storeError("store_integrity_failed", "Checkpoint storyboard relation-action binding does not semantically bind intent, action facts, identity, and COW start.");
  if (!detach) return await checkedHead(facts, head, Object.freeze({ state: "bound" as const, active: 1 as const, bindingId: binding.id, outputHandle: binding.outputHandle, receiptFingerprint: binding.receiptFingerprint }), repair, intent, start, binding);
  if (!sameIdentity(detach.identity, identity) || !sameIdentity(detach.root, root) || !sameRef(detach.binding, binding)) throw storeError("store_integrity_failed", "Checkpoint storyboard relation-action detach does not bind immutable binding.");
  return await checkedHead(facts, head, Object.freeze({ state: "detached" as const, active: 0 as const, bindingId: binding.id, outputHandle: binding.outputHandle, receiptFingerprint: binding.receiptFingerprint }), repair, intent, start, binding, detach);
}
export async function assertLineageHasNoPreparingOrBoundRelationActionResolutions(facts: AuthorityFacts, root: CheckpointStoryboardRecordIdentity, requireHeadsFor = new Set<string>()): Promise<void> { const members = await readLineageMembers(facts, root); if (!members.length) throw storeError("store_integrity_failed", "Checkpoint storyboard lineage has no signed membership records."); for (const member of members) { if (!sameIdentity(member.root, root)) throw storeError("store_integrity_failed", "Checkpoint storyboard lineage membership root changed."); const state = await readRelationActionResolutionState(facts, member.identity, root, { requireHead: requireHeadsFor.has(member.identity.id) }); if (state.state === "preparing" || state.state === "bound") throw storeError("materialization_binding_conflict", "Checkpoint storyboard remove/archive requires every action-resolution member to be unbound or detached."); } }
/** Archive scans the complete B4 namespace so copied/foreign/hidden phase leaves cannot be hidden. */
export async function assertRelationActionResolutionJournalCompleteForLineage(facts: AuthorityFacts, root: CheckpointStoryboardRecordIdentity, requireHeadsFor = new Set<string>()): Promise<void> {
  const members = await readLineageMembers(facts, root), byId = new Map(members.map((member) => [member.identity.id, member.identity])), reader = await opendir(facts.relationActionResolutions.path);
  try { for await (const entry of reader) { if (!entry.isFile() || !FILE.test(entry.name)) throw storeError("store_integrity_failed", "Checkpoint storyboard relation-action journal contains an invalid entry."); const identityId = entry.name.slice(0, 54), identity = byId.get(identityId), head = await readRelationActionStateHead(facts, identityId); if (!head) throw storeError("store_integrity_failed", "Checkpoint storyboard relation-action journal state head is missing."); if (head.identity.id !== identityId) throw storeError("store_integrity_failed", "Checkpoint storyboard relation-action filename does not match signed identity."); if (identity) { if (!requireHeadsFor.has(identity.id) || !sameIdentity(head.root, root) || !sameIdentity(head.identity, identity)) throw storeError("store_integrity_failed", "Checkpoint storyboard relation-action journal attaches to a sealed non-B4 lineage member."); } else { const foreign = (await readLineageMembers(facts, head.root)).find((member) => sameIdentity(member.identity, head.identity)); if (!foreign || !sameIdentity(foreign.root, head.root)) throw storeError("store_integrity_failed", "Checkpoint storyboard relation-action journal references an unknown lineage member."); const foreignRecord = await readStoredRecordUnlocked(facts, head.identity); if (foreignRecord.admission.profile !== "c6b4-relation-action@1") throw storeError("store_integrity_failed", "Checkpoint storyboard relation-action journal attaches to a foreign non-B4 member."); await readRelationActionResolutionState(facts, head.identity, head.root, { requireHead: true }); } } } finally { await reader.close().catch(() => undefined); }
  for (const member of members) await readRelationActionResolutionState(facts, member.identity, root, { requireHead: requireHeadsFor.has(member.identity.id) });
}

function path(facts: AuthorityFacts, identity: CheckpointStoryboardRecordIdentity, kind: "intent" | "cow-start" | "binding" | "detach" | "abandon"): string { return join(facts.relationActionResolutions.path, `${identity.id}.${kind}.json`); }
function statePath(facts: AuthorityFacts, identity: CheckpointStoryboardRecordIdentity): string { return join(facts.relationActionResolutions.path, `${identity.id}.state.json`); }
async function optional<T>(file: string, facts: AuthorityFacts, read: (value: unknown) => T): Promise<T | null> { try { return read(await readSignedFile(file, facts, MAX_JOURNAL_BYTES, "record_not_found")); } catch (error) { if (error instanceof Error && (error as { code?: string }).code === "record_not_found") return null; throw error; } }
async function syncActionDirectory(facts: AuthorityFacts): Promise<void> { try { await syncPrivateDirectory(facts.relationActionResolutions.path); } catch { throw storeError("record_commit_uncertain", "Checkpoint storyboard relation-action state requires a durable directory resync."); } }
async function checkedHead(facts: AuthorityFacts, head: RelationActionStateHead, state: RelationActionResolutionBindingState, repair: boolean, intent?: RelationActionIntent, cowStart?: RelationActionCowStart, binding?: RelationActionBinding, detach?: RelationActionDetach, abandon?: RelationActionAbandon): Promise<RelationActionResolutionBindingState> {
  const matches = (actual: Ref | undefined, value: { readonly id: string; readonly sha256: string } | undefined) => value ? sameRef(actual, value) : !actual;
  if (!legalHead(head)) throw storeError("store_integrity_failed", "Checkpoint storyboard relation-action state head has invalid phase fields.");
  const exactHead = head.state === state.state && head.active === state.active && matches(head.intent, intent) && matches(head.cowStart, cowStart) && matches(head.binding, binding) && matches(head.detach, detach) && matches(head.abandon, abandon);
  if (exactHead) return state;
  if (!repair) throw storeError("record_commit_uncertain", "Checkpoint storyboard action phase evidence is one publication ahead of its signed head; read-only lifecycle inspection will not repair it.");
  const next = relationActionStateHead(head.identity, head.root, state.state, state.active, { ...(intent ? { intent: ref(intent) } : {}), ...(cowStart ? { cowStart: ref(cowStart) } : {}), ...(binding ? { binding: ref(binding) } : {}), ...(detach ? { detach: ref(detach) } : {}), ...(abandon ? { abandon: ref(abandon) } : {}) });
  const oneStep = (head.state === "unbound" && state.state === "preparing" && !!intent && !cowStart)
    || (head.state === "preparing" && state.state === "preparing" && !!intent && !!cowStart && matches(head.intent, intent) && !head.cowStart)
    || (head.state === "preparing" && state.state === "bound" && !!intent && !!cowStart && !!binding && matches(head.intent, intent) && matches(head.cowStart, cowStart))
    || (head.state === "preparing" && state.state === "abandoned" && !!intent && !!abandon && matches(head.intent, intent) && matches(head.cowStart, cowStart))
    || (head.state === "bound" && state.state === "detached" && !!intent && !!cowStart && !!binding && !!detach && matches(head.intent, intent) && matches(head.cowStart, cowStart) && matches(head.binding, binding));
  if (!oneStep) throw storeError("store_integrity_failed", "Checkpoint storyboard relation-action head skips, diverges from, or rolls back immutable phase evidence.");
  await publishRelationActionStateHead(facts, next); return await reopenPromoted(facts, head.identity, head.root, next, state);
}
function legalHead(head: RelationActionStateHead): boolean { return (head.state === "unbound" && head.active === 0 && !hasRef(head)) || (head.state === "preparing" && head.active === 0 && !!head.intent && !head.binding && !head.detach && !head.abandon) || (head.state === "bound" && head.active === 1 && !!head.intent && !!head.cowStart && !!head.binding && !head.detach && !head.abandon) || (head.state === "detached" && head.active === 0 && !!head.intent && !!head.cowStart && !!head.binding && !!head.detach && !head.abandon) || (head.state === "abandoned" && head.active === 0 && !!head.intent && !!head.abandon && !head.binding && !head.detach); }
async function reopenPromoted(facts: AuthorityFacts, identity: CheckpointStoryboardRecordIdentity, root: CheckpointStoryboardRecordIdentity, expected: RelationActionStateHead, state: RelationActionResolutionBindingState): Promise<RelationActionResolutionBindingState> { const reopened = await optional(statePath(facts, identity), facts, readHead); if (!reopened || canonicalJson(reopened) !== canonicalJson(expected)) throw storeError("record_commit_uncertain", "Checkpoint storyboard relation-action head promotion could not be reopened exactly."); await syncActionDirectory(facts); return state; }
async function publishExact(file: string, value: object, facts: AuthorityFacts): Promise<void> { try { await writeExclusiveSignedFile(file, value, facts, MAX_JOURNAL_BYTES); } catch (error) { if (!(error instanceof Error) || (error as { code?: string }).code !== "record_identity_conflict") throw error; const existing = await readSignedFile(file, facts, MAX_JOURNAL_BYTES, "record_not_found"); if (canonicalJson(existing) !== canonicalJson(value)) throw storeError("materialization_binding_conflict", "Checkpoint storyboard immutable relation-action journal leaf is occupied by different content."); } }
function seal<K extends keyof typeof PREFIX, S extends string, T extends object>(kind: K, schema: S, payload: T): T & { readonly schema: S; readonly id: string; readonly sha256: string } { const sha256 = createHash("sha256").update(canonicalJson({ schema, ...payload })).digest("hex"); return Object.freeze({ schema, id: `${PREFIX[kind]}${sha256.slice(0, 32)}`, sha256, ...payload }); }
function ref(value: { readonly id: string; readonly sha256: string }): Ref { return Object.freeze({ id: value.id, sha256: value.sha256 }); }
function sameRef(value: Ref | undefined, target: { readonly id: string; readonly sha256: string }): boolean { return !!value && value.id === target.id && value.sha256 === target.sha256; }
function hasRef(head: RelationActionStateHead): boolean { return !!(head.intent || head.cowStart || head.binding || head.detach || head.abandon); }
function readIntent(value: unknown): RelationActionIntent { const record = exact(value, ["schema", "id", "sha256", "identity", "root", "plan", "expectedBase", "outputHandle"], "Relation-action resolution intent"); if (record.schema !== "shellx-motion/private-checkpoint-storyboard-relation-action-resolution-intent@1") bad("action intent schema"); const identity = readIdentity(record.identity, "Action intent identity"), root = readIdentity(record.root, "Action intent root"), plan = readPlan(record.plan), expectedBase = readBase(record.expectedBase, "Action intent expected base"), outputHandle = str(record.outputHandle, "Action intent output handle"); if (!HANDLE.test(outputHandle) || !samePlan(plan, expectedBase)) bad("action intent plan"); return checked(record, PREFIX.intent, { schema: record.schema, identity, root, plan, expectedBase, outputHandle }) as RelationActionIntent; }
function readStart(value: unknown): RelationActionCowStart { const record = exact(value, ["schema", "id", "sha256", "identity", "root", "intent"], "Action COW start"); if (record.schema !== "shellx-motion/private-checkpoint-storyboard-relation-action-resolution-cow-start@1") bad("action COW start schema"); return checked(record, PREFIX.cowStart, { schema: record.schema, identity: readIdentity(record.identity, "Action start identity"), root: readIdentity(record.root, "Action start root"), intent: readRef(record.intent, PREFIX.intent) }) as RelationActionCowStart; }
function readBinding(value: unknown): RelationActionBinding { const record = exact(value, ["schema", "id", "sha256", "identity", "root", "intent", "plan", "source", "output", "receiptFingerprint", "outputHandle"], "Action binding"); if (record.schema !== "shellx-motion/private-checkpoint-storyboard-relation-action-resolution-binding@1") bad("action binding schema"); const source = basePair(record.source, "Action binding source"), output = outputPair(record.output, "Action binding output"), receiptFingerprint = str(record.receiptFingerprint, "Action binding receipt"), outputHandle = str(record.outputHandle, "Action binding handle"), plan = readPlan(record.plan); if (!SHA256.test(receiptFingerprint) || !HANDLE.test(outputHandle) || receiptFingerprint !== output.expected.receipt.fingerprint || !samePlan(plan, source.expected) || !samePlan(plan, output.expected) || output.expected.package.id !== source.expected.packageId || output.expected.package.manifest.rawSha256 !== source.expected.manifestRawSha256 || output.expected.package.manifest.canonicalSha256 !== source.expected.manifestCanonicalSha256) bad("action binding action/package identity"); return checked(record, PREFIX.binding, { schema: record.schema, identity: readIdentity(record.identity, "Action binding identity"), root: readIdentity(record.root, "Action binding root"), intent: readRef(record.intent, PREFIX.intent), plan, source, output, receiptFingerprint, outputHandle }) as RelationActionBinding; }
function readDetach(value: unknown): RelationActionDetach { const record = exact(value, ["schema", "id", "sha256", "identity", "root", "binding"], "Action detach"); if (record.schema !== "shellx-motion/private-checkpoint-storyboard-relation-action-resolution-detach@1") bad("action detach schema"); return checked(record, PREFIX.detach, { schema: record.schema, identity: readIdentity(record.identity, "Action detach identity"), root: readIdentity(record.root, "Action detach root"), binding: readRef(record.binding, PREFIX.binding) }) as RelationActionDetach; }
function readAbandon(value: unknown): RelationActionAbandon { const record = exact(value, ["schema", "id", "sha256", "identity", "root", "intent", "reason"], "Action abandon"), reason = record.reason; if (record.schema !== "shellx-motion/private-checkpoint-storyboard-relation-action-resolution-abandon@1" || (reason !== "proven-no-install" && reason !== "no-cow-start")) bad("action abandonment"); return checked(record, PREFIX.abandon, { schema: record.schema, identity: readIdentity(record.identity, "Action abandon identity"), root: readIdentity(record.root, "Action abandon root"), intent: readRef(record.intent, PREFIX.intent), reason }) as RelationActionAbandon; }
function readHead(value: unknown): RelationActionStateHead { const record = exact(value, ["schema", "identity", "root", "state", "active"], ["intent", "cowStart", "binding", "detach", "abandon"], "Action state"), state = record.state; if (record.schema !== "shellx-motion/private-checkpoint-storyboard-relation-action-resolution-state@1" || (state !== "unbound" && state !== "preparing" && state !== "bound" && state !== "detached" && state !== "abandoned") || (record.active !== 0 && record.active !== 1)) bad("action state schema"); const read = (key: "intent" | "cowStart" | "binding" | "detach" | "abandon", prefix: string) => Object.hasOwn(record, key) ? readRef(record[key], prefix) : undefined; return Object.freeze({ schema: record.schema, identity: readIdentity(record.identity, "Action state identity"), root: readIdentity(record.root, "Action state root"), state, active: record.active, ...(read("intent", PREFIX.intent) ? { intent: read("intent", PREFIX.intent) } : {}), ...(read("cowStart", PREFIX.cowStart) ? { cowStart: read("cowStart", PREFIX.cowStart) } : {}), ...(read("binding", PREFIX.binding) ? { binding: read("binding", PREFIX.binding) } : {}), ...(read("detach", PREFIX.detach) ? { detach: read("detach", PREFIX.detach) } : {}), ...(read("abandon", PREFIX.abandon) ? { abandon: read("abandon", PREFIX.abandon) } : {}) }); }
function checked(record: Record<string, unknown>, prefix: string, payload: object): object { const id = str(record.id, "Action journal id"), sha256 = str(record.sha256, "Action journal hash"), expected = createHash("sha256").update(canonicalJson(payload)).digest("hex"); if (!SHA256.test(sha256) || sha256 !== expected || id !== `${prefix}${sha256.slice(0, 32)}`) bad("action journal deterministic identity"); return Object.freeze({ ...payload, id, sha256 }); }
function readPlan(value: unknown): RelationActionPlanIdentity { const record = exact(value, ["planFingerprint", "profileFingerprint", "actionStoreSchema", "actionStoreSha256", "actionDefinitionId", "actionDefinitionSha256", "actionRequestInstanceId", "actionRequestSha256", "actionApplyPlanFingerprint", "actionObjects", "actionRelations", "actionKeyframeWrites", "actionChangedPath", "actionOutputCanonicalMotionSha256", "relationId", "storeSha256", "staticFingerprint", "gpuStaticFingerprint", "startFramePlanFingerprint", "endFramePlanFingerprint"], "Action plan"); const hashes = ["planFingerprint", "profileFingerprint", "actionStoreSha256", "actionDefinitionSha256", "actionRequestSha256", "actionApplyPlanFingerprint", "actionOutputCanonicalMotionSha256", "storeSha256", "staticFingerprint", "gpuStaticFingerprint", "startFramePlanFingerprint", "endFramePlanFingerprint"] as const; if (record.actionStoreSchema !== "shellx-motion/relation-actions@2" || !hashes.every((key) => hash(record[key])) || !id(record.actionDefinitionId) || !id(record.actionRequestInstanceId) || !id(record.relationId) || record.actionObjects !== 0 || record.actionRelations !== 1 || record.actionKeyframeWrites !== 0 || record.actionChangedPath !== `/relations/bindings/${record.relationId}`) bad("action plan"); return frozen({ ...record }) as RelationActionPlanIdentity; }
function readBase(value: unknown, label: string): C6B4bExactBase { const record = exact(value, ["packageId", "manifestRawSha256", "motionRawSha256", "manifestCanonicalSha256", "motionCanonicalSha256", "inventory", "planFingerprint", "profileFingerprint", "actionStoreSchema", "actionStoreSha256", "actionDefinitionId", "actionDefinitionSha256", "actionRequestInstanceId", "actionRequestSha256", "actionApplyPlanFingerprint", "actionObjects", "actionRelations", "actionKeyframeWrites", "actionChangedPath", "actionOutputCanonicalMotionSha256", "relationId", "storeSha256", "staticFingerprint", "gpuStaticFingerprint", "startFramePlanFingerprint", "endFramePlanFingerprint"], label); if (!id(record.packageId)) bad(`${label}.packageId`); const plan = readPlan(Object.fromEntries(Object.entries(record).filter(([key]) => !["packageId", "manifestRawSha256", "motionRawSha256", "manifestCanonicalSha256", "motionCanonicalSha256", "inventory"].includes(key)))); if (![record.manifestRawSha256, record.motionRawSha256, record.manifestCanonicalSha256, record.motionCanonicalSha256].every(hash)) bad(`${label}.hashes`); const inventory = readInventory(record.inventory, `${label}.inventory`); return frozen({ packageId: record.packageId, manifestRawSha256: record.manifestRawSha256, motionRawSha256: record.motionRawSha256, manifestCanonicalSha256: record.manifestCanonicalSha256, motionCanonicalSha256: record.motionCanonicalSha256, inventory, ...plan }) as C6B4bExactBase; }
function basePair(value: unknown, label: string): RelationActionBinding["source"] { const record = exact(value, ["expected", "reopened"], label), expected = readBase(record.expected, `${label}.expected`), reopened = readBase(record.reopened, `${label}.reopened`); if (canonicalJson(expected) !== canonicalJson(reopened)) bad(`${label} reopened base`); return Object.freeze({ expected, reopened }); }
function outputPair(value: unknown, label: string): RelationActionBinding["output"] { const record = exact(value, ["expected", "reopened"], label), expected = readOutput(record.expected, `${label}.expected`), reopened = readOutput(record.reopened, `${label}.reopened`); if (canonicalJson(expected) !== canonicalJson(reopened)) bad(`${label} reopened output`); return Object.freeze({ expected, reopened }); }
function readOutput(value: unknown, label: string): RelationActionOutputIdentity {
  if (forbidden(value)) bad(`${label} host authority field`);
  const root = exact(value, ["schema", "receipt", "package", "storyboard", "plan", "profile", "relationAction", "relationStore", "relationStatic", "gpuRelationStatic", "endpointFramePlans", "materialization"], label);
  const receipt = exact(root.receipt, ["schema", "fingerprint"], `${label}.receipt`), pkg = exact(root.package, ["id", "manifest", "motion", "currentInventory", "nonReceiptInventory", "preservedLeaves"], `${label}.package`), storyboard = exact(root.storyboard, ["id", "sha256", "revision"], `${label}.storyboard`), plan = exact(root.plan, ["fingerprint"], `${label}.plan`), profile = exact(root.profile, ["fingerprint"], `${label}.profile`), action = exact(root.relationAction, ["store", "definition", "request", "apply"], `${label}.action`), store = exact(root.relationStore, ["schema", "sha256", "bindings"], `${label}.store`), relationStatic = exact(root.relationStatic, ["fingerprint"], `${label}.relationStatic`), gpu = exact(root.gpuRelationStatic, ["fingerprint", "relationStaticFingerprint"], `${label}.gpu`), endpoints = exact(root.endpointFramePlans, ["startFingerprint", "endFingerprint"], `${label}.endpoints`), materialization = exact(root.materialization, ["changedMotionRoot", "changedLeafCount", "renderer"], `${label}.materialization`), renderer = exact(materialization.renderer, ["invoked", "pixels"], `${label}.renderer`);
  const manifest = exact(pkg.manifest, ["rawSha256", "canonicalSha256"], `${label}.manifest`), motion = exact(pkg.motion, ["rawSha256", "canonicalSha256"], `${label}.motion`), actionStore = exact(action.store, ["schema", "sha256"], `${label}.action.store`), definition = exact(action.definition, ["id", "sha256"], `${label}.action.definition`), request = exact(action.request, ["instanceId", "sha256"], `${label}.action.request`), apply = exact(action.apply, ["planFingerprint", "objectCount", "relationCount", "keyframeWriteCount", "changedPath", "outputCanonicalMotionSha256"], `${label}.action.apply`), preserved = exact(pkg.preservedLeaves, ["sha256", "count"], `${label}.preserved`), currentInventory = readInventory(pkg.currentInventory, `${label}.currentInventory`), nonReceiptInventory = readInventory(pkg.nonReceiptInventory, `${label}.nonReceiptInventory`);
  if (root.schema !== "shellx-motion/private-checkpoint-storyboard-relation-action-materialization-installed-output@1" || receipt.schema !== "shellx-motion/private-checkpoint-storyboard-relation-action-materialization-receipt@1" || !hash(receipt.fingerprint) || !id(pkg.id) || ![manifest.rawSha256, manifest.canonicalSha256, motion.rawSha256, motion.canonicalSha256, storyboard.sha256, plan.fingerprint, profile.fingerprint, actionStore.sha256, definition.sha256, request.sha256, apply.planFingerprint, apply.outputCanonicalMotionSha256, store.sha256, relationStatic.fingerprint, gpu.fingerprint, gpu.relationStaticFingerprint, endpoints.startFingerprint, endpoints.endFingerprint, preserved.sha256].every(hash) || !/^checkpoint_storyboard_[a-f0-9]{32}$/u.test(String(storyboard.id)) || !count(storyboard.revision, 1_000_000) || actionStore.schema !== "shellx-motion/relation-actions@2" || !id(definition.id) || !id(request.instanceId) || apply.objectCount !== 0 || apply.relationCount !== 1 || apply.keyframeWriteCount !== 0 || store.schema !== "shellx-motion/relations@1" || !Array.isArray(store.bindings) || store.bindings.length !== 1 || gpu.relationStaticFingerprint !== relationStatic.fingerprint || !count(preserved.count, 1024) || currentInventory.entryCount !== nonReceiptInventory.entryCount + 1 || currentInventory.leafCount !== nonReceiptInventory.leafCount + 1 || materialization.changedMotionRoot !== "relations" || materialization.changedLeafCount !== 2 || renderer.invoked !== false || renderer.pixels !== false) bad(`${label} static output facts`);
  const binding = store.bindings[0] as unknown, source = field(binding, "source", label), target = field(binding, "target", label), durationUs = numberField(binding, "durationUs", label), sourceId = stringField(source, "layerId", label), targetId = stringField(target, "layerId", label);
  if (durationUs <= 0 || durationUs > 3_600_000_000 || durationUs % 1_000 !== 0 || sourceId === targetId) bad(`${label} relation endpoints`);
  const validated = validateMotionRelations({ schema: "shellx-motion/relations@1", bindings: structuredClone(store.bindings as object[]) }, { durationMs: durationUs / 1_000, layers: [{ id: sourceId, type: "shape", transform: { x: 0, y: 0, rotation: 0, scale: 1 } }, { id: targetId, type: "shape", transform: { x: 0, y: 0, rotation: 0, scale: 1 } }] });
  const installed = validated.ok && validated.store?.bindings[0], resolved = validated.ok && validated.bindings[0];
  if (!installed || !resolved || canonicalJsonSha256(validated.store) !== store.sha256 || installed.id !== String(apply.changedPath).slice("/relations/bindings/".length) || apply.changedPath !== `/relations/bindings/${installed.id}` || installed.enabled !== true || installed.kind !== "attach" || installed.mode !== "follow" || installed.offset.space !== "world" || installed.offset.rotationDeg !== 0 || installed.offset.scale !== 1 || installed.startUs !== 0 || installed.durationUs !== durationUs || resolved.binding.target.layerId !== installed.target.layerId || resolved.writeMask.length !== 2 || resolved.writeMask[0] !== "transform.x" || resolved.writeMask[1] !== "transform.y") bad(`${label} closed action relation`);
  return frozen({ schema: root.schema, receipt: { schema: receipt.schema, fingerprint: receipt.fingerprint }, package: { id: pkg.id, manifest: { rawSha256: manifest.rawSha256, canonicalSha256: manifest.canonicalSha256 }, motion: { rawSha256: motion.rawSha256, canonicalSha256: motion.canonicalSha256 }, currentInventory, nonReceiptInventory, preservedLeaves: { sha256: preserved.sha256, count: preserved.count } }, storyboard: { id: storyboard.id, sha256: storyboard.sha256, revision: storyboard.revision }, plan: { fingerprint: plan.fingerprint }, profile: { fingerprint: profile.fingerprint }, relationAction: { store: { schema: actionStore.schema, sha256: actionStore.sha256 }, definition: { id: definition.id, sha256: definition.sha256 }, request: { instanceId: request.instanceId, sha256: request.sha256 }, apply: { planFingerprint: apply.planFingerprint, objectCount: 0, relationCount: 1, keyframeWriteCount: 0, changedPath: apply.changedPath, outputCanonicalMotionSha256: apply.outputCanonicalMotionSha256 } }, relationStore: { schema: store.schema, sha256: store.sha256, bindings: structuredClone(validated.store!.bindings) }, relationStatic: { fingerprint: relationStatic.fingerprint }, gpuRelationStatic: { fingerprint: gpu.fingerprint, relationStaticFingerprint: gpu.relationStaticFingerprint }, endpointFramePlans: { startFingerprint: endpoints.startFingerprint, endFingerprint: endpoints.endFingerprint }, materialization: { changedMotionRoot: "relations", changedLeafCount: 2, renderer: { invoked: false, pixels: false } } }) as RelationActionOutputIdentity;
}
function samePlan(plan: RelationActionPlanIdentity, value: C6B4bExactBase | RelationActionOutputIdentity): boolean { if ("planFingerprint" in value) return canonicalJson(plan) === canonicalJson({ planFingerprint: value.planFingerprint, profileFingerprint: value.profileFingerprint, actionStoreSchema: value.actionStoreSchema, actionStoreSha256: value.actionStoreSha256, actionDefinitionId: value.actionDefinitionId, actionDefinitionSha256: value.actionDefinitionSha256, actionRequestInstanceId: value.actionRequestInstanceId, actionRequestSha256: value.actionRequestSha256, actionApplyPlanFingerprint: value.actionApplyPlanFingerprint, actionObjects: value.actionObjects, actionRelations: value.actionRelations, actionKeyframeWrites: value.actionKeyframeWrites, actionChangedPath: value.actionChangedPath, actionOutputCanonicalMotionSha256: value.actionOutputCanonicalMotionSha256, relationId: value.relationId, storeSha256: value.storeSha256, staticFingerprint: value.staticFingerprint, gpuStaticFingerprint: value.gpuStaticFingerprint, startFramePlanFingerprint: value.startFramePlanFingerprint, endFramePlanFingerprint: value.endFramePlanFingerprint }); return plan.planFingerprint === value.plan.fingerprint && plan.profileFingerprint === value.profile.fingerprint && plan.actionStoreSchema === value.relationAction.store.schema && plan.actionStoreSha256 === value.relationAction.store.sha256 && plan.actionDefinitionId === value.relationAction.definition.id && plan.actionDefinitionSha256 === value.relationAction.definition.sha256 && plan.actionRequestInstanceId === value.relationAction.request.instanceId && plan.actionRequestSha256 === value.relationAction.request.sha256 && plan.actionApplyPlanFingerprint === value.relationAction.apply.planFingerprint && plan.actionObjects === value.relationAction.apply.objectCount && plan.actionRelations === value.relationAction.apply.relationCount && plan.actionKeyframeWrites === value.relationAction.apply.keyframeWriteCount && plan.actionChangedPath === value.relationAction.apply.changedPath && plan.actionOutputCanonicalMotionSha256 === value.relationAction.apply.outputCanonicalMotionSha256 && plan.relationId === value.relationAction.apply.changedPath.slice("/relations/bindings/".length) && plan.storeSha256 === value.relationStore.sha256 && plan.staticFingerprint === value.relationStatic.fingerprint && plan.gpuStaticFingerprint === value.gpuRelationStatic.fingerprint && plan.startFramePlanFingerprint === value.endpointFramePlans.startFingerprint && plan.endFramePlanFingerprint === value.endpointFramePlans.endFingerprint; }
function forbidden(value: unknown): boolean { if (Array.isArray(value)) return value.some(forbidden); if (!value || typeof value !== "object") return false; return Object.entries(value).some(([key, child]) => (key !== "changedPath" && /(?:path|workspace|approval|authority)/iu.test(key)) || forbidden(child)); }
function field(value: unknown, key: string, label: string): Record<string, unknown> { if (!value || typeof value !== "object" || Array.isArray(value) || !Object.hasOwn(value, key)) bad(`${label} object field`); const child = (value as Record<string, unknown>)[key]; if (!child || typeof child !== "object" || Array.isArray(child)) bad(`${label} object field`); return child as Record<string, unknown>; }
function stringField(value: Record<string, unknown>, key: string, label: string): string { const candidate = value[key]; if (typeof candidate !== "string") bad(`${label} string field`); return candidate; }
function numberField(value: unknown, key: string, label: string): number { if (!value || typeof value !== "object" || Array.isArray(value) || !Number.isSafeInteger((value as Record<string, unknown>)[key])) bad(`${label} number field`); return (value as Record<string, number>)[key]!; }
function readInventory(value: unknown, label: string): { readonly sha256: string; readonly entryCount: number; readonly leafCount: number } { const record = exact(value, ["sha256", "entryCount", "leafCount"], label); if (!hash(record.sha256) || !count(record.entryCount, 2048) || !count(record.leafCount, 1024)) bad(`${label} inventory`); return Object.freeze({ sha256: record.sha256, entryCount: record.entryCount, leafCount: record.leafCount }); }
function readRef(value: unknown, prefix: string): Ref { const record = exact(value, ["id", "sha256"], "Action journal reference"), idValue = str(record.id, "Action ref id"), sha256 = str(record.sha256, "Action ref hash"); if (!SHA256.test(sha256) || idValue !== `${prefix}${sha256.slice(0, 32)}`) bad("action journal reference"); return Object.freeze({ id: idValue, sha256 }); }
function hash(value: unknown): value is string { return typeof value === "string" && SHA256.test(value); }
function id(value: unknown): value is string { return typeof value === "string" && /^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$/u.test(value); }
function count(value: unknown, max: number): value is number { return typeof value === "number" && Number.isSafeInteger(value) && value >= 1 && value <= max; }
function str(value: unknown, label: string): string { if (typeof value !== "string") bad(label); return value; }
function frozen<T>(value: T): T { if (value && typeof value === "object" && !Object.isFrozen(value)) { for (const child of Object.values(value as object)) frozen(child); Object.freeze(value); } return value; }
function bad(label: string): never { throw storeError("store_integrity_failed", `Checkpoint storyboard relation-action journal ${label} is invalid.`); }
