/** Signed append-only C6C B6 geometry-morph-resolution journal. B6b receipts remain diagnostic only. */
import { createHash } from "node:crypto";
import { opendir } from "node:fs/promises";
import { join } from "node:path";
import { canonicalJson } from "@shellx-motion/core";
import { readC6B6bExactBase, type C6B6bExactBase } from "./checkpoint-storyboard-geometry-morph-materialize-private/checkpoint-storyboard-geometry-morph-materialize-receipt-private.js";
import type { CheckpointStoryboardGeometryMorphMaterializationInstalledOutput } from "./checkpoint-storyboard-geometry-morph-materialize-private/checkpoint-storyboard-geometry-morph-materialize-output-private.js";
import { readSignedFile, replaceSignedFile, syncPrivateDirectory, writeExclusiveSignedFile } from "./checkpoint-storyboard-record-store-signed-files.js";
import { readLineageMembers } from "./checkpoint-storyboard-materialization-bindings.js";
import { readStoredRecordUnlocked } from "./checkpoint-storyboard-record-store-state.js";
import { MAX_STATE_BYTES, SHA256, exact, readIdentity, sameIdentity, storeError, type AuthorityFacts, type CheckpointStoryboardRecordIdentity } from "./checkpoint-storyboard-record-store-types.js";

const MAX_JOURNAL_BYTES = 192 * 1024;
const HANDLE = /^checkpoint_storyboard_geometry_morph_output_[a-f0-9]{32}$/u;
const FILE = /^checkpoint_storyboard_[a-f0-9]{32}\.(?:state|intent|binding|cow-start|detach|abandon)\.json$/u;
const PREFIX = { intent: "checkpoint_storyboard_geometry_morph_resolution_intent_", cowStart: "checkpoint_storyboard_geometry_morph_resolution_cow_start_", binding: "checkpoint_storyboard_geometry_morph_resolution_binding_", detach: "checkpoint_storyboard_geometry_morph_resolution_detach_", abandon: "checkpoint_storyboard_geometry_morph_resolution_abandon_" } as const;
type Ref = Readonly<{ id: string; sha256: string }>;

export type CheckpointStoryboardGeometryMorphResolutionState = "unbound" | "preparing" | "bound" | "detached" | "abandoned";
export type GeometryMorphPlanIdentity = Readonly<{
  planFingerprint: string; profileFingerprint: string; storyboardId: string; storyboardSha256: string; storyboardRevision: number;
  sourceLayerId: string; sourceLayerIndex: 0; staticGeometrySha256: string; sourceGeometryKeyframes: "absent";
  materializedGeometryKeyframesSha256: string; endpointSequenceSha256: string; topologySha256: string; areaProofSha256: string; outputCanonicalMotionSha256: string;
}>;
export type GeometryMorphOutputIdentity = CheckpointStoryboardGeometryMorphMaterializationInstalledOutput;
export type GeometryMorphIntent = Readonly<{ schema: "shellx-motion/private-checkpoint-storyboard-geometry-morph-resolution-intent@1"; id: string; sha256: string; identity: CheckpointStoryboardRecordIdentity; root: CheckpointStoryboardRecordIdentity; plan: GeometryMorphPlanIdentity; expectedBase: C6B6bExactBase; outputHandle: string }>;
export type GeometryMorphCowStart = Readonly<{ schema: "shellx-motion/private-checkpoint-storyboard-geometry-morph-resolution-cow-start@1"; id: string; sha256: string; identity: CheckpointStoryboardRecordIdentity; root: CheckpointStoryboardRecordIdentity; intent: Ref }>;
export type GeometryMorphBinding = Readonly<{ schema: "shellx-motion/private-checkpoint-storyboard-geometry-morph-resolution-binding@1"; id: string; sha256: string; identity: CheckpointStoryboardRecordIdentity; root: CheckpointStoryboardRecordIdentity; intent: Ref; plan: GeometryMorphPlanIdentity; source: Readonly<{ expected: C6B6bExactBase; reopened: C6B6bExactBase }>; output: Readonly<{ expected: GeometryMorphOutputIdentity; reopened: GeometryMorphOutputIdentity }>; receiptFingerprint: string; outputHandle: string }>;
export type GeometryMorphDetach = Readonly<{ schema: "shellx-motion/private-checkpoint-storyboard-geometry-morph-resolution-detach@1"; id: string; sha256: string; identity: CheckpointStoryboardRecordIdentity; root: CheckpointStoryboardRecordIdentity; binding: Ref }>;
export type GeometryMorphAbandon = Readonly<{ schema: "shellx-motion/private-checkpoint-storyboard-geometry-morph-resolution-abandon@1"; id: string; sha256: string; identity: CheckpointStoryboardRecordIdentity; root: CheckpointStoryboardRecordIdentity; intent: Ref; reason: "proven-no-install" | "no-cow-start" }>;
export type GeometryMorphStateHead = Readonly<{ schema: "shellx-motion/private-checkpoint-storyboard-geometry-morph-resolution-state@1"; identity: CheckpointStoryboardRecordIdentity; root: CheckpointStoryboardRecordIdentity; state: CheckpointStoryboardGeometryMorphResolutionState; active: 0 | 1; intent?: Ref; cowStart?: Ref; binding?: Ref; detach?: Ref; abandon?: Ref }>;
export type GeometryMorphResolutionBindingState = Readonly<{ state: CheckpointStoryboardGeometryMorphResolutionState; active: 0 | 1; bindingId?: string; outputHandle?: string; receiptFingerprint?: string }>;

export function createGeometryMorphIntent(input: Omit<GeometryMorphIntent, "schema" | "id" | "sha256">): GeometryMorphIntent { return seal("intent", "shellx-motion/private-checkpoint-storyboard-geometry-morph-resolution-intent@1", input); }
export function createGeometryMorphCowStart(input: Omit<GeometryMorphCowStart, "schema" | "id" | "sha256">): GeometryMorphCowStart { return seal("cowStart", "shellx-motion/private-checkpoint-storyboard-geometry-morph-resolution-cow-start@1", input); }
export function createGeometryMorphBinding(input: Omit<GeometryMorphBinding, "schema" | "id" | "sha256">): GeometryMorphBinding { return seal("binding", "shellx-motion/private-checkpoint-storyboard-geometry-morph-resolution-binding@1", input); }
export function createGeometryMorphDetach(input: Omit<GeometryMorphDetach, "schema" | "id" | "sha256">): GeometryMorphDetach { return seal("detach", "shellx-motion/private-checkpoint-storyboard-geometry-morph-resolution-detach@1", input); }
export function createGeometryMorphAbandon(input: Omit<GeometryMorphAbandon, "schema" | "id" | "sha256">): GeometryMorphAbandon { return seal("abandon", "shellx-motion/private-checkpoint-storyboard-geometry-morph-resolution-abandon@1", input); }
export function geometryMorphStateHead(identity: CheckpointStoryboardRecordIdentity, root: CheckpointStoryboardRecordIdentity, state: CheckpointStoryboardGeometryMorphResolutionState, active: 0 | 1, refs: Partial<Pick<GeometryMorphStateHead, "intent" | "cowStart" | "binding" | "detach" | "abandon">> = {}): GeometryMorphStateHead { return Object.freeze({ schema: "shellx-motion/private-checkpoint-storyboard-geometry-morph-resolution-state@1", identity, root, state, active, ...refs }); }
export async function initializeGeometryMorphStateHead(facts: AuthorityFacts, identity: CheckpointStoryboardRecordIdentity, root: CheckpointStoryboardRecordIdentity): Promise<void> { await publishExact(statePath(facts, identity), geometryMorphStateHead(identity, root, "unbound", 0), facts); }
export async function publishGeometryMorphIntent(facts: AuthorityFacts, value: GeometryMorphIntent): Promise<void> { await publishExact(path(facts, value.identity, "intent"), value, facts); }
export async function publishGeometryMorphCowStart(facts: AuthorityFacts, value: GeometryMorphCowStart): Promise<void> { await publishExact(path(facts, value.identity, "cow-start"), value, facts); }
export async function publishGeometryMorphBinding(facts: AuthorityFacts, value: GeometryMorphBinding): Promise<void> { await publishExact(path(facts, value.identity, "binding"), value, facts); }
export async function publishGeometryMorphDetach(facts: AuthorityFacts, value: GeometryMorphDetach): Promise<void> { await publishExact(path(facts, value.identity, "detach"), value, facts); }
export async function publishGeometryMorphAbandon(facts: AuthorityFacts, value: GeometryMorphAbandon): Promise<void> { await publishExact(path(facts, value.identity, "abandon"), value, facts); }
export async function publishGeometryMorphStateHead(facts: AuthorityFacts, value: GeometryMorphStateHead, afterRename?: () => void | Promise<void>): Promise<void> { await replaceSignedFile(statePath(facts, value.identity), value, facts, MAX_STATE_BYTES, afterRename); }
export async function readGeometryMorphIntent(facts: AuthorityFacts, identity: CheckpointStoryboardRecordIdentity): Promise<GeometryMorphIntent | null> { return await optional(path(facts, identity, "intent"), facts, readIntent); }
export async function readGeometryMorphCowStart(facts: AuthorityFacts, identity: CheckpointStoryboardRecordIdentity): Promise<GeometryMorphCowStart | null> { return await optional(path(facts, identity, "cow-start"), facts, readStart); }
export async function readGeometryMorphBinding(facts: AuthorityFacts, identity: CheckpointStoryboardRecordIdentity): Promise<GeometryMorphBinding | null> { return await optional(path(facts, identity, "binding"), facts, readBinding); }
export async function readGeometryMorphStateHead(facts: AuthorityFacts, identityId: string): Promise<GeometryMorphStateHead | null> { if (!/^checkpoint_storyboard_[a-f0-9]{32}$/u.test(identityId)) throw storeError("store_integrity_failed", "Checkpoint storyboard geometry-morph state filename identity is invalid."); return await optional(join(facts.geometryMorphResolutions.path, `${identityId}.state.json`), facts, readHead); }
export async function assertNoGeometryMorphResolutionEvidence(facts: AuthorityFacts, identity: CheckpointStoryboardRecordIdentity): Promise<void> { if (await readGeometryMorphStateHead(facts, identity.id) || await readGeometryMorphIntent(facts, identity) || await readGeometryMorphCowStart(facts, identity) || await readGeometryMorphBinding(facts, identity) || await optional(path(facts, identity, "detach"), facts, readDetach) || await optional(path(facts, identity, "abandon"), facts, readAbandon)) throw storeError("store_integrity_failed", "Checkpoint storyboard non-geometry-morph record has forbidden C6B6 resolution evidence."); }

/** Reads all signed phases. Forward head repair is legal only while a resolver holds the lineage lock. */
export async function readGeometryMorphResolutionState(facts: AuthorityFacts, identity: CheckpointStoryboardRecordIdentity, root: CheckpointStoryboardRecordIdentity, options: { readonly requireHead?: boolean; readonly allowForwardRecovery?: boolean } = {}): Promise<GeometryMorphResolutionBindingState> {
  await syncGeometryMorphDirectory(facts); const repair = options.allowForwardRecovery ?? false;
  const head = await optional(statePath(facts, identity), facts, readHead), intent = await readGeometryMorphIntent(facts, identity), start = await readGeometryMorphCowStart(facts, identity), binding = await readGeometryMorphBinding(facts, identity), detach = await optional(path(facts, identity, "detach"), facts, readDetach), abandon = await optional(path(facts, identity, "abandon"), facts, readAbandon);
  if (!head) {
    if (!options.requireHead && !intent && !start && !binding && !detach && !abandon) return Object.freeze({ state: "unbound" as const, active: 0 as const });
    if (intent && !start && !binding && !detach && !abandon && repair) { const next = geometryMorphStateHead(identity, root, "preparing", 0, { intent: ref(intent) }); await publishGeometryMorphStateHead(facts, next); return await reopenPromoted(facts, identity, root, next, Object.freeze({ state: "preparing" as const, active: 0 as const, outputHandle: intent.outputHandle })); }
    throw storeError(intent ? "record_commit_uncertain" : "store_integrity_failed", "Checkpoint storyboard geometry-morph resolution is missing its required signed state head.");
  }
  if (!sameIdentity(head.identity, identity) || !sameIdentity(head.root, root)) throw storeError("store_integrity_failed", "Checkpoint storyboard geometry-morph state head does not bind this record lineage.");
  if (!intent) { if (start || binding || detach || abandon) throw storeError("store_integrity_failed", "Checkpoint storyboard geometry-morph unbound state has phase evidence."); return await checkedHead(facts, head, Object.freeze({ state: "unbound" as const, active: 0 as const }), repair); }
  if (!sameIdentity(intent.identity, identity) || !sameIdentity(intent.root, root)) throw storeError("store_integrity_failed", "Checkpoint storyboard geometry-morph intent does not bind this record lineage.");
  if (!binding) {
    if (detach) throw storeError("store_integrity_failed", "Checkpoint storyboard geometry-morph detach has no immutable binding.");
    if (start && (!sameIdentity(start.identity, identity) || !sameIdentity(start.root, root) || !sameRef(start.intent, intent))) throw storeError("store_integrity_failed", "Checkpoint storyboard geometry-morph COW start does not bind intent.");
    if (abandon) { if (!sameIdentity(abandon.identity, identity) || !sameIdentity(abandon.root, root) || !sameRef(abandon.intent, intent) || (abandon.reason === "no-cow-start" && start) || (abandon.reason === "proven-no-install" && !start)) throw storeError("store_integrity_failed", "Checkpoint storyboard geometry-morph abandonment is inconsistent."); return await checkedHead(facts, head, Object.freeze({ state: "abandoned" as const, active: 0 as const, outputHandle: intent.outputHandle }), repair, intent, start ?? undefined, undefined, undefined, abandon); }
    return await checkedHead(facts, head, Object.freeze({ state: "preparing" as const, active: 0 as const, outputHandle: intent.outputHandle }), repair, intent, start ?? undefined);
  }
  if (!start || abandon || !sameIdentity(binding.identity, identity) || !sameIdentity(binding.root, root) || !sameRef(binding.intent, intent) || binding.outputHandle !== intent.outputHandle || !samePlan(binding.plan, intent.expectedBase) || !samePlan(binding.plan, binding.output.expected) || canonicalJson(binding.plan) !== canonicalJson(intent.plan) || canonicalJson(binding.source.expected) !== canonicalJson(intent.expectedBase) || !sameIdentity(binding.output.expected.storyboard, identity) || !sameIdentity(binding.output.reopened.storyboard, identity) || !sameIdentity(start.identity, identity) || !sameIdentity(start.root, root) || !sameRef(start.intent, intent)) throw storeError("store_integrity_failed", "Checkpoint storyboard geometry-morph binding does not semantically bind intent, geometry facts, identity, and COW start.");
  if (!detach) return await checkedHead(facts, head, Object.freeze({ state: "bound" as const, active: 1 as const, bindingId: binding.id, outputHandle: binding.outputHandle, receiptFingerprint: binding.receiptFingerprint }), repair, intent, start, binding);
  if (!sameIdentity(detach.identity, identity) || !sameIdentity(detach.root, root) || !sameRef(detach.binding, binding)) throw storeError("store_integrity_failed", "Checkpoint storyboard geometry-morph detach does not bind immutable binding.");
  return await checkedHead(facts, head, Object.freeze({ state: "detached" as const, active: 0 as const, bindingId: binding.id, outputHandle: binding.outputHandle, receiptFingerprint: binding.receiptFingerprint }), repair, intent, start, binding, detach);
}
export async function assertLineageHasNoPreparingOrBoundGeometryMorphResolutions(facts: AuthorityFacts, root: CheckpointStoryboardRecordIdentity, requireHeadsFor = new Set<string>()): Promise<void> { const members = await readLineageMembers(facts, root); if (!members.length) throw storeError("store_integrity_failed", "Checkpoint storyboard lineage has no signed membership records."); for (const member of members) { if (!sameIdentity(member.root, root)) throw storeError("store_integrity_failed", "Checkpoint storyboard lineage membership root changed."); const state = await readGeometryMorphResolutionState(facts, member.identity, root, { requireHead: requireHeadsFor.has(member.identity.id) }); if (state.state === "preparing" || state.state === "bound") throw storeError("materialization_binding_conflict", "Checkpoint storyboard remove/archive requires every geometry-morph-resolution member to be unbound or detached."); } }
/** Archive scans the complete B6 namespace so copied/foreign/hidden phase leaves cannot be hidden. */
export async function assertGeometryMorphResolutionJournalCompleteForLineage(facts: AuthorityFacts, root: CheckpointStoryboardRecordIdentity, requireHeadsFor = new Set<string>()): Promise<void> {
  const members = await readLineageMembers(facts, root), byId = new Map(members.map((member) => [member.identity.id, member.identity])), reader = await opendir(facts.geometryMorphResolutions.path);
  try { for await (const entry of reader) { if (!entry.isFile() || !FILE.test(entry.name)) throw storeError("store_integrity_failed", "Checkpoint storyboard geometry-morph journal contains an invalid entry."); const identityId = entry.name.slice(0, 54), identity = byId.get(identityId), head = await readGeometryMorphStateHead(facts, identityId); if (!head) throw storeError("store_integrity_failed", "Checkpoint storyboard geometry-morph journal state head is missing."); if (head.identity.id !== identityId) throw storeError("store_integrity_failed", "Checkpoint storyboard geometry-morph filename does not match signed identity."); if (identity) { if (!requireHeadsFor.has(identity.id) || !sameIdentity(head.root, root) || !sameIdentity(head.identity, identity)) throw storeError("store_integrity_failed", "Checkpoint storyboard geometry-morph journal attaches to a sealed non-B6 lineage member."); } else { const foreign = (await readLineageMembers(facts, head.root)).find((member) => sameIdentity(member.identity, head.identity)); if (!foreign || !sameIdentity(foreign.root, head.root)) throw storeError("store_integrity_failed", "Checkpoint storyboard geometry-morph journal references an unknown lineage member."); const foreignRecord = await readStoredRecordUnlocked(facts, head.identity); if (foreignRecord.admission.profile !== "c6b6-geometry-morph@1") throw storeError("store_integrity_failed", "Checkpoint storyboard geometry-morph journal attaches to a foreign non-B6 member."); await readGeometryMorphResolutionState(facts, head.identity, head.root, { requireHead: true }); } } } finally { await reader.close().catch(() => undefined); }
  for (const member of members) await readGeometryMorphResolutionState(facts, member.identity, root, { requireHead: requireHeadsFor.has(member.identity.id) });
}

function path(facts: AuthorityFacts, identity: CheckpointStoryboardRecordIdentity, kind: "intent" | "cow-start" | "binding" | "detach" | "abandon"): string { return join(facts.geometryMorphResolutions.path, `${identity.id}.${kind}.json`); }
function statePath(facts: AuthorityFacts, identity: CheckpointStoryboardRecordIdentity): string { return join(facts.geometryMorphResolutions.path, `${identity.id}.state.json`); }
async function optional<T>(file: string, facts: AuthorityFacts, read: (value: unknown) => T): Promise<T | null> { try { return read(await readSignedFile(file, facts, MAX_JOURNAL_BYTES, "record_not_found")); } catch (error) { if (error instanceof Error && (error as { code?: string }).code === "record_not_found") return null; throw error; } }
async function syncGeometryMorphDirectory(facts: AuthorityFacts): Promise<void> { try { await syncPrivateDirectory(facts.geometryMorphResolutions.path); } catch { throw storeError("record_commit_uncertain", "Checkpoint storyboard geometry-morph state requires a durable directory resync."); } }
async function checkedHead(facts: AuthorityFacts, head: GeometryMorphStateHead, state: GeometryMorphResolutionBindingState, repair: boolean, intent?: GeometryMorphIntent, cowStart?: GeometryMorphCowStart, binding?: GeometryMorphBinding, detach?: GeometryMorphDetach, abandon?: GeometryMorphAbandon): Promise<GeometryMorphResolutionBindingState> {
  const matches = (actual: Ref | undefined, value: { readonly id: string; readonly sha256: string } | undefined) => value ? sameRef(actual, value) : !actual;
  if (!legalHead(head)) throw storeError("store_integrity_failed", "Checkpoint storyboard geometry-morph state head has invalid phase fields.");
  const exactHead = head.state === state.state && head.active === state.active && matches(head.intent, intent) && matches(head.cowStart, cowStart) && matches(head.binding, binding) && matches(head.detach, detach) && matches(head.abandon, abandon);
  if (exactHead) { await syncGeometryMorphDirectory(facts); return state; }
  if (!repair) throw storeError("record_commit_uncertain", "Checkpoint storyboard geometry-morph phase evidence is one publication ahead of its signed head; read-only inspection will not repair it.");
  const next = geometryMorphStateHead(head.identity, head.root, state.state, state.active, { ...(intent ? { intent: ref(intent) } : {}), ...(cowStart ? { cowStart: ref(cowStart) } : {}), ...(binding ? { binding: ref(binding) } : {}), ...(detach ? { detach: ref(detach) } : {}), ...(abandon ? { abandon: ref(abandon) } : {}) });
  const oneStep = (head.state === "unbound" && state.state === "preparing" && !!intent && !cowStart)
    || (head.state === "preparing" && state.state === "preparing" && !!intent && !!cowStart && matches(head.intent, intent) && !head.cowStart)
    || (head.state === "preparing" && state.state === "bound" && !!intent && !!cowStart && !!binding && matches(head.intent, intent) && matches(head.cowStart, cowStart))
    || (head.state === "preparing" && state.state === "abandoned" && !!intent && !!abandon && matches(head.intent, intent) && matches(head.cowStart, cowStart))
    || (head.state === "bound" && state.state === "detached" && !!intent && !!cowStart && !!binding && !!detach && matches(head.intent, intent) && matches(head.cowStart, cowStart) && matches(head.binding, binding));
  if (!oneStep) throw storeError("store_integrity_failed", "Checkpoint storyboard geometry-morph head skips, diverges from, or rolls back immutable phase evidence.");
  await publishGeometryMorphStateHead(facts, next); return await reopenPromoted(facts, head.identity, head.root, next, state);
}
function legalHead(head: GeometryMorphStateHead): boolean { return (head.state === "unbound" && head.active === 0 && !hasRef(head)) || (head.state === "preparing" && head.active === 0 && !!head.intent && !head.binding && !head.detach && !head.abandon) || (head.state === "bound" && head.active === 1 && !!head.intent && !!head.cowStart && !!head.binding && !head.detach && !head.abandon) || (head.state === "detached" && head.active === 0 && !!head.intent && !!head.cowStart && !!head.binding && !!head.detach && !head.abandon) || (head.state === "abandoned" && head.active === 0 && !!head.intent && !!head.abandon && !head.binding && !head.detach); }
async function reopenPromoted(facts: AuthorityFacts, identity: CheckpointStoryboardRecordIdentity, root: CheckpointStoryboardRecordIdentity, expected: GeometryMorphStateHead, state: GeometryMorphResolutionBindingState): Promise<GeometryMorphResolutionBindingState> { const reopened = await optional(statePath(facts, identity), facts, readHead); if (!reopened || canonicalJson(reopened) !== canonicalJson(expected)) throw storeError("record_commit_uncertain", "Checkpoint storyboard geometry-morph head promotion could not be reopened exactly."); await syncGeometryMorphDirectory(facts); return state; }
async function publishExact(file: string, value: object, facts: AuthorityFacts): Promise<void> { try { await writeExclusiveSignedFile(file, value, facts, MAX_JOURNAL_BYTES); } catch (error) { if (!(error instanceof Error) || (error as { code?: string }).code !== "record_identity_conflict") throw error; const existing = await readSignedFile(file, facts, MAX_JOURNAL_BYTES, "record_not_found"); if (canonicalJson(existing) !== canonicalJson(value)) throw storeError("materialization_binding_conflict", "Checkpoint storyboard immutable geometry-morph journal leaf is occupied by different content."); } }
function seal<K extends keyof typeof PREFIX, S extends string, T extends object>(kind: K, schema: S, payload: T): T & { readonly schema: S; readonly id: string; readonly sha256: string } { const sha256 = createHash("sha256").update(canonicalJson({ schema, ...payload })).digest("hex"); return Object.freeze({ schema, id: `${PREFIX[kind]}${sha256.slice(0, 32)}`, sha256, ...payload }); }
function ref(value: { readonly id: string; readonly sha256: string }): Ref { return Object.freeze({ id: value.id, sha256: value.sha256 }); }
function sameRef(value: Ref | undefined, target: { readonly id: string; readonly sha256: string }): boolean { return !!value && value.id === target.id && value.sha256 === target.sha256; }
function hasRef(head: GeometryMorphStateHead): boolean { return !!(head.intent || head.cowStart || head.binding || head.detach || head.abandon); }
function readIntent(value: unknown): GeometryMorphIntent { const record = exact(value, ["schema", "id", "sha256", "identity", "root", "plan", "expectedBase", "outputHandle"], "Geometry-morph resolution intent"); if (record.schema !== "shellx-motion/private-checkpoint-storyboard-geometry-morph-resolution-intent@1") bad("geometry-morph intent schema"); const identity = readIdentity(record.identity, "Geometry-morph intent identity"), root = readIdentity(record.root, "Geometry-morph intent root"), plan = readPlan(record.plan), expectedBase = readBase(record.expectedBase, "Geometry-morph intent expected base"), outputHandle = str(record.outputHandle, "Geometry-morph intent output handle"); if (!HANDLE.test(outputHandle) || !samePlan(plan, expectedBase)) bad("geometry-morph intent plan"); return checked(record, PREFIX.intent, { schema: record.schema, identity, root, plan, expectedBase, outputHandle }) as GeometryMorphIntent; }
function readStart(value: unknown): GeometryMorphCowStart { const record = exact(value, ["schema", "id", "sha256", "identity", "root", "intent"], "Geometry-morph COW start"); if (record.schema !== "shellx-motion/private-checkpoint-storyboard-geometry-morph-resolution-cow-start@1") bad("geometry-morph COW start schema"); return checked(record, PREFIX.cowStart, { schema: record.schema, identity: readIdentity(record.identity, "Geometry-morph start identity"), root: readIdentity(record.root, "Geometry-morph start root"), intent: readRef(record.intent, PREFIX.intent) }) as GeometryMorphCowStart; }
function readBinding(value: unknown): GeometryMorphBinding { const record = exact(value, ["schema", "id", "sha256", "identity", "root", "intent", "plan", "source", "output", "receiptFingerprint", "outputHandle"], "Geometry-morph binding"); if (record.schema !== "shellx-motion/private-checkpoint-storyboard-geometry-morph-resolution-binding@1") bad("geometry-morph binding schema"); const source = basePair(record.source, "Geometry-morph binding source"), output = outputPair(record.output, "Geometry-morph binding output"), receiptFingerprint = str(record.receiptFingerprint, "Geometry-morph binding receipt"), outputHandle = str(record.outputHandle, "Geometry-morph binding handle"), plan = readPlan(record.plan); if (!SHA256.test(receiptFingerprint) || !HANDLE.test(outputHandle) || receiptFingerprint !== output.expected.receipt.fingerprint || !samePlan(plan, source.expected) || !samePlan(plan, output.expected) || output.expected.package.id !== source.expected.packageId || output.expected.package.manifest.rawSha256 !== source.expected.manifestRawSha256 || output.expected.package.manifest.canonicalSha256 !== source.expected.manifestCanonicalSha256) bad("geometry-morph binding package identity"); return checked(record, PREFIX.binding, { schema: record.schema, identity: readIdentity(record.identity, "Geometry-morph binding identity"), root: readIdentity(record.root, "Geometry-morph binding root"), intent: readRef(record.intent, PREFIX.intent), plan, source, output, receiptFingerprint, outputHandle }) as GeometryMorphBinding; }
function readDetach(value: unknown): GeometryMorphDetach { const record = exact(value, ["schema", "id", "sha256", "identity", "root", "binding"], "Geometry-morph detach"); if (record.schema !== "shellx-motion/private-checkpoint-storyboard-geometry-morph-resolution-detach@1") bad("geometry-morph detach schema"); return checked(record, PREFIX.detach, { schema: record.schema, identity: readIdentity(record.identity, "Geometry-morph detach identity"), root: readIdentity(record.root, "Geometry-morph detach root"), binding: readRef(record.binding, PREFIX.binding) }) as GeometryMorphDetach; }
function readAbandon(value: unknown): GeometryMorphAbandon { const record = exact(value, ["schema", "id", "sha256", "identity", "root", "intent", "reason"], "Geometry-morph abandon"), reason = record.reason; if (record.schema !== "shellx-motion/private-checkpoint-storyboard-geometry-morph-resolution-abandon@1" || (reason !== "proven-no-install" && reason !== "no-cow-start")) bad("geometry-morph abandonment"); return checked(record, PREFIX.abandon, { schema: record.schema, identity: readIdentity(record.identity, "Geometry-morph abandon identity"), root: readIdentity(record.root, "Geometry-morph abandon root"), intent: readRef(record.intent, PREFIX.intent), reason }) as GeometryMorphAbandon; }
function readHead(value: unknown): GeometryMorphStateHead { const record = exact(value, ["schema", "identity", "root", "state", "active"], ["intent", "cowStart", "binding", "detach", "abandon"], "Geometry-morph state"), state = record.state; if (record.schema !== "shellx-motion/private-checkpoint-storyboard-geometry-morph-resolution-state@1" || (state !== "unbound" && state !== "preparing" && state !== "bound" && state !== "detached" && state !== "abandoned") || (record.active !== 0 && record.active !== 1)) bad("geometry-morph state schema"); const read = (key: "intent" | "cowStart" | "binding" | "detach" | "abandon", prefix: string) => Object.hasOwn(record, key) ? readRef(record[key], prefix) : undefined; return Object.freeze({ schema: record.schema, identity: readIdentity(record.identity, "Geometry-morph state identity"), root: readIdentity(record.root, "Geometry-morph state root"), state, active: record.active, ...(read("intent", PREFIX.intent) ? { intent: read("intent", PREFIX.intent) } : {}), ...(read("cowStart", PREFIX.cowStart) ? { cowStart: read("cowStart", PREFIX.cowStart) } : {}), ...(read("binding", PREFIX.binding) ? { binding: read("binding", PREFIX.binding) } : {}), ...(read("detach", PREFIX.detach) ? { detach: read("detach", PREFIX.detach) } : {}), ...(read("abandon", PREFIX.abandon) ? { abandon: read("abandon", PREFIX.abandon) } : {}) }); }
function checked(record: Record<string, unknown>, prefix: string, payload: object): object { const idValue = str(record.id, "Geometry-morph journal id"), sha256 = str(record.sha256, "Geometry-morph journal hash"), expected = createHash("sha256").update(canonicalJson(payload)).digest("hex"); if (!SHA256.test(sha256) || sha256 !== expected || idValue !== `${prefix}${sha256.slice(0, 32)}`) bad("geometry-morph journal deterministic identity"); return Object.freeze({ ...payload, id: idValue, sha256 }); }
function readPlan(value: unknown): GeometryMorphPlanIdentity {
  const record = exact(value, ["planFingerprint", "profileFingerprint", "storyboardId", "storyboardSha256", "storyboardRevision", "sourceLayerId", "sourceLayerIndex", "staticGeometrySha256", "sourceGeometryKeyframes", "materializedGeometryKeyframesSha256", "endpointSequenceSha256", "topologySha256", "areaProofSha256", "outputCanonicalMotionSha256"], "Geometry-morph plan");
  if (![record.planFingerprint, record.profileFingerprint, record.storyboardSha256, record.staticGeometrySha256, record.materializedGeometryKeyframesSha256, record.endpointSequenceSha256, record.topologySha256, record.areaProofSha256, record.outputCanonicalMotionSha256].every(hash) || !id(record.storyboardId) || !revision(record.storyboardRevision) || !id(record.sourceLayerId) || record.sourceLayerIndex !== 0 || record.sourceGeometryKeyframes !== "absent") bad("geometry-morph plan");
  return frozen({ planFingerprint: record.planFingerprint, profileFingerprint: record.profileFingerprint, storyboardId: record.storyboardId, storyboardSha256: record.storyboardSha256, storyboardRevision: record.storyboardRevision, sourceLayerId: record.sourceLayerId, sourceLayerIndex: 0 as const, staticGeometrySha256: record.staticGeometrySha256, sourceGeometryKeyframes: "absent" as const, materializedGeometryKeyframesSha256: record.materializedGeometryKeyframesSha256, endpointSequenceSha256: record.endpointSequenceSha256, topologySha256: record.topologySha256, areaProofSha256: record.areaProofSha256, outputCanonicalMotionSha256: record.outputCanonicalMotionSha256 }) as GeometryMorphPlanIdentity;
}
function readBase(value: unknown, label: string): C6B6bExactBase { try { return readC6B6bExactBase(value); } catch { bad(label); } }
function basePair(value: unknown, label: string): GeometryMorphBinding["source"] { const record = exact(value, ["expected", "reopened"], label), expected = readBase(record.expected, `${label}.expected`), reopened = readBase(record.reopened, `${label}.reopened`); if (canonicalJson(expected) !== canonicalJson(reopened)) bad(`${label} reopened base`); return Object.freeze({ expected, reopened }); }
function outputPair(value: unknown, label: string): GeometryMorphBinding["output"] { const record = exact(value, ["expected", "reopened"], label), expected = readOutput(record.expected, `${label}.expected`), reopened = readOutput(record.reopened, `${label}.reopened`); if (canonicalJson(expected) !== canonicalJson(reopened)) bad(`${label} reopened output`); return Object.freeze({ expected, reopened }); }
function readOutput(value: unknown, label: string): GeometryMorphOutputIdentity {
  if (forbidden(value)) bad(`${label} host authority field`);
  const root = exact(value, ["schema", "receipt", "package", "storyboard", "plan", "profile", "geometry", "materialization"], label);
  const receipt = exact(root.receipt, ["schema", "fingerprint"], `${label}.receipt`), pkg = exact(root.package, ["id", "manifest", "motion", "currentInventory", "nonReceiptInventory", "preservedLeaves"], `${label}.package`), storyboard = exact(root.storyboard, ["id", "sha256", "revision"], `${label}.storyboard`), plan = exact(root.plan, ["fingerprint"], `${label}.plan`), profile = exact(root.profile, ["fingerprint"], `${label}.profile`), geometry = exact(root.geometry, ["layerId", "layerIndex", "staticGeometrySha256", "geometryKeyframesSha256", "endpointSha256"], `${label}.geometry`), materialization = exact(root.materialization, ["changedMotionRoot", "changedLeafCount", "renderer"], `${label}.materialization`), renderer = exact(materialization.renderer, ["invoked", "pixels"], `${label}.renderer`);
  const manifest = exact(pkg.manifest, ["rawSha256", "canonicalSha256"], `${label}.manifest`), motion = exact(pkg.motion, ["rawSha256", "canonicalSha256"], `${label}.motion`), preserved = exact(pkg.preservedLeaves, ["sha256", "count"], `${label}.preserved`); readEndpointHashes(geometry.endpointSha256, `${label}.endpoints`);
  if (root.schema !== "shellx-motion/private-checkpoint-storyboard-geometry-morph-materialization-installed-output@1" || receipt.schema !== "shellx-motion/private-checkpoint-storyboard-geometry-morph-materialization-receipt@1" || !hash(receipt.fingerprint) || !id(pkg.id) || ![manifest.rawSha256, manifest.canonicalSha256, motion.rawSha256, motion.canonicalSha256, storyboard.sha256, plan.fingerprint, profile.fingerprint, geometry.staticGeometrySha256, geometry.geometryKeyframesSha256, preserved.sha256].every(hash) || !/^checkpoint_storyboard_[a-f0-9]{32}$/u.test(String(storyboard.id)) || !revision(storyboard.revision) || !id(geometry.layerId) || geometry.layerIndex !== 0 || !count(preserved.count, 100_000) || !sameInventory(pkg.currentInventory, `${label}.current inventory`) || !sameInventory(pkg.nonReceiptInventory, `${label}.non-receipt inventory`) || materialization.changedMotionRoot !== "layers" || materialization.changedLeafCount !== 2 || renderer.invoked !== false || renderer.pixels !== false) bad(`${label} geometry-morph output facts`);
  return frozen(structuredClone(root)) as unknown as GeometryMorphOutputIdentity;
}
function samePlan(plan: GeometryMorphPlanIdentity, value: C6B6bExactBase | GeometryMorphOutputIdentity): boolean {
  if ("planFingerprint" in value) return plan.planFingerprint === value.planFingerprint && plan.profileFingerprint === value.profileFingerprint && plan.storyboardId === value.storyboardId && plan.storyboardSha256 === value.storyboardSha256 && plan.storyboardRevision === value.storyboardRevision && plan.sourceLayerId === value.sourceLayerId && plan.sourceLayerIndex === value.sourceLayerIndex && plan.staticGeometrySha256 === value.sourceGeometrySha256 && plan.sourceGeometryKeyframes === value.sourceGeometryKeyframes && plan.materializedGeometryKeyframesSha256 === value.materializedGeometryKeyframesSha256 && plan.outputCanonicalMotionSha256 === value.outputCanonicalMotionSha256;
  return plan.planFingerprint === value.plan.fingerprint && plan.profileFingerprint === value.profile.fingerprint && plan.storyboardId === value.storyboard.id && plan.storyboardSha256 === value.storyboard.sha256 && plan.storyboardRevision === value.storyboard.revision && plan.sourceLayerId === value.geometry.layerId && plan.sourceLayerIndex === value.geometry.layerIndex && plan.staticGeometrySha256 === value.geometry.staticGeometrySha256 && plan.materializedGeometryKeyframesSha256 === value.geometry.geometryKeyframesSha256 && plan.outputCanonicalMotionSha256 === value.package.motion.canonicalSha256;
}
function forbidden(value: unknown): boolean { if (Array.isArray(value)) return value.some(forbidden); if (!value || typeof value !== "object") return false; return Object.entries(value).some(([key, child]) => /(?:path|workspace|approval|authority)/iu.test(key) || forbidden(child)); }
function readEndpointHashes(value: unknown, label: string): readonly [string, string] { if (!Array.isArray(value) || value.length !== 2 || !value.every(hash)) bad(label); return Object.freeze([value[0]!, value[1]!]) as readonly [string, string]; }
function readInventory(value: unknown, label: string): { readonly sha256: string; readonly entryCount: number; readonly leafCount: number } { const record = exact(value, ["sha256", "entryCount", "leafCount"], label); if (!hash(record.sha256) || !count(record.entryCount, 2048) || !count(record.leafCount, 1024)) bad(`${label} inventory`); return Object.freeze({ sha256: record.sha256, entryCount: record.entryCount, leafCount: record.leafCount }); }
function sameInventory(value: unknown, label: string): boolean { try { readInventory(value, label); return true; } catch { return false; } }
function readRef(value: unknown, prefix: string): Ref { const record = exact(value, ["id", "sha256"], "Geometry-morph journal reference"), idValue = str(record.id, "Geometry-morph reference id"), sha256 = str(record.sha256, "Geometry-morph reference hash"); if (!SHA256.test(sha256) || idValue !== `${prefix}${sha256.slice(0, 32)}`) bad("geometry-morph journal reference"); return Object.freeze({ id: idValue, sha256 }); }
function hash(value: unknown): value is string { return typeof value === "string" && SHA256.test(value); }
function id(value: unknown): value is string { return typeof value === "string" && /^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$/u.test(value); }
function count(value: unknown, max: number): value is number { return typeof value === "number" && Number.isSafeInteger(value) && value >= 1 && value <= max; }
function revision(value: unknown): value is number { return typeof value === "number" && Number.isSafeInteger(value) && value >= 1 && value <= 1_000_000; }
function str(value: unknown, label: string): string { if (typeof value !== "string") bad(label); return value; }
function frozen<T>(value: T): T { if (value && typeof value === "object" && !Object.isFrozen(value)) { for (const child of Object.values(value as object)) frozen(child); Object.freeze(value); } return value; }
function bad(label: string): never { throw storeError("store_integrity_failed", `Checkpoint storyboard geometry-morph journal ${label} is invalid.`); }
