import { copyFile, lstat, mkdir, mkdtemp, readFile, rename, rm, symlink, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { canonicalJsonSha256 } from "@shellx-motion/core";
import { createTrustedWorkspaceAnchor } from "@shellx-motion/core/internal/trusted-host-workspace";
import { createCheckpointStoryboard, createTransitionRecipe } from "@shellx-motion/core/internal/checkpoint-storyboard-relation-action-profile";
import { createCheckpointStoryboard as createBehaviorStoryboard, createTransitionRecipe as createBehaviorRecipe } from "@shellx-motion/core/internal/checkpoint-storyboard-behavior-profile";
import { createCheckpointStoryboard as createRelationStoryboard, createTransitionRecipe as createRelationRecipe } from "@shellx-motion/core/internal/checkpoint-storyboard-relation-profile";
import { configureCheckpointStoryboardBehaviorResolutionAuthority, configureCheckpointStoryboardRelationActionResolutionAuthority, configureCheckpointStoryboardRelationResolutionAuthority, dispatchDebugCommand } from "../index.js";
import { resolveCheckpointStoryboardBehaviorStoredRecord } from "./checkpoint-storyboard-behavior-resolution.js";
import { resolveCheckpointStoryboardRelationStoredRecord } from "./checkpoint-storyboard-relation-resolution.js";
import { configureCheckpointStoryboardMaterializationAuthority } from "./checkpoint-storyboard-materialization-authority.js";
import { detachCheckpointStoryboardStoredRecord, materializeCheckpointStoryboardStoredRecord } from "./checkpoint-storyboard-materialization.js";
import { CHECKPOINT_STORYBOARD_RECORD_COMMANDS } from "./checkpoint-storyboard-record-lifecycle.js";
import { archiveCheckpointStoryboardStoredLineage, configureCheckpointStoryboardRecordStore, createCheckpointStoryboardStoredRecord, inspectCheckpointStoryboardStoredRecordAuditView, issueCheckpointStoryboardRecordStoreQuiescentAdmission, recoverCheckpointStoryboardRecordStoreForQuiescentHost, tombstoneCheckpointStoryboardStoredRecord } from "./checkpoint-storyboard-record-store.js";
import { detachCheckpointStoryboardRelationActionStoredRecord, resolveCheckpointStoryboardRelationActionStoredRecord, setCheckpointStoryboardRelationActionResolutionFaultHooksForTest } from "./checkpoint-storyboard-relation-action-resolution.js";

const roots: string[] = [];
const itLinux = process.platform === "linux" ? it : it.skip;
const journal = (root: string, id: string, suffix: string) => join(root, ".shellx-motion-c6c-record-store", "relation-action-resolutions", `${id}.${suffix}.json`);
const b1State = (root: string, id: string) => join(root, ".shellx-motion-c6c-record-store", "bindings", `${id}.state.json`);
const b2State = (root: string, id: string) => join(root, ".shellx-motion-c6c-record-store", "behavior-resolutions", `${id}.state.json`);
const b3State = (root: string, id: string) => join(root, ".shellx-motion-c6c-record-store", "relation-resolutions", `${id}.state.json`);
afterEach(async () => await Promise.all(roots.splice(0).map(async (root) => await rm(root, { recursive: true, force: true }))));

const literal = (value: number) => ({ source: "literal" as const, value });
const role = (roleId: string) => ({ source: "role" as const, roleId });
function actionDefinition() { return { id: "follow-action", roles: [{ id: "guide", kind: "layer" as const, layerTypes: ["shape"] }, { id: "orb", kind: "layer" as const, layerTypes: ["shape"] }], parameters: [], templateLayers: [], relationTemplates: [{ id: "follow-template", enabled: true, kind: "attach" as const, source: { layer: role("guide"), anchorX: literal(10), anchorY: literal(10) }, target: { layer: role("orb"), anchorX: literal(5), anchorY: literal(5) }, startUs: 0, durationUs: literal(1_000_000), mode: "follow" as const, offset: { space: "world" as const, x: literal(20), y: literal(-5), rotationDeg: literal(0), scale: literal(1) } }], sequence: [{ id: "relate", kind: "relation" as const, atUs: 0, relationTemplateId: "follow-template" }] }; }
function state(objectId: "guide" | "orb", x: number, y: number) { return { objectId, state: "present" as const, properties: [{ property: "transform.x" as const, value: x }, { property: "transform.y" as const, value: y }] }; }
function actionStoryboard(action = actionDefinition()) { return createCheckpointStoryboard({ seed: 1, capabilityRequirements: ["renderer.gpu"], objectCatalog: [{ objectId: "guide", rootShapeKind: "rect", propertyMask: ["transform.x", "transform.y"] }, { objectId: "orb", rootShapeKind: "ellipse", propertyMask: ["transform.x", "transform.y"] }], checkpoints: [{ id: "start", atUs: 0, objects: [state("guide", 100, 50), state("orb", 125, 50)] }, { id: "finish", atUs: 1_000_000, objects: [state("guide", 100, 50), state("orb", 125, 50)] }], edges: [{ id: "follow-edge", fromCheckpointId: "start", toCheckpointId: "finish", lifecycle: [{ kind: "preserve", objectId: "guide" }, { kind: "preserve", objectId: "orb" }], recipeIds: ["follow-action-recipe"] }], recipes: [createTransitionRecipe({ recipeId: "follow-action-recipe", seed: 2, exactBaseRequirements: [{ resolution: "deferred-exact-base", definitionId: action.id, definitionSha256: canonicalJsonSha256(action) }], intent: { kind: "relation-action", roleBindings: [{ roleId: "guide", objectId: "guide" }, { roleId: "orb", objectId: "orb" }], parameterValues: [], declaredWrites: [{ objectId: "orb", propertyMask: ["transform.x", "transform.y"] }] } })] }); }
function b1Descriptor() { return { seed: 9, capabilityRequirements: ["renderer.native"], objectCatalog: [{ objectId: "legacy", rootShapeKind: "rect", propertyMask: ["transform.x", "transform.y", "transform.rotation", "transform.scale", "opacity"] }], checkpoints: [{ id: "start", atUs: 0, objects: [{ objectId: "legacy", state: "present", properties: [{ property: "transform.x", value: 0 }, { property: "transform.y", value: 0 }, { property: "transform.rotation", value: 0 }, { property: "transform.scale", value: 1 }, { property: "opacity", value: 1 }] }] }, { id: "end", atUs: 1_000_000, objects: [{ objectId: "legacy", state: "present", properties: [{ property: "transform.x", value: 1 }, { property: "transform.y", value: 1 }, { property: "transform.rotation", value: 0 }, { property: "transform.scale", value: 1 }, { property: "opacity", value: 1 }] }] }], edges: [{ id: "edge", fromCheckpointId: "start", toCheckpointId: "end", lifecycle: [{ kind: "preserve", objectId: "legacy" }], recipeIds: ["keyframes", "path"] }], recipes: [{ recipeId: "keyframes", seed: 10, exactBaseRequirements: [], intent: { kind: "checkpoint-keyframe", easing: "linear", targets: [{ objectId: "legacy", propertyMask: ["transform.rotation", "transform.scale", "opacity"] }] } }, { recipeId: "path", seed: 11, exactBaseRequirements: [], intent: { kind: "checkpoint-spatial-path", targets: [{ objectId: "legacy", tangentMode: "linear" }] } }] }; }
function behaviorStoryboard() { return createBehaviorStoryboard({ seed: 3, capabilityRequirements: ["renderer.gpu"], objectCatalog: [{ objectId: "orb", rootShapeKind: "ellipse", propertyMask: ["transform.x", "transform.y"] }], checkpoints: [{ id: "start", atUs: 0, objects: [{ objectId: "orb", state: "present", properties: [{ property: "transform.x", value: 0 }, { property: "transform.y", value: 0 }] }] }, { id: "end", atUs: 1_000_000, objects: [{ objectId: "orb", state: "present", properties: [{ property: "transform.x", value: 30 }, { property: "transform.y", value: 20 }] }] }], edges: [{ id: "edge", fromCheckpointId: "start", toCheckpointId: "end", lifecycle: [{ kind: "preserve", objectId: "orb" }], recipeIds: ["gravity"] }], recipes: [createBehaviorRecipe({ recipeId: "gravity", seed: 4, exactBaseRequirements: [], intent: { kind: "transform-behavior", targetObjectId: "orb", behavior: { kind: "gravity", velocityX: 1, velocityY: 2, gravityY: 3 } } })] }); }
function relationStoryboard() { return createRelationStoryboard({ seed: 5, capabilityRequirements: ["renderer.gpu"], objectCatalog: [{ objectId: "guide", rootShapeKind: "rect", propertyMask: ["transform.x", "transform.y"] }, { objectId: "orb", rootShapeKind: "ellipse", propertyMask: ["transform.x", "transform.y"] }], checkpoints: [{ id: "start", atUs: 0, objects: [state("guide", 100, 50), state("orb", 125, 50)] }, { id: "finish", atUs: 1_000_000, objects: [state("guide", 100, 50), state("orb", 125, 50)] }], edges: [{ id: "follow-edge", fromCheckpointId: "start", toCheckpointId: "finish", lifecycle: [{ kind: "preserve", objectId: "guide" }, { kind: "preserve", objectId: "orb" }], recipeIds: ["follow-guide"] }], recipes: [createRelationRecipe({ recipeId: "follow-guide", seed: 6, exactBaseRequirements: [], intent: { kind: "relation", relationKind: "follow", sourceObjectId: "guide", targetObjectId: "orb", sourceAnchor: { x: 10, y: 10 }, targetAnchor: { x: 5, y: 5 }, offset: { space: "world", x: 20, y: -5, rotationDeg: 0, scale: 1 } } })] }); }

async function fixture() {
  const root = await mkdtemp(join(process.cwd(), ".c6c-b4a-resolution-")); roots.push(root);
  const workspace = join(root, "workspace"), source = join(workspace, "source"), output = join(workspace, "output"), action = actionDefinition();
  await mkdir(join(source, "assets"), { recursive: true });
  await writeFile(join(source, "manifest.json"), JSON.stringify({ schema: "shellx-motion/package-manifest@1", id: "package-b4", name: "B4", motion: "motion.json", assets: [], sourceApp: "test", compatibility: { lanes: ["gpu"], hosts: [] } }));
  await writeFile(join(source, "motion.json"), JSON.stringify({ schema: "shellx-motion/motion@1", id: "motion-b4", name: "B4", durationMs: 1000, fps: 30, width: 1280, height: 720, layers: [{ id: "guide", type: "shape", shape: "rect", startMs: 0, durationMs: 1000, transform: { x: 100, y: 50 } }, { id: "orb", type: "shape", shape: "ellipse", startMs: 0, durationMs: 1000, transform: { x: 125, y: 50 } }], assets: [], provenance: { sourceApp: "test", createdBy: "test" }, relationActions: { schema: "shellx-motion/relation-actions@2", definitions: [action] } }));
  await writeFile(join(source, "assets", "retained.txt"), "retained\n");
  const store = await configureCheckpointStoryboardRecordStore({ root, integrityKey: Buffer.alloc(32, 41) }), anchor = await createTrustedWorkspaceAnchor(workspace);
  const authority = await configureCheckpointStoryboardRelationActionResolutionAuthority({ recordStore: store, sourcePackageRoot: source, outputPackageRoot: output, packageWorkspaceRoot: workspace, packageWorkspaceAuthority: anchor, objectLayerBindings: [{ objectId: "guide", layerId: "guide" }, { objectId: "orb", layerId: "orb" }] });
  const created = await createCheckpointStoryboardStoredRecord(store, actionStoryboard(action));
  return { root, workspace, source, output, store, anchor, authority, created };
}
function services(value: Awaited<ReturnType<typeof fixture>>) { return { tier: "write_local" as const, checkpointStoryboardRecordStore: value.store, checkpointStoryboardRelationActionResolutionAuthority: value.authority }; }

describe("C6C B4a private relation-action resolution", () => {
  itLinux("resolves, replays, detaches, and replays through exact identity-only Debug/MCP commands", async () => {
    const value = await fixture(), identity = value.created.record.identity;
    expect(value.created.record.admission).toEqual({ staticProfileAdmitted: true, profile: "c6b4-relation-action@1" });
    await expect(dispatchDebugCommand(CHECKPOINT_STORYBOARD_RECORD_COMMANDS.relationActionResolve, { identity, outputPackageRoot: value.output }, services(value))).resolves.toMatchObject({ ok: false, error: { code: "invalid_args" } });
    await expect(dispatchDebugCommand(CHECKPOINT_STORYBOARD_RECORD_COMMANDS.relationActionResolve, { identity }, { tier: "write_local", checkpointStoryboardRecordStore: value.store })).resolves.toMatchObject({ ok: false, error: { code: "capability_unavailable" } });
    await expect(dispatchDebugCommand(CHECKPOINT_STORYBOARD_RECORD_COMMANDS.relationActionResolve, { identity }, { ...services(value), tier: "read_motion" as const })).resolves.toMatchObject({ ok: false, error: { code: "permission_denied" } });
    const first = await dispatchDebugCommand(CHECKPOINT_STORYBOARD_RECORD_COMMANDS.relationActionResolve, { identity }, services(value));
    expect(first).toMatchObject({ ok: true, result: { renderer: { invoked: false, pixels: false }, binding: { state: "bound", active: 1 } } }); expect(JSON.stringify(first)).not.toContain(value.workspace);
    await expect(resolveCheckpointStoryboardRelationActionStoredRecord(value.authority, identity)).resolves.toMatchObject({ replayed: true, binding: { state: "bound" } });
    await expect(dispatchDebugCommand(CHECKPOINT_STORYBOARD_RECORD_COMMANDS.relationActionDetach, { identity }, services(value))).resolves.toMatchObject({ ok: true, result: { binding: { state: "detached", active: 0 } } });
    await expect(dispatchDebugCommand(CHECKPOINT_STORYBOARD_RECORD_COMMANDS.relationActionDetach, { identity }, services(value))).resolves.toMatchObject({ ok: true, result: { replay: "same-input", binding: { state: "detached" } } });
    await expect(lstat(value.output)).resolves.toMatchObject({ isDirectory: expect.any(Function) });
    await expect(readFile(join(value.output, "receipts", "checkpoint-storyboard-relation-action-materialization.v1.json"), "utf8")).resolves.toContain("checkpoint-storyboard.relation-action.materialize");
  }, 30_000);

  itLinux("repairs only one legal head lag and retains COW-uncertain output without a repeated COW", async () => {
    const intent = await fixture(), intentIdentity = intent.created.record.identity;
    setCheckpointStoryboardRelationActionResolutionFaultHooksForTest(intent.authority, { "after-intent-before-state-head": () => { throw new Error("intent lag"); } });
    await expect(resolveCheckpointStoryboardRelationActionStoredRecord(intent.authority, intentIdentity)).rejects.toMatchObject({ code: "materialization_binding_uncertain" });
    await expect(inspectCheckpointStoryboardStoredRecordAuditView(intent.store, intentIdentity)).rejects.toMatchObject({ code: "record_commit_uncertain" });
    setCheckpointStoryboardRelationActionResolutionFaultHooksForTest(intent.authority, undefined);
    await expect(resolveCheckpointStoryboardRelationActionStoredRecord(intent.authority, intentIdentity)).resolves.toMatchObject({ binding: { state: "bound" } });

    const binding = await fixture(), bindingIdentity = binding.created.record.identity;
    setCheckpointStoryboardRelationActionResolutionFaultHooksForTest(binding.authority, { "after-binding": () => { throw new Error("binding lag"); } });
    await expect(resolveCheckpointStoryboardRelationActionStoredRecord(binding.authority, bindingIdentity)).rejects.toMatchObject({ code: "materialization_binding_uncertain" });
    setCheckpointStoryboardRelationActionResolutionFaultHooksForTest(binding.authority, undefined);
    await expect(resolveCheckpointStoryboardRelationActionStoredRecord(binding.authority, bindingIdentity)).resolves.toMatchObject({ replayed: true, binding: { state: "bound" } });
    setCheckpointStoryboardRelationActionResolutionFaultHooksForTest(binding.authority, { "after-detach": () => { throw new Error("detach lag"); } });
    await expect(detachCheckpointStoryboardRelationActionStoredRecord(binding.authority, bindingIdentity)).rejects.toMatchObject({ code: "materialization_binding_uncertain" });
    setCheckpointStoryboardRelationActionResolutionFaultHooksForTest(binding.authority, undefined);
    await expect(detachCheckpointStoryboardRelationActionStoredRecord(binding.authority, bindingIdentity)).resolves.toMatchObject({ replayed: true, binding: { state: "detached" } });

    const head = await fixture(), headIdentity = head.created.record.identity;
    setCheckpointStoryboardRelationActionResolutionFaultHooksForTest(head.authority, { "after-bound-state-head-rename": () => { throw new Error("bound head reopen"); } });
    await expect(resolveCheckpointStoryboardRelationActionStoredRecord(head.authority, headIdentity)).rejects.toMatchObject({ code: "record_commit_uncertain" });
    setCheckpointStoryboardRelationActionResolutionFaultHooksForTest(head.authority, undefined);
    await expect(resolveCheckpointStoryboardRelationActionStoredRecord(head.authority, headIdentity)).resolves.toMatchObject({ replayed: true, binding: { state: "bound" } });
    setCheckpointStoryboardRelationActionResolutionFaultHooksForTest(head.authority, { "after-detached-state-head-rename": () => { throw new Error("detached head reopen"); } });
    await expect(detachCheckpointStoryboardRelationActionStoredRecord(head.authority, headIdentity)).rejects.toMatchObject({ code: "record_commit_uncertain" });
    setCheckpointStoryboardRelationActionResolutionFaultHooksForTest(head.authority, undefined);
    await expect(detachCheckpointStoryboardRelationActionStoredRecord(head.authority, headIdentity)).resolves.toMatchObject({ replayed: true, binding: { state: "detached" } });

    const uncertain = await fixture(), uncertainIdentity = uncertain.created.record.identity;
    let cows = 0; setCheckpointStoryboardRelationActionResolutionFaultHooksForTest(uncertain.authority, { "after-cow-start-before-state-head": () => { throw new Error("COW start lag"); }, "before-c6b4b": () => { cows += 1; } });
    await expect(resolveCheckpointStoryboardRelationActionStoredRecord(uncertain.authority, uncertainIdentity)).rejects.toMatchObject({ code: "materialization_binding_uncertain" });
    setCheckpointStoryboardRelationActionResolutionFaultHooksForTest(uncertain.authority, { "before-c6b4b": () => { cows += 1; } });
    await expect(resolveCheckpointStoryboardRelationActionStoredRecord(uncertain.authority, uncertainIdentity)).rejects.toMatchObject({ code: "materialization_binding_uncertain" }); expect(cows).toBe(0);

    const started = await fixture(), startedIdentity = started.created.record.identity; let startedCows = 0;
    setCheckpointStoryboardRelationActionResolutionFaultHooksForTest(started.authority, { "after-cow-start": () => { throw new Error("durable COW start"); }, "before-c6b4b": () => { startedCows += 1; } });
    await expect(resolveCheckpointStoryboardRelationActionStoredRecord(started.authority, startedIdentity)).rejects.toMatchObject({ code: "materialization_binding_uncertain" });
    setCheckpointStoryboardRelationActionResolutionFaultHooksForTest(started.authority, { "before-c6b4b": () => { startedCows += 1; } });
    await expect(resolveCheckpointStoryboardRelationActionStoredRecord(started.authority, startedIdentity)).rejects.toMatchObject({ code: "materialization_binding_uncertain" }); expect(startedCows).toBe(0); await expect(lstat(started.output)).rejects.toMatchObject({ code: "ENOENT" });

    const committed = await fixture(), committedIdentity = committed.created.record.identity; let committedCows = 0;
    setCheckpointStoryboardRelationActionResolutionFaultHooksForTest(committed.authority, { "before-c6b4b": () => { committedCows += 1; }, "after-c6b4b-commit": () => { throw new Error("installed before binding"); } });
    await expect(resolveCheckpointStoryboardRelationActionStoredRecord(committed.authority, committedIdentity)).rejects.toMatchObject({ code: "materialization_binding_uncertain" }); await expect(lstat(committed.output)).resolves.toMatchObject({ isDirectory: expect.any(Function) });
    setCheckpointStoryboardRelationActionResolutionFaultHooksForTest(committed.authority, { "before-c6b4b": () => { committedCows += 1; } });
    await expect(resolveCheckpointStoryboardRelationActionStoredRecord(committed.authority, committedIdentity)).resolves.toMatchObject({ replayed: true, binding: { state: "bound" } }); expect(committedCows).toBe(1);

    const abandoned = await fixture(), abandonedIdentity = abandoned.created.record.identity;
    setCheckpointStoryboardRelationActionResolutionFaultHooksForTest(abandoned.authority, { "before-c6b4b": () => { throw new Error("proved pre-install failure"); }, "after-abandon": () => { throw new Error("abandon head lag"); } });
    await expect(resolveCheckpointStoryboardRelationActionStoredRecord(abandoned.authority, abandonedIdentity)).rejects.toMatchObject({ code: "materialization_binding_uncertain" }); await expect(lstat(abandoned.output)).rejects.toMatchObject({ code: "ENOENT" });
    setCheckpointStoryboardRelationActionResolutionFaultHooksForTest(abandoned.authority, undefined);
    await expect(resolveCheckpointStoryboardRelationActionStoredRecord(abandoned.authority, abandonedIdentity)).rejects.toMatchObject({ code: "materialization_binding_conflict" }); await expect(lstat(abandoned.output)).rejects.toMatchObject({ code: "ENOENT" });
  }, 45_000);

  itLinux("refuses output aliases before intent, retains occupied output, and rejects output, receipt, inventory, action, and journal tampering", async () => {
    const alias = await fixture(), identity = alias.created.record.identity, outside = join(alias.root, "outside"), linked = join(alias.workspace, "link"); await mkdir(outside); await symlink(outside, linked);
    const unsafe = await configureCheckpointStoryboardRelationActionResolutionAuthority({ recordStore: alias.store, sourcePackageRoot: alias.source, outputPackageRoot: join(linked, "output"), packageWorkspaceRoot: alias.workspace, packageWorkspaceAuthority: alias.anchor, objectLayerBindings: [{ objectId: "guide", layerId: "guide" }, { objectId: "orb", layerId: "orb" }] });
    await expect(resolveCheckpointStoryboardRelationActionStoredRecord(unsafe, identity)).rejects.toMatchObject({ code: "materialization_binding_uncertain" }); await expect(lstat(journal(alias.root, identity.id, "intent"))).rejects.toMatchObject({ code: "ENOENT" });
    const occupied = await fixture(); await mkdir(occupied.output); await expect(resolveCheckpointStoryboardRelationActionStoredRecord(occupied.authority, occupied.created.record.identity)).rejects.toMatchObject({ code: "materialization_binding_uncertain" }); await expect(lstat(journal(occupied.root, occupied.created.record.identity.id, "intent"))).rejects.toMatchObject({ code: "ENOENT" });
    for (const tamper of ["motion", "receipt", "inventory", "action", "journal"] as const) { const value = await fixture(), id = value.created.record.identity; await resolveCheckpointStoryboardRelationActionStoredRecord(value.authority, id); if (tamper === "motion") await writeFile(join(value.output, "motion.json"), "{}"); if (tamper === "receipt") await writeFile(join(value.output, "receipts", "checkpoint-storyboard-relation-action-materialization.v1.json"), "{}"); if (tamper === "inventory") await writeFile(join(value.output, "unexpected.txt"), "drift"); if (tamper === "action") { const motion = JSON.parse(await readFile(join(value.output, "motion.json"), "utf8")); motion.relationActions.definitions[0].relationTemplates[0].offset.x.value = 21; await writeFile(join(value.output, "motion.json"), JSON.stringify(motion)); } if (tamper === "journal") await writeFile(journal(value.root, id.id, "binding"), "{}"); await expect(detachCheckpointStoryboardRelationActionStoredRecord(value.authority, id)).rejects.toMatchObject({ code: expect.stringMatching(/^(?:store_integrity_failed|materialization_binding_(?:conflict|uncertain))$/u) }); await expect(lstat(value.output)).resolves.toMatchObject({ isDirectory: expect.any(Function) }); }
  }, 45_000);

  itLinux("keeps lifecycle, namespace, and B1/B2/B3/B4 residue partitioned in every resolver direction", async () => {
    const bound = await fixture(), id = bound.created.record.identity; await resolveCheckpointStoryboardRelationActionStoredRecord(bound.authority, id);
    await expect(tombstoneCheckpointStoryboardStoredRecord(bound.store, id)).rejects.toMatchObject({ code: "materialization_binding_conflict" }); await detachCheckpointStoryboardRelationActionStoredRecord(bound.authority, id); await expect(tombstoneCheckpointStoryboardStoredRecord(bound.store, id)).resolves.toMatchObject({ record: { target: { state: "tombstoned" } } });
    const revision = await fixture(), revisionId = revision.created.record.identity; await expect(dispatchDebugCommand(CHECKPOINT_STORYBOARD_RECORD_COMMANDS.revise, { parent: revisionId, descriptor: b1Descriptor() }, { tier: "write_local", checkpointStoryboardRecordStore: revision.store })).resolves.toMatchObject({ ok: false, error: { code: "record_identity_conflict" } });
    const preparing = await fixture(), preparingId = preparing.created.record.identity; setCheckpointStoryboardRelationActionResolutionFaultHooksForTest(preparing.authority, { "after-intent": () => { throw new Error("preparing"); } }); await expect(resolveCheckpointStoryboardRelationActionStoredRecord(preparing.authority, preparingId)).rejects.toMatchObject({ code: "materialization_binding_uncertain" }); setCheckpointStoryboardRelationActionResolutionFaultHooksForTest(preparing.authority, undefined); await expect(tombstoneCheckpointStoryboardStoredRecord(preparing.store, preparingId)).rejects.toMatchObject({ code: "materialization_binding_conflict" }); await expect(detachCheckpointStoryboardRelationActionStoredRecord(preparing.authority, preparingId)).rejects.toMatchObject({ code: "materialization_not_bound" }); await expect(tombstoneCheckpointStoryboardStoredRecord(preparing.store, preparingId)).resolves.toMatchObject({ record: { target: { state: "tombstoned" } } });
    for (const kind of ["hidden", "symlink", "residual"] as const) { const value = await fixture(), identity = value.created.record.identity, directory = join(value.root, ".shellx-motion-c6c-record-store", "relation-action-resolutions"); if (kind === "hidden") await writeFile(join(directory, ".hidden"), "nope"); else if (kind === "symlink") await symlink(journal(value.root, identity.id, "state"), join(directory, "linked")); else await writeFile(join(directory, `${identity.id}.state.json.00000000-0000-0000-0000-000000000000.tmp`), "residue"); await expect(archiveCheckpointStoryboardStoredLineage(value.store, identity)).rejects.toMatchObject({ code: "store_integrity_failed" }); }
    const copied = await fixture(), copiedId = copied.created.record.identity;
    const b1 = await dispatchDebugCommand(CHECKPOINT_STORYBOARD_RECORD_COMMANDS.create, { descriptor: b1Descriptor() }, { tier: "write_local", checkpointStoryboardRecordStore: copied.store }); if (!b1.ok) throw new Error("Expected B1 record."); const b1Id = (b1.result as { record: { identity: typeof copiedId } }).record.identity;
    const b2 = await createCheckpointStoryboardStoredRecord(copied.store, behaviorStoryboard()), b3 = await createCheckpointStoryboardStoredRecord(copied.store, relationStoryboard()), actionState = join(copied.root, "b4-state.backup"); await copyFile(journal(copied.root, copiedId.id, "state"), actionState);
    for (const [foreign, state] of [[b1Id, b1State], [b2.record.identity, b2State], [b3.record.identity, b3State]] as const) { await copyFile(state(copied.root, foreign.id), journal(copied.root, copiedId.id, "state")); await expect(resolveCheckpointStoryboardRelationActionStoredRecord(copied.authority, copiedId)).rejects.toMatchObject({ code: "store_integrity_failed" }); await copyFile(actionState, journal(copied.root, copiedId.id, "state")); }
    await resolveCheckpointStoryboardRelationActionStoredRecord(copied.authority, copiedId);
    const b1Authority = await configureCheckpointStoryboardMaterializationAuthority({ recordStore: copied.store, sourcePackageRoot: copied.source, outputPackageRoot: join(copied.workspace, "b1-output"), packageWorkspaceRoot: copied.workspace, packageWorkspaceAuthority: copied.anchor, objectLayerBindings: [{ objectId: "legacy", layerId: "legacy" }] });
    await copyFile(journal(copied.root, copiedId.id, "state"), journal(copied.root, b1Id.id, "state")); await expect(materializeCheckpointStoryboardStoredRecord(b1Authority, b1Id)).rejects.toMatchObject({ code: "store_integrity_failed" }); await expect(detachCheckpointStoryboardStoredRecord(b1Authority, b1Id)).rejects.toMatchObject({ code: "store_integrity_failed" });
    const b2Authority = await configureCheckpointStoryboardBehaviorResolutionAuthority({ recordStore: copied.store, sourcePackageRoot: copied.source, outputPackageRoot: join(copied.workspace, "b2-output"), packageWorkspaceRoot: copied.workspace, packageWorkspaceAuthority: copied.anchor, objectLayerBinding: { objectId: "orb", layerId: "orb" } });
    await copyFile(journal(copied.root, copiedId.id, "state"), b2State(copied.root, b2.record.identity.id)); await expect(resolveCheckpointStoryboardBehaviorStoredRecord(b2Authority, b2.record.identity)).rejects.toMatchObject({ code: "store_integrity_failed" });
    const b3Authority = await configureCheckpointStoryboardRelationResolutionAuthority({ recordStore: copied.store, sourcePackageRoot: copied.source, outputPackageRoot: join(copied.workspace, "b3-output"), packageWorkspaceRoot: copied.workspace, packageWorkspaceAuthority: copied.anchor, objectLayerBindings: [{ objectId: "guide", layerId: "guide" }, { objectId: "orb", layerId: "orb" }] });
    await copyFile(journal(copied.root, copiedId.id, "state"), b3State(copied.root, b3.record.identity.id)); await expect(resolveCheckpointStoryboardRelationStoredRecord(b3Authority, b3.record.identity)).rejects.toMatchObject({ code: "store_integrity_failed" });
  }, 45_000);

  itLinux("refuses a replaced B4 store child, quiescently cleans only recognized action stages, serializes a duplicate resolve, and has no raw surface", async () => {
    const replaced = await fixture(), replacedId = replaced.created.record.identity, relationRoot = join(replaced.root, ".shellx-motion-c6c-record-store", "relation-action-resolutions"), held = `${relationRoot}.held`; await rename(relationRoot, held); await mkdir(relationRoot, { mode: 0o700 }); await expect(resolveCheckpointStoryboardRelationActionStoredRecord(replaced.authority, replacedId)).rejects.toMatchObject({ code: "materialization_authority_refused" });
    const recoverable = await fixture(), recoverableId = recoverable.created.record.identity, uuid = `${"a".repeat(8)}-${"b".repeat(4)}-${"c".repeat(4)}-${"d".repeat(4)}-${"e".repeat(12)}`, stage = join(recoverable.root, ".shellx-motion-c6c-record-store", "relation-action-resolutions", `${recoverableId.id}.state.json.${uuid}.tmp`); await writeFile(stage, "recoverable private action stage", { mode: 0o600 }); await expect(recoverCheckpointStoryboardRecordStoreForQuiescentHost(recoverable.store, issueCheckpointStoryboardRecordStoreQuiescentAdmission(recoverable.store))).resolves.toEqual({ removedTemporaryFiles: 1, removedStaleLocks: 0 }); await expect(lstat(stage)).rejects.toMatchObject({ code: "ENOENT" });
    const concurrent = await fixture(), concurrentId = concurrent.created.record.identity; let entered!: () => void, release!: () => void, cows = 0; const heldLock = new Promise<void>((resolve) => { entered = resolve; }), releaseLock = new Promise<void>((resolve) => { release = resolve; }); setCheckpointStoryboardRelationActionResolutionFaultHooksForTest(concurrent.authority, { "while-lineage-lock-held": async () => { entered(); await releaseLock; }, "before-c6b4b": () => { cows += 1; } }); const first = resolveCheckpointStoryboardRelationActionStoredRecord(concurrent.authority, concurrentId); await heldLock; await expect(resolveCheckpointStoryboardRelationActionStoredRecord(concurrent.authority, concurrentId)).rejects.toMatchObject({ code: "store_busy" }); release(); await expect(first).resolves.toMatchObject({ replayed: false, binding: { state: "bound" } }); setCheckpointStoryboardRelationActionResolutionFaultHooksForTest(concurrent.authority, undefined); await expect(resolveCheckpointStoryboardRelationActionStoredRecord(concurrent.authority, concurrentId)).resolves.toMatchObject({ replayed: true, binding: { state: "bound" } }); expect(cows).toBe(1);
    const files = ["../index.ts", "../command-registry.ts", "../command-metadata.ts", "../../../core/src/index.ts", "../../../cli/src/main.ts", "../../../sdk/src/index.ts", "../../../actions/src/catalog.ts", "../../../connectors/src/index.ts", "../../../renderer-browser/src/index.ts", "../../../renderer-native/src/index.ts"]; const contents = await Promise.all(files.map(async (file) => await readFile(new URL(file, import.meta.url), "utf8"))); expect(contents.every((text) => !text.includes("checkpoint-storyboard.relation-action.materialize"))).toBe(true); expect(contents.slice(3).every((text) => !text.includes("checkpoint-storyboard-relation-action-materialize"))).toBe(true);
  }, 45_000);
});
