/** Signed append-only C6C B7 retained-trace-resolution journal. B7b receipts are re-opened evidence. */
import { createHash } from "node:crypto";
import { opendir } from "node:fs/promises";
import { join } from "node:path";
import { canonicalJson } from "@shellx-motion/core";
import { readC6B7bExactBase, type C6B7bArtifactIdentity, type C6B7bExactBase } from "./checkpoint-storyboard-retained-trace-materialize-private/checkpoint-storyboard-retained-trace-materialize-receipt-private.js";
import type { CheckpointStoryboardRetainedTraceMaterializationInstalledOutput } from "./checkpoint-storyboard-retained-trace-materialize-private/checkpoint-storyboard-retained-trace-materialize-output-private.js";
import { readSignedFile, replaceSignedFile, syncPrivateDirectory, writeExclusiveSignedFile } from "./checkpoint-storyboard-record-store-signed-files.js";
import { readLineageMembers } from "./checkpoint-storyboard-materialization-bindings.js";
import { readStoredRecordUnlocked } from "./checkpoint-storyboard-record-store-state.js";
import { MAX_STATE_BYTES, SHA256, exact, readIdentity, sameIdentity, storeError, type AuthorityFacts, type CheckpointStoryboardRecordIdentity } from "./checkpoint-storyboard-record-store-types.js";

const MAX_JOURNAL_BYTES = 192 * 1024;
const HANDLE = /^checkpoint_storyboard_retained_trace_output_[a-f0-9]{32}$/u;
const FILE = /^checkpoint_storyboard_[a-f0-9]{32}\.(?:state|intent|binding|cow-start|detach|abandon)\.json$/u;
const PREFIX = { intent: "checkpoint_storyboard_retained_trace_resolution_intent_", cowStart: "checkpoint_storyboard_retained_trace_resolution_cow_start_", binding: "checkpoint_storyboard_retained_trace_resolution_binding_", detach: "checkpoint_storyboard_retained_trace_resolution_detach_", abandon: "checkpoint_storyboard_retained_trace_resolution_abandon_" } as const;
type Ref = Readonly<{ id: string; sha256: string }>;

export type CheckpointStoryboardRetainedTraceResolutionState = "unbound" | "preparing" | "bound" | "detached" | "abandoned";
export type RetainedTracePlanIdentity = Readonly<{
  planFingerprint: string; profileFingerprint: string; storyboardId: string; storyboardSha256: string; storyboardRevision: number;
  sourceLayerId: string; sourceLayerIndex: 0; staticOpacity: number;
  traceSourceSha256: string; tracePlanFingerprint: string; scheduleSha256: string; sidecarCanonicalSha256: string;
  packageId: string; manifestRawSha256: string; manifestCanonicalSha256: string; motionRawSha256: string; motionCanonicalSha256: string;
}>;
export type RetainedTraceOutputIdentity = CheckpointStoryboardRetainedTraceMaterializationInstalledOutput;
export type RetainedTraceIntent = Readonly<{ schema: "shellx-motion/private-checkpoint-storyboard-retained-trace-resolution-intent@1"; id: string; sha256: string; identity: CheckpointStoryboardRecordIdentity; root: CheckpointStoryboardRecordIdentity; plan: RetainedTracePlanIdentity; expectedBase: C6B7bExactBase; outputHandle: string }>;
export type RetainedTraceCowStart = Readonly<{ schema: "shellx-motion/private-checkpoint-storyboard-retained-trace-resolution-cow-start@1"; id: string; sha256: string; identity: CheckpointStoryboardRecordIdentity; root: CheckpointStoryboardRecordIdentity; intent: Ref }>;
export type RetainedTraceBinding = Readonly<{ schema: "shellx-motion/private-checkpoint-storyboard-retained-trace-resolution-binding@1"; id: string; sha256: string; identity: CheckpointStoryboardRecordIdentity; root: CheckpointStoryboardRecordIdentity; intent: Ref; plan: RetainedTracePlanIdentity; source: Readonly<{ expected: C6B7bExactBase; reopened: C6B7bExactBase }>; output: Readonly<{ expected: RetainedTraceOutputIdentity; reopened: RetainedTraceOutputIdentity }>; sidecar: C6B7bArtifactIdentity; receiptFingerprint: string; outputHandle: string }>;
export type RetainedTraceDetach = Readonly<{ schema: "shellx-motion/private-checkpoint-storyboard-retained-trace-resolution-detach@1"; id: string; sha256: string; identity: CheckpointStoryboardRecordIdentity; root: CheckpointStoryboardRecordIdentity; binding: Ref }>;
export type RetainedTraceAbandon = Readonly<{ schema: "shellx-motion/private-checkpoint-storyboard-retained-trace-resolution-abandon@1"; id: string; sha256: string; identity: CheckpointStoryboardRecordIdentity; root: CheckpointStoryboardRecordIdentity; intent: Ref; reason: "proven-no-install" | "no-cow-start" }>;
export type RetainedTraceStateHead = Readonly<{ schema: "shellx-motion/private-checkpoint-storyboard-retained-trace-resolution-state@1"; identity: CheckpointStoryboardRecordIdentity; root: CheckpointStoryboardRecordIdentity; state: CheckpointStoryboardRetainedTraceResolutionState; active: 0 | 1; intent?: Ref; cowStart?: Ref; binding?: Ref; detach?: Ref; abandon?: Ref }>;
export type RetainedTraceResolutionBindingState = Readonly<{ state: CheckpointStoryboardRetainedTraceResolutionState; active: 0 | 1; bindingId?: string; outputHandle?: string; receiptFingerprint?: string }>;

export function createRetainedTraceIntent(input: Omit<RetainedTraceIntent, "schema" | "id" | "sha256">): RetainedTraceIntent { return seal("intent", "shellx-motion/private-checkpoint-storyboard-retained-trace-resolution-intent@1", input); }
export function createRetainedTraceCowStart(input: Omit<RetainedTraceCowStart, "schema" | "id" | "sha256">): RetainedTraceCowStart { return seal("cowStart", "shellx-motion/private-checkpoint-storyboard-retained-trace-resolution-cow-start@1", input); }
export function createRetainedTraceBinding(input: Omit<RetainedTraceBinding, "schema" | "id" | "sha256">): RetainedTraceBinding { return seal("binding", "shellx-motion/private-checkpoint-storyboard-retained-trace-resolution-binding@1", input); }
export function createRetainedTraceDetach(input: Omit<RetainedTraceDetach, "schema" | "id" | "sha256">): RetainedTraceDetach { return seal("detach", "shellx-motion/private-checkpoint-storyboard-retained-trace-resolution-detach@1", input); }
export function createRetainedTraceAbandon(input: Omit<RetainedTraceAbandon, "schema" | "id" | "sha256">): RetainedTraceAbandon { return seal("abandon", "shellx-motion/private-checkpoint-storyboard-retained-trace-resolution-abandon@1", input); }
export function retainedTraceStateHead(identity: CheckpointStoryboardRecordIdentity, root: CheckpointStoryboardRecordIdentity, state: CheckpointStoryboardRetainedTraceResolutionState, active: 0 | 1, refs: Partial<Pick<RetainedTraceStateHead, "intent" | "cowStart" | "binding" | "detach" | "abandon">> = {}): RetainedTraceStateHead { return Object.freeze({ schema: "shellx-motion/private-checkpoint-storyboard-retained-trace-resolution-state@1", identity, root, state, active, ...refs }); }
export async function initializeRetainedTraceStateHead(facts: AuthorityFacts, identity: CheckpointStoryboardRecordIdentity, root: CheckpointStoryboardRecordIdentity): Promise<void> { await publishExact(statePath(facts, identity), retainedTraceStateHead(identity, root, "unbound", 0), facts); }
export async function publishRetainedTraceIntent(facts: AuthorityFacts, value: RetainedTraceIntent): Promise<void> { await publishExact(path(facts, value.identity, "intent"), value, facts); }
export async function publishRetainedTraceCowStart(facts: AuthorityFacts, value: RetainedTraceCowStart): Promise<void> { await publishExact(path(facts, value.identity, "cow-start"), value, facts); }
export async function publishRetainedTraceBinding(facts: AuthorityFacts, value: RetainedTraceBinding): Promise<void> { await publishExact(path(facts, value.identity, "binding"), value, facts); }
export async function publishRetainedTraceDetach(facts: AuthorityFacts, value: RetainedTraceDetach): Promise<void> { await publishExact(path(facts, value.identity, "detach"), value, facts); }
export async function publishRetainedTraceAbandon(facts: AuthorityFacts, value: RetainedTraceAbandon): Promise<void> { await publishExact(path(facts, value.identity, "abandon"), value, facts); }
export async function publishRetainedTraceStateHead(facts: AuthorityFacts, value: RetainedTraceStateHead, afterRename?: () => void | Promise<void>): Promise<void> { await replaceSignedFile(statePath(facts, value.identity), value, facts, MAX_STATE_BYTES, afterRename); }
export async function readRetainedTraceIntent(facts: AuthorityFacts, identity: CheckpointStoryboardRecordIdentity): Promise<RetainedTraceIntent | null> { return await optional(path(facts, identity, "intent"), facts, readIntent); }
export async function readRetainedTraceCowStart(facts: AuthorityFacts, identity: CheckpointStoryboardRecordIdentity): Promise<RetainedTraceCowStart | null> { return await optional(path(facts, identity, "cow-start"), facts, readStart); }
export async function readRetainedTraceBinding(facts: AuthorityFacts, identity: CheckpointStoryboardRecordIdentity): Promise<RetainedTraceBinding | null> { return await optional(path(facts, identity, "binding"), facts, readBinding); }
export async function readRetainedTraceStateHead(facts: AuthorityFacts, identityId: string): Promise<RetainedTraceStateHead | null> { if (!/^checkpoint_storyboard_[a-f0-9]{32}$/u.test(identityId)) throw storeError("store_integrity_failed", "Checkpoint storyboard retained-trace state filename identity is invalid."); return await optional(join(facts.retainedTraceResolutions.path, `${identityId}.state.json`), facts, readHead); }
export async function assertNoRetainedTraceResolutionEvidence(facts: AuthorityFacts, identity: CheckpointStoryboardRecordIdentity): Promise<void> { if (await readRetainedTraceStateHead(facts, identity.id) || await readRetainedTraceIntent(facts, identity) || await readRetainedTraceCowStart(facts, identity) || await readRetainedTraceBinding(facts, identity) || await optional(path(facts, identity, "detach"), facts, readDetach) || await optional(path(facts, identity, "abandon"), facts, readAbandon)) throw storeError("store_integrity_failed", "Checkpoint storyboard non-retained-trace record has forbidden C6B7 resolution evidence."); }

/** Reads all signed phases. Forward head repair is legal only while a resolver holds the lineage lock. */
export async function readRetainedTraceResolutionState(facts: AuthorityFacts, identity: CheckpointStoryboardRecordIdentity, root: CheckpointStoryboardRecordIdentity, options: { readonly requireHead?: boolean; readonly allowForwardRecovery?: boolean } = {}): Promise<RetainedTraceResolutionBindingState> {
  await syncRetainedTraceDirectory(facts); const repair = options.allowForwardRecovery ?? false;
  const head = await optional(statePath(facts, identity), facts, readHead), intent = await readRetainedTraceIntent(facts, identity), start = await readRetainedTraceCowStart(facts, identity), binding = await readRetainedTraceBinding(facts, identity), detach = await optional(path(facts, identity, "detach"), facts, readDetach), abandon = await optional(path(facts, identity, "abandon"), facts, readAbandon);
  if (!head) {
    if (!options.requireHead && !intent && !start && !binding && !detach && !abandon) return Object.freeze({ state: "unbound" as const, active: 0 as const });
    if (intent && !start && !binding && !detach && !abandon && repair) { const next = retainedTraceStateHead(identity, root, "preparing", 0, { intent: ref(intent) }); await publishRetainedTraceStateHead(facts, next); return await reopenPromoted(facts, identity, root, next, Object.freeze({ state: "preparing" as const, active: 0 as const, outputHandle: intent.outputHandle })); }
    throw storeError(intent ? "record_commit_uncertain" : "store_integrity_failed", "Checkpoint storyboard retained-trace resolution is missing its required signed state head.");
  }
  if (!sameIdentity(head.identity, identity) || !sameIdentity(head.root, root)) throw storeError("store_integrity_failed", "Checkpoint storyboard retained-trace state head does not bind this record lineage.");
  if (!intent) { if (start || binding || detach || abandon) throw storeError("store_integrity_failed", "Checkpoint storyboard retained-trace unbound state has phase evidence."); return await checkedHead(facts, head, Object.freeze({ state: "unbound" as const, active: 0 as const }), repair); }
  if (!sameIdentity(intent.identity, identity) || !sameIdentity(intent.root, root)) throw storeError("store_integrity_failed", "Checkpoint storyboard retained-trace intent does not bind this record lineage.");
  if (!binding) {
    if (detach) throw storeError("store_integrity_failed", "Checkpoint storyboard retained-trace detach has no immutable binding.");
    if (start && (!sameIdentity(start.identity, identity) || !sameIdentity(start.root, root) || !sameRef(start.intent, intent))) throw storeError("store_integrity_failed", "Checkpoint storyboard retained-trace COW start does not bind intent.");
    if (abandon) { if (!sameIdentity(abandon.identity, identity) || !sameIdentity(abandon.root, root) || !sameRef(abandon.intent, intent) || (abandon.reason === "no-cow-start" && start) || (abandon.reason === "proven-no-install" && !start)) throw storeError("store_integrity_failed", "Checkpoint storyboard retained-trace abandonment is inconsistent."); return await checkedHead(facts, head, Object.freeze({ state: "abandoned" as const, active: 0 as const, outputHandle: intent.outputHandle }), repair, intent, start ?? undefined, undefined, undefined, abandon); }
    return await checkedHead(facts, head, Object.freeze({ state: "preparing" as const, active: 0 as const, outputHandle: intent.outputHandle }), repair, intent, start ?? undefined);
  }
  if (!start || abandon || !sameIdentity(binding.identity, identity) || !sameIdentity(binding.root, root) || !sameRef(binding.intent, intent) || binding.outputHandle !== intent.outputHandle || !samePlan(binding.plan, intent.expectedBase) || !samePlan(binding.plan, binding.output.expected) || canonicalJson(binding.plan) !== canonicalJson(intent.plan) || canonicalJson(binding.source.expected) !== canonicalJson(intent.expectedBase) || binding.plan.storyboardId !== identity.id || binding.plan.storyboardSha256 !== identity.sha256 || binding.plan.storyboardRevision !== identity.revision || !sameIdentity(start.identity, identity) || !sameIdentity(start.root, root) || !sameRef(start.intent, intent)) throw storeError("store_integrity_failed", "Checkpoint storyboard retained-trace binding does not semantically bind intent, sidecar plan, identity, and COW start.");
  if (!detach) return await checkedHead(facts, head, Object.freeze({ state: "bound" as const, active: 1 as const, bindingId: binding.id, outputHandle: binding.outputHandle, receiptFingerprint: binding.receiptFingerprint }), repair, intent, start, binding);
  if (!sameIdentity(detach.identity, identity) || !sameIdentity(detach.root, root) || !sameRef(detach.binding, binding)) throw storeError("store_integrity_failed", "Checkpoint storyboard retained-trace detach does not bind immutable binding.");
  return await checkedHead(facts, head, Object.freeze({ state: "detached" as const, active: 0 as const, bindingId: binding.id, outputHandle: binding.outputHandle, receiptFingerprint: binding.receiptFingerprint }), repair, intent, start, binding, detach);
}
export async function assertLineageHasNoPreparingOrBoundRetainedTraceResolutions(facts: AuthorityFacts, root: CheckpointStoryboardRecordIdentity, requireHeadsFor = new Set<string>()): Promise<void> { const members = await readLineageMembers(facts, root); if (!members.length) throw storeError("store_integrity_failed", "Checkpoint storyboard lineage has no signed membership records."); for (const member of members) { if (!sameIdentity(member.root, root)) throw storeError("store_integrity_failed", "Checkpoint storyboard lineage membership root changed."); const state = await readRetainedTraceResolutionState(facts, member.identity, root, { requireHead: requireHeadsFor.has(member.identity.id) }); if (state.state === "preparing" || state.state === "bound") throw storeError("materialization_binding_conflict", "Checkpoint storyboard remove/archive requires every retained-trace-resolution member to be unbound or detached."); } }
/** Archive scans the complete B7 namespace so copied/foreign/hidden phase leaves cannot be hidden. */
export async function assertRetainedTraceResolutionJournalCompleteForLineage(facts: AuthorityFacts, root: CheckpointStoryboardRecordIdentity, requireHeadsFor = new Set<string>()): Promise<void> {
  const members = await readLineageMembers(facts, root), byId = new Map(members.map((member) => [member.identity.id, member.identity])), reader = await opendir(facts.retainedTraceResolutions.path);
  try { for await (const entry of reader) { if (!entry.isFile() || !FILE.test(entry.name)) throw storeError("store_integrity_failed", "Checkpoint storyboard retained-trace journal contains an invalid entry."); const identityId = entry.name.slice(0, 54), identity = byId.get(identityId), head = await readRetainedTraceStateHead(facts, identityId); if (!head) throw storeError("store_integrity_failed", "Checkpoint storyboard retained-trace journal state head is missing."); if (head.identity.id !== identityId) throw storeError("store_integrity_failed", "Checkpoint storyboard retained-trace filename does not match signed identity."); if (identity) { if (!requireHeadsFor.has(identity.id) || !sameIdentity(head.root, root) || !sameIdentity(head.identity, identity)) throw storeError("store_integrity_failed", "Checkpoint storyboard retained-trace journal attaches to a sealed non-B7 lineage member."); } else { const foreign = (await readLineageMembers(facts, head.root)).find((member) => sameIdentity(member.identity, head.identity)); if (!foreign || !sameIdentity(foreign.root, head.root)) throw storeError("store_integrity_failed", "Checkpoint storyboard retained-trace journal references an unknown lineage member."); const foreignRecord = await readStoredRecordUnlocked(facts, head.identity); if (foreignRecord.admission.profile !== "c6b7-retained-trace@1") throw storeError("store_integrity_failed", "Checkpoint storyboard retained-trace journal attaches to a foreign non-B7 member."); await readRetainedTraceResolutionState(facts, head.identity, head.root, { requireHead: true }); } } } finally { await reader.close().catch(() => undefined); }
  for (const member of members) await readRetainedTraceResolutionState(facts, member.identity, root, { requireHead: requireHeadsFor.has(member.identity.id) });
}

function path(facts: AuthorityFacts, identity: CheckpointStoryboardRecordIdentity, kind: "intent" | "cow-start" | "binding" | "detach" | "abandon"): string { return join(facts.retainedTraceResolutions.path, `${identity.id}.${kind}.json`); }
function statePath(facts: AuthorityFacts, identity: CheckpointStoryboardRecordIdentity): string { return join(facts.retainedTraceResolutions.path, `${identity.id}.state.json`); }
async function optional<T>(file: string, facts: AuthorityFacts, read: (value: unknown) => T): Promise<T | null> { try { return read(await readSignedFile(file, facts, MAX_JOURNAL_BYTES, "record_not_found")); } catch (error) { if (error instanceof Error && (error as { code?: string }).code === "record_not_found") return null; throw error; } }
async function syncRetainedTraceDirectory(facts: AuthorityFacts): Promise<void> { try { await syncPrivateDirectory(facts.retainedTraceResolutions.path); } catch { throw storeError("record_commit_uncertain", "Checkpoint storyboard retained-trace state requires a durable directory resync."); } }
async function checkedHead(facts: AuthorityFacts, head: RetainedTraceStateHead, state: RetainedTraceResolutionBindingState, repair: boolean, intent?: RetainedTraceIntent, cowStart?: RetainedTraceCowStart, binding?: RetainedTraceBinding, detach?: RetainedTraceDetach, abandon?: RetainedTraceAbandon): Promise<RetainedTraceResolutionBindingState> {
  const matches = (actual: Ref | undefined, value: { readonly id: string; readonly sha256: string } | undefined) => value ? sameRef(actual, value) : !actual;
  if (!legalHead(head)) throw storeError("store_integrity_failed", "Checkpoint storyboard retained-trace state head has invalid phase fields.");
  const exactHead = head.state === state.state && head.active === state.active && matches(head.intent, intent) && matches(head.cowStart, cowStart) && matches(head.binding, binding) && matches(head.detach, detach) && matches(head.abandon, abandon);
  if (exactHead) { await syncRetainedTraceDirectory(facts); return state; }
  if (!repair) throw storeError("record_commit_uncertain", "Checkpoint storyboard retained-trace phase evidence is one publication ahead of its signed head; read-only inspection will not repair it.");
  const next = retainedTraceStateHead(head.identity, head.root, state.state, state.active, { ...(intent ? { intent: ref(intent) } : {}), ...(cowStart ? { cowStart: ref(cowStart) } : {}), ...(binding ? { binding: ref(binding) } : {}), ...(detach ? { detach: ref(detach) } : {}), ...(abandon ? { abandon: ref(abandon) } : {}) });
  const oneStep = (head.state === "unbound" && state.state === "preparing" && !!intent && !cowStart)
    || (head.state === "preparing" && state.state === "preparing" && !!intent && !!cowStart && matches(head.intent, intent) && !head.cowStart)
    || (head.state === "preparing" && state.state === "bound" && !!intent && !!cowStart && !!binding && matches(head.intent, intent) && matches(head.cowStart, cowStart))
    || (head.state === "preparing" && state.state === "abandoned" && !!intent && !!abandon && matches(head.intent, intent) && matches(head.cowStart, cowStart))
    || (head.state === "bound" && state.state === "detached" && !!intent && !!cowStart && !!binding && !!detach && matches(head.intent, intent) && matches(head.cowStart, cowStart) && matches(head.binding, binding));
  if (!oneStep) throw storeError("store_integrity_failed", "Checkpoint storyboard retained-trace head skips, diverges from, or rolls back immutable phase evidence.");
  await publishRetainedTraceStateHead(facts, next); return await reopenPromoted(facts, head.identity, head.root, next, state);
}
function legalHead(head: RetainedTraceStateHead): boolean { return (head.state === "unbound" && head.active === 0 && !hasRef(head)) || (head.state === "preparing" && head.active === 0 && !!head.intent && !head.binding && !head.detach && !head.abandon) || (head.state === "bound" && head.active === 1 && !!head.intent && !!head.cowStart && !!head.binding && !head.detach && !head.abandon) || (head.state === "detached" && head.active === 0 && !!head.intent && !!head.cowStart && !!head.binding && !!head.detach && !head.abandon) || (head.state === "abandoned" && head.active === 0 && !!head.intent && !!head.abandon && !head.binding && !head.detach); }
async function reopenPromoted(facts: AuthorityFacts, identity: CheckpointStoryboardRecordIdentity, root: CheckpointStoryboardRecordIdentity, expected: RetainedTraceStateHead, state: RetainedTraceResolutionBindingState): Promise<RetainedTraceResolutionBindingState> { const reopened = await optional(statePath(facts, identity), facts, readHead); if (!reopened || canonicalJson(reopened) !== canonicalJson(expected)) throw storeError("record_commit_uncertain", "Checkpoint storyboard retained-trace head promotion could not be reopened exactly."); await syncRetainedTraceDirectory(facts); return state; }
async function publishExact(file: string, value: object, facts: AuthorityFacts): Promise<void> { try { await writeExclusiveSignedFile(file, value, facts, MAX_JOURNAL_BYTES); } catch (error) { if (!(error instanceof Error) || (error as { code?: string }).code !== "record_identity_conflict") throw error; const existing = await readSignedFile(file, facts, MAX_JOURNAL_BYTES, "record_not_found"); if (canonicalJson(existing) !== canonicalJson(value)) throw storeError("materialization_binding_conflict", "Checkpoint storyboard immutable retained-trace journal leaf is occupied by different content."); } }
function seal<K extends keyof typeof PREFIX, S extends string, T extends object>(kind: K, schema: S, payload: T): T & { readonly schema: S; readonly id: string; readonly sha256: string } { const sha256 = createHash("sha256").update(canonicalJson({ schema, ...payload })).digest("hex"); return Object.freeze({ schema, id: `${PREFIX[kind]}${sha256.slice(0, 32)}`, sha256, ...payload }); }
function ref(value: { readonly id: string; readonly sha256: string }): Ref { return Object.freeze({ id: value.id, sha256: value.sha256 }); }
function sameRef(value: Ref | undefined, target: { readonly id: string; readonly sha256: string }): boolean { return !!value && value.id === target.id && value.sha256 === target.sha256; }
function hasRef(head: RetainedTraceStateHead): boolean { return !!(head.intent || head.cowStart || head.binding || head.detach || head.abandon); }
function readIntent(value: unknown): RetainedTraceIntent { const record = exact(value, ["schema", "id", "sha256", "identity", "root", "plan", "expectedBase", "outputHandle"], "Retained-trace resolution intent"); if (record.schema !== "shellx-motion/private-checkpoint-storyboard-retained-trace-resolution-intent@1") bad("retained-trace intent schema"); const identity = readIdentity(record.identity, "Retained-trace intent identity"), root = readIdentity(record.root, "Retained-trace intent root"), plan = readPlan(record.plan), expectedBase = readBase(record.expectedBase, "Retained-trace intent expected base"), outputHandle = str(record.outputHandle, "Retained-trace intent output handle"); if (!HANDLE.test(outputHandle) || !samePlan(plan, expectedBase)) bad("retained-trace intent plan"); return checked(record, PREFIX.intent, { schema: record.schema, identity, root, plan, expectedBase, outputHandle }) as RetainedTraceIntent; }
function readStart(value: unknown): RetainedTraceCowStart { const record = exact(value, ["schema", "id", "sha256", "identity", "root", "intent"], "Retained-trace COW start"); if (record.schema !== "shellx-motion/private-checkpoint-storyboard-retained-trace-resolution-cow-start@1") bad("retained-trace COW start schema"); return checked(record, PREFIX.cowStart, { schema: record.schema, identity: readIdentity(record.identity, "Retained-trace start identity"), root: readIdentity(record.root, "Retained-trace start root"), intent: readRef(record.intent, PREFIX.intent) }) as RetainedTraceCowStart; }
function readBinding(value: unknown): RetainedTraceBinding { const record = exact(value, ["schema", "id", "sha256", "identity", "root", "intent", "plan", "source", "output", "sidecar", "receiptFingerprint", "outputHandle"], "Retained-trace binding"); if (record.schema !== "shellx-motion/private-checkpoint-storyboard-retained-trace-resolution-binding@1") bad("retained-trace binding schema"); const source = basePair(record.source, "Retained-trace binding source"), output = outputPair(record.output, "Retained-trace binding output"), sidecar = readArtifact(record.sidecar, "Retained-trace binding sidecar"), receiptFingerprint = str(record.receiptFingerprint, "Retained-trace binding receipt"), outputHandle = str(record.outputHandle, "Retained-trace binding handle"), plan = readPlan(record.plan); if (!SHA256.test(receiptFingerprint) || !HANDLE.test(outputHandle) || !samePlan(plan, source.expected) || !samePlan(plan, output.expected) || canonicalJson(sidecar) !== canonicalJson(output.expected.sidecar) || sidecar.canonicalSha256 !== plan.sidecarCanonicalSha256 || output.expected.package.id !== source.expected.source.packageId || output.expected.package.manifestRawSha256 !== source.expected.source.manifestRawSha256 || output.expected.package.manifestCanonicalSha256 !== source.expected.source.manifestCanonicalSha256 || output.expected.package.motionRawSha256 !== source.expected.source.motionRawSha256 || output.expected.package.motionCanonicalSha256 !== source.expected.source.motionCanonicalSha256) bad("retained-trace binding package identity"); return checked(record, PREFIX.binding, { schema: record.schema, identity: readIdentity(record.identity, "Retained-trace binding identity"), root: readIdentity(record.root, "Retained-trace binding root"), intent: readRef(record.intent, PREFIX.intent), plan, source, output, sidecar, receiptFingerprint, outputHandle }) as RetainedTraceBinding; }
function readDetach(value: unknown): RetainedTraceDetach { const record = exact(value, ["schema", "id", "sha256", "identity", "root", "binding"], "Retained-trace detach"); if (record.schema !== "shellx-motion/private-checkpoint-storyboard-retained-trace-resolution-detach@1") bad("retained-trace detach schema"); return checked(record, PREFIX.detach, { schema: record.schema, identity: readIdentity(record.identity, "Retained-trace detach identity"), root: readIdentity(record.root, "Retained-trace detach root"), binding: readRef(record.binding, PREFIX.binding) }) as RetainedTraceDetach; }
function readAbandon(value: unknown): RetainedTraceAbandon { const record = exact(value, ["schema", "id", "sha256", "identity", "root", "intent", "reason"], "Retained-trace abandon"), reason = record.reason; if (record.schema !== "shellx-motion/private-checkpoint-storyboard-retained-trace-resolution-abandon@1" || (reason !== "proven-no-install" && reason !== "no-cow-start")) bad("retained-trace abandonment"); return checked(record, PREFIX.abandon, { schema: record.schema, identity: readIdentity(record.identity, "Retained-trace abandon identity"), root: readIdentity(record.root, "Retained-trace abandon root"), intent: readRef(record.intent, PREFIX.intent), reason }) as RetainedTraceAbandon; }
function readHead(value: unknown): RetainedTraceStateHead { const record = exact(value, ["schema", "identity", "root", "state", "active"], ["intent", "cowStart", "binding", "detach", "abandon"], "Retained-trace state"), state = record.state; if (record.schema !== "shellx-motion/private-checkpoint-storyboard-retained-trace-resolution-state@1" || (state !== "unbound" && state !== "preparing" && state !== "bound" && state !== "detached" && state !== "abandoned") || (record.active !== 0 && record.active !== 1)) bad("retained-trace state schema"); const read = (key: "intent" | "cowStart" | "binding" | "detach" | "abandon", prefix: string) => Object.hasOwn(record, key) ? readRef(record[key], prefix) : undefined; return Object.freeze({ schema: record.schema, identity: readIdentity(record.identity, "Retained-trace state identity"), root: readIdentity(record.root, "Retained-trace state root"), state, active: record.active, ...(read("intent", PREFIX.intent) ? { intent: read("intent", PREFIX.intent) } : {}), ...(read("cowStart", PREFIX.cowStart) ? { cowStart: read("cowStart", PREFIX.cowStart) } : {}), ...(read("binding", PREFIX.binding) ? { binding: read("binding", PREFIX.binding) } : {}), ...(read("detach", PREFIX.detach) ? { detach: read("detach", PREFIX.detach) } : {}), ...(read("abandon", PREFIX.abandon) ? { abandon: read("abandon", PREFIX.abandon) } : {}) }); }
function checked(record: Record<string, unknown>, prefix: string, payload: object): object { const idValue = str(record.id, "Retained-trace journal id"), sha256 = str(record.sha256, "Retained-trace journal hash"), expected = createHash("sha256").update(canonicalJson(payload)).digest("hex"); if (!SHA256.test(sha256) || sha256 !== expected || idValue !== `${prefix}${sha256.slice(0, 32)}`) bad("retained-trace journal deterministic identity"); return Object.freeze({ ...payload, id: idValue, sha256 }); }
function readPlan(value: unknown): RetainedTracePlanIdentity {
  const record = exact(value, ["planFingerprint", "profileFingerprint", "storyboardId", "storyboardSha256", "storyboardRevision", "sourceLayerId", "sourceLayerIndex", "staticOpacity", "traceSourceSha256", "tracePlanFingerprint", "scheduleSha256", "sidecarCanonicalSha256", "packageId", "manifestRawSha256", "manifestCanonicalSha256", "motionRawSha256", "motionCanonicalSha256"], "Retained-trace plan");
  if (![record.planFingerprint, record.profileFingerprint, record.storyboardSha256, record.traceSourceSha256, record.tracePlanFingerprint, record.scheduleSha256, record.sidecarCanonicalSha256, record.manifestRawSha256, record.manifestCanonicalSha256, record.motionRawSha256, record.motionCanonicalSha256].every(hash) || !id(record.storyboardId) || !revision(record.storyboardRevision) || !id(record.sourceLayerId) || !id(record.packageId) || record.sourceLayerIndex !== 0 || typeof record.staticOpacity !== "number" || !Number.isFinite(record.staticOpacity) || record.staticOpacity < 0 || record.staticOpacity > 1) bad("retained-trace plan");
  return frozen({ planFingerprint: record.planFingerprint, profileFingerprint: record.profileFingerprint, storyboardId: record.storyboardId, storyboardSha256: record.storyboardSha256, storyboardRevision: record.storyboardRevision, sourceLayerId: record.sourceLayerId, sourceLayerIndex: 0 as const, staticOpacity: record.staticOpacity, traceSourceSha256: record.traceSourceSha256, tracePlanFingerprint: record.tracePlanFingerprint, scheduleSha256: record.scheduleSha256, sidecarCanonicalSha256: record.sidecarCanonicalSha256, packageId: record.packageId, manifestRawSha256: record.manifestRawSha256, manifestCanonicalSha256: record.manifestCanonicalSha256, motionRawSha256: record.motionRawSha256, motionCanonicalSha256: record.motionCanonicalSha256 }) as RetainedTracePlanIdentity;
}
function readBase(value: unknown, label: string): C6B7bExactBase { try { return readC6B7bExactBase(value); } catch { bad(label); } }
function basePair(value: unknown, label: string): RetainedTraceBinding["source"] { const record = exact(value, ["expected", "reopened"], label), expected = readBase(record.expected, `${label}.expected`), reopened = readBase(record.reopened, `${label}.reopened`); if (canonicalJson(expected) !== canonicalJson(reopened)) bad(`${label} reopened base`); return Object.freeze({ expected, reopened }); }
function outputPair(value: unknown, label: string): RetainedTraceBinding["output"] { const record = exact(value, ["expected", "reopened"], label), expected = readOutput(record.expected, `${label}.expected`), reopened = readOutput(record.reopened, `${label}.reopened`); if (canonicalJson(expected) !== canonicalJson(reopened)) bad(`${label} reopened output`); return Object.freeze({ expected, reopened }); }
function readOutput(value: unknown, label: string): RetainedTraceOutputIdentity {
  const root = exact(value, ["schema", "planFingerprint", "profileFingerprint", "tracePlanFingerprint", "package", "sidecar", "renderer"], label), pkg = exact(root.package, ["id", "manifestRawSha256", "manifestCanonicalSha256", "motionRawSha256", "motionCanonicalSha256", "inventory"], `${label}.package`), renderer = exact(root.renderer, ["invoked", "pixels", "gpuAbi", "upload"], `${label}.renderer`), sidecar = readArtifact(root.sidecar, `${label}.sidecar`);
  if (root.schema !== "shellx-motion/private-checkpoint-storyboard-retained-trace-materialization-installed-output@1" || !id(pkg.id) || ![root.planFingerprint, root.profileFingerprint, root.tracePlanFingerprint, pkg.manifestRawSha256, pkg.manifestCanonicalSha256, pkg.motionRawSha256, pkg.motionCanonicalSha256].every(hash) || !sameInventory(pkg.inventory, `${label}.inventory`) || renderer.invoked !== false || renderer.pixels !== false || renderer.gpuAbi !== "none" || renderer.upload !== "none") bad(`${label} retained-trace output facts`);
  return frozen(structuredClone(root)) as unknown as RetainedTraceOutputIdentity;
}
function samePlan(plan: RetainedTracePlanIdentity, value: C6B7bExactBase | RetainedTraceOutputIdentity): boolean {
  if ("sourceArtifacts" in value) return plan.planFingerprint === value.planFingerprint && plan.profileFingerprint === value.profileFingerprint && plan.storyboardId === value.storyboardId && plan.storyboardSha256 === value.storyboardSha256 && plan.storyboardRevision === value.storyboardRevision && plan.sourceLayerId === value.sourceLayerId && plan.sourceLayerIndex === value.sourceLayerIndex && plan.staticOpacity === value.staticOpacity && plan.traceSourceSha256 === value.traceSourceSha256 && plan.tracePlanFingerprint === value.tracePlanFingerprint && plan.scheduleSha256 === value.scheduleSha256 && plan.packageId === value.source.packageId && plan.manifestRawSha256 === value.source.manifestRawSha256 && plan.manifestCanonicalSha256 === value.source.manifestCanonicalSha256 && plan.motionRawSha256 === value.source.motionRawSha256 && plan.motionCanonicalSha256 === value.source.motionCanonicalSha256;
  return plan.planFingerprint === value.planFingerprint && plan.profileFingerprint === value.profileFingerprint && plan.tracePlanFingerprint === value.tracePlanFingerprint && plan.packageId === value.package.id && plan.manifestRawSha256 === value.package.manifestRawSha256 && plan.manifestCanonicalSha256 === value.package.manifestCanonicalSha256 && plan.motionRawSha256 === value.package.motionRawSha256 && plan.motionCanonicalSha256 === value.package.motionCanonicalSha256;
}
function readArtifact(value: unknown, label: string): C6B7bArtifactIdentity { const item = exact(value, ["path", "rawSha256", "byteLength", "canonicalSha256"], label); if (item.path !== "analysis/checkpoint-storyboard/parametric-trace.plan.json" || !hash(item.rawSha256) || !hash(item.canonicalSha256) || typeof item.byteLength !== "number" || !Number.isSafeInteger(item.byteLength) || item.byteLength < 1 || item.byteLength > 512 * 1024) bad(label); return Object.freeze({ path: item.path, rawSha256: item.rawSha256, byteLength: item.byteLength, canonicalSha256: item.canonicalSha256 }); }
function readEndpointHashes(value: unknown, label: string): readonly [string, string] { if (!Array.isArray(value) || value.length !== 2 || !value.every(hash)) bad(label); return Object.freeze([value[0]!, value[1]!]) as readonly [string, string]; }
function readInventory(value: unknown, label: string): { readonly sha256: string; readonly entryCount: number; readonly leafCount: number } { const record = exact(value, ["sha256", "entryCount", "leafCount"], label); if (!hash(record.sha256) || !count(record.entryCount, 2048) || !count(record.leafCount, 1024)) bad(`${label} inventory`); return Object.freeze({ sha256: record.sha256, entryCount: record.entryCount, leafCount: record.leafCount }); }
function sameInventory(value: unknown, label: string): boolean { try { readInventory(value, label); return true; } catch { return false; } }
function readRef(value: unknown, prefix: string): Ref { const record = exact(value, ["id", "sha256"], "Retained-trace journal reference"), idValue = str(record.id, "Retained-trace reference id"), sha256 = str(record.sha256, "Retained-trace reference hash"); if (!SHA256.test(sha256) || idValue !== `${prefix}${sha256.slice(0, 32)}`) bad("retained-trace journal reference"); return Object.freeze({ id: idValue, sha256 }); }
function hash(value: unknown): value is string { return typeof value === "string" && SHA256.test(value); }
function id(value: unknown): value is string { return typeof value === "string" && /^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$/u.test(value); }
function count(value: unknown, max: number): value is number { return typeof value === "number" && Number.isSafeInteger(value) && value >= 1 && value <= max; }
function revision(value: unknown): value is number { return typeof value === "number" && Number.isSafeInteger(value) && value >= 1 && value <= 1_000_000; }
function str(value: unknown, label: string): string { if (typeof value !== "string") bad(label); return value; }
function frozen<T>(value: T): T { if (value && typeof value === "object" && !Object.isFrozen(value)) { for (const child of Object.values(value as object)) frozen(child); Object.freeze(value); } return value; }
function bad(label: string): never { throw storeError("store_integrity_failed", `Checkpoint storyboard retained-trace journal ${label} is invalid.`); }
