/** Signed, append-only C6C B3a relation-resolution journal.  B3b's package receipt is only
 * diagnostic; this host-store journal is the durable relation authority boundary. */
import { createHash } from "node:crypto";
import { opendir } from "node:fs/promises";
import { join } from "node:path";
import { canonicalJson, canonicalJsonSha256, validateMotionRelations } from "@shellx-motion/core";
import type { C6B3bExactBase } from "./checkpoint-storyboard-relation-materialize-private/checkpoint-storyboard-relation-materialize-receipt-private.js";
import type { CheckpointStoryboardRelationMaterializationInstalledOutput } from "./checkpoint-storyboard-relation-materialize-private/checkpoint-storyboard-relation-materialize-output-private.js";
import { readSignedFile, replaceSignedFile, syncPrivateDirectory, writeExclusiveSignedFile } from "./checkpoint-storyboard-record-store-signed-files.js";
import { readLineageMembers } from "./checkpoint-storyboard-materialization-bindings.js";
import { readStoredRecordUnlocked } from "./checkpoint-storyboard-record-store-state.js";
import { MAX_STATE_BYTES, SHA256, exact, readIdentity, sameIdentity, storeError, type AuthorityFacts, type CheckpointStoryboardRecordIdentity } from "./checkpoint-storyboard-record-store-types.js";

const MAX_JOURNAL_BYTES = 192 * 1024;
const HANDLE = /^checkpoint_storyboard_relation_output_[a-f0-9]{32}$/u;
const FILE = /^checkpoint_storyboard_[a-f0-9]{32}\.(?:state|intent|binding|cow-start|detach|abandon)\.json$/u;
const PREFIX = {
  intent: "checkpoint_storyboard_relation_resolution_intent_",
  cowStart: "checkpoint_storyboard_relation_resolution_cow_start_",
  binding: "checkpoint_storyboard_relation_resolution_binding_",
  detach: "checkpoint_storyboard_relation_resolution_detach_",
  abandon: "checkpoint_storyboard_relation_resolution_abandon_",
} as const;
type Ref = Readonly<{ id: string; sha256: string }>;
export type CheckpointStoryboardRelationResolutionState = "unbound" | "preparing" | "bound" | "detached" | "abandoned";
export type RelationPlanIdentity = Readonly<{ planFingerprint: string; profileFingerprint: string; storeSha256: string; staticFingerprint: string; gpuStaticFingerprint: string; startFramePlanFingerprint: string; endFramePlanFingerprint: string }>;
export type RelationOutputIdentity = CheckpointStoryboardRelationMaterializationInstalledOutput;
export type RelationIntent = Readonly<{ schema: "shellx-motion/private-checkpoint-storyboard-relation-resolution-intent@1"; id: string; sha256: string; identity: CheckpointStoryboardRecordIdentity; root: CheckpointStoryboardRecordIdentity; plan: RelationPlanIdentity; expectedBase: C6B3bExactBase; outputHandle: string }>;
export type RelationCowStart = Readonly<{ schema: "shellx-motion/private-checkpoint-storyboard-relation-resolution-cow-start@1"; id: string; sha256: string; identity: CheckpointStoryboardRecordIdentity; root: CheckpointStoryboardRecordIdentity; intent: Ref }>;
export type RelationBinding = Readonly<{ schema: "shellx-motion/private-checkpoint-storyboard-relation-resolution-binding@1"; id: string; sha256: string; identity: CheckpointStoryboardRecordIdentity; root: CheckpointStoryboardRecordIdentity; intent: Ref; plan: RelationPlanIdentity; source: Readonly<{ expected: C6B3bExactBase; reopened: C6B3bExactBase }>; output: Readonly<{ expected: RelationOutputIdentity; reopened: RelationOutputIdentity }>; receiptFingerprint: string; outputHandle: string }>;
export type RelationDetach = Readonly<{ schema: "shellx-motion/private-checkpoint-storyboard-relation-resolution-detach@1"; id: string; sha256: string; identity: CheckpointStoryboardRecordIdentity; root: CheckpointStoryboardRecordIdentity; binding: Ref }>;
export type RelationAbandon = Readonly<{ schema: "shellx-motion/private-checkpoint-storyboard-relation-resolution-abandon@1"; id: string; sha256: string; identity: CheckpointStoryboardRecordIdentity; root: CheckpointStoryboardRecordIdentity; intent: Ref; reason: "proven-no-install" | "no-cow-start" }>;
export type RelationStateHead = Readonly<{ schema: "shellx-motion/private-checkpoint-storyboard-relation-resolution-state@1"; identity: CheckpointStoryboardRecordIdentity; root: CheckpointStoryboardRecordIdentity; state: CheckpointStoryboardRelationResolutionState; active: 0 | 1; intent?: Ref; cowStart?: Ref; binding?: Ref; detach?: Ref; abandon?: Ref }>;
export type RelationResolutionBindingState = Readonly<{ state: CheckpointStoryboardRelationResolutionState; active: 0 | 1; bindingId?: string; outputHandle?: string; receiptFingerprint?: string }>;

export function createRelationIntent(input: Omit<RelationIntent, "schema" | "id" | "sha256">): RelationIntent { return seal("intent", "shellx-motion/private-checkpoint-storyboard-relation-resolution-intent@1", input); }
export function createRelationCowStart(input: Omit<RelationCowStart, "schema" | "id" | "sha256">): RelationCowStart { return seal("cowStart", "shellx-motion/private-checkpoint-storyboard-relation-resolution-cow-start@1", input); }
export function createRelationBinding(input: Omit<RelationBinding, "schema" | "id" | "sha256">): RelationBinding { return seal("binding", "shellx-motion/private-checkpoint-storyboard-relation-resolution-binding@1", input); }
export function createRelationDetach(input: Omit<RelationDetach, "schema" | "id" | "sha256">): RelationDetach { return seal("detach", "shellx-motion/private-checkpoint-storyboard-relation-resolution-detach@1", input); }
export function createRelationAbandon(input: Omit<RelationAbandon, "schema" | "id" | "sha256">): RelationAbandon { return seal("abandon", "shellx-motion/private-checkpoint-storyboard-relation-resolution-abandon@1", input); }
export function relationStateHead(identity: CheckpointStoryboardRecordIdentity, root: CheckpointStoryboardRecordIdentity, state: CheckpointStoryboardRelationResolutionState, active: 0 | 1, refs: Partial<Pick<RelationStateHead, "intent" | "cowStart" | "binding" | "detach" | "abandon">> = {}): RelationStateHead { return Object.freeze({ schema: "shellx-motion/private-checkpoint-storyboard-relation-resolution-state@1", identity, root, state, active, ...refs }); }
export async function initializeRelationStateHead(facts: AuthorityFacts, identity: CheckpointStoryboardRecordIdentity, root: CheckpointStoryboardRecordIdentity): Promise<void> { await publishExact(statePath(facts, identity), relationStateHead(identity, root, "unbound", 0), facts); }

export async function publishRelationIntent(facts: AuthorityFacts, value: RelationIntent): Promise<void> { await publishExact(path(facts, value.identity, "intent"), value, facts); }
export async function publishRelationCowStart(facts: AuthorityFacts, value: RelationCowStart): Promise<void> { await publishExact(path(facts, value.identity, "cow-start"), value, facts); }
export async function publishRelationBinding(facts: AuthorityFacts, value: RelationBinding): Promise<void> { await publishExact(path(facts, value.identity, "binding"), value, facts); }
export async function publishRelationDetach(facts: AuthorityFacts, value: RelationDetach): Promise<void> { await publishExact(path(facts, value.identity, "detach"), value, facts); }
export async function publishRelationAbandon(facts: AuthorityFacts, value: RelationAbandon): Promise<void> { await publishExact(path(facts, value.identity, "abandon"), value, facts); }
export async function publishRelationStateHead(facts: AuthorityFacts, value: RelationStateHead, afterRename?: () => void | Promise<void>): Promise<void> { await replaceSignedFile(statePath(facts, value.identity), value, facts, MAX_STATE_BYTES, afterRename); }

export async function readRelationIntent(facts: AuthorityFacts, identity: CheckpointStoryboardRecordIdentity): Promise<RelationIntent | null> { return await optional(path(facts, identity, "intent"), facts, readIntent); }
export async function readRelationCowStart(facts: AuthorityFacts, identity: CheckpointStoryboardRecordIdentity): Promise<RelationCowStart | null> { return await optional(path(facts, identity, "cow-start"), facts, readStart); }
export async function readRelationBinding(facts: AuthorityFacts, identity: CheckpointStoryboardRecordIdentity): Promise<RelationBinding | null> { return await optional(path(facts, identity, "binding"), facts, readBinding); }
export async function readRelationStateHead(facts: AuthorityFacts, identityId: string): Promise<RelationStateHead | null> {
  if (!/^checkpoint_storyboard_[a-f0-9]{32}$/u.test(identityId)) throw storeError("store_integrity_failed", "Checkpoint storyboard relation state filename identity is invalid.");
  return await optional(join(facts.relationResolutions.path, `${identityId}.state.json`), facts, readHead);
}
export async function assertNoRelationResolutionEvidence(facts: AuthorityFacts, identity: CheckpointStoryboardRecordIdentity): Promise<void> {
  if (await readRelationStateHead(facts, identity.id) || await readRelationIntent(facts, identity) || await readRelationCowStart(facts, identity) || await readRelationBinding(facts, identity) || await optional(path(facts, identity, "detach"), facts, readDetach) || await optional(path(facts, identity, "abandon"), facts, readAbandon)) throw storeError("store_integrity_failed", "Checkpoint storyboard non-relation record has forbidden C6B3a relation-resolution evidence.");
}

/** Read all signed phases together. A forward head repair is legal only under the resolver lock. */
export async function readRelationResolutionState(facts: AuthorityFacts, identity: CheckpointStoryboardRecordIdentity, root: CheckpointStoryboardRecordIdentity, options: { readonly requireHead?: boolean; readonly allowForwardRecovery?: boolean } = {}): Promise<RelationResolutionBindingState> {
  await syncRelationDirectory(facts);
  const allowForwardRecovery = options.allowForwardRecovery ?? false;
  const head = await optional(statePath(facts, identity), facts, readHead), intent = await readRelationIntent(facts, identity), start = await readRelationCowStart(facts, identity), binding = await readRelationBinding(facts, identity), detach = await optional(path(facts, identity, "detach"), facts, readDetach), abandon = await optional(path(facts, identity, "abandon"), facts, readAbandon);
  if (!head) {
    if (!options.requireHead && !intent && !start && !binding && !detach && !abandon) return Object.freeze({ state: "unbound" as const, active: 0 as const });
    if (intent && !start && !binding && !detach && !abandon && allowForwardRecovery) {
      const next = relationStateHead(identity, root, "preparing", 0, { intent: ref(intent) }); await publishRelationStateHead(facts, next); return await reopenPromoted(facts, identity, root, next, Object.freeze({ state: "preparing" as const, active: 0 as const, outputHandle: intent.outputHandle }));
    }
    throw storeError(intent ? "record_commit_uncertain" : "store_integrity_failed", "Checkpoint storyboard relation resolution is missing its required signed state head.");
  }
  if (!sameIdentity(head.identity, identity) || !sameIdentity(head.root, root)) throw storeError("store_integrity_failed", "Checkpoint storyboard relation state head does not bind this record lineage.");
  if (!intent) {
    if (start || binding || detach || abandon) throw storeError("store_integrity_failed", "Checkpoint storyboard relation unbound state has phase evidence.");
    return await checkedRelationHead(facts, head, Object.freeze({ state: "unbound" as const, active: 0 as const }), allowForwardRecovery);
  }
  if (!sameIdentity(intent.identity, identity) || !sameIdentity(intent.root, root)) throw storeError("store_integrity_failed", "Checkpoint storyboard relation intent does not bind this record lineage.");
  if (!binding) {
    if (detach) throw storeError("store_integrity_failed", "Checkpoint storyboard relation detach has no immutable binding.");
    if (start && (!sameIdentity(start.identity, identity) || !sameIdentity(start.root, root) || !sameRef(start.intent, intent))) throw storeError("store_integrity_failed", "Checkpoint storyboard relation COW start does not bind its intent.");
    if (abandon) {
      if (!sameIdentity(abandon.identity, identity) || !sameIdentity(abandon.root, root) || !sameRef(abandon.intent, intent) || (abandon.reason === "no-cow-start" && start) || (abandon.reason === "proven-no-install" && !start)) throw storeError("store_integrity_failed", "Checkpoint storyboard relation abandonment is inconsistent.");
      return await checkedRelationHead(facts, head, Object.freeze({ state: "abandoned" as const, active: 0 as const, outputHandle: intent.outputHandle }), allowForwardRecovery, intent, start ?? undefined, undefined, undefined, abandon);
    }
    return await checkedRelationHead(facts, head, Object.freeze({ state: "preparing" as const, active: 0 as const, outputHandle: intent.outputHandle }), allowForwardRecovery, intent, start ?? undefined);
  }
  if (!start || abandon || !sameIdentity(binding.identity, identity) || !sameIdentity(binding.root, root) || !sameRef(binding.intent, intent) || binding.outputHandle !== intent.outputHandle || !samePlan(binding.plan, intent.plan) || canonicalJson(binding.source.expected) !== canonicalJson(intent.expectedBase) || !sameIdentity(binding.output.expected.storyboard, identity) || !sameIdentity(binding.output.reopened.storyboard, identity) || !sameIdentity(start.identity, identity) || !sameIdentity(start.root, root) || !sameRef(start.intent, intent)) throw storeError("store_integrity_failed", "Checkpoint storyboard relation binding does not semantically bind its durable intent, identity, and COW start.");
  if (!detach) {
    return await checkedRelationHead(facts, head, Object.freeze({ state: "bound" as const, active: 1 as const, bindingId: binding.id, outputHandle: binding.outputHandle, receiptFingerprint: binding.receiptFingerprint }), allowForwardRecovery, intent, start, binding);
  }
  if (!sameIdentity(detach.identity, identity) || !sameIdentity(detach.root, root) || !sameRef(detach.binding, binding)) throw storeError("store_integrity_failed", "Checkpoint storyboard relation detach does not bind its immutable binding.");
  return await checkedRelationHead(facts, head, Object.freeze({ state: "detached" as const, active: 0 as const, bindingId: binding.id, outputHandle: binding.outputHandle, receiptFingerprint: binding.receiptFingerprint }), allowForwardRecovery, intent, start, binding, detach);
}

export async function assertLineageHasNoPreparingOrBoundRelationResolutions(facts: AuthorityFacts, root: CheckpointStoryboardRecordIdentity, requireHeadsFor = new Set<string>()): Promise<void> {
  const members = await readLineageMembers(facts, root);
  if (members.length === 0) throw storeError("store_integrity_failed", "Checkpoint storyboard lineage has no signed membership records.");
  for (const member of members) {
    if (!sameIdentity(member.root, root)) throw storeError("store_integrity_failed", "Checkpoint storyboard lineage membership root changed.");
    const state = await readRelationResolutionState(facts, member.identity, root, { requireHead: requireHeadsFor.has(member.identity.id) });
    if (state.state === "preparing" || state.state === "bound") throw storeError("materialization_binding_conflict", "Checkpoint storyboard remove/archive requires every signed lineage member to be relation-unbound or detached.");
  }
}

/** Archive scans the entire append-only namespace, so copied, foreign, hidden, or missing
 * relation phases cannot be concealed by a caller-selected lineage roster. */
export async function assertRelationResolutionJournalCompleteForLineage(facts: AuthorityFacts, root: CheckpointStoryboardRecordIdentity, requireHeadsFor = new Set<string>()): Promise<void> {
  const members = await readLineageMembers(facts, root);
  const byId = new Map(members.map((member) => [member.identity.id, member.identity]));
  const reader = await opendir(facts.relationResolutions.path);
  try {
    for await (const entry of reader) {
      if (!entry.isFile() || !FILE.test(entry.name)) throw storeError("store_integrity_failed", "Checkpoint storyboard relation-resolution journal contains an invalid entry.");
      const identityId = entry.name.slice(0, 54), identity = byId.get(identityId), head = await readRelationStateHead(facts, identityId);
      if (!head) throw storeError("store_integrity_failed", "Checkpoint storyboard relation-resolution journal state head is missing.");
      if (head.identity.id !== identityId) throw storeError("store_integrity_failed", "Checkpoint storyboard relation-resolution filename does not match its signed identity.");
      if (identity) {
        if (!requireHeadsFor.has(identity.id)) throw storeError("store_integrity_failed", "Checkpoint storyboard relation-resolution journal attaches to a sealed non-relation lineage member.");
        if (!sameIdentity(head.root, root) || !sameIdentity(head.identity, identity)) throw storeError("store_integrity_failed", "Checkpoint storyboard relation-resolution journal state head changed roots or identities.");
      } else {
        const foreignMembers = await readLineageMembers(facts, head.root);
        const foreign = foreignMembers.find((member) => sameIdentity(member.identity, head.identity));
        if (!foreign || !sameIdentity(foreign.root, head.root)) throw storeError("store_integrity_failed", "Checkpoint storyboard relation-resolution journal references an unknown lineage member.");
        const foreignRecord = await readStoredRecordUnlocked(facts, head.identity);
        if (foreignRecord.admission.profile !== "c6b3-relation@1") throw storeError("store_integrity_failed", "Checkpoint storyboard relation-resolution journal attaches to a foreign non-relation member.");
        await readRelationResolutionState(facts, head.identity, head.root, { requireHead: true });
      }
    }
  } finally { await reader.close().catch(() => undefined); }
  for (const member of members) await readRelationResolutionState(facts, member.identity, root, { requireHead: requireHeadsFor.has(member.identity.id) });
}

function path(facts: AuthorityFacts, identity: CheckpointStoryboardRecordIdentity, kind: "intent" | "cow-start" | "binding" | "detach" | "abandon"): string { return join(facts.relationResolutions.path, `${identity.id}.${kind}.json`); }
function statePath(facts: AuthorityFacts, identity: CheckpointStoryboardRecordIdentity): string { return join(facts.relationResolutions.path, `${identity.id}.state.json`); }
async function optional<T>(file: string, facts: AuthorityFacts, read: (value: unknown) => T): Promise<T | null> { try { return read(await readSignedFile(file, facts, MAX_JOURNAL_BYTES, "record_not_found")); } catch (error) { if (error instanceof Error && (error as { code?: string }).code === "record_not_found") return null; throw error; } }
async function syncRelationDirectory(facts: AuthorityFacts): Promise<void> { try { await syncPrivateDirectory(facts.relationResolutions.path); } catch { throw storeError("record_commit_uncertain", "Checkpoint storyboard relation-resolution state requires a durable directory resync."); } }
async function checkedRelationHead(facts: AuthorityFacts, head: RelationStateHead, state: RelationResolutionBindingState, allowForwardRecovery: boolean, intent?: RelationIntent, cowStart?: RelationCowStart, binding?: RelationBinding, detach?: RelationDetach, abandon?: RelationAbandon): Promise<RelationResolutionBindingState> {
  const matches = (actual: Ref | undefined, value: { readonly id: string; readonly sha256: string } | undefined) => value ? sameRef(actual, value) : !actual;
  if (!legalRelationHead(head)) throw storeError("store_integrity_failed", "Checkpoint storyboard relation state head has fields invalid for its durable phase.");
  const exactHead = head.state === state.state && head.active === state.active && matches(head.intent, intent) && matches(head.cowStart, cowStart) && matches(head.binding, binding) && matches(head.detach, detach) && matches(head.abandon, abandon);
  if (exactHead) return state;
  if (!allowForwardRecovery) throw storeError("record_commit_uncertain", "Checkpoint storyboard relation phase evidence is one publication ahead of its signed state head; read-only lifecycle inspection will not repair it.");
  const next = relationStateHead(head.identity, head.root, state.state, state.active, { ...(intent ? { intent: ref(intent) } : {}), ...(cowStart ? { cowStart: ref(cowStart) } : {}), ...(binding ? { binding: ref(binding) } : {}), ...(detach ? { detach: ref(detach) } : {}), ...(abandon ? { abandon: ref(abandon) } : {}) });
  const oneStep = (head.state === "unbound" && state.state === "preparing" && !!intent && !cowStart)
    || (head.state === "preparing" && state.state === "preparing" && !!intent && !!cowStart && matches(head.intent, intent) && !head.cowStart)
    || (head.state === "preparing" && state.state === "bound" && !!intent && !!cowStart && !!binding && matches(head.intent, intent) && matches(head.cowStart, cowStart))
    || (head.state === "preparing" && state.state === "abandoned" && !!intent && !!abandon && matches(head.intent, intent) && matches(head.cowStart, cowStart))
    || (head.state === "bound" && state.state === "detached" && !!intent && !!cowStart && !!binding && !!detach && matches(head.intent, intent) && matches(head.cowStart, cowStart) && matches(head.binding, binding));
  if (!oneStep) throw storeError("store_integrity_failed", "Checkpoint storyboard relation state head skips, diverges from, or rolls back immutable phase evidence.");
  await publishRelationStateHead(facts, next);
  return await reopenPromoted(facts, head.identity, head.root, next, state);
}
function legalRelationHead(head: RelationStateHead): boolean {
  return (head.state === "unbound" && head.active === 0 && !hasRef(head))
    || (head.state === "preparing" && head.active === 0 && !!head.intent && !head.binding && !head.detach && !head.abandon)
    || (head.state === "bound" && head.active === 1 && !!head.intent && !!head.cowStart && !!head.binding && !head.detach && !head.abandon)
    || (head.state === "detached" && head.active === 0 && !!head.intent && !!head.cowStart && !!head.binding && !!head.detach && !head.abandon)
    || (head.state === "abandoned" && head.active === 0 && !!head.intent && !!head.abandon && !head.binding && !head.detach);
}
async function reopenPromoted(facts: AuthorityFacts, identity: CheckpointStoryboardRecordIdentity, root: CheckpointStoryboardRecordIdentity, expected: RelationStateHead, state: RelationResolutionBindingState): Promise<RelationResolutionBindingState> {
  const reopened = await optional(statePath(facts, identity), facts, readHead);
  if (!reopened || canonicalJson(reopened) !== canonicalJson(expected)) throw storeError("record_commit_uncertain", "Checkpoint storyboard relation state head promotion could not be reopened exactly.");
  await syncRelationDirectory(facts);
  return state;
}
async function publishExact(file: string, value: object, facts: AuthorityFacts): Promise<void> { try { await writeExclusiveSignedFile(file, value, facts, MAX_JOURNAL_BYTES); } catch (error) { if (!(error instanceof Error) || (error as { code?: string }).code !== "record_identity_conflict") throw error; const existing = await readSignedFile(file, facts, MAX_JOURNAL_BYTES, "record_not_found"); if (canonicalJson(existing) !== canonicalJson(value)) throw storeError("materialization_binding_conflict", "Checkpoint storyboard immutable relation journal leaf is already occupied by different content."); } }
function seal<K extends keyof typeof PREFIX, S extends string, T extends object>(kind: K, schema: S, payload: T): T & { readonly schema: S; readonly id: string; readonly sha256: string } { const sha256 = createHash("sha256").update(canonicalJson({ schema, ...payload })).digest("hex"), id = `${PREFIX[kind]}${sha256.slice(0, 32)}`; return Object.freeze({ schema, id, sha256, ...payload }); }
function ref(value: { readonly id: string; readonly sha256: string }): Ref { return Object.freeze({ id: value.id, sha256: value.sha256 }); }
function sameRef(value: Ref | undefined, target: { readonly id: string; readonly sha256: string }): boolean { return !!value && value.id === target.id && value.sha256 === target.sha256; }
function hasRef(head: RelationStateHead): boolean { return !!(head.intent || head.cowStart || head.binding || head.detach || head.abandon); }
function readIntent(value: unknown): RelationIntent { const record = exact(value, ["schema", "id", "sha256", "identity", "root", "plan", "expectedBase", "outputHandle"], "Relation resolution intent"); if (record.schema !== "shellx-motion/private-checkpoint-storyboard-relation-resolution-intent@1") throw storeError("store_integrity_failed", "Checkpoint storyboard relation intent schema is invalid."); const identity = readIdentity(record.identity, "Relation resolution intent identity"), root = readIdentity(record.root, "Relation resolution intent root"), plan = readPlan(record.plan), expectedBase = readBase(record.expectedBase, "Relation resolution intent expected base"), outputHandle = str(record.outputHandle, "Relation resolution intent output handle"); if (!HANDLE.test(outputHandle) || !samePlan(plan, expectedBase)) throw storeError("store_integrity_failed", "Checkpoint storyboard relation intent output handle or exact plan facts are invalid."); return checked(record, PREFIX.intent, { schema: record.schema, identity, root, plan, expectedBase, outputHandle }) as RelationIntent; }
function readStart(value: unknown): RelationCowStart { const record = exact(value, ["schema", "id", "sha256", "identity", "root", "intent"], "Relation resolution COW start"); if (record.schema !== "shellx-motion/private-checkpoint-storyboard-relation-resolution-cow-start@1") throw storeError("store_integrity_failed", "Checkpoint storyboard relation COW start schema is invalid."); return checked(record, PREFIX.cowStart, { schema: record.schema, identity: readIdentity(record.identity, "Relation start identity"), root: readIdentity(record.root, "Relation start root"), intent: readRef(record.intent, PREFIX.intent) }) as RelationCowStart; }
function readBinding(value: unknown): RelationBinding { const record = exact(value, ["schema", "id", "sha256", "identity", "root", "intent", "plan", "source", "output", "receiptFingerprint", "outputHandle"], "Relation resolution binding"); if (record.schema !== "shellx-motion/private-checkpoint-storyboard-relation-resolution-binding@1") throw storeError("store_integrity_failed", "Checkpoint storyboard relation binding schema is invalid."); const source = basePair(record.source, "Relation binding source"), output = outputPair(record.output, "Relation binding output"), receiptFingerprint = str(record.receiptFingerprint, "Relation binding receipt fingerprint"), outputHandle = str(record.outputHandle, "Relation binding output handle"), plan = readPlan(record.plan); if (!SHA256.test(receiptFingerprint) || !HANDLE.test(outputHandle) || receiptFingerprint !== output.expected.receipt.fingerprint || !samePlan(plan, source.expected) || !samePlan(plan, output.expected) || output.expected.package.id !== source.expected.packageId || output.expected.package.manifest.rawSha256 !== source.expected.manifestRawSha256 || output.expected.package.manifest.canonicalSha256 !== source.expected.manifestCanonicalSha256) throw storeError("store_integrity_failed", "Checkpoint storyboard relation binding handle, receipt, package identity, or durable plan facts are inconsistent."); return checked(record, PREFIX.binding, { schema: record.schema, identity: readIdentity(record.identity, "Relation binding identity"), root: readIdentity(record.root, "Relation binding root"), intent: readRef(record.intent, PREFIX.intent), plan, source, output, receiptFingerprint, outputHandle }) as RelationBinding; }
function readDetach(value: unknown): RelationDetach { const record = exact(value, ["schema", "id", "sha256", "identity", "root", "binding"], "Relation resolution detach"); if (record.schema !== "shellx-motion/private-checkpoint-storyboard-relation-resolution-detach@1") throw storeError("store_integrity_failed", "Checkpoint storyboard relation detach schema is invalid."); return checked(record, PREFIX.detach, { schema: record.schema, identity: readIdentity(record.identity, "Relation detach identity"), root: readIdentity(record.root, "Relation detach root"), binding: readRef(record.binding, PREFIX.binding) }) as RelationDetach; }
function readAbandon(value: unknown): RelationAbandon { const record = exact(value, ["schema", "id", "sha256", "identity", "root", "intent", "reason"], "Relation resolution abandon"); const reason = record.reason; if (record.schema !== "shellx-motion/private-checkpoint-storyboard-relation-resolution-abandon@1" || (reason !== "proven-no-install" && reason !== "no-cow-start")) throw storeError("store_integrity_failed", "Checkpoint storyboard relation abandonment is invalid."); return checked(record, PREFIX.abandon, { schema: record.schema, identity: readIdentity(record.identity, "Relation abandon identity"), root: readIdentity(record.root, "Relation abandon root"), intent: readRef(record.intent, PREFIX.intent), reason }) as RelationAbandon; }
function readHead(value: unknown): RelationStateHead { const record = exact(value, ["schema", "identity", "root", "state", "active"], ["intent", "cowStart", "binding", "detach", "abandon"], "Relation resolution state"); const state = record.state; if (record.schema !== "shellx-motion/private-checkpoint-storyboard-relation-resolution-state@1" || (state !== "unbound" && state !== "preparing" && state !== "bound" && state !== "detached" && state !== "abandoned") || (record.active !== 0 && record.active !== 1)) throw storeError("store_integrity_failed", "Checkpoint storyboard relation state head is invalid."); const read = (key: "intent" | "cowStart" | "binding" | "detach" | "abandon", prefix: string) => Object.hasOwn(record, key) ? readRef(record[key], prefix) : undefined; return Object.freeze({ schema: record.schema, identity: readIdentity(record.identity, "Relation state identity"), root: readIdentity(record.root, "Relation state root"), state, active: record.active, ...(read("intent", PREFIX.intent) ? { intent: read("intent", PREFIX.intent) } : {}), ...(read("cowStart", PREFIX.cowStart) ? { cowStart: read("cowStart", PREFIX.cowStart) } : {}), ...(read("binding", PREFIX.binding) ? { binding: read("binding", PREFIX.binding) } : {}), ...(read("detach", PREFIX.detach) ? { detach: read("detach", PREFIX.detach) } : {}), ...(read("abandon", PREFIX.abandon) ? { abandon: read("abandon", PREFIX.abandon) } : {}) }); }
function checked(record: Record<string, unknown>, prefix: string, payload: object): object { const id = str(record.id, "Relation journal id"), sha256 = str(record.sha256, "Relation journal sha256"), expected = createHash("sha256").update(canonicalJson(payload)).digest("hex"); if (!SHA256.test(sha256) || sha256 !== expected || id !== `${prefix}${sha256.slice(0, 32)}`) throw storeError("store_integrity_failed", "Checkpoint storyboard relation journal deterministic identity is invalid."); return Object.freeze({ ...payload, id, sha256 }); }
function readPlan(value: unknown): RelationPlanIdentity { const record = exact(value, ["planFingerprint", "profileFingerprint", "storeSha256", "staticFingerprint", "gpuStaticFingerprint", "startFramePlanFingerprint", "endFramePlanFingerprint"], "Relation resolution plan"); for (const key of Object.keys(record)) if (typeof record[key] !== "string" || !SHA256.test(record[key] as string)) throw storeError("store_integrity_failed", "Checkpoint storyboard relation plan fingerprint is invalid."); return Object.freeze(record as RelationPlanIdentity); }
function readBase(value: unknown, label: string): C6B3bExactBase { const record = exact(value, ["packageId", "manifestRawSha256", "motionRawSha256", "manifestCanonicalSha256", "motionCanonicalSha256", "inventory", "planFingerprint", "profileFingerprint", "storeSha256", "staticFingerprint", "gpuStaticFingerprint", "startFramePlanFingerprint", "endFramePlanFingerprint"], label); if (!validId(record.packageId)) throw storeError("store_integrity_failed", `${label}.packageId is invalid.`); for (const key of ["manifestRawSha256", "motionRawSha256", "manifestCanonicalSha256", "motionCanonicalSha256", "planFingerprint", "profileFingerprint", "storeSha256", "staticFingerprint", "gpuStaticFingerprint", "startFramePlanFingerprint", "endFramePlanFingerprint"] as const) if (typeof record[key] !== "string" || !SHA256.test(record[key] as string)) throw storeError("store_integrity_failed", `${label}.${key} is invalid.`); const inventory = exact(record.inventory, ["sha256", "entryCount", "leafCount"], `${label}.inventory`); if (typeof inventory.sha256 !== "string" || !SHA256.test(inventory.sha256) || !count(inventory.entryCount, 2048) || !count(inventory.leafCount, 1024)) throw storeError("store_integrity_failed", `${label}.inventory is invalid.`); return Object.freeze({ ...record, inventory: Object.freeze({ sha256: inventory.sha256, entryCount: inventory.entryCount as number, leafCount: inventory.leafCount as number }) }) as C6B3bExactBase; }
function basePair(value: unknown, label: string): RelationBinding["source"] { const record = exact(value, ["expected", "reopened"], label), expected = readBase(record.expected, `${label}.expected`), reopened = readBase(record.reopened, `${label}.reopened`); if (canonicalJson(expected) !== canonicalJson(reopened)) throw storeError("store_integrity_failed", `${label} exact reopen identity is inconsistent.`); return Object.freeze({ expected, reopened }); }
function outputPair(value: unknown, label: string): RelationBinding["output"] { const record = exact(value, ["expected", "reopened"], label), expected = readOutput(record.expected, `${label}.expected`), reopened = readOutput(record.reopened, `${label}.reopened`); if (canonicalJson(expected) !== canonicalJson(reopened)) throw storeError("store_integrity_failed", `${label} exact reopen identity is inconsistent.`); return Object.freeze({ expected, reopened }); }
function readOutput(value: unknown, label: string): RelationOutputIdentity {
  if (containsForbiddenField(value)) throw storeError("store_integrity_failed", `${label} contains forbidden host-authority fields.`);
  const root = exact(value, ["schema", "receipt", "package", "storyboard", "plan", "profile", "relationStore", "relationStatic", "gpuRelationStatic", "endpointFramePlans", "materialization"], label);
  if (root.schema !== "shellx-motion/private-checkpoint-storyboard-relation-materialization-installed-output@1") throw storeError("store_integrity_failed", `${label}.schema is invalid.`);
  const receipt = exact(root.receipt, ["schema", "fingerprint"], `${label}.receipt`), pkg = exact(root.package, ["id", "manifest", "motion", "currentInventory", "nonReceiptInventory", "preservedLeaves"], `${label}.package`), storyboard = exact(root.storyboard, ["id", "sha256", "revision"], `${label}.storyboard`), plan = exact(root.plan, ["fingerprint"], `${label}.plan`), profile = exact(root.profile, ["fingerprint"], `${label}.profile`), relationStore = exact(root.relationStore, ["schema", "sha256", "bindings"], `${label}.relationStore`), relationStatic = exact(root.relationStatic, ["fingerprint"], `${label}.relationStatic`), gpu = exact(root.gpuRelationStatic, ["fingerprint", "relationStaticFingerprint"], `${label}.gpuRelationStatic`), endpoints = exact(root.endpointFramePlans, ["startFingerprint", "endFingerprint"], `${label}.endpointFramePlans`), materialization = exact(root.materialization, ["changedMotionRoot", "changedLeafCount", "renderer"], `${label}.materialization`), renderer = exact(materialization.renderer, ["invoked", "pixels"], `${label}.materialization.renderer`);
  const manifest = exact(pkg.manifest, ["rawSha256", "canonicalSha256"], `${label}.package.manifest`), motion = exact(pkg.motion, ["rawSha256", "canonicalSha256"], `${label}.package.motion`), currentInventory = readInventory(pkg.currentInventory, `${label}.package.currentInventory`), nonReceiptInventory = readInventory(pkg.nonReceiptInventory, `${label}.package.nonReceiptInventory`), preserved = exact(pkg.preservedLeaves, ["sha256", "count"], `${label}.package.preservedLeaves`);
  if (receipt.schema !== "shellx-motion/private-checkpoint-storyboard-relation-materialization-receipt@1" || !hash(receipt.fingerprint) || !validId(pkg.id) || !hash(manifest.rawSha256) || !hash(manifest.canonicalSha256) || !hash(motion.rawSha256) || !hash(motion.canonicalSha256) || typeof storyboard.id !== "string" || !/^checkpoint_storyboard_[a-f0-9]{32}$/u.test(storyboard.id) || !hash(storyboard.sha256) || !count(storyboard.revision, 1_000_000) || !hash(plan.fingerprint) || !hash(profile.fingerprint) || relationStore.schema !== "shellx-motion/relations@1" || !hash(relationStore.sha256) || !Array.isArray(relationStore.bindings) || relationStore.bindings.length !== 1 || !hash(relationStatic.fingerprint) || !hash(gpu.fingerprint) || !hash(gpu.relationStaticFingerprint) || gpu.relationStaticFingerprint !== relationStatic.fingerprint || !hash(endpoints.startFingerprint) || !hash(endpoints.endFingerprint) || !hash(preserved.sha256) || !count(preserved.count, 1024) || currentInventory.entryCount !== nonReceiptInventory.entryCount + 1 || currentInventory.leafCount !== nonReceiptInventory.leafCount + 1 || materialization.changedMotionRoot !== "relations" || materialization.changedLeafCount !== 2 || renderer.invoked !== false || renderer.pixels !== false) throw storeError("store_integrity_failed", `${label} static output facts are invalid.`);
  const rawBinding = relationStore.bindings[0];
  const source = objectField(rawBinding, "source", label), target = objectField(rawBinding, "target", label), durationUs = objectNumber(rawBinding, "durationUs", label);
  const sourceId = objectString(source, "layerId", label), targetId = objectString(target, "layerId", label);
  if (durationUs % 1_000 !== 0 || durationUs <= 0 || durationUs > 3_600_000_000 || sourceId === targetId) throw storeError("store_integrity_failed", `${label} relation duration or endpoint identity is invalid.`);
  const relations = validateMotionRelations({ schema: relationStore.schema, bindings: structuredClone(relationStore.bindings) }, { durationMs: durationUs / 1_000, layers: [{ id: sourceId, type: "shape", transform: { x: 0, y: 0, rotation: 0, scale: 1 } }, { id: targetId, type: "shape", transform: { x: 0, y: 0, rotation: 0, scale: 1 } }] });
  if (!relations.ok || !relations.store || relations.store.bindings.length !== 1 || relations.bindings.length !== 1 || canonicalJsonSha256(relations.store) !== relationStore.sha256) throw storeError("store_integrity_failed", `${label} relation store is not a closed canonical relation store.`);
  const installed = relations.store.bindings[0]!, resolved = relations.bindings[0]!;
  if (installed.enabled !== true || installed.kind !== "attach" || installed.mode !== "follow" || installed.offset.space !== "world" || installed.offset.rotationDeg !== 0 || installed.offset.scale !== 1 || installed.source.layerId === installed.target.layerId || installed.startUs !== 0 || installed.durationUs !== durationUs || resolved.binding.id !== installed.id || resolved.binding.target.layerId !== installed.target.layerId || !sameMask(resolved.writeMask, ["transform.x", "transform.y"])) throw storeError("store_integrity_failed", `${label} relation store does not retain the exact target-only world-follow binding.`);
  const output: RelationOutputIdentity = {
    schema: "shellx-motion/private-checkpoint-storyboard-relation-materialization-installed-output@1",
    receipt: { schema: "shellx-motion/private-checkpoint-storyboard-relation-materialization-receipt@1", fingerprint: receipt.fingerprint as string },
    package: { id: pkg.id as string, manifest: { rawSha256: manifest.rawSha256 as string, canonicalSha256: manifest.canonicalSha256 as string }, motion: { rawSha256: motion.rawSha256 as string, canonicalSha256: motion.canonicalSha256 as string }, currentInventory, nonReceiptInventory, preservedLeaves: { sha256: preserved.sha256 as string, count: preserved.count as number } },
    storyboard: { id: storyboard.id as string, sha256: storyboard.sha256 as string, revision: storyboard.revision as number }, plan: { fingerprint: plan.fingerprint as string }, profile: { fingerprint: profile.fingerprint as string }, relationStore: { schema: "shellx-motion/relations@1", sha256: relationStore.sha256 as string, bindings: structuredClone(relations.store.bindings) }, relationStatic: { fingerprint: relationStatic.fingerprint as string }, gpuRelationStatic: { fingerprint: gpu.fingerprint as string, relationStaticFingerprint: gpu.relationStaticFingerprint as string }, endpointFramePlans: { startFingerprint: endpoints.startFingerprint as string, endFingerprint: endpoints.endFingerprint as string }, materialization: { changedMotionRoot: "relations", changedLeafCount: 2, renderer: { invoked: false, pixels: false } },
  };
  return frozen(output);
}
function containsForbiddenField(value: unknown): boolean { if (Array.isArray(value)) return value.some(containsForbiddenField); if (!value || typeof value !== "object") return false; return Object.entries(value).some(([key, child]) => /(?:path|workspace|approval|authority)/iu.test(key) || containsForbiddenField(child)); }
function objectField(value: unknown, key: string, label: string): Record<string, unknown> { if (!value || typeof value !== "object" || Array.isArray(value) || !Object.hasOwn(value, key)) throw storeError("store_integrity_failed", `${label} relation binding is invalid.`); const child = (value as Record<string, unknown>)[key]; if (!child || typeof child !== "object" || Array.isArray(child)) throw storeError("store_integrity_failed", `${label} relation binding is invalid.`); return child as Record<string, unknown>; }
function objectString(value: Record<string, unknown>, key: string, label: string): string { const candidate = value[key]; if (typeof candidate !== "string") throw storeError("store_integrity_failed", `${label} relation binding is invalid.`); return candidate; }
function objectNumber(value: unknown, key: string, label: string): number { if (!value || typeof value !== "object" || Array.isArray(value)) throw storeError("store_integrity_failed", `${label} relation binding is invalid.`); const candidate = (value as Record<string, unknown>)[key]; if (typeof candidate !== "number" || !Number.isSafeInteger(candidate)) throw storeError("store_integrity_failed", `${label} relation binding is invalid.`); return candidate; }
function sameMask(left: readonly string[], right: readonly string[]): boolean { return left.length === right.length && left.every((value, index) => value === right[index]); }
function samePlan(plan: RelationPlanIdentity, value: Pick<C6B3bExactBase, "planFingerprint" | "profileFingerprint" | "storeSha256" | "staticFingerprint" | "gpuStaticFingerprint" | "startFramePlanFingerprint" | "endFramePlanFingerprint"> | RelationOutputIdentity): boolean { if ("planFingerprint" in value) return plan.planFingerprint === value.planFingerprint && plan.profileFingerprint === value.profileFingerprint && plan.storeSha256 === value.storeSha256 && plan.staticFingerprint === value.staticFingerprint && plan.gpuStaticFingerprint === value.gpuStaticFingerprint && plan.startFramePlanFingerprint === value.startFramePlanFingerprint && plan.endFramePlanFingerprint === value.endFramePlanFingerprint; return plan.planFingerprint === value.plan.fingerprint && plan.profileFingerprint === value.profile.fingerprint && plan.storeSha256 === value.relationStore.sha256 && plan.staticFingerprint === value.relationStatic.fingerprint && plan.gpuStaticFingerprint === value.gpuRelationStatic.fingerprint && plan.startFramePlanFingerprint === value.endpointFramePlans.startFingerprint && plan.endFramePlanFingerprint === value.endpointFramePlans.endFingerprint; }
function frozen<T>(value: T): T { if (value && typeof value === "object" && !Object.isFrozen(value)) { for (const child of Object.values(value as object)) frozen(child); Object.freeze(value); } return value; }
function readInventory(value: unknown, label: string) { const record = exact(value, ["sha256", "entryCount", "leafCount"], label); if (!hash(record.sha256) || !count(record.entryCount, 2048) || !count(record.leafCount, 1024)) throw storeError("store_integrity_failed", `${label} is invalid.`); return Object.freeze({ sha256: record.sha256 as string, entryCount: record.entryCount as number, leafCount: record.leafCount as number }); }
function hash(value: unknown): value is string { return typeof value === "string" && SHA256.test(value); }
function validId(value: unknown): value is string { return typeof value === "string" && /^[A-Za-z0-9._-]{1,128}$/u.test(value); }
function count(value: unknown, max: number): value is number { return typeof value === "number" && Number.isSafeInteger(value) && value >= 1 && value <= max; }
function readRef(value: unknown, prefix: string): Ref { const record = exact(value, ["id", "sha256"], "Relation journal reference"), id = str(record.id, "Relation journal reference id"), sha256 = str(record.sha256, "Relation journal reference hash"); if (!SHA256.test(sha256) || id !== `${prefix}${sha256.slice(0, 32)}`) throw storeError("store_integrity_failed", "Checkpoint storyboard relation journal reference is invalid."); return Object.freeze({ id, sha256 }); }
function str(value: unknown, label: string): string { if (typeof value !== "string") throw storeError("store_integrity_failed", `${label} is invalid.`); return value; }
