/** C6C B3a private resolver. Debug/MCP owns the host authority and durable signed link only. */
import { lstat } from "node:fs/promises";
import { canonicalJson, isPublicationCommitUncertain } from "@shellx-motion/core";
import { materializeCheckpointStoryboardRelation, prepareCheckpointStoryboardRelationMaterialization, reopenCheckpointStoryboardRelationMaterializationOutput } from "./checkpoint-storyboard-relation-materialize-private/checkpoint-storyboard-relation-materialize-private.js";
import { readC6B3bReceipt, type C6B3bExactBase } from "./checkpoint-storyboard-relation-materialize-private/checkpoint-storyboard-relation-materialize-receipt-private.js";
import { assertCheckpointStoryboardRelationResolutionAuthorityStore, checkpointStoryboardRelationResolutionOutputHandle, checkedCheckpointStoryboardRelationResolutionAuthority, withCheckpointStoryboardRelationResolutionAuthority, withCheckpointStoryboardRelationResolutionOutputAuthority, type CheckpointStoryboardRelationResolutionAuthority } from "./checkpoint-storyboard-relation-resolution-authority.js";
import { createRelationAbandon, createRelationBinding, createRelationCowStart, createRelationDetach, createRelationIntent, publishRelationAbandon, publishRelationBinding, publishRelationCowStart, publishRelationDetach, publishRelationIntent, publishRelationStateHead, readRelationBinding, readRelationCowStart, readRelationIntent, readRelationResolutionState, relationStateHead, type RelationBinding, type RelationIntent, type RelationPlanIdentity } from "./checkpoint-storyboard-relation-resolution-journal.js";
import { assertNoLegacyMaterializationEvidence } from "./checkpoint-storyboard-materialization-bindings.js";
import { assertNoBehaviorResolutionEvidence } from "./checkpoint-storyboard-behavior-resolution-journal.js";
import { assertNoRelationActionResolutionEvidence } from "./checkpoint-storyboard-relation-action-resolution-journal.js";
import { assertNoLifecycleResolutionEvidence } from "./checkpoint-storyboard-lifecycle-resolution-journal.js";
import { assertNoGeometryMorphResolutionEvidence } from "./checkpoint-storyboard-geometry-morph-resolution-journal.js";
import { assertNoRetainedTraceResolutionEvidence } from "./checkpoint-storyboard-retained-trace-resolution-journal.js";
import { checkedAuthority, withLineageLock } from "./checkpoint-storyboard-record-store-authority.js";
import { readImmutableRecordRoot, readStoredRecordUnlocked } from "./checkpoint-storyboard-record-store-state.js";
import { CheckpointStoryboardRecordStoreError, sameIdentity, storeError, type CheckpointStoryboardRecordIdentity } from "./checkpoint-storyboard-record-store-types.js";

type RelationResolutionFaultPhase = "while-lineage-lock-held" | "after-intent-before-state-head" | "after-intent" | "after-cow-start-before-state-head" | "after-cow-start" | "before-c6b3b" | "after-c6b3b-commit" | "after-binding" | "after-bound-state-head-rename" | "after-detach" | "after-detached-state-head-rename" | "after-abandon";
type RelationResolutionFaultHooks = Partial<Record<RelationResolutionFaultPhase, () => void | Promise<void>>>;
const hooks = new WeakMap<CheckpointStoryboardRelationResolutionAuthority, RelationResolutionFaultHooks>();
/** Test-only seam. It is intentionally absent from the command registry. */
export function setCheckpointStoryboardRelationResolutionFaultHooksForTest(authority: CheckpointStoryboardRelationResolutionAuthority, value: RelationResolutionFaultHooks | undefined): void { checkedCheckpointStoryboardRelationResolutionAuthority(authority); if (value) hooks.set(authority, Object.freeze({ ...value })); else hooks.delete(authority); }
async function fault(authority: CheckpointStoryboardRelationResolutionAuthority, phase: RelationResolutionFaultPhase): Promise<void> { await hooks.get(authority)?.[phase]?.(); }

export interface CheckpointStoryboardRelationResolutionResult {
  readonly identity: CheckpointStoryboardRecordIdentity;
  readonly binding: { readonly state: "bound" | "detached"; readonly active: 0 | 1; readonly bindingId: string; readonly outputHandle: string; readonly receiptFingerprint: string };
  readonly renderer: { readonly invoked: false; readonly pixels: false };
  readonly replayed: boolean;
}

export async function resolveCheckpointStoryboardRelationStoredRecord(authority: CheckpointStoryboardRelationResolutionAuthority, identity: CheckpointStoryboardRecordIdentity): Promise<CheckpointStoryboardRelationResolutionResult> {
  try { return await withCheckpointStoryboardRelationResolutionOutputAuthority(authority, async (host) => {
    const store = checkedAuthority(host.store), root = await readImmutableRecordRoot(store, identity);
    return await withLineageLock(store, root.id, async () => {
      const record = await readStoredRecordUnlocked(store, identity); assertB3Record(record); assertCheckpointStoryboardRelationResolutionAuthorityStore(authority, host.store); await assertForeignPartitionEvidenceAbsent(store, identity);
      const outputHandle = checkpointStoryboardRelationResolutionOutputHandle(authority, identity);
      let state = await readRelationResolutionState(store, identity, root, { requireHead: true, allowForwardRecovery: true }); await fault(authority, "while-lineage-lock-held");
      if (state.state === "abandoned") throw storeError("materialization_binding_conflict", "Checkpoint storyboard relation resolution was terminally abandoned after a proved no-install outcome.");
      if (state.state === "detached") throw storeError("materialization_detached", "Checkpoint storyboard relation resolution has terminally detached its link and cannot resolve again.");
      if (state.state === "bound") return await replayBound(store, host, identity, root, state.bindingId!, outputHandle);
      const prior = await readRelationIntent(store, identity);
      if (prior) {
        const recovered = await recognizeInstalledOutput(host, record.identity, prior.expectedBase, prior.plan);
        if (recovered) return await publishAndReopen(store, host, authority, identity, root, prior, recovered, outputHandle, true);
        if (await outputExists(host.outputPackageRoot) || await readRelationCowStart(store, identity)) throw storeError("materialization_binding_uncertain", "Checkpoint storyboard relation resolution retains an occupied or COW-uncertain output for exact recovery and will not repeat COW.");
      } else if (await outputExists(host.outputPackageRoot)) throw storeError("materialization_binding_uncertain", "Checkpoint storyboard relation output is already occupied without a durable intent and was retained without replacement.");
      return await withCheckpointStoryboardRelationResolutionAuthority(authority, async (sourceHost) => {
        const c6bHost = { sourcePackageRoot: sourceHost.sourcePackageRoot, outputPackageRoot: sourceHost.outputPackageRoot, packageWorkspaceRoot: sourceHost.packageWorkspaceRoot, packageWorkspaceAuthority: sourceHost.packageWorkspaceAuthority };
        assertTwoCatalogOrderBindings(record.storyboard.objectCatalog, sourceHost.objectLayerBindings);
        // B3b canonicalizes source and absent output, including intermediate aliases, before it
        // mints approval or this resolver publishes an output intent.
        const prepared = await prepareCheckpointStoryboardRelationMaterialization(c6bHost, record.storyboard, sourceHost.objectLayerBindings);
        const plan = planIdentity(prepared.plan);
        const intent = createRelationIntent({ identity, root, plan, expectedBase: prepared.expected, outputHandle });
        if (prior && canonicalJson(prior) !== canonicalJson(intent)) throw storeError("materialization_binding_conflict", "Checkpoint storyboard relation intent conflicts with exact host-selected C6B3 facts.");
        if (!prior) { await publishRelationIntent(store, intent); await fault(authority, "after-intent-before-state-head"); await publishRelationStateHead(store, relationStateHead(identity, root, "preparing", 0, { intent: ref(intent) })); await fault(authority, "after-intent"); }
        if (await outputExists(sourceHost.outputPackageRoot)) throw storeError("materialization_binding_uncertain", "Checkpoint storyboard relation output appeared after intent publication and was retained without replacement.");
        const start = createRelationCowStart({ identity, root, intent: ref(intent) }); await publishRelationCowStart(store, start); await fault(authority, "after-cow-start-before-state-head"); await publishRelationStateHead(store, relationStateHead(identity, root, "preparing", 0, { intent: ref(intent), cowStart: ref(start) })); await fault(authority, "after-cow-start");
        try { await fault(authority, "before-c6b3b"); await materializeCheckpointStoryboardRelation(c6bHost, prepared.approval, { schema: "shellx-motion/private-checkpoint-storyboard-relation-materialization-request@1", expected: prepared.expected }); }
        catch (error) {
          const recovered = await recognizeInstalledOutput(sourceHost, record.identity, prepared.expected, plan);
          if (recovered) return await publishAndReopen(store, sourceHost, authority, identity, root, intent, recovered, outputHandle, true);
          if (isPublicationCommitUncertain(error) || await outputExists(sourceHost.outputPackageRoot)) throw storeError("materialization_binding_uncertain", "Checkpoint storyboard relation publication may have committed; its output was retained for exact recovery.");
          const abandon = createRelationAbandon({ identity, root, intent: ref(intent), reason: "proven-no-install" }); await publishRelationAbandon(store, abandon); await fault(authority, "after-abandon"); await publishRelationStateHead(store, relationStateHead(identity, root, "abandoned", 0, { intent: ref(intent), cowStart: ref(start), abandon: ref(abandon) }));
          throw storeError("materialization_binding_conflict", "Checkpoint storyboard relation COW refused before a recognized output was installed.");
        }
        await fault(authority, "after-c6b3b-commit"); const installed = await recognizeInstalledOutput(sourceHost, record.identity, prepared.expected, plan);
        if (!installed) throw storeError("materialization_binding_uncertain", "Checkpoint storyboard relation COW completed without an exact output reopen; output was retained.");
        return await publishAndReopen(store, sourceHost, authority, identity, root, intent, installed, outputHandle, false);
      });
    });
  }); } catch (error) { throw sanitized(error); }
}

export async function detachCheckpointStoryboardRelationStoredRecord(authority: CheckpointStoryboardRelationResolutionAuthority, identity: CheckpointStoryboardRecordIdentity): Promise<CheckpointStoryboardRelationResolutionResult> {
  try { return await withCheckpointStoryboardRelationResolutionOutputAuthority(authority, async (host) => {
    const store = checkedAuthority(host.store), root = await readImmutableRecordRoot(store, identity);
    return await withLineageLock(store, root.id, async () => {
      const record = await readStoredRecordUnlocked(store, identity); assertB3Record(record); assertCheckpointStoryboardRelationResolutionAuthorityStore(authority, host.store); await assertForeignPartitionEvidenceAbsent(store, identity);
      const outputHandle = checkpointStoryboardRelationResolutionOutputHandle(authority, identity);
      let state = await readRelationResolutionState(store, identity, root, { requireHead: true, allowForwardRecovery: true });
      if (state.state === "unbound" || state.state === "abandoned") throw storeError("materialization_not_bound", "Checkpoint storyboard relation record has no bound output to detach.");
      if (state.state === "preparing") {
        const intent = await readRelationIntent(store, identity), start = await readRelationCowStart(store, identity);
        if (intent) { const recovered = await recognizeInstalledOutput(host, record.identity, intent.expectedBase, intent.plan); if (recovered) { await publishAndReopen(store, host, authority, identity, root, intent, recovered, outputHandle, true); state = await readRelationResolutionState(store, identity, root, { requireHead: true, allowForwardRecovery: true }); } }
        if (state.state === "preparing" && intent && !start && !(await outputExists(host.outputPackageRoot))) { const abandon = createRelationAbandon({ identity, root, intent: ref(intent), reason: "no-cow-start" }); await publishRelationAbandon(store, abandon); await publishRelationStateHead(store, relationStateHead(identity, root, "abandoned", 0, { intent: ref(intent), abandon: ref(abandon) })); throw storeError("materialization_not_bound", "Checkpoint storyboard relation intent was abandoned before COW start; no output was deleted."); }
        if (state.state === "preparing") throw storeError("materialization_binding_uncertain", "Checkpoint storyboard relation resolution is COW-uncertain; its output was retained and cannot be detached yet.");
      }
      const binding = await readRelationBinding(store, identity); if (!binding) throw storeError("store_integrity_failed", "Checkpoint storyboard relation state lost its immutable binding.");
      if (state.state === "detached") { await verifyBinding(host, binding, identity, outputHandle); return result(identity, binding, "detached", true); }
      await verifyBinding(host, binding, identity, outputHandle); const detach = createRelationDetach({ identity, root, binding: ref(binding) }); await publishRelationDetach(store, detach); await fault(authority, "after-detach");
      const intent = await readRelationIntent(store, identity), start = await readRelationCowStart(store, identity); if (!intent || !start) throw storeError("store_integrity_failed", "Checkpoint storyboard relation detach lost its required durable intent or COW start.");
      await publishRelationStateHead(store, relationStateHead(identity, root, "detached", 0, { intent: ref(intent), cowStart: ref(start), binding: ref(binding), detach: ref(detach) }), async () => await fault(authority, "after-detached-state-head-rename"));
      const final = await readRelationResolutionState(store, identity, root, { requireHead: true, allowForwardRecovery: true }); if (final.state !== "detached" || final.bindingId !== binding.id) throw storeError("materialization_binding_uncertain", "Checkpoint storyboard relation detach publication could not be reopened exactly.");
      return result(identity, binding, "detached", false);
    });
  }); } catch (error) { throw sanitized(error); }
}

function assertB3Record(record: Awaited<ReturnType<typeof readStoredRecordUnlocked>>): void { if (record.archive.terminal) throw storeError("lineage_archived", "Checkpoint storyboard lineage is terminally archived."); if (record.target.state === "tombstoned") throw storeError("record_tombstoned", "A tombstoned checkpoint storyboard record cannot resolve relations."); if (record.admission.profile !== "c6b3-relation@1") throw storeError("materialization_profile_refused", "C6C B3a relation resolution accepts only a sealed C6B3 relation profile record."); }
async function assertForeignPartitionEvidenceAbsent(store: ReturnType<typeof checkedAuthority>, identity: CheckpointStoryboardRecordIdentity): Promise<void> { await assertNoLegacyMaterializationEvidence(store, identity); await assertNoBehaviorResolutionEvidence(store, identity); await assertNoRelationActionResolutionEvidence(store, identity); await assertNoLifecycleResolutionEvidence(store, identity); await assertNoGeometryMorphResolutionEvidence(store, identity); await assertNoRetainedTraceResolutionEvidence(store, identity); }
function assertTwoCatalogOrderBindings(catalog: readonly { readonly objectId: string }[], bindings: readonly { readonly objectId: string; readonly layerId: string }[]): void { if (catalog.length !== 2 || bindings.length !== 2 || bindings.some((binding, index) => binding.objectId !== catalog[index]!.objectId || binding.layerId !== binding.objectId)) throw storeError("materialization_authority_refused", "Checkpoint storyboard relation resolution requires exactly two catalog-order same-ID object/layer bindings."); }
function planIdentity(plan: Awaited<ReturnType<typeof prepareCheckpointStoryboardRelationMaterialization>>["plan"]): RelationPlanIdentity { return Object.freeze({ planFingerprint: plan.fingerprint, profileFingerprint: plan.lowererProfile.fingerprint, storeSha256: plan.projection.storeSha256, staticFingerprint: plan.projection.staticFingerprint, gpuStaticFingerprint: plan.projection.gpuPreviewStaticPlan.fingerprint, startFramePlanFingerprint: plan.endpointFramePlans.start.fingerprint, endFramePlanFingerprint: plan.endpointFramePlans.end.fingerprint }); }
function ref(value: { readonly id: string; readonly sha256: string }) { return Object.freeze({ id: value.id, sha256: value.sha256 }); }
type Recognized = Readonly<{ output: Awaited<ReturnType<typeof reopenCheckpointStoryboardRelationMaterializationOutput>>; receipt: Awaited<ReturnType<typeof readC6B3bReceipt>>; plan: RelationPlanIdentity }>;
async function recognizeInstalledOutput(host: { readonly outputPackageRoot: string; readonly packageWorkspaceRoot: string; readonly packageWorkspaceAuthority: Parameters<typeof reopenCheckpointStoryboardRelationMaterializationOutput>[0]["packageWorkspaceAuthority"] }, identity: CheckpointStoryboardRecordIdentity, expected: C6B3bExactBase, plan: RelationPlanIdentity): Promise<Recognized | null> { try { const output = await reopenCheckpointStoryboardRelationMaterializationOutput(host), receipt = await readC6B3bReceipt(host.outputPackageRoot); if (output.storyboard.id !== identity.id || output.storyboard.sha256 !== identity.sha256 || output.storyboard.revision !== identity.revision || output.plan.fingerprint !== plan.planFingerprint || output.profile.fingerprint !== plan.profileFingerprint || output.relationStore.sha256 !== plan.storeSha256 || output.relationStatic.fingerprint !== plan.staticFingerprint || output.gpuRelationStatic.fingerprint !== plan.gpuStaticFingerprint || output.endpointFramePlans.startFingerprint !== plan.startFramePlanFingerprint || output.endpointFramePlans.endFingerprint !== plan.endFramePlanFingerprint || output.receipt.fingerprint !== receipt.fingerprint || canonicalJson(receipt.base.expected) !== canonicalJson(expected) || canonicalJson(receipt.base.reopened) !== canonicalJson(expected) || receipt.approval.storeSha256 !== plan.storeSha256 || receipt.approval.staticFingerprint !== plan.staticFingerprint || receipt.approval.gpuStaticFingerprint !== plan.gpuStaticFingerprint || receipt.approval.startFramePlanFingerprint !== plan.startFramePlanFingerprint || receipt.approval.endFramePlanFingerprint !== plan.endFramePlanFingerprint || receipt.renderer.invoked !== false || receipt.renderer.pixels !== false) return null; return Object.freeze({ output, receipt, plan }); } catch { return null; } }
async function publishAndReopen(store: ReturnType<typeof checkedAuthority>, host: Parameters<typeof recognizeInstalledOutput>[0], authority: CheckpointStoryboardRelationResolutionAuthority, identity: CheckpointStoryboardRecordIdentity, root: CheckpointStoryboardRecordIdentity, intent: RelationIntent, recognized: Recognized, outputHandle: string, replayed: boolean): Promise<CheckpointStoryboardRelationResolutionResult> { const start = await readRelationCowStart(store, identity); if (!start || !sameIdentity(start.identity, identity) || !sameIdentity(start.root, root) || start.intent.id !== intent.id || start.intent.sha256 !== intent.sha256) throw storeError("store_integrity_failed", "Checkpoint storyboard relation binding lost its durable COW-start evidence."); const binding = createRelationBinding({ identity, root, intent: ref(intent), plan: recognized.plan, source: Object.freeze({ expected: recognized.receipt.base.expected, reopened: recognized.receipt.base.reopened }), output: Object.freeze({ expected: recognized.output, reopened: recognized.output }), receiptFingerprint: recognized.receipt.fingerprint, outputHandle }); await publishRelationBinding(store, binding); await fault(authority, "after-binding"); await publishRelationStateHead(store, relationStateHead(identity, root, "bound", 1, { intent: ref(intent), cowStart: ref(start), binding: ref(binding) }), async () => await fault(authority, "after-bound-state-head-rename")); const reopened = await readRelationBinding(store, identity); if (!reopened || canonicalJson(reopened) !== canonicalJson(binding)) throw storeError("materialization_binding_uncertain", "Checkpoint storyboard relation binding publication could not be reopened exactly."); await verifyBinding(host, reopened, identity, outputHandle); return result(identity, reopened, "bound", replayed); }
async function replayBound(store: ReturnType<typeof checkedAuthority>, host: Parameters<typeof recognizeInstalledOutput>[0], identity: CheckpointStoryboardRecordIdentity, root: CheckpointStoryboardRecordIdentity, bindingId: string, outputHandle: string): Promise<CheckpointStoryboardRelationResolutionResult> { const binding = await readRelationBinding(store, identity); if (!binding || binding.id !== bindingId || !sameIdentity(binding.root, root)) throw storeError("store_integrity_failed", "Checkpoint storyboard bound relation state does not match its immutable binding."); await verifyBinding(host, binding, identity, outputHandle); return result(identity, binding, "bound", true); }
async function verifyBinding(host: Parameters<typeof recognizeInstalledOutput>[0], binding: RelationBinding, identity: CheckpointStoryboardRecordIdentity, outputHandle: string): Promise<void> { if (binding.outputHandle !== outputHandle) throw storeError("materialization_binding_conflict", "Checkpoint storyboard relation binding belongs to a different exact authority-store output handle."); const output = await reopenCheckpointStoryboardRelationMaterializationOutput(host), receipt = await readC6B3bReceipt(host.outputPackageRoot); if (output.receipt.fingerprint !== binding.receiptFingerprint || receipt.fingerprint !== binding.receiptFingerprint || output.storyboard.id !== identity.id || output.storyboard.sha256 !== identity.sha256 || output.storyboard.revision !== identity.revision || output.plan.fingerprint !== binding.plan.planFingerprint || output.profile.fingerprint !== binding.plan.profileFingerprint || output.relationStore.sha256 !== binding.plan.storeSha256 || output.relationStatic.fingerprint !== binding.plan.staticFingerprint || output.gpuRelationStatic.fingerprint !== binding.plan.gpuStaticFingerprint || output.endpointFramePlans.startFingerprint !== binding.plan.startFramePlanFingerprint || output.endpointFramePlans.endFingerprint !== binding.plan.endFramePlanFingerprint || canonicalJson(receipt.base.expected) !== canonicalJson(binding.source.expected) || canonicalJson(receipt.base.reopened) !== canonicalJson(binding.source.reopened) || canonicalJson(output) !== canonicalJson(binding.output.expected) || canonicalJson(output) !== canonicalJson(binding.output.reopened)) throw storeError("materialization_binding_conflict", "Checkpoint storyboard relation binding no longer reopens the full B3b exact base, output, receipt, store, static, GPU, and endpoint identity."); }
function result(identity: CheckpointStoryboardRecordIdentity, binding: RelationBinding, state: "bound" | "detached", replayed: boolean): CheckpointStoryboardRelationResolutionResult { return Object.freeze({ identity, binding: Object.freeze({ state, active: state === "bound" ? 1 as const : 0 as const, bindingId: binding.id, outputHandle: binding.outputHandle, receiptFingerprint: binding.receiptFingerprint }), renderer: Object.freeze({ invoked: false as const, pixels: false as const }), replayed }); }
async function outputExists(file: string): Promise<boolean> { try { await lstat(file); return true; } catch (error) { if (error && typeof error === "object" && "code" in error && (error as { code?: unknown }).code === "ENOENT") return false; throw storeError("materialization_binding_uncertain", "Checkpoint storyboard relation output could not be safely classified as absent and was not recreated."); } }
function sanitized(error: unknown): never { if (error instanceof CheckpointStoryboardRecordStoreError) throw error; throw storeError("materialization_binding_uncertain", "Checkpoint storyboard relation resolution did not complete exact host/package verification; output was retained and no path evidence was returned."); }
