/** Signed append-only C6C B5 lifecycle-resolution journal. B5b receipts remain diagnostic only. */
import { createHash } from "node:crypto";
import { opendir } from "node:fs/promises";
import { join } from "node:path";
import { canonicalJson, canonicalJsonSha256 } from "@shellx-motion/core";
import { readC6B5bExactBase, type C6B5bExactBase } from "./checkpoint-storyboard-lifecycle-materialize-private/checkpoint-storyboard-lifecycle-materialize-receipt-private.js";
import type { CheckpointStoryboardLifecycleMaterializationInstalledOutput } from "./checkpoint-storyboard-lifecycle-materialize-private/checkpoint-storyboard-lifecycle-materialize-output-private.js";
import { readSignedFile, replaceSignedFile, syncPrivateDirectory, writeExclusiveSignedFile } from "./checkpoint-storyboard-record-store-signed-files.js";
import { readLineageMembers } from "./checkpoint-storyboard-materialization-bindings.js";
import { readStoredRecordUnlocked } from "./checkpoint-storyboard-record-store-state.js";
import { MAX_STATE_BYTES, SHA256, exact, readIdentity, sameIdentity, storeError, type AuthorityFacts, type CheckpointStoryboardRecordIdentity } from "./checkpoint-storyboard-record-store-types.js";

const MAX_JOURNAL_BYTES = 192 * 1024;
const HANDLE = /^checkpoint_storyboard_lifecycle_output_[a-f0-9]{32}$/u;
const FILE = /^checkpoint_storyboard_[a-f0-9]{32}\.(?:state|intent|binding|cow-start|detach|abandon)\.json$/u;
const PREFIX = { intent: "checkpoint_storyboard_lifecycle_resolution_intent_", cowStart: "checkpoint_storyboard_lifecycle_resolution_cow_start_", binding: "checkpoint_storyboard_lifecycle_resolution_binding_", detach: "checkpoint_storyboard_lifecycle_resolution_detach_", abandon: "checkpoint_storyboard_lifecycle_resolution_abandon_" } as const;
type Ref = Readonly<{ id: string; sha256: string }>;
export type CheckpointStoryboardLifecycleResolutionState = "unbound" | "preparing" | "bound" | "detached" | "abandoned";
export type LifecyclePlanIdentity = Readonly<{
  planFingerprint: string; profileFingerprint: string; storyboardId: string; storyboardSha256: string; storyboardRevision: number;
  sourceLayerPrefixCount: number; sourceLayerPrefixSha256: string; generatedLayerIds: readonly string[]; generatedLayerIdsSha256: string;
  generatedLayersSha256: string; timingSha256: string; outputCanonicalMotionSha256: string;
}>;
export type LifecycleOutputIdentity = CheckpointStoryboardLifecycleMaterializationInstalledOutput;
export type LifecycleIntent = Readonly<{ schema: "shellx-motion/private-checkpoint-storyboard-lifecycle-resolution-intent@1"; id: string; sha256: string; identity: CheckpointStoryboardRecordIdentity; root: CheckpointStoryboardRecordIdentity; plan: LifecyclePlanIdentity; expectedBase: C6B5bExactBase; outputHandle: string }>;
export type LifecycleCowStart = Readonly<{ schema: "shellx-motion/private-checkpoint-storyboard-lifecycle-resolution-cow-start@1"; id: string; sha256: string; identity: CheckpointStoryboardRecordIdentity; root: CheckpointStoryboardRecordIdentity; intent: Ref }>;
export type LifecycleBinding = Readonly<{ schema: "shellx-motion/private-checkpoint-storyboard-lifecycle-resolution-binding@1"; id: string; sha256: string; identity: CheckpointStoryboardRecordIdentity; root: CheckpointStoryboardRecordIdentity; intent: Ref; plan: LifecyclePlanIdentity; source: Readonly<{ expected: C6B5bExactBase; reopened: C6B5bExactBase }>; output: Readonly<{ expected: LifecycleOutputIdentity; reopened: LifecycleOutputIdentity }>; receiptFingerprint: string; outputHandle: string }>;
export type LifecycleDetach = Readonly<{ schema: "shellx-motion/private-checkpoint-storyboard-lifecycle-resolution-detach@1"; id: string; sha256: string; identity: CheckpointStoryboardRecordIdentity; root: CheckpointStoryboardRecordIdentity; binding: Ref }>;
export type LifecycleAbandon = Readonly<{ schema: "shellx-motion/private-checkpoint-storyboard-lifecycle-resolution-abandon@1"; id: string; sha256: string; identity: CheckpointStoryboardRecordIdentity; root: CheckpointStoryboardRecordIdentity; intent: Ref; reason: "proven-no-install" | "no-cow-start" }>;
export type LifecycleStateHead = Readonly<{ schema: "shellx-motion/private-checkpoint-storyboard-lifecycle-resolution-state@1"; identity: CheckpointStoryboardRecordIdentity; root: CheckpointStoryboardRecordIdentity; state: CheckpointStoryboardLifecycleResolutionState; active: 0 | 1; intent?: Ref; cowStart?: Ref; binding?: Ref; detach?: Ref; abandon?: Ref }>;
export type LifecycleResolutionBindingState = Readonly<{ state: CheckpointStoryboardLifecycleResolutionState; active: 0 | 1; bindingId?: string; outputHandle?: string; receiptFingerprint?: string }>;

export function createLifecycleIntent(input: Omit<LifecycleIntent, "schema" | "id" | "sha256">): LifecycleIntent { return seal("intent", "shellx-motion/private-checkpoint-storyboard-lifecycle-resolution-intent@1", input); }
export function createLifecycleCowStart(input: Omit<LifecycleCowStart, "schema" | "id" | "sha256">): LifecycleCowStart { return seal("cowStart", "shellx-motion/private-checkpoint-storyboard-lifecycle-resolution-cow-start@1", input); }
export function createLifecycleBinding(input: Omit<LifecycleBinding, "schema" | "id" | "sha256">): LifecycleBinding { return seal("binding", "shellx-motion/private-checkpoint-storyboard-lifecycle-resolution-binding@1", input); }
export function createLifecycleDetach(input: Omit<LifecycleDetach, "schema" | "id" | "sha256">): LifecycleDetach { return seal("detach", "shellx-motion/private-checkpoint-storyboard-lifecycle-resolution-detach@1", input); }
export function createLifecycleAbandon(input: Omit<LifecycleAbandon, "schema" | "id" | "sha256">): LifecycleAbandon { return seal("abandon", "shellx-motion/private-checkpoint-storyboard-lifecycle-resolution-abandon@1", input); }
export function lifecycleStateHead(identity: CheckpointStoryboardRecordIdentity, root: CheckpointStoryboardRecordIdentity, state: CheckpointStoryboardLifecycleResolutionState, active: 0 | 1, refs: Partial<Pick<LifecycleStateHead, "intent" | "cowStart" | "binding" | "detach" | "abandon">> = {}): LifecycleStateHead { return Object.freeze({ schema: "shellx-motion/private-checkpoint-storyboard-lifecycle-resolution-state@1", identity, root, state, active, ...refs }); }
export async function initializeLifecycleStateHead(facts: AuthorityFacts, identity: CheckpointStoryboardRecordIdentity, root: CheckpointStoryboardRecordIdentity): Promise<void> { await publishExact(statePath(facts, identity), lifecycleStateHead(identity, root, "unbound", 0), facts); }
export async function publishLifecycleIntent(facts: AuthorityFacts, value: LifecycleIntent): Promise<void> { await publishExact(path(facts, value.identity, "intent"), value, facts); }
export async function publishLifecycleCowStart(facts: AuthorityFacts, value: LifecycleCowStart): Promise<void> { await publishExact(path(facts, value.identity, "cow-start"), value, facts); }
export async function publishLifecycleBinding(facts: AuthorityFacts, value: LifecycleBinding): Promise<void> { await publishExact(path(facts, value.identity, "binding"), value, facts); }
export async function publishLifecycleDetach(facts: AuthorityFacts, value: LifecycleDetach): Promise<void> { await publishExact(path(facts, value.identity, "detach"), value, facts); }
export async function publishLifecycleAbandon(facts: AuthorityFacts, value: LifecycleAbandon): Promise<void> { await publishExact(path(facts, value.identity, "abandon"), value, facts); }
export async function publishLifecycleStateHead(facts: AuthorityFacts, value: LifecycleStateHead, afterRename?: () => void | Promise<void>): Promise<void> { await replaceSignedFile(statePath(facts, value.identity), value, facts, MAX_STATE_BYTES, afterRename); }
export async function readLifecycleIntent(facts: AuthorityFacts, identity: CheckpointStoryboardRecordIdentity): Promise<LifecycleIntent | null> { return await optional(path(facts, identity, "intent"), facts, readIntent); }
export async function readLifecycleCowStart(facts: AuthorityFacts, identity: CheckpointStoryboardRecordIdentity): Promise<LifecycleCowStart | null> { return await optional(path(facts, identity, "cow-start"), facts, readStart); }
export async function readLifecycleBinding(facts: AuthorityFacts, identity: CheckpointStoryboardRecordIdentity): Promise<LifecycleBinding | null> { return await optional(path(facts, identity, "binding"), facts, readBinding); }
export async function readLifecycleStateHead(facts: AuthorityFacts, identityId: string): Promise<LifecycleStateHead | null> { if (!/^checkpoint_storyboard_[a-f0-9]{32}$/u.test(identityId)) throw storeError("store_integrity_failed", "Checkpoint storyboard lifecycle state filename identity is invalid."); return await optional(join(facts.lifecycleResolutions.path, `${identityId}.state.json`), facts, readHead); }
export async function assertNoLifecycleResolutionEvidence(facts: AuthorityFacts, identity: CheckpointStoryboardRecordIdentity): Promise<void> { if (await readLifecycleStateHead(facts, identity.id) || await readLifecycleIntent(facts, identity) || await readLifecycleCowStart(facts, identity) || await readLifecycleBinding(facts, identity) || await optional(path(facts, identity, "detach"), facts, readDetach) || await optional(path(facts, identity, "abandon"), facts, readAbandon)) throw storeError("store_integrity_failed", "Checkpoint storyboard non-lifecycle record has forbidden C6B5 lifecycle-resolution evidence."); }

/** Reads all signed phases. Forward head repair is legal only while a resolver holds the lineage lock. */
export async function readLifecycleResolutionState(facts: AuthorityFacts, identity: CheckpointStoryboardRecordIdentity, root: CheckpointStoryboardRecordIdentity, options: { readonly requireHead?: boolean; readonly allowForwardRecovery?: boolean } = {}): Promise<LifecycleResolutionBindingState> {
  await syncActionDirectory(facts); const repair = options.allowForwardRecovery ?? false;
  const head = await optional(statePath(facts, identity), facts, readHead), intent = await readLifecycleIntent(facts, identity), start = await readLifecycleCowStart(facts, identity), binding = await readLifecycleBinding(facts, identity), detach = await optional(path(facts, identity, "detach"), facts, readDetach), abandon = await optional(path(facts, identity, "abandon"), facts, readAbandon);
  if (!head) {
    if (!options.requireHead && !intent && !start && !binding && !detach && !abandon) return Object.freeze({ state: "unbound" as const, active: 0 as const });
    if (intent && !start && !binding && !detach && !abandon && repair) { const next = lifecycleStateHead(identity, root, "preparing", 0, { intent: ref(intent) }); await publishLifecycleStateHead(facts, next); return await reopenPromoted(facts, identity, root, next, Object.freeze({ state: "preparing" as const, active: 0 as const, outputHandle: intent.outputHandle })); }
    throw storeError(intent ? "record_commit_uncertain" : "store_integrity_failed", "Checkpoint storyboard lifecycle resolution is missing its required signed state head.");
  }
  if (!sameIdentity(head.identity, identity) || !sameIdentity(head.root, root)) throw storeError("store_integrity_failed", "Checkpoint storyboard lifecycle state head does not bind this record lineage.");
  if (!intent) { if (start || binding || detach || abandon) throw storeError("store_integrity_failed", "Checkpoint storyboard lifecycle unbound state has phase evidence."); return await checkedHead(facts, head, Object.freeze({ state: "unbound" as const, active: 0 as const }), repair); }
  if (!sameIdentity(intent.identity, identity) || !sameIdentity(intent.root, root)) throw storeError("store_integrity_failed", "Checkpoint storyboard lifecycle intent does not bind this record lineage.");
  if (!binding) {
    if (detach) throw storeError("store_integrity_failed", "Checkpoint storyboard lifecycle detach has no immutable binding.");
    if (start && (!sameIdentity(start.identity, identity) || !sameIdentity(start.root, root) || !sameRef(start.intent, intent))) throw storeError("store_integrity_failed", "Checkpoint storyboard lifecycle COW start does not bind intent.");
    if (abandon) { if (!sameIdentity(abandon.identity, identity) || !sameIdentity(abandon.root, root) || !sameRef(abandon.intent, intent) || (abandon.reason === "no-cow-start" && start) || (abandon.reason === "proven-no-install" && !start)) throw storeError("store_integrity_failed", "Checkpoint storyboard lifecycle abandonment is inconsistent."); return await checkedHead(facts, head, Object.freeze({ state: "abandoned" as const, active: 0 as const, outputHandle: intent.outputHandle }), repair, intent, start ?? undefined, undefined, undefined, abandon); }
    return await checkedHead(facts, head, Object.freeze({ state: "preparing" as const, active: 0 as const, outputHandle: intent.outputHandle }), repair, intent, start ?? undefined);
  }
  if (!start || abandon || !sameIdentity(binding.identity, identity) || !sameIdentity(binding.root, root) || !sameRef(binding.intent, intent) || binding.outputHandle !== intent.outputHandle || !samePlan(binding.plan, intent.expectedBase) || !samePlan(binding.plan, binding.output.expected) || canonicalJson(binding.plan) !== canonicalJson(intent.plan) || canonicalJson(binding.source.expected) !== canonicalJson(intent.expectedBase) || !sameIdentity(binding.output.expected.storyboard, identity) || !sameIdentity(binding.output.reopened.storyboard, identity) || !sameIdentity(start.identity, identity) || !sameIdentity(start.root, root) || !sameRef(start.intent, intent)) throw storeError("store_integrity_failed", "Checkpoint storyboard lifecycle binding does not semantically bind intent, lifecycle facts, identity, and COW start.");
  if (!detach) return await checkedHead(facts, head, Object.freeze({ state: "bound" as const, active: 1 as const, bindingId: binding.id, outputHandle: binding.outputHandle, receiptFingerprint: binding.receiptFingerprint }), repair, intent, start, binding);
  if (!sameIdentity(detach.identity, identity) || !sameIdentity(detach.root, root) || !sameRef(detach.binding, binding)) throw storeError("store_integrity_failed", "Checkpoint storyboard lifecycle detach does not bind immutable binding.");
  return await checkedHead(facts, head, Object.freeze({ state: "detached" as const, active: 0 as const, bindingId: binding.id, outputHandle: binding.outputHandle, receiptFingerprint: binding.receiptFingerprint }), repair, intent, start, binding, detach);
}
export async function assertLineageHasNoPreparingOrBoundLifecycleResolutions(facts: AuthorityFacts, root: CheckpointStoryboardRecordIdentity, requireHeadsFor = new Set<string>()): Promise<void> { const members = await readLineageMembers(facts, root); if (!members.length) throw storeError("store_integrity_failed", "Checkpoint storyboard lineage has no signed membership records."); for (const member of members) { if (!sameIdentity(member.root, root)) throw storeError("store_integrity_failed", "Checkpoint storyboard lineage membership root changed."); const state = await readLifecycleResolutionState(facts, member.identity, root, { requireHead: requireHeadsFor.has(member.identity.id) }); if (state.state === "preparing" || state.state === "bound") throw storeError("materialization_binding_conflict", "Checkpoint storyboard remove/archive requires every lifecycle-resolution member to be unbound or detached."); } }
/** Archive scans the complete B5 namespace so copied/foreign/hidden phase leaves cannot be hidden. */
export async function assertLifecycleResolutionJournalCompleteForLineage(facts: AuthorityFacts, root: CheckpointStoryboardRecordIdentity, requireHeadsFor = new Set<string>()): Promise<void> {
  const members = await readLineageMembers(facts, root), byId = new Map(members.map((member) => [member.identity.id, member.identity])), reader = await opendir(facts.lifecycleResolutions.path);
  try { for await (const entry of reader) { if (!entry.isFile() || !FILE.test(entry.name)) throw storeError("store_integrity_failed", "Checkpoint storyboard lifecycle journal contains an invalid entry."); const identityId = entry.name.slice(0, 54), identity = byId.get(identityId), head = await readLifecycleStateHead(facts, identityId); if (!head) throw storeError("store_integrity_failed", "Checkpoint storyboard lifecycle journal state head is missing."); if (head.identity.id !== identityId) throw storeError("store_integrity_failed", "Checkpoint storyboard lifecycle filename does not match signed identity."); if (identity) { if (!requireHeadsFor.has(identity.id) || !sameIdentity(head.root, root) || !sameIdentity(head.identity, identity)) throw storeError("store_integrity_failed", "Checkpoint storyboard lifecycle journal attaches to a sealed non-B5 lineage member."); } else { const foreign = (await readLineageMembers(facts, head.root)).find((member) => sameIdentity(member.identity, head.identity)); if (!foreign || !sameIdentity(foreign.root, head.root)) throw storeError("store_integrity_failed", "Checkpoint storyboard lifecycle journal references an unknown lineage member."); const foreignRecord = await readStoredRecordUnlocked(facts, head.identity); if (foreignRecord.admission.profile !== "c6b5-lifecycle@1") throw storeError("store_integrity_failed", "Checkpoint storyboard lifecycle journal attaches to a foreign non-B5 member."); await readLifecycleResolutionState(facts, head.identity, head.root, { requireHead: true }); } } } finally { await reader.close().catch(() => undefined); }
  for (const member of members) await readLifecycleResolutionState(facts, member.identity, root, { requireHead: requireHeadsFor.has(member.identity.id) });
}

function path(facts: AuthorityFacts, identity: CheckpointStoryboardRecordIdentity, kind: "intent" | "cow-start" | "binding" | "detach" | "abandon"): string { return join(facts.lifecycleResolutions.path, `${identity.id}.${kind}.json`); }
function statePath(facts: AuthorityFacts, identity: CheckpointStoryboardRecordIdentity): string { return join(facts.lifecycleResolutions.path, `${identity.id}.state.json`); }
async function optional<T>(file: string, facts: AuthorityFacts, read: (value: unknown) => T): Promise<T | null> { try { return read(await readSignedFile(file, facts, MAX_JOURNAL_BYTES, "record_not_found")); } catch (error) { if (error instanceof Error && (error as { code?: string }).code === "record_not_found") return null; throw error; } }
async function syncActionDirectory(facts: AuthorityFacts): Promise<void> { try { await syncPrivateDirectory(facts.lifecycleResolutions.path); } catch { throw storeError("record_commit_uncertain", "Checkpoint storyboard lifecycle state requires a durable directory resync."); } }
async function checkedHead(facts: AuthorityFacts, head: LifecycleStateHead, state: LifecycleResolutionBindingState, repair: boolean, intent?: LifecycleIntent, cowStart?: LifecycleCowStart, binding?: LifecycleBinding, detach?: LifecycleDetach, abandon?: LifecycleAbandon): Promise<LifecycleResolutionBindingState> {
  const matches = (actual: Ref | undefined, value: { readonly id: string; readonly sha256: string } | undefined) => value ? sameRef(actual, value) : !actual;
  if (!legalHead(head)) throw storeError("store_integrity_failed", "Checkpoint storyboard lifecycle state head has invalid phase fields.");
  const exactHead = head.state === state.state && head.active === state.active && matches(head.intent, intent) && matches(head.cowStart, cowStart) && matches(head.binding, binding) && matches(head.detach, detach) && matches(head.abandon, abandon);
  if (exactHead) return state;
  if (!repair) throw storeError("record_commit_uncertain", "Checkpoint storyboard lifecycle phase evidence is one publication ahead of its signed head; read-only inspection will not repair it.");
  const next = lifecycleStateHead(head.identity, head.root, state.state, state.active, { ...(intent ? { intent: ref(intent) } : {}), ...(cowStart ? { cowStart: ref(cowStart) } : {}), ...(binding ? { binding: ref(binding) } : {}), ...(detach ? { detach: ref(detach) } : {}), ...(abandon ? { abandon: ref(abandon) } : {}) });
  const oneStep = (head.state === "unbound" && state.state === "preparing" && !!intent && !cowStart)
    || (head.state === "preparing" && state.state === "preparing" && !!intent && !!cowStart && matches(head.intent, intent) && !head.cowStart)
    || (head.state === "preparing" && state.state === "bound" && !!intent && !!cowStart && !!binding && matches(head.intent, intent) && matches(head.cowStart, cowStart))
    || (head.state === "preparing" && state.state === "abandoned" && !!intent && !!abandon && matches(head.intent, intent) && matches(head.cowStart, cowStart))
    || (head.state === "bound" && state.state === "detached" && !!intent && !!cowStart && !!binding && !!detach && matches(head.intent, intent) && matches(head.cowStart, cowStart) && matches(head.binding, binding));
  if (!oneStep) throw storeError("store_integrity_failed", "Checkpoint storyboard lifecycle head skips, diverges from, or rolls back immutable phase evidence.");
  await publishLifecycleStateHead(facts, next); return await reopenPromoted(facts, head.identity, head.root, next, state);
}
function legalHead(head: LifecycleStateHead): boolean { return (head.state === "unbound" && head.active === 0 && !hasRef(head)) || (head.state === "preparing" && head.active === 0 && !!head.intent && !head.binding && !head.detach && !head.abandon) || (head.state === "bound" && head.active === 1 && !!head.intent && !!head.cowStart && !!head.binding && !head.detach && !head.abandon) || (head.state === "detached" && head.active === 0 && !!head.intent && !!head.cowStart && !!head.binding && !!head.detach && !head.abandon) || (head.state === "abandoned" && head.active === 0 && !!head.intent && !!head.abandon && !head.binding && !head.detach); }
async function reopenPromoted(facts: AuthorityFacts, identity: CheckpointStoryboardRecordIdentity, root: CheckpointStoryboardRecordIdentity, expected: LifecycleStateHead, state: LifecycleResolutionBindingState): Promise<LifecycleResolutionBindingState> { const reopened = await optional(statePath(facts, identity), facts, readHead); if (!reopened || canonicalJson(reopened) !== canonicalJson(expected)) throw storeError("record_commit_uncertain", "Checkpoint storyboard lifecycle head promotion could not be reopened exactly."); await syncActionDirectory(facts); return state; }
async function publishExact(file: string, value: object, facts: AuthorityFacts): Promise<void> { try { await writeExclusiveSignedFile(file, value, facts, MAX_JOURNAL_BYTES); } catch (error) { if (!(error instanceof Error) || (error as { code?: string }).code !== "record_identity_conflict") throw error; const existing = await readSignedFile(file, facts, MAX_JOURNAL_BYTES, "record_not_found"); if (canonicalJson(existing) !== canonicalJson(value)) throw storeError("materialization_binding_conflict", "Checkpoint storyboard immutable lifecycle journal leaf is occupied by different content."); } }
function seal<K extends keyof typeof PREFIX, S extends string, T extends object>(kind: K, schema: S, payload: T): T & { readonly schema: S; readonly id: string; readonly sha256: string } { const sha256 = createHash("sha256").update(canonicalJson({ schema, ...payload })).digest("hex"); return Object.freeze({ schema, id: `${PREFIX[kind]}${sha256.slice(0, 32)}`, sha256, ...payload }); }
function ref(value: { readonly id: string; readonly sha256: string }): Ref { return Object.freeze({ id: value.id, sha256: value.sha256 }); }
function sameRef(value: Ref | undefined, target: { readonly id: string; readonly sha256: string }): boolean { return !!value && value.id === target.id && value.sha256 === target.sha256; }
function hasRef(head: LifecycleStateHead): boolean { return !!(head.intent || head.cowStart || head.binding || head.detach || head.abandon); }
function readIntent(value: unknown): LifecycleIntent { const record = exact(value, ["schema", "id", "sha256", "identity", "root", "plan", "expectedBase", "outputHandle"], "Lifecycle resolution intent"); if (record.schema !== "shellx-motion/private-checkpoint-storyboard-lifecycle-resolution-intent@1") bad("lifecycle intent schema"); const identity = readIdentity(record.identity, "Lifecycle intent identity"), root = readIdentity(record.root, "Lifecycle intent root"), plan = readPlan(record.plan), expectedBase = readBase(record.expectedBase, "Lifecycle intent expected base"), outputHandle = str(record.outputHandle, "Lifecycle intent output handle"); if (!HANDLE.test(outputHandle) || !samePlan(plan, expectedBase)) bad("lifecycle intent plan"); return checked(record, PREFIX.intent, { schema: record.schema, identity, root, plan, expectedBase, outputHandle }) as LifecycleIntent; }
function readStart(value: unknown): LifecycleCowStart { const record = exact(value, ["schema", "id", "sha256", "identity", "root", "intent"], "Lifecycle COW start"); if (record.schema !== "shellx-motion/private-checkpoint-storyboard-lifecycle-resolution-cow-start@1") bad("lifecycle COW start schema"); return checked(record, PREFIX.cowStart, { schema: record.schema, identity: readIdentity(record.identity, "Lifecycle start identity"), root: readIdentity(record.root, "Lifecycle start root"), intent: readRef(record.intent, PREFIX.intent) }) as LifecycleCowStart; }
function readBinding(value: unknown): LifecycleBinding { const record = exact(value, ["schema", "id", "sha256", "identity", "root", "intent", "plan", "source", "output", "receiptFingerprint", "outputHandle"], "Lifecycle binding"); if (record.schema !== "shellx-motion/private-checkpoint-storyboard-lifecycle-resolution-binding@1") bad("lifecycle binding schema"); const source = basePair(record.source, "Lifecycle binding source"), output = outputPair(record.output, "Lifecycle binding output"), receiptFingerprint = str(record.receiptFingerprint, "Lifecycle binding receipt"), outputHandle = str(record.outputHandle, "Lifecycle binding handle"), plan = readPlan(record.plan); if (!SHA256.test(receiptFingerprint) || !HANDLE.test(outputHandle) || receiptFingerprint !== output.expected.receipt.fingerprint || !samePlan(plan, source.expected) || !samePlan(plan, output.expected) || output.expected.package.id !== source.expected.packageId || output.expected.package.manifest.rawSha256 !== source.expected.manifestRawSha256 || output.expected.package.manifest.canonicalSha256 !== source.expected.manifestCanonicalSha256) bad("lifecycle binding package identity"); return checked(record, PREFIX.binding, { schema: record.schema, identity: readIdentity(record.identity, "Lifecycle binding identity"), root: readIdentity(record.root, "Lifecycle binding root"), intent: readRef(record.intent, PREFIX.intent), plan, source, output, receiptFingerprint, outputHandle }) as LifecycleBinding; }
function readDetach(value: unknown): LifecycleDetach { const record = exact(value, ["schema", "id", "sha256", "identity", "root", "binding"], "Action detach"); if (record.schema !== "shellx-motion/private-checkpoint-storyboard-lifecycle-resolution-detach@1") bad("action detach schema"); return checked(record, PREFIX.detach, { schema: record.schema, identity: readIdentity(record.identity, "Action detach identity"), root: readIdentity(record.root, "Action detach root"), binding: readRef(record.binding, PREFIX.binding) }) as LifecycleDetach; }
function readAbandon(value: unknown): LifecycleAbandon { const record = exact(value, ["schema", "id", "sha256", "identity", "root", "intent", "reason"], "Action abandon"), reason = record.reason; if (record.schema !== "shellx-motion/private-checkpoint-storyboard-lifecycle-resolution-abandon@1" || (reason !== "proven-no-install" && reason !== "no-cow-start")) bad("action abandonment"); return checked(record, PREFIX.abandon, { schema: record.schema, identity: readIdentity(record.identity, "Action abandon identity"), root: readIdentity(record.root, "Action abandon root"), intent: readRef(record.intent, PREFIX.intent), reason }) as LifecycleAbandon; }
function readHead(value: unknown): LifecycleStateHead { const record = exact(value, ["schema", "identity", "root", "state", "active"], ["intent", "cowStart", "binding", "detach", "abandon"], "Action state"), state = record.state; if (record.schema !== "shellx-motion/private-checkpoint-storyboard-lifecycle-resolution-state@1" || (state !== "unbound" && state !== "preparing" && state !== "bound" && state !== "detached" && state !== "abandoned") || (record.active !== 0 && record.active !== 1)) bad("action state schema"); const read = (key: "intent" | "cowStart" | "binding" | "detach" | "abandon", prefix: string) => Object.hasOwn(record, key) ? readRef(record[key], prefix) : undefined; return Object.freeze({ schema: record.schema, identity: readIdentity(record.identity, "Action state identity"), root: readIdentity(record.root, "Action state root"), state, active: record.active, ...(read("intent", PREFIX.intent) ? { intent: read("intent", PREFIX.intent) } : {}), ...(read("cowStart", PREFIX.cowStart) ? { cowStart: read("cowStart", PREFIX.cowStart) } : {}), ...(read("binding", PREFIX.binding) ? { binding: read("binding", PREFIX.binding) } : {}), ...(read("detach", PREFIX.detach) ? { detach: read("detach", PREFIX.detach) } : {}), ...(read("abandon", PREFIX.abandon) ? { abandon: read("abandon", PREFIX.abandon) } : {}) }); }
function checked(record: Record<string, unknown>, prefix: string, payload: object): object { const id = str(record.id, "Action journal id"), sha256 = str(record.sha256, "Action journal hash"), expected = createHash("sha256").update(canonicalJson(payload)).digest("hex"); if (!SHA256.test(sha256) || sha256 !== expected || id !== `${prefix}${sha256.slice(0, 32)}`) bad("action journal deterministic identity"); return Object.freeze({ ...payload, id, sha256 }); }
function readPlan(value: unknown): LifecyclePlanIdentity {
  const record = exact(value, ["planFingerprint", "profileFingerprint", "storyboardId", "storyboardSha256", "storyboardRevision", "sourceLayerPrefixCount", "sourceLayerPrefixSha256", "generatedLayerIds", "generatedLayerIdsSha256", "generatedLayersSha256", "timingSha256", "outputCanonicalMotionSha256"], "Lifecycle plan");
  const ids = readIds(record.generatedLayerIds, "Lifecycle plan generated layer ids");
  if (![record.planFingerprint, record.profileFingerprint, record.storyboardSha256, record.sourceLayerPrefixSha256, record.generatedLayerIdsSha256, record.generatedLayersSha256, record.timingSha256, record.outputCanonicalMotionSha256].every(hash) || !id(record.storyboardId) || !revision(record.storyboardRevision) || !zeroCount(record.sourceLayerPrefixCount, 10_000) || record.generatedLayerIdsSha256 !== canonicalJsonSha256(ids)) bad("lifecycle plan");
  return frozen({ planFingerprint: record.planFingerprint, profileFingerprint: record.profileFingerprint, storyboardId: record.storyboardId, storyboardSha256: record.storyboardSha256, storyboardRevision: record.storyboardRevision, sourceLayerPrefixCount: record.sourceLayerPrefixCount, sourceLayerPrefixSha256: record.sourceLayerPrefixSha256, generatedLayerIds: ids, generatedLayerIdsSha256: record.generatedLayerIdsSha256, generatedLayersSha256: record.generatedLayersSha256, timingSha256: record.timingSha256, outputCanonicalMotionSha256: record.outputCanonicalMotionSha256 }) as LifecyclePlanIdentity;
}
function readBase(value: unknown, label: string): C6B5bExactBase { try { return readC6B5bExactBase(value); } catch { bad(label); } }
function basePair(value: unknown, label: string): LifecycleBinding["source"] { const record = exact(value, ["expected", "reopened"], label), expected = readBase(record.expected, `${label}.expected`), reopened = readBase(record.reopened, `${label}.reopened`); if (canonicalJson(expected) !== canonicalJson(reopened)) bad(`${label} reopened base`); return Object.freeze({ expected, reopened }); }
function outputPair(value: unknown, label: string): LifecycleBinding["output"] { const record = exact(value, ["expected", "reopened"], label), expected = readOutput(record.expected, `${label}.expected`), reopened = readOutput(record.reopened, `${label}.reopened`); if (canonicalJson(expected) !== canonicalJson(reopened)) bad(`${label} reopened output`); return Object.freeze({ expected, reopened }); }
function readOutput(value: unknown, label: string): LifecycleOutputIdentity {
  if (forbidden(value)) bad(`${label} host authority field`);
  const root = exact(value, ["schema", "receipt", "package", "storyboard", "plan", "profile", "layers", "materialization"], label);
  const receipt = exact(root.receipt, ["schema", "fingerprint"], `${label}.receipt`), pkg = exact(root.package, ["id", "manifest", "motion", "currentInventory", "nonReceiptInventory", "preservedLeaves"], `${label}.package`), storyboard = exact(root.storyboard, ["id", "sha256", "revision"], `${label}.storyboard`), plan = exact(root.plan, ["fingerprint"], `${label}.plan`), profile = exact(root.profile, ["fingerprint"], `${label}.profile`), layers = exact(root.layers, ["sourcePrefix", "ids", "idsSha256", "generatedSha256", "timingSha256"], `${label}.layers`), materialization = exact(root.materialization, ["changedMotionRoot", "changedLeafCount", "renderer"], `${label}.materialization`), renderer = exact(materialization.renderer, ["invoked", "pixels"], `${label}.renderer`);
  const manifest = exact(pkg.manifest, ["rawSha256", "canonicalSha256"], `${label}.manifest`), motion = exact(pkg.motion, ["rawSha256", "canonicalSha256"], `${label}.motion`), prefix = exact(layers.sourcePrefix, ["count", "sha256"], `${label}.sourcePrefix`), preserved = exact(pkg.preservedLeaves, ["sha256", "count"], `${label}.preserved`), ids = readIds(layers.ids, `${label}.layer ids`);
  if (root.schema !== "shellx-motion/private-checkpoint-storyboard-lifecycle-materialization-installed-output@1" || receipt.schema !== "shellx-motion/private-checkpoint-storyboard-lifecycle-materialization-receipt@1" || !hash(receipt.fingerprint) || !id(pkg.id) || ![manifest.rawSha256, manifest.canonicalSha256, motion.rawSha256, motion.canonicalSha256, storyboard.sha256, plan.fingerprint, profile.fingerprint, prefix.sha256, layers.idsSha256, layers.generatedSha256, layers.timingSha256, preserved.sha256].every(hash) || !/^checkpoint_storyboard_[a-f0-9]{32}$/u.test(String(storyboard.id)) || !revision(storyboard.revision) || !zeroCount(prefix.count, 10_000) || layers.idsSha256 !== canonicalJsonSha256(ids) || !count(preserved.count, 100_000) || !sameInventory(pkg.currentInventory, `${label}.current inventory`) || !sameInventory(pkg.nonReceiptInventory, `${label}.non-receipt inventory`) || materialization.changedMotionRoot !== "layers" || materialization.changedLeafCount !== 2 || renderer.invoked !== false || renderer.pixels !== false) bad(`${label} lifecycle output facts`);
  return frozen(structuredClone(root)) as unknown as LifecycleOutputIdentity;
}
function samePlan(plan: LifecyclePlanIdentity, value: C6B5bExactBase | LifecycleOutputIdentity): boolean {
  if ("planFingerprint" in value) return canonicalJson(plan) === canonicalJson({ planFingerprint: value.planFingerprint, profileFingerprint: value.profileFingerprint, storyboardId: value.storyboardId, storyboardSha256: value.storyboardSha256, storyboardRevision: value.storyboardRevision, sourceLayerPrefixCount: value.sourceLayerPrefixCount, sourceLayerPrefixSha256: value.sourceLayerPrefixSha256, generatedLayerIds: value.generatedLayerIds, generatedLayerIdsSha256: value.generatedLayerIdsSha256, generatedLayersSha256: value.generatedLayersSha256, timingSha256: value.timingSha256, outputCanonicalMotionSha256: value.outputCanonicalMotionSha256 });
  return plan.planFingerprint === value.plan.fingerprint && plan.profileFingerprint === value.profile.fingerprint && plan.storyboardId === value.storyboard.id && plan.storyboardSha256 === value.storyboard.sha256 && plan.storyboardRevision === value.storyboard.revision && plan.sourceLayerPrefixCount === value.layers.sourcePrefix.count && plan.sourceLayerPrefixSha256 === value.layers.sourcePrefix.sha256 && canonicalJson(plan.generatedLayerIds) === canonicalJson(value.layers.ids) && plan.generatedLayerIdsSha256 === value.layers.idsSha256 && plan.generatedLayersSha256 === value.layers.generatedSha256 && plan.timingSha256 === value.layers.timingSha256 && plan.outputCanonicalMotionSha256 === value.package.motion.canonicalSha256;
}
function forbidden(value: unknown): boolean { if (Array.isArray(value)) return value.some(forbidden); if (!value || typeof value !== "object") return false; return Object.entries(value).some(([key, child]) => (key !== "changedPath" && /(?:path|workspace|approval|authority)/iu.test(key)) || forbidden(child)); }
function readInventory(value: unknown, label: string): { readonly sha256: string; readonly entryCount: number; readonly leafCount: number } { const record = exact(value, ["sha256", "entryCount", "leafCount"], label); if (!hash(record.sha256) || !count(record.entryCount, 2048) || !count(record.leafCount, 1024)) bad(`${label} inventory`); return Object.freeze({ sha256: record.sha256, entryCount: record.entryCount, leafCount: record.leafCount }); }
function readRef(value: unknown, prefix: string): Ref { const record = exact(value, ["id", "sha256"], "Action journal reference"), idValue = str(record.id, "Action ref id"), sha256 = str(record.sha256, "Action ref hash"); if (!SHA256.test(sha256) || idValue !== `${prefix}${sha256.slice(0, 32)}`) bad("action journal reference"); return Object.freeze({ id: idValue, sha256 }); }
function hash(value: unknown): value is string { return typeof value === "string" && SHA256.test(value); }
function id(value: unknown): value is string { return typeof value === "string" && /^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$/u.test(value); }
function count(value: unknown, max: number): value is number { return typeof value === "number" && Number.isSafeInteger(value) && value >= 1 && value <= max; }
function zeroCount(value: unknown, max: number): value is number { return typeof value === "number" && Number.isSafeInteger(value) && value >= 0 && value <= max; }
function revision(value: unknown): value is number { return typeof value === "number" && Number.isSafeInteger(value) && value >= 1 && value <= 1_000_000; }
function readIds(value: unknown, label: string): readonly string[] { if (!Array.isArray(value) || value.length > 1_000 || !value.every(id) || new Set(value).size !== value.length) bad(label); return Object.freeze([...value]); }
function sameInventory(value: unknown, label: string): boolean { try { readInventory(value, label); return true; } catch { return false; } }
function str(value: unknown, label: string): string { if (typeof value !== "string") bad(label); return value; }
function frozen<T>(value: T): T { if (value && typeof value === "object" && !Object.isFrozen(value)) { for (const child of Object.values(value as object)) frozen(child); Object.freeze(value); } return value; }
function bad(label: string): never { throw storeError("store_integrity_failed", `Checkpoint storyboard lifecycle journal ${label} is invalid.`); }
